{
  "name": "SemanticModel",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Marketing performance",
        "columns": [
          {
            "name": "Week",
            "dataType": "dateTime",
            "sourceColumn": "Week",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "Channel",
            "dataType": "string",
            "sourceColumn": "Channel",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Channel Group",
            "dataType": "string",
            "sourceColumn": "Channel Group",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Channel Type",
            "dataType": "string",
            "sourceColumn": "Channel Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Super Region",
            "dataType": "string",
            "sourceColumn": "Super Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Spend",
            "dataType": "double",
            "sourceColumn": "Spend",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Impressions (raw)",
            "dataType": "int64",
            "sourceColumn": "Impressions",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Clicks (raw)",
            "dataType": "int64",
            "sourceColumn": "Clicks",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Conversions (raw)",
            "dataType": "int64",
            "sourceColumn": "Conversions",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Leads (raw)",
            "dataType": "int64",
            "sourceColumn": "Leads",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Revenue (raw)",
            "dataType": "double",
            "sourceColumn": "Revenue",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "New Customers (raw)",
            "dataType": "int64",
            "sourceColumn": "New Customers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "measures": [
          {
            "name": "Revenue",
            "expression": "SUM('Marketing performance'[Revenue (raw)])",
            "formatString": "\"$\"#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Marketing Spend",
            "expression": "SUM('Marketing performance'[Spend])",
            "formatString": "\"$\"#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Gross Profit",
            "expression": "SUM('Marketing performance'[Revenue (raw)]) - SUM('Marketing performance'[Spend])",
            "formatString": "\"$\"#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "ROAS",
            "expression": "DIVIDE(SUM('Marketing performance'[Revenue (raw)]), SUM('Marketing performance'[Spend]))",
            "formatString": "#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "ROI %",
            "expression": "DIVIDE((SUM('Marketing performance'[Revenue (raw)]) - SUM('Marketing performance'[Spend])), SUM('Marketing performance'[Spend]))",
            "formatString": "0.0%",
            "displayFolder": "Measures"
          },
          {
            "name": "Impressions",
            "expression": "SUM('Marketing performance'[Impressions (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Clicks",
            "expression": "SUM('Marketing performance'[Clicks (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Conversions",
            "expression": "SUM('Marketing performance'[Conversions (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Leads",
            "expression": "SUM('Marketing performance'[Leads (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "New Customers",
            "expression": "SUM('Marketing performance'[New Customers (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "CTR",
            "expression": "DIVIDE(SUM('Marketing performance'[Clicks (raw)]), SUM('Marketing performance'[Impressions (raw)]))",
            "formatString": "0.00%",
            "displayFolder": "Measures"
          },
          {
            "name": "Conversion Rate",
            "expression": "DIVIDE(SUM('Marketing performance'[Conversions (raw)]), SUM('Marketing performance'[Clicks (raw)]))",
            "formatString": "0.00%",
            "displayFolder": "Measures"
          },
          {
            "name": "CPC",
            "expression": "DIVIDE(SUM('Marketing performance'[Spend]), SUM('Marketing performance'[Clicks (raw)]))",
            "formatString": "\"$\"#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "CPM",
            "expression": "DIVIDE(SUM('Marketing performance'[Spend]), SUM('Marketing performance'[Impressions (raw)])) * 1000",
            "formatString": "\"$\"#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "CPA",
            "expression": "DIVIDE(SUM('Marketing performance'[Spend]), SUM('Marketing performance'[Conversions (raw)]))",
            "formatString": "\"$\"#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "CPL",
            "expression": "DIVIDE(SUM('Marketing performance'[Spend]), SUM('Marketing performance'[Leads (raw)]))",
            "formatString": "\"$\"#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "AOV",
            "expression": "DIVIDE(SUM('Marketing performance'[Revenue (raw)]), SUM('Marketing performance'[Conversions (raw)]))",
            "formatString": "\"$\"#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "Cost per New Customer",
            "expression": "DIVIDE(SUM('Marketing performance'[Spend]), SUM('Marketing performance'[New Customers (raw)]))",
            "formatString": "\"$\"#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "Target ROAS",
            "expression": "3.5",
            "formatString": "#,0.00",
            "displayFolder": "Measures"
          }
        ],
        "partitions": [
          {
            "name": "Marketing performance",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"tH1BrzRJktRfQXumSxEe4R4RxxHsgQOwgMQFcWgtA7S0zKJhJMS/xz3MsupVVlbV+15G7a52evp7Pc8mM9LDzd3c/L/8l7+TJPW3lP3//u5f/t0//P7Hf/sX/+nPv//1H/+n/7t/989//dv//Bd/+l9//usf//i7//vrH8SP+b/wT/6P/2X8p/BffvsPefur+Z+ZrdRxUfW/LMUktfh7vebi/9p6j58VjX/po+Rxmf85Vevf/dd/+RLc3//bv//TAaZ/85e//fmvf/n9b3/8819+/6c3wPJQuaT5x0VTl/n38ggsKvMnisafWm7FLtXmfwN5B+xP//Cnf3UOmI2ulx4PLMsoJQWelgKe2MRTy4RSe73ofJwtP0P1z//4x/x1D+9y+4Nfe5dFWr/k+TtzyqmV+TdLin+V+TKbxg8WcXiXiTa39A7c9i53mH7hkQ1/VZc2f38Sma+ylT5/vY3AMybCpF0uNp+sn8M3qLYX+XNUtQ+7BBY/R3l+ATWNeHgdP5cmEM16mQ+wHhz6f/3H//nf//T7/zt4g7c/+aVX2P11Xdp8g+bvasJpdX6V87HJPG+9iT/PAKXpFSi+uQcsv/CQVPzjyvN0pVxyq/N1zc9yfnI52/wp8SAyz31+BYgv7Qyg4jAuI06NVqkSfyG5xwOa/4jF8xE/cBeZ8A5e2n/+47/9+Z8PXtn293/tm0v+MV3mV+WnCG+q1pq3F5bn0R6tJIQoleeA+Lp2OH4lNOWBR2QZD8YDeuARvL749UXSJXU8radA+Jp+DqRU8VMzf22rii/JZgCQeBzzG/dYVRAU8sEh/vv/9fsfR5HxX/3Hf+v//9//37/8+Rc+qmbjMvCbpNkWAefJkflQbB6aPtKlzfBTxnNEfEv3QH7pi/J7LfPDnmCk4A3VNB/dfEw5+bU8vza/ap5i4Yv6MZaS/UOZX3D1mILXNOLfjvkZlY5bZdRLH/Pif4Ty7//6P37/yx//+I285O9//+uvvDWzmi/zhs/ib3DGZ0vz5BR8bvOtda1A2b+BbZ+WXCH9yjNr5h98PKOCb6rYDNNZ5yOasVL8uXryEgDb+AaufVbyE1yikZ8FMM1ZgQLA5vcnONl51HTJdZ76R2B/+u///Y9/+uP3v/354D3+w+9//dtf/vzXXw2Q6kHoMo95rrXhS+vG0AnY8/X5l3lBcOivcfEdPsD5pWNvnsIZMJhNTDI/NqRMY77e6l/g/DCPosFXRHx7ZxBJZEgzLluO6DOfVp/fJXK4eJJdPbubj+weT/8UN9DSB+5aPz1m89n4c5opeE74dzI/VX+KlzZ/sMs7cAu4QXI+cNH5AkftM5iOMQ94mYEqp5lXVvNwhoxS/GN8g+s8NWj+xPAJ5hrHZ3KoyQFKmRhBDZr5WdftpD1BtZga5Oa/cx7xkfzhDHAEfI6TTWmb/0T3hOWCFy3voJ0nBt0D5UXmEWotqEjAmylunkm4gv9lf2QE396BOs8LtGlDdKh+Gc7gqUg0PXoieoB9DrkUvPZHUMuZgTVnKwm0U2vJiK1IhEn+ZvorFUfrKEisZQbJE19jEM02U/Da+kw4EcDwU/5JFOR7rwCtYAaa+0VmYpVbm0WLknTmVPFAJv91qid8PukRzlJm0M3zW2s4Rm3wL9IkwQhc8UOlN+QJpT3Hc54YFH8LKJGogusWAR+ZCVbVefN0v4NmtHrxbE5zgyop8xV4rAHd7/OszNfUUBAIPgn+9AhlJTfwA2uXquQGMwUuhlCIUz4fUIRFuwgohD1HdJobtOpfy+SxpQGFzJsjF5yRGZlb5HCNlYqnWM5ygxqhZAYc57O4rcpk1wO4hBWwjhdlB9fF57iBvyPwFr+m8rxVPfsd13TS5tNx3pL90jsidP1T7KCaXx6T1fakMyORgXODr24+vNxT7ThOw74BbAk9aCIXhGQTQUo0M6gBWt7wMLufrBkXDq6PT7CDyDBJANo8+EXmnZ8zaHoG/4vHNVA5eAlrBTkYpeHG8kxpPrA8Zi2p8a/j3dZIxWeK2V4DWsENnBtdkGf7PYvPzuxWgJuUz7FexmPonn/4EW7gcVNAzz33H6j1WJ/ZUqvoIuBRqUZKMuPIrvh1AG5F38A/fhwWj1Fl3q0RB3DzTKIwD55fduWCSq/ld7AWdA38fF/wkeUMTqC4gVFo1oSCnWdVaHr4dfQM1WJqUK0l0pFsBR2N7Kxqxqv5AYwZ7KuzLkOBTLK+A7eAHHTPjWY+Z/H0QM/Bh5FWkRwkUQS2iBlvUC1gB1kNIbK0OmaNt9q8nWfhTADQ70W9zIxcDzCtbxsMTRc0VJqnEDO8m8wghrLPTBy65w+gp9VegVpDDvQym4ij+PmaR0k76puoac4EQy6jPCZ5OzgLqEHUdi/zzTifU3RSFN3N+ajmm/MsfSNYj3AWNw2SeZ4H7lbyPDi1TsrZwU0KKvbdg4E83sZ3iM6TgxR3x/yse62oltj8tRU3MVqcNlDRF3uO5XzjoGdPx/EIsuEvcMnMuwTcIFfE93yAZGnfoKriweRIM9HWHXbt6vBZ9ei6sun6HNBZalC7U4P5iTe/ZnF0UUYVFJjmuxp+6+JWO7rUlrUNqnT0H2vuaCP7fTqf2C2XzKUN8t+D0/s5alDLuKCd4pfYvGcL7izr6CrM/wJ1kJzvG+DH6JY0DoZWCCiGgRr4jWqgv7NogmTPc16UxEb/BrA11GDU+cjUSsclxnJXR6EADMp/qOERPuL6BDVIvbOHqL1NluLJCSg43idadZ6o4CM9umlXcwP/HzSWRyrgmGnmctRSTJrQ5x+U+hrNEmLgt4igl9MaOmWztoR6xsx5NamgdLqrv80j9qGugQfoSS2LPyRDLXDMKK6QNugMVs2py0Ado6T8DtwKZiDVM8UBRRGZeB6IrrMwl8tMmaLVIcjxpL0FtqBtMDycZoTRrpNW2ph3b5nHps/zHmUpFpzzrmrwBdVibiCeZKMgNZynIBJ4yJ8nH4RcIC6KqNUGj90bbEsERR2pY6uKompOdZ59QROxMhmXdsnMyN/BOs8NPHwqwoMzA4hALM00E8XwgsK4NY8i87sY8ghqOTlonuBdDLwpR+sMnSq5lTRm2LIoPc52Z38FagU5UP/v35Ek6OjzUql1Fuw1XTMadWa39RRfAVrROajRFJ9xvHnOMP+wgpA3lDYjRCWoxfLBt7eUHQzrFFNFhWA+EdV5qvutwunkoBlam3U8B3SaHLTkMRNdyz6Qados5qAbPJ9Vk57xNdb0HMr5xoE/iwsFICVB3jUMXZ3Zb4mfKRWx6RHHWkWRX3G4cf09oGtQ8ZtZ1pz/pLWk/LGdEO0O0VlqYEXbRSGvTOCyCdStUOuEgp3TFEH18jmW89Sg1QvTWVAniHW/8loRq4jKtTwi+RgzaMm/mMo6d0Y+Uuf5kZmEoHdZ/KYwRqddtfkY3gpqoLlSEdB7RTsQJUsI+lAakCIRyAcKwN9AtoQbjJEvHcKUgfiDulue/wjqq36veMiahLAdPLJPkIMRSmdoY1rPUBXhnFNVRALjpxEq8foa1wpy0E0vkxuMPiNSHrOWSoI879thGb2F8uY5LaAHHhwVaaXTTcgfy2xDQ1+ECs8Ym+R6d4uMD9EDP8OaLxDCjEQS19FA6KTA7MdaBPy88YY36BbwA0lRCJ9/LKmjPTdQ5qg4WvM7VOupXAY6jOkdrgWtA/99F4qvFH1XkwkLxWYIszzKD4VeLUt5hmoxPVBPBrbae/PLB79dp7RBBtR884K2qAd3VqLfYFvQOVBjy8lyQQ+xUc+PHiO+gKapX6bowNo7UAsaB7UJ2hl+mnRmBdrRRZ/xa5MViR/6glL1I6j1nYPmxA3B0s+ZzPNjX8nBvCB7JJvzb9b2CtQCclCHGcTanm4WpHfsRfWrmDVaCpfZXtxnemM5Nyj+PmayGYM/SKjyTa6CknQI+po8iaJryUEToxi7mc3fWQHHtpQlzn9wFX2Urt7hOc0NdETEQRoghZMX2m6NA0OHX9B6OYpKC1VF1hAkpbRUSJTydfqBzXopGN06OjZLCYJo5b0qtXS8Ch5Yu6otS/ULBPKvXNpzRKdlRbWScPck0HugppRnQYJUN8dQGCaOXmA5TRA8N8L37R9xRuCZCSVmwNjSUKGsSA8OzQdlRXVwfk4N2krDuJpgeg36T+e7HRnMQ1VpfExXVAYrz91Boh5Y03WCrs7/7/zK8108zfQNYCsIQslZQEpitgiyCyQrGZVdDiF6njlB7Auq42PdA9kG6SxBDGq1XQUzJC61OnGZD8zkNa4VBKEJO2J+i1WUtpAlodacMGdb5YKO8JsntaKDEBfXDAyWUmZ1N98COAQMllg1/3rY5bf0CW0RZsaSZ7zzZRVxPpzx9wwFOhCG+fSc+EXzZ9Kp9g7bOYLAzLaxB+Y5rsrWf4Lwmiip1Y58qUBv+w7YOYYweVOrnfMs1nDKW4GQFkUFQwhJteJoSXn6uNYxBAHjLGwgeDxwPsdbZ9KXkqAFEYy9lQ6GcNdfPMR2jiFgGjJqKTOcew5e5rc1oDQQKC4yJuDKllZk0XewznGE+Vt7jNpBemEZw6QYb8GomSDkS/S4wUUPPsmlHAESvsxZxNy66Sx39jL5FQZvFTeO5+TA/hLUSY4AgtLGBXUwv1fm79RUUCiAGAE/1FhnsFd4TnIEdEz8fcwyjyeYhipZQ7FckE5F8M8JQvO7yQPCWcYRcLgjHmCqZ9QEnT/CFZg5qxnOSDFydxSjlrCEbdIfZfvS01Bevuk6ezAplfn3Bix3ffMdllMsAZN8fpehfDnSEIZsudOBFZGERtidnJBQVpEEwVR4Rps5p54xnoFoKFNQaIiMOTShKChWfY7oDEnAEJ9VtAlbT2ilVijX0WViQJwUqjE7eArmDEvAF6Udv0ar4aJtbPOCJhi65XHOn53gj9AEgS8KOym5KClUK/kaCS0jW4oaNdpUVr8B7yxNQHnGIyPCsUdtqrMzb9WrZDaNTprQxzeAnaUJUA1mKlQtUzlT+zZPs3Vgsn97/dLyXsxDYItpAg69CoWzKkIbHI62oiiH2Y2YI8U0/htcJ2kCddaNwiePC5idw/Q2BBaD5XvnCelhBOEA0kmegKJF5hytUxhqL0u59utRQzXh0dtlSlk+xRNGSHYHZ/DLFGhmHbhQMGSnA8LnGhwGPYf6DtwCopD8wECZlT01qMjRwdqhk4SPkpPAfsHhS+9QnWcJTSP9F1Y35mfXodUsBUrtBJKaPPSyZfwM1WKWUENcSLEx5Zqebyt8C+ZV2GDUk4uhsJ9be4ftPEvoMeKL7uFANt4zbYtQWUQ613uBRVDXd5jOUwTzh0WxhecPAskrXQIqiuWYNqucYmoHoJZThDbbxMhR/FNEPahBTdeu+icLy5c69jZBD6AWUASVoQgNcaIKZJGWxlUdKXiEIbbd16Yf8KygCDFUXjAX2KDBKjojOdsaHdL2hBaRHDyfpRxheMZNDUbz/8UEAthKQrY1OzCjQ1tbX+A5zRCsQS3aPL9FnWxcrZww6tNSbwhdpTwHcpoeeBbXUMsUHQZVQZ0REowp48zkitkNOQhBK/lBF0/m0IULi6CJAwOAgvF/PDaJhwNZSMrPEZ3mB1k4G+pvY9YkxFhEBbIOyUNHGefo7ljFDpyX2MXwxjLjHeYyYHXDaWUNDx7d13aJ5WPswE8z1QEehEsDu8VHPcAeoP9orbEwVvUb8Jawg1EzZDoeoud3XqDlzZNbKf7BkERfqKXp30C2gh4UsQ63RB2KsRpcZ5kyTLCtlDN4Szs4XR+gBxqzpCj/+assm1ngtTZeJro4aQWlL3uDawU9iLrW/L1DMfoueZbrOY8w05RWBuyEjs7WanIwUkWrJdgUazoDXndzeBt2BoqB97IDND5GDkTpQVezZCS0Y0BHKzA2Ndh4mTOpCkfD+g7cAnJQUwBrYL1tG7ydsYFnCyM3VhzaZRu4egdsAT+wpJtrYlK8NkixpWLGHDMdLRUIoXdNhDw+RQ/UYqarMQQgrcytQnoAtgAvg+q0ZlzwTfR34BZ0EXJkmQYZDWemEqaAZGYI6GxL9+9xY176DtYCimCZaXbtCeV6xftE1lvQhdG2FVvawYtcThGG1u1eHK0l3IXtNg4sM9/qHv7B1FVegVrSRUjGvCl3rTPnrKjggU8hyarCqZuSXgFawRGKJywD0i+nvSjVZ91cMxVS5b5Z/B7AWdtGkFQ57x9+Kx1yCGbCtGKFBiJOtx3cymNpH6FZhhNt8bcFdZOM2ygC7daigfYgLd9hOU8UQuXOQ9tmJVioMahbU6yqB29E04NItJImhCxVt4Lh6HTChhYKH78gV2lbIyaX+hzSeZ6Q2CTvNuAj2ugpkVDDQQk6DdTQW36O5XQbwfKAulHjG8eMZsLg1exv4PxaxTGv9gjlYzyhh60qa5bOLDF4yKm/eZTnsytDoksHj8j6DXhreIJnayCeadDSrZAczAMF89ymMY+AGJC/AW1JH2GEenzGyF5QIIQ7D2ddUDRoyTk6dBkHV9sn+gj+SbGx2BJKloUydvTNcM8Uv4/h6GDlNa4FRKHUMThWmk1xncBQkS6nCZaUA+/wKDFfzRRCcD3jUxjSGQeDr4aB/AZaB6BdeWW+5c8whRICexaYIQ/Llubjsf7FFLmHqGbqDuquXniAbQFR8DfUL5z0zoauVDgb0kppzjEVPDLP5NAY3Wm0DoAtkBvVYRy+abUwg+tQWhid4ukNQZcz2bXSv8BarTfqsUNgljhCtE7hEZqzMEfGMPxoMXHVHgaWD7GdZwojHPvnI3LKlzoHlWq+yv7oFVeTMLzl949sAVPooeCev98J6Pwi/SiNm5s1ajA9KozzSh/6CGq93ujmLKpKbzGD9B4vdP5Z05HBJ3bZzA7UimZCZAi86MLFA8JkTuaCoGKaY9A/M78CtIAp1GwFgLrqmMWgUvAF3sRijrRd8oPanXgWK46cUyLv1lw7nY2QxrTrGferuzDOjueAzhMFHQV3sT8mRWGntqsXluRK/Rr82OqLh3OaKGg8F5jRtY6BCBpPfd2eUf1FVX1ycJYqjmKYZdtdg0y4Ktg3cyokDp7sXXA/H90ny5hCj/kreKZ0+ObjGsmK+4P2eKHjg+vDcyznWwrBvdE57Kjqam5XhWPm4PLmrqQH9//n9EahnUFhtdaKOjPlvYiXBVLf6kEB+Z7Vb8BbwRSmlcNkdKMaAlDXL+65Bc1VaWx+ZvkOsiUdhVD2YAbQaOJboCBDGTp1to0ayin94I1+gijURKuJGJqGxkj5aCbfY5mzZfpCW3uNa0VHwWwjCslTSYgaMDWJ+sX0rk810cazv0a0hChEaXKe/Yrefca8BKMmymGeKqUHR7ry2wz9q4kCasoalS5cKAnjNyJ15iRwFZUG9hA7UzpGPfROcHSI7hxVQPEruolwCeh5m8MFSYDKwG/leQMWDckRpr7KO2DnqAIUMUHXkcpJo74ADVAwUXQhh/lxxzDY3f6IO1TrmAKsS+pIXNZQhrOYLd9EkQp1vIzxyvBk7TS9fgPuHFWgLnsbTWidRh5d4fvbMYyOg9c8zQENTOMdrHNUoWAEn7tAqlQuJJGJ8s731G+oyzZB9IBpKVPgs2rUb0oaTfsXLkotAClgbA3DAJG+wnWSLMB6Klce+TzM6IAIU23oEhI0wpWKxPIK0EmyAEoQq3Uwv5ha5rwuVVjcduf3TSfvPHg+y7hCoXl1oa9v5XWjqI/BhJQuY5H0tAfz0x2iU2Rh0nHPcFGFLR4QIdFMrd9M9DCn72e/7mViOyinuML8rjVx4ZV4lpfQeEUpsV+V77X4i4JkOj1iWcUV8P005eCff+59lp9qggWssheEbTZVyCnucpUdpDNkAZ+VsP0zrOMQo7uRmRigJG20q7ozz9xBOcMV4HLVBZUH9dQS3Z+iX0QhmJpwzgnNtB28qY+QBRjw9Ip+QbZeZ6XXMKtF+ZFQ5bsZ738L3VmuQLvcwQZwdH/wjWG1JCzZE+2Fgr43TIS/R3aWKyAE+9nCtMmAPMvjEVnyfFjIQOOgY3FffgS2mCuUzcqWVvpdtpLOVXAP1XZukWrCPucNrJNUAfJ5ZV7rNAo2KjKwfwsdtW3Sc1z6niocIDpJFWA9ue21iFBOUjcrc3atJFj0HRCt7h9Rzh+iCrn7Eb/QbMYvXRgHwt1A6Ys2g2hTT8yRLtybCR2CW8AU4pqD5Nm5AJ5XxZpQ455OzIN7wB+oXJX3D+08URjBizHCPFKeFbJRUruWgTJMf6u/7UYLD7VnsBYzBb+EO70EsnYcKedTaMpimzEmhzQ7ONRp+jtsK4jCCMvOgtFl42NCTo65DphHeizzZ6uda4Te4DrPFFo03WvjNrIMF6jMgT1cn/MLmbI7mGw9glpOFeZ48uDoyMDF2PrAvONNfmSeg7W2V7w/gFrBEywLD0sqkGQZlm982Q82rTXx1F7iWUAT/HrrkPGMXAf2TYFQ1Xrzi+sxESN7NRTxrOUJ4Q0L5ZUnMEaTDu7gyldPFv8xz+AFPaznkE4ThV6T4mOrqtBp+kHGO5rHGXNdSjetWp5jOc8URjJgcYKAioUkHVdPKoAzTiXJwZtaSxRiiR04t2TljE1B6EEND8Lf5IyOAfU5orM8oUUpCR5MZVBlm29etXDyk1KiXiYPq+Z3YE4zhVY4uq29Y6acY8xod+BLtxLXhux33xLLx5hCj7YT8m+lFloH3KFmnadvosRoYaFi9g10K5iCevZ04Zir0k4fNisYfq2dZhiVhbks5RvQllAFjzcQjcYuIvlipSVfuJ/2wuqOHcSkD1CFFiY9uGP9NME6p3F9t94oTLhAgJPuyqw5r+cKHqXKtRAGGFJ6urpQ0GMhqkG9PFbmcv4EWQjfeLi+2LafPm3a2jzjVLNK4WbZAeqf6ivUKXhAV3hAYpcHTHsGpStCTUjJFFFbknfolrCFvtVXa+fhTtx6BR9y5AXaYlfO1Q3mDbDzdGHOmyrbtKoofEBphzuZpkKmlUnfPn/qn2ILPWz0bJv0wIRONsjdyqBn+LyK2ihjW9bb36FbwhdCMdOhLR0osWCLA6aGFA13T9YzpVH7JK9/gC5YrO3N9PDh+k6ldSKcsDEhP2L2qx/Eif6ZzkKtDWWoUCCQ5sE1jhZkmBCvGCDe53t9NV1QjYwFdKl2dvCM9kZ0T6x+PWK+L9srOCuaCmEuPaOmh1SUDDyl6jd3aRz3wTVncnCQFncVauzlg/GTCLRZGM+j4xlMy2OIFdw0P0d0vqsQ0lvjsveO69iq3htU+c3TGFvHcyynycLcwN1Q8RGsBhQawvWrbtoPlx4s2yCWlWxh9JI5rFD96zFkyf0mQUKhs9VKqXB+heh8V8ETgvlM+oBwpeSvpkdotfot2LHRqJfnWE6ThXAXZCDMnBxBSQ79HtwdxR8Q2woHCcDn2gqxvAwC996S4fxCg8QpSpjVyVaSup9WeAZvCVuQLckc5esmaEzgsfURrrNoLIp9A9cSqmBRAoaGJ+EmYVcBpitw1NMQRWp9LN/n/qGuQkpkMOGiif0S8GqlAomlOu0c0DnKTVZThVptm2ozg7e9zjuOGwXnvVc3J+6qrxEtYArO84wKpAwdSNZ53MkU8FqjgqePTEH0U0whlUo9aU2DUq0MZ1R4yQvNGP17tG0QrrwDt0KA5FEBU+l+6cJQOntAmweOhlFwuk3V0z3MyrX0DtiCvoKzFnrseQIJMQ3MtAoE7cikVDz2ju2sPUG1mCh4lsvRG8+ztWCzWzOMOCptghMGKa7VqmHv0C0gCuIfISjM6H582O7D1rfZo4FhTJg20IdzVxoS/QBR6JGRF4ooFUtOB8dQIE5AKz5WmjAJPXiVH2AKKTxiOaGXYKLTUa4aFDNObYtz/Nb31nYPqBZQhTb3QXG8qmIPnbLHp5QHz11RTM7rS0ArWgsps0TvxxvqrKjEIPPl5gJnzQlfYD444ou5Qs/c/d5yg5q0FW6G0tuevhIFrIzz/hzSabIwiifo2E/QFYYLtWS59/sb28Tx0elZxxVCs8Itz61yawPsfdK1B6RRAsXo0sGbWtpZiMNC52EPPJC5D6jEKiwysPomZmTzQWdBdGVnoXa7kGwXwWAzrzZMpYMrhNIQH/+Lp7NAgmSoTphCShNx78YVkN+ZxMYzhdXuA5aPcYVRZfOL9s+dO4xQG5jZ+FAknSq0BBXJ34C3gitYigUJoAshvZhyVt77ehvDG56D0mdQ9RvQltCFkP/R1r6gmYfLFqvqCkhNsrD/Y9f6AdgnOgt+cV1ARmNQFlXVchu45rqMpob0r6fXsJawhRja4NB3QmkDC18ZMNkj7nLhbM9rSCsaC/FaBHtUUVn1nKTeDFIhAwxAZW+QylUMa+iCXFHxTHtWjqZ1rAtCnMjz0xyM7p3bu1IsHcVo9niH7id84R6ZJ0pGSW3lymPHgGk4Ti/McGqWR2M3JqV3uH5CF+5xdX8s22hzw/KEIYOKSfS6Z+xSs4RtBXdC0ztUZ+nC7om1NjI5st8+lmm2yfoGmoAonaXrzMVdiegQ3E/Ywg5YktQuuCD99pkBXkq6peUQIaVW6NV9V0M7BPUTrnAPqonTd5jDJFV4ogl3VcL0ErrKcMGEgqo+glpAFfaPKjs3gRqhdwFHaFyDkW+5XszocKvBK1Q/ogr3iIzzEVIFOhJFiwq9vRnuNewA68Oc1QOaH/GEezQ1NN6YJvSMbqr8PNG5LRSbSZf/QYJdyxGek0Rh975yDUNQDPIOwbzsMJx16HLnbL+zcyw06c8B/YAm7I70cILEjIU7mGtJMKmYWOZ8V4sDJvulFzssP+AJ91icTbJoWdKAbtRP8c3zD5Szh8+d7bVixHKOJzyEoNijhqnKYvjtuFXQsYNEo6onMHRAai8g/TpR2L2peWehU4dJfOPPgolX8l/W8XN+geXXicLuTaUCnb9q77xH9CZAGmzEjEG5SnuEspAn7E90yShm5iY6T1GDo0nBjD6EhqN5bsXZJPsGvJ/xhN1j68oe+BjGcSCUpWHNCMF2jeWZFCD1byD7GU3Yxci0feEtfL8w8ZmvG4bZVWjT6XXiP3ijS2jC7iIJpRu0DEmxBSu2LdLbPmCjaR6mHRmZ+ktYP6IJuyc1Mteih5MOdH9YzN5v/aERzvOz5qLyGtGPWMI9ooiRFyxyQK+c0hXOBaKiEZu0234u0P+vf4okeArQNrNYg0+k0BLcAytaj0iJnQJ6qof9HE3fwVvAEqxuetriLB3zLoalsBCVxovFpG7IjwxbJd8BO08TcupauNU0iWK1Jpc6YDFMyjhTMUMHDxZLz3AtJgqeWCqqPtmPe0VZqGNMrsDcJ9HUPNJRHoL6Dt0CpiChlkHbpcvgPh/0hfA1cnN0KHcv29X0Dtd5suAB3iiyH9p5SWu+uU/Di6iMwm0QB29yPVfI4fGTqV1JyK6iqJGvDghlK2T1jnKbjVfAFtCFHss+WfCJyDlf2RcRfMOO2dHpv/MSzxLCYGxS9+x5+axOQUaCOI9xk6g0PCxeI5y1fKHmLakLEyIEdIya0PuHGo5qnY2F/BzSacbgly13YFSP4FjBBnkNuo4VevnEzmdpz7GcZgw1KqqQbZdUOidusCEWVcNZQac9fT6IRksJg/RtmtjfWcG3b/VmqdM6/aOcV+B2Hi8gnSYMob7iZKxsMiROASEsIVmPuqe0h2WUOzRnKUONdY8zCoZLM8bQWW1NKP/Cw9mP+pTW2cGT+RhnGHFG0Ar3qI2tMtgOULhrsfKbN9w0eeRvwFvCGdTzTeHYMDodCidEruuAlLvFFuCD9QrPoK0gDaX2Ohv1/kYTi6l6Gw7ghoOofaK/fhC3P8AZ2rQUAWdISOQ8MqSrvgYuLJ7PxLsse/fBA1wrSEOo/1EcrBVHqqAEhf4LmkIldw4taHkNaQFrkOG5Lcz+Kh/PmMUelO4aChyDszzl/mvM+jHaoCGKhOxY4Oqce+WCGJB6NEtzbGvVB8HPIbYFnKFEnQy0xXJvfF/z7SkSpsJFI+Z5coYtbnsH7DxnGLHcCTUET5C4BrzRK5zrpTPMlxtW6NxPBdzBWt1bEL8OaXGnDAcVLs8YwqYJdMpjoxY9v8O2gDDkYpnef6ljwjHHzfNlwnlbsJDpHyX1Ha4F3YUxuLsnNp5AGFyh2ELeAMm5H0V6y+wjfdZPUIa5ewm9R00Fi7NEr4tt0feLthaEjUVeYVrRXOijcMK5bEBQ5rObr5zFbgzMzukrPCvYArbGh2CrcqaaS6Su83v+5vplUyY9oFlLFvzSM/SDPYNBQDCachuDEjykFJ11leeIznOFnhIGWbqi1elPS7a+lAgsHv1VYTjenkM5TRWmNRamAKKtDrUYlljn27bRGCaGW/7BY1nbXOhSLnTKyLWxToCuP9quULNOwXR9cFnYQTrNFeYK6wI7chbL2YzqmHnBwp6wDm8H3YWsK7sLqhQ1xrZ17NVGoQImmxhldDIll7zfj0koH2MKPUR+GIHtA+Wcju2rpfPyJTGVCkOU1L4BbwVTMOcnm8t3wuVfBVVCLM6CR7nmIty0VL+BbAlRaGLc5eJEC92FbWsVnIHZrakgYf0A2CeYgqfltCKL0cUMWfvX5YNs7eeM0YYur3EtYApaw+aEdc3UoIeceSf0eByPrY0m3PYG0or+QvG7YhZSu+e26HPid+fbhhxTNCd3zWqRTxGF2oQRy4OSIjNnlcOvYjw3LjyIhT4cgRr2Dt4CrqBR0oV3T7KmLA3R2ZilOmwRCQUzphzLW2ALZEhRLRPukNT5Rlum5sEgp+R4c8fhyjvRlsiHqEIwdaEDmHlagJnBJBwJH+QQtD6n76TsJD8inyALfgNTqBKrFbgJJmNFslintG0Wijx8QSHb+jtgC9jCzaCmCAecK3CivoBhBf+xyv2q9RHU+v6CSK3ko85doLbp1AhQpQgOFuJqFPr6K1wrCMNwbtI5ESMVwwmDO6yuObol437Sna5EZDljSCbIb9oIQ0eeHmSd85aZJknUmWZ9hLOWMmgcJWSBDVacHlvHbfc3zQakZqiW+niOaAFlUE6k1/AiRgUfs9X9urnZKVejbXB5juW8ICk71eQKAeuC40vdNKb5sZqCaw3k4OCs7S9MiTLfWWFlEc5sWKiHpvYwpzp4Wjt2J7KQM1j4lkNL7t9ORZmQq1TwamCoJ/75lYdR1B2Y0+2FFquykObCAF8wwMimJmfDR/Rk5bHbKvLR9kLtdD3MQ8GlnB6k27ggqgTd8YEJy65rJvKx9kKLnWYIjmPA2r2VdrPjZTQKnzsMf5X6DWhLWMNUS80w2TqqhhVFFUzR2+aRy0A5Dl7pJzRJfnWwmBNvE70t+tqgR0z/4EbVaXuDa0V/IarmTNmkVRio8mh9MVC9rtOp9hrSCtbg54dvj2rbDCW50Z1sJpz0Vd4V6WR8ijVEIQFazZqE+78HFPmNhu8QmafaPYmHCfROMyXjI6QhitKKPU+1gpWazrNkmxcgJmd62PShw1bfAVshSooNqVwVOTB3FfEeJU6sPsGuL3gDNrolPQG2uMVgwxkUujExfsm/KSRfDRIO1NGc66OOpm/BrRAl1UGpZJ4+nHSLQt0Re/+4UrVk5eyY2Ttg52lD969xtoE8R2D5ikYXHbOiINK5JXZkcn8E9YERhtjkToePwr2lA5uAGcGQcEVHqcID8RWsBayhxZAoC0CSafuB8gdLkhiXUwo9q7wCtIA1hH0LR0Bjufy8ahAZsN59U1nUC4SoBw9oLW2AaSE6MmB4DRaqW8pVuXUeTUDLzwGdZg1j7nLHoq0q/AuUzdJ1DNOPT2uouWt5DuZ8q8FCqc/1eegJeXDq171+HE8fXMtdDuLRUtowN35C3aLVkCRXGJcjRHJev8fC0sJppqeQztKG3hI3Owzd3K6HXb3PKtTnns9z1CpnfQ7mNG0IRQ+KJ9aNCUDlb42PCPewZ8RoGB+F6M/RBmu2LV3QdJ1Am/nSuNU5C9Tmxo2I7/Gt4A0t+ZmyzfyMZTq7VqjhziIjBgZ6f1ge9wzZmlGGIFvzXNeMvUtc0g1/mMEZ25SgOR8Hx+sDtKHnvO1g7YaMszSTL1UWEvbYpVj2I88HuFY0G0Q6BBoOCN4DOp8JlZRb/scJMZXXiFaoknrk57CmqJy7hkHSuFmptop7565Qp78l+wBr2NZ2JG7y8BQTKa5mWi4rJLiDTvhJWf9sdxz+EN452oBOTGwcxWSH+O1LvbD2q09/hqeN3z+hyLWHNdOHwM7RBkVXn5rulgGn12TX/SKwXw5NqJC33tXM70CtowyQa2t4HRjdPzGG7REeLlMwEqbZeDe54E64S+4OwZ2jDLznSrnA+9LJw1QmojjM1ByD9rG58MJ92O9AnaMLik0BBn6lraA81CoWJFUqK0nD8oV/+ghqKV1ABjUdp6EhHghZgz7CkN4h25Gx7b1u7RWsk3QByvzcsfnXY0BFy0orHKjTdY6uhSFYe5DFPwA6SRdgMmmGvlW3UToWfs3cinu/Zh3IDznKenJwmJbRBaU3Q0G33cPpoDE8l7xiYAx0M4a1y/622SE6xRc4KlculG14LIJzIu7Ech01dk5hWy/rOZZTdAFfVuKWTQ/hmHspUEtqvS4bUr8PUeY8uvVW0QX6I+dEumAdYiAFmYOJI0foW+2NJ37k55DO0AVEoLrthortOP22r4r20kilchBxTqE9B3OGLsAmK/acYqIyNZRKKB/LNzePHjlcKU+i4UfogsLJjpUkyZ74gtkJXILntZZhi1vDPhm2gPoNeGfZAj50Z3Od+kSdlMYfpVyZOUYuJMRBl6tu8j20s3RhnmPxvAhlndygxh+41OgnhamQSOtmGjMOPr/FdAFgBn2b/AnBZU/BSdn9QLFM0Gp7B+okV8DQSSEgv/kTFuyWvjkNTMsGyCg320IdrzGdZAswSBWhYiwVLkKBsgaCsoIMRi95r0zS32aC9RG2IBHPYalRwyqJf8/Q3EbSwh6DE8ALu7jvwC3gCtYyar/x3FAL7whZjWVfbLhpLRalKLcxvMF1nirEsg52iP05NYge/E/1upMlc9Ci+T2EmY/8FNdatpCdj1aWgWOdbGHxQNBCYoMZBjIx6IRide7v0C2gCyWMizG74JlVZW+Wxk36ZdNOPF1MhjV7h+s8Y+jFU0rYqHpqhTZf4wbFdDX29jsyzGfz3tCQoNYzBr+gK4qbEiIFukI3BAoEsLxtCNZNfPwK2ALO4KnuoGLMmicNdDLu2+QqP8dwWwMDHK8ALeAMOrfh0pAMPhsFjqr0bUAVaHBdvRzgWcwZikcsTMIkw3qB1q7+/Zvz4/QrA1Nv5Tmk06Rh9MzrJgxVC0egYc93lcqPFFrnsbfZ2mE5TxpEGxtmqgNhB+t8CjYO0niDS0APoKzlDKM0ytVq+DxDYof5YpxnbO6QUCPqs1i0ijOMUnhsYosc+qxMN3O6raRxrtUuOEDyHMx5zhBC5Y7iPdJzGGxx8Bm8d8R6y1maPjrCH+MMnoOMzTCqhU3FrBticGpewB1SruQJOWSk9xsYnuFbQRosak9sNcYkLwQHXFw1SWnFcu5SOQ8n+g1oK0hDiSV3UCKGgAoiycyTNPuyHDHOYFrt4Pv7AGmY41Yo5yTBclROG3MkTbgXO4zY+wFZfgC2gjjYxghyiBUFBmG8f2lhg8p5vzyMiR9AWsEb0jAO8SQPRMjaUaDLNwM+6xl0utyf+EnGPsIcNJT3WB3QO4QrG10e+AnUGTxhGR7hIIjfpSkH6BZQhxoF18YBwoZBS0ks4rN6Td8W/2grHTneAVvQZmiQaw0n6J3WUvDYoE4/o3LuSXyhhOkZqNVthp47axnq9w3LCMLVC7Meg4XinrQzfoUe7Q24BbxBYisKHEGT0g8kZ/r2YmN3xujKaLQ1LG9xLeg0zFo94r5/noIdYPlm+IqU2I8+C7ejPIL6AG+Iwg+32WnY0U22DPG+Xg0yw6ULxZEyXqFaQBqsJ73QfsBjF3wzMceK5h/2wm55lrRXeFb0GXrlUtIcnriYokPfqt42hdb4GiDY7Y+AFpOGqy6pVRA8y3qTSAmb7hab6FEregroNGXw9Emg2I+e0KBzMa+5637nqXUZj12hOyynKUOMgSPQlFJbx46DWSNDqjyL6hZVfdkbBRLKUsqQzK8UGMe1ZDPy+EHmFg84GM+UJcz6KFCvzyGdbjPENntj05W3/kC2hAYIrTNaY+08vXg+pymDxqmZrbJcB//sy+5K3HnWpdEWzB6xfK7NYNEDQTZSsYC0d3z2iftxYPnce6F3Z27fwLeEMtTwpcW44OjzWKt2ve6uQDgo/tltpueavwFtSZ8hPiwsLm/WcMMiBbV8ref7F5pIFnM6SJ8+0WiIDfTQKKZkmBpXerWgww+Xjxjhhhl0eY1rBWWYi9uQZJaBjj4cprArRth3CMO7MR57DQ+YVnCGNgZ7DTZw1TZMyNiVX7VZBcFC+HtA7VOUoWpNF+qDUwP3Uy5qSZVkiw43Fn5w/cFm9RDeCmlSi/F6yBU7K3WmVIlUZu3zearndJjm0/YO2IJ+Qyp+brCPc9SOPZ1lZlLQ5fWKL7Jte272Bf0vsBa3G8aoBVLObFWUDaXeaZ3C9AYeGV3Zbmhv0S2gDZ6/cB7GWVVD793/ImNiBVp49MAjUmBAe39Htk/0G0LJgQ9RB1YXN2y1QcWvcnSlZ+oqc5JHVB+QKMXEHJSCsUqU1Rb0YWClT3eC4PyylxY/wFohUQpjPMxRqDS4qmphQPgieilKCxx9BWgFdZjjtUhgrLBzRWeezfzV0cBHJR+gWcsbNGZQuPSyYZ9c65AClH6r6mmMkOmD8cwO0mnm4Gwqc+12+D1nrNuZLTQcYzp7lm3vqtpzNOfbDUbTLbGOTr9UuqtSijgvoIJGoxx8YUu5Q+mtXijqlsH8SpEaTIMyCuM1PAJRiy3PIZ3mDq1v5hXx1iDgajTIxh7a+eRiXnqSh9GegznLHar5W4DtVzc2PEGf8m0oDhMNnAR5xPK5dkM413Af44il0zNas8XQvmxCClt2DA7Irh58DHAJeUAlOBY0VvQX4HplGNeBU1FPsErIVr4Ba0mvIYxuYHmJpZuekcvteuMrTo6roZjwiOsTrYZSScsl1rTBLkluBtBwuMnNeoc5wlGSspg21MlRuLERs6klz58eFOGANYxt2XF5DWkFa8hX76TMKejev0xBo6InHe/urs5q2AG3mjWwhu+XPPRtLXNpS05ww0WVH2My/vTS4My43ZVfDtGdIw221cqh7B5RTkTm2eFUgNSlYjpTB0VWJb/FdY4zgHc6KabqIQ34kVx9VulN11CE9f8Gl83U9wmudaSBc3PKhckldfr+KBRBwrnMbYWbXa6+a2+wnaMMRk9VARMYjorL4GE1JZXz/+jg2jZtfFcdPsR1jjFg8HpAYZmwE74PVCEHlB0YfSpSMfGT76RmhLSULuBZQVzjrKHCorMrxXgzcoG4WExO5r205AHTSa4wo3Upm81hbY2lYaxCYG+7YUZ6i1ztFaCTXAEmnYNlqqgvqjLlGzf/zvlTxb8EQ1R4BLSMLqAyZZUb45ypywxVhnlRUJi6iQMNJvy1PUd0ii1gd3B0YSA3GZhnUJji4upD9SWlyrd6dICWkAWDfTJvWM+XBmgcFZz9asNubXBS/c76jlhWsQXj3EChQqR5mEafukEVNHMZpZlF4fadbOk5pDNsgeFH+GtSgVmMc9zM6d3pX4TJ42GbrOUFmjN0AeVx59doNWij7V6V285yocdzzpfNuPcBy0foAk51M06kt47tQq3B2wMTDQMVnrFt2skjfQPeWbJAz4N8sW1TTqLLc7t+a4Z94iMGRrbywjegnSUMmPDo3JTTBa00GTRG0euyJv/xYketLCJbTBmwRtnytXGELmyFpw3VSQhSkfehAHXnM3eA6yRlmMe/UX0kHT2Qhpwzgfk1bjGuqLSavAZ0kjAgIjkxn1/akAbRSP9im8TkVxSvrtynSzl9ijBYrI1CghR7sgcqLYhimIAqug0f11xofFXGO3gLGEPvXGxQrGLTV0zzJiwZp9xttnVTSReU08o7WAsIQ0x3sOA8BiwUR4L/eENsmxW97pFsM755+jLX8gUJq/pNhZs6DARj8BC1KtSKsLY3df8WZXOIfYNuAWOQljK8GzxWdMwZe9xvfDxTTMsi5DbTsGOlOX2AMdjockGq2WGSazAEokvI4FiUH/y89xYkpPWMISIWHK2c/g0oA6Llp9edxpyIDhcOWsC2V8AW0IbuXO5CAmqpzbxXO/xV261N2mxsG8ReAVpAG2qMZdPhvsNev6B+DatVZZmYooGDL3AtaXCCUiCGbbH5eZJgmrlQAohD7VQLsqEmzyGdZg1diyBG1fjikYzPYMSFRB1rd8aF47/PsZwmDRrTq2C73aHUm2nSZl6IoVH6DMjBc1lKGkr40CZqp6tgP8M8tKWgAErPzqDAIOnjOaTTpCFc4tCyjqFs1IUxtJft6ivuRztTQHyvhd+hOUsa6qh0xrCuWz2n3saglcYtHjXRmT14Mp8jDb0yVQkrJ4HcgL3E+Sgzxn4lXP03e4338FaQBjX/3rCBtOS0+ZnX6wJoNB2d+qWyja/oN6CtIA0l6CYCk+dzWJMi/WpcUVE7t7G5JvWDa/cDnMG/MkWEkrAGgg8KzNwMLT5a/faBe2fYa1wLOENtsXiE1Wos/ynUZiC/6vS7CAK/N7I4gLSCNZReYb3ZFYJBz+e+rEQaUC2jdbUnDe1TpEG0sSjlr4nOoRxrQBaVm+AshTLJtr1gb8CtaDLEIgT4gjpbT7QpmgfKOtc7QpZQM+l7aeUdsCWkoZP9ibM/qrigNseKoAz7fA2WBXcX2Uev9rk2gxOoTfejYFX+Bg1iWQypzFgRE4CX/tB1P8S2hDSoUDOViiRMfhRIuYTbyRS3o7KpnPffZPtEn2GMbfAvD/hoe8KlN00xphClRs1aDgp9uX2EOCRtjbY2/hvRdx/CVsi1NzNiDppG269QrWg2tJgoBnHnpuyGxXeY+UCQiLVFtb3Fs6LXMFNRPKuRKpcRJDDi68IID7QGsWc5OOVraUNRv3fZymtpltYbDPvyF2OeXIZUbhBMzyGdbzbEfhtuK6pGXj4fDxQbuIhHS6AN+uLxnO81xDwQWwyloYfWaO15JcKx7IZFloNguZQ2iJTKs1MzZkIVR0fmRw+5aRmxwAlDkSbPIZ2mDX00NOic/WKqt2CSgbv/cINMW9zC/P0pmNOthm60SAvvaRgcYHAe5v6sQ0ksWBt7xQixfI41jM011LMl0BgPS0iXYEiCpbSeJ3O3UxCv9/iW9BpCiEz3pAqn5WqwwIItNXrWYeR92UQS34C2hDbEcG+HKB6LzjF/uXl9MJkSgwyvH2R3H2ENaheSUCng7jI28/dZ7UBXy7PmrPtZwgNcC1iDhS3t2HYJYxQO44Qcg0YDK1Zo08pCXmNaQhsKMY1mKGWmdOvxG/Rk0rCj4f5znP+hH6ENnlJy7a7WgsUtUrhklY2Zzsqmn7oMPhp5+xt4K4iDpwEclunWsOhDlFvo2KttcIcLH/ZKs/83wM4Th4GUJDfDAuOuaPXN+7fTmy6qCpjQ0qfPanGnQSC/m5ugtx3jqJttrdPEEa3CUfsk76AtYAwlKvUF515TpwcQSgkQJ6AWmsNDE7Fil8Qc4DpPGJqTTJA6lYYd1PSlzbDxQ2XdIjOnJO8R1AekSWE92fEZ+t/GJkzc1rS74lSNox9lr0R/gLWAMFgzDoFn8bQPImsOydzM27V45ELzqr4CtKTNUDJGq0bhJ1hx9BEjsC0lD7bdJD/iWdxnyD1jSUzzIIqtBJSkM1nYtF2dvr3jOaTzhCFtOo7q7wvCXIgl7KZL6LGFLumTm2Zdn2FOwaDWJFheWuDaQrUphFzxicl+fp5Y1oqTRmGRbLoow5ade6A7dsHPY5SiI9SpAXgK6SxhaLFNS2VbloHhPXRBsAuJHiAex1EC7S+ez2nCEL0VrG0ddH/42t1Ex8F/qHLf+cER/hxfaH5atdKTBWqbMmFgooq7GZz7NaH1yK4jc4xvSZthNnyhiozlW5N7oUfF1eJwLMr1aln9HWhLtElhAFahHR2wPCilXfc6ViSeI0orZT8oQ1wf4AvWY7YRXYYw8OfC+tuCamjQerzLCdrqa1wrlEmpDipwJQaMZsDi0UORA7LhYhdsoXyNaAVbUBvgev5LSaDq1WwVnCX8/FFn+Poxtt/mx7CGLZQrKHRd/X67cN/kQHVcIimYfYWOvuzgzrJBOXq9syY6RPcTsnCPLHa2NESmUvqAVqrp5HGgDoKaQvccr6GwXuXtY/sJWdgBS+HWTz8pnvOYDb+NMjAt97jWMPTX7Rmss4RhB61L1e2ai0SK4QB7TVmShR1QjbiPwbq7ntEhup9whh2yUpNc2KRpNDuudKFk0QFRNcr524X5BtZPKMM9LE8eBAsFon+FayglPjWsRYXlaUhC5aHCR1QLOMPuaWVPZvALnTM4GaY/EPdo46GBdnUPYKzkvgL2I9ZwD6r7waciz8yv75l/gihzoxvm1IzWSVVfAfoRa7gHVP2dQcE1QprP2xChdiumT3ES9SWPcE6Sht1L88uZNLz1jP12ndVPDEDTxtcQw8ZzPD9gDPsY5TwBXbHoxszioSJc0uuUhrTbam99geYHnOEejdWQJaLJYAm7nht0Uumaj5p0mvYc3S7nOMPu4UjrBQI6JzCoW9SOLx0Wolgi0cL2DqEoP0f065Rh91mFkKZuWxyxUyPTPDuDG8OUZGxmx1meo/l1zrD7pmqr1LFQ+CvbMhhIIhMyOSU9toObbSFpeDjVnkFyenfwXWF1NzcPDaQnlimDlSLfwPcz0nCPrYVcBTddMsAwzg7h+wJTTkLfyXwUrxdxhntkJQTeKNMnRavP8BptW2c1veudkCFuHoSCJaRhd+5bbPpqXCY3SP0QSJGuYHBFPR+AoF9f4/oRadid/qG8UTx9SkbjpCnNuPnm5hxLQoftWcMBpB+xhl2CPgr9CEZiMROlHx23tUilK+PrLnT2T9GG2LF1oW1ihqW4lLGtdEOJDFL4mv3QoaXbmr2Dt4I3+JnhaP0I1oLsE2ahSIgrxis0+5Hv9CN+B+w8b4jlz8g1g8ZAPz22EtH8c3iUFOrMcs/PQC1mDSNcJVAOqv4oIIBTmoAUqL9Rk9VujL9D34FbQBrS8HsGXqYeXhHisQMkQ9RlFMolBVPcx67+Ac7QWqNzlFUrmRZcgwuBIpXgVxqv2w4CV/8MZfBbhxtvJPnr0dv+IlQ8CtiXcxncjXfdjwdYCwhDi0k0RFNxPLCO58yxXaexrCXqjY+C12LC4OG9oDBWsKrbGfsXq1VYVSod4aQ94lnLGDyd4kYEk9oh0ddxU24l7rmpHPyr8hzRac7QtaTNa9XTKQQjeFphuAPMJqZvy35kfYflPGNIKpcCwU3DdG8R+lFeXXo9y0soO5aDSLmUMTgDKBduSFLDcFeDgRNGoDN6aCZG+8mWnkM6SxlaGN6ymmMY4uWaBoG5HfhLCv+IxvUtz9GcpQxaAw2W7DUoohJcZNB1hZDMmmUU/NvBwfkYZeh+01KbNRobZQnLAucZGjMq+a1nhdY3pt+At4IxmJTOYa8sUE8rKj2Cr27iiUUpjdPZd7N6z6CtoAy1pg4Xev/4cKcMfAiYk8EDbSNvy4YP8roPUIYmJYOcSuyLQJEVObkxbkGbFwMGBU5vL3EtoAwaSyoaJdOKGgcNaG+rpLJYGegL6ngNaQFlKNH+aRhQS6gsoGUFfy7r2wxhLXsXp/bbDGcfoQzFL5ULfKY65NyiRTYXPpyxzdLRj3yjb947dAsYQ4uFHvBsDOMrhIE2GUNDa3k0BBMtjd5X+vaxLeg0ZH9onFHN11WFaCTDwzpB51Vi7gFSja7PcK0mDUkpg3eq0IUrRWFoXWmZS7Od6PtBHvf8sK1sNUR/5qp3g19DFtY5YLxToAfqfs7QLdlxrQNgC4iDp8Bo3mrsxp5Fe9FxU/AKi+vKIZZ2cPg/QRw8vcSKBj/7TbbGKDcHXgf/wnuqYqTBXgJb0WuoUjmgbp7NwO0KzRhQ+M7wVvZmPA9oVvCG4UlEQqMhY/SqKNa7jY1e1ejuovAhj3AWNxpi3otNBC3z17ecyhfXmc7tb9xxtku57iCd5w29JpB0J1OKL6vNE0MpM8ToMYDboOh6iuU0b6iddreeQglrdpj2LZvxa9gsokuT7RHJUtbgt1unT371nB0NRRyfhEH+jm02qWFt4JDniE73GabTOTKThoHsAj0LWlVcEONv02jMI/U5mtN9htilij5DRVNBKtXdsL/EddLDZtWeRJwP9hliBQpqFN2jI9xNUQ6DgzAq53kYetWS9RvwVpAGje0RXBVckRFoZp8G5QNkAc2vwKwPQ3HPoC3pM2iXC7fhKo9X+rIHIUFhnRnY28GN+wHOMFK4JpEXNORuuW8WtBGOMAE95UJos4/XwFaQhtxY88rqbBQjaM1uI9BUnw1rWCRs8hrTCtaQwpG2wDYMg2gs0G2jqBHqjQGt3B/4ScI+o0/yK47LDeIl4fLHgo2G2n6fKIeFExB/cLwDt4A0FP/G4Ewopigm5kLxG16tcLdG7JkpcpD+HgBb0GYY4QALj7IumYb5mCw2mkygd+U0/nJdIfgE12p9kvZNQ+Ih3gYXJ2FcYPLjTu2IVjrhiOR34BZwhhy5EqfpE4fYEwVwmPXDmsOmHk5QtNnJpg5wnacMPZTfM+31kApXl964ehwafXg7xe5stJaOUC3nDOOaEOfWWxH4wfZxU6TDNsTIw3Zd+B2oBXzBT1JHSzbXPtKM72aoErdr+LK+eYoVewVoCWWIYjrsAWVgDULFzggO1sI9OlwQ+2OvYQJaSxpi+zqHm3NNaN1C9II8GVrZaE1yBU9/jmgBZwixD3wZwnsVA2Cy5ehYpBiq9Qs3UD7Hcr7XEAKcvg33ojYsGM/eVlzNw8TseVeEnViWsoY0Ek14c8wJYFs18mEQYGTIPRgVRg2OLuNltGEOTmRsx8VTgmoTn5Sythc+YfZoubMDc7rVYJkjQJax18qDjl0tBQptOrsI2sHt4Ax/rtXQO5enhZZmst7eBnLMSncSnHO7FfW+gW9Jr8GJMcQ2s4ABNy68unmyrFHr0uulsMH2HtmSVkPK22I0v+Aaycv1uyNt6LFyCnqSdJCrfKLXUI3OSX7F0WySMbJgUSnKxDlVrqWz17hW0IYa9QRQc+4ZaPOcj3Edvcw5dvi1BxOLA0QrSIOGkhJyLtiqZSCy27R4CycLrBrYfY7jU6Qh3hSqTWHBaZy5Ktw6AIbMBQ3lavFg+0RzfESdFPtloPoRTwwQv4eiGIyg3zB3CJ/v4KdvUJ3nDJ4yXe00MtTCDdVoyLwb9Mv+ISh9AXb1mC+oVrcZLE4PfmcI4BFfAaiiRAPzeA27OrYZWn2HbgFlqEHiOVJRx2ZfAtE+nhqGV8wZIIcHen+Ha4k8aWB0XtWwT9iULs3pZkkew5Js8ZZHUB/oMoTxRwUJNtzdAzKOba0wBx96hvvxrg+/g7WCM0yzXNTI2oA3JcuzkKWjt9acGEKAkl4BWsAZyjDZJBIDGyL8I4SUY2t8lBLLbvb73IhmLWGY8kh4JcXKD1RhaVk9bu2quTMC7lf1OaTTjGGEYxv9TK0br+ApSUrX+UfP3gsMOeqLx3OaMfilkpCzSOxXxpjOvHJn2wMAbCO/uT1CWTvOEDvWscVDBR95rZADab/eKyUqCNw0rvIc0lnCYD1zoWQwGehFlIYxdp2R88897hLFQMpTMKfbDNrYcvVrl3ua5OaHy21ufuPlTcH0iOWDbQYnBjCscBrTkLMNwewJa9dolfjRhxi9tm/gW9JnGDltfYamuq26gFv2DJ6CNk0WxIjYfvke2pI+QxMOCjXL1CjjnWKrDRrXQ2NxjD2KgCawj4iTnDCgGVRQeaJEiTI46AwsJEwC3etrWCvGGTwPvmy1aDQbBbu3ELykbqaPF3puvIa0gjB4FodyQvM8F/RK+nW1DRYliQcqWP1/DQ0dK+FWE4ZOxTRZaBn8udwrl1JD0sgZzFo2a/Ha3qI7xxfYxG9UjnlWO+DxVgXTJ41CfWx7DcNtFDdTfgfsHGVAdVw8E6GFds7gfsmwBAGVoLIpvhuF8Peblu+ArWMNOEc9pU36qtahV+RjE0pYILnxixvXUL7rGh2CO0caWF8tTLvHKFwdUeq2xw3pO6Z7wz5UHqyTDnGdIw1zTlUG3UotVgmDR0Cb18ptBWtKIZjShz4DUS1lDdMNyMbYqFMYOsD4fyYQYPEQ5aQyLsygX4E6yRngRNs7dcIxTlu+9BkaVlBNiDYoH3gN6CRnQPlcE2wuhvGDK0wb6BAG4/2OGbKjM76MNYAaeOYJlwjzvEXRdrkemUCAgRAJ0RBM259DOsUaOlgDHeM1Fe0Uc9GAfVtpGv4ItMZ9geUUa4DbWOwvpj4Lq2wEK3ZwD2IoJxyz60OfgVhW0QaEohi4BgNXRYVADdcufO+Yrkvi4bkv+uwgnaENMEUZGWWLkZJx1jhfG5349mNIJuEuuR9p2IE5QxvwVRkzbuOckNNx1vCvkdovGSfI2CiVHrF8hDbgTMd9ivdmGOSn+o8jDZylldvkQ/0GvLOsgWZbG/fLNQk0gWpXp1UMpoi/63Sh+9Q3kJ0lDei9im2SyQELX3hicaKBDhax6bCPvS8XgS0mDZDh+8dFoVmFEKhmKgbR5aO5UyrI7bq8xnWSNaAxVFn3yTHDi4GUYbc10AjmPeob7UkAX8gawFoKR3r7EK6BrretboryWKn0E78/7lk+xRpqT3QMrqPx5yobQ2CmMjBW60feuAHSdq8wyydog2cguvl6e0ZHMzPstMB1ozCijKo6zM5qegvsPG0YkUAhr7UMnXKzfksMGsRwI0YGto3Wz1Ct5Qye3MZGVdLQxHjfeBc12BxjxVtsl8J+ypregVvAGTzx5eKI5gGWKik0s3BF0x9PwoL7sUd6COs8ZTDr2Dqgni7Me8a4cBEadM6ThyxeHvyJiGk5Ych+6Q3EeSlWC6rCg0/FqHWbtX1nr+A5L3Et4AxOPzvMTf0OsoTBWno4lOvSJ3P+frHHmkeW5ZTBjzSXIXhKWmFkzX/ZdlgUv6Ivui9eE81iwnDVQPn7Qn9PsYUP1w0VjFkKmjUqzxGd5gst1k1jpNiScXJg5OuE+Gx5WEhirOxHPXZYTvOFubIb+r7eO5bVoGHMaXWBAJA2h2KPWJbyhRjgQ6c8a8GzqQ2hZzKsBq5ZUlMcnd6eIzpLF8yzON4j4ceHujAqnNysgV5n+OFJPShYZFnKF1IDtVOWJwRzDNQl1a3Q2VBTt/6I5WN8ofsTofZnFJlnp2GoF7PrrUMUn3RbT2TpG/BW8AWNvVuD/uGGShOzAYpuwfo8Hmwrv+0b0FYQhtKl0qxUB3chpW0KO1paSNJ7lovu1T/E9Qm+EE5qqDT53Q9VEvO5r6ZJI5gpZt1fw1pBF9Q6tSNF4HVc4DEJVVKjYKk0qNKP4vdiuuCnvEGN2ArsEbJxbf11ANqir891i/eAxofoQh6xBpfzcV1QRRyJq57h7s/mTMyNcdexvAO3oscwi4hYn62CklBDSb9hMxLa/60Xz94x4pDePrUVPYYqMDKWZAjyA7M7lTF9HvoYMCbZkV2JKo9PdRgs5v4V5E7VODReaVWC/WWJ44ZKaex7cAvYwpRBcfVdylgXmGVb7YRYBZPBUbYht33AHx/gC636IYMmz0knpfkspdfrIFZ03bbJtXSAaj1jSP4/TLOifwWPTIWt6Ben6DQXy/SDADaWNxmmKS3t3TyCYQAMzUioYet2FUAGV14BWsEYemgW56hzkczZeWvbegZonMNHGm1le4SzmjI4qaT2R9O8Zpyn23U7QxEKF3qGGsjac0jnewwFsxx+aObsvB8hVFZwS8PZTfBsND0Hcp4whIUjzmxsGP6ShmJxLwarEtf2ysGpWdtf0DroUuS8F5N51OJijmGe6KJXiU50/59COt1fKNoxFDBirQ5XEF2tBKhK0iENms5Xj+c0XehN0DjweIPh50THDHjtQDbWHDEaaAd37efaCzLqNn7S+yytWsGrmuU6CKeLv73BtG+0b8BbQhc0jN7RhzHhDLYwP7jukBItYaDBjPQb0JbQBSlcKhTeuJmpFFQH8wPMHJbLUBu0gyD5Cb4Qbtw0JBtwvywNFRXke2BVGiNHs+f3BtYCvqBJbfNST1g1KZCw0K+BazmlQJCgbyCtaC+ELyB6ZwkmI57w3vgCyoQjvKf2XnP9t5nqfaS7UEKfDIsmVXTOcu8Nbpibsf/MUppR7KK7IscBuAV0wblcQpdPxLNgZFEIo2XAoxO+P0ErMN24o+0HuM6zhV6FK5XRDe2Y9sd+lJHhkleujj+tPIO0mCkM8ffIcoFfM50r5LgWG5N1UAynkOthi1p9B25FX6HFGm8UgjPe40BVkT13iLZq8ddNpb6+g7WgrxAabjjXSxqdsvNxc9GneUM3mhu2g2e1XomknXLl3J0JwLMTUyjURkC85Zk7Fnr3V6AWkAS/m5kd5Gi/YMC4w2FHb9MLcaRgRCevAK0gCTlsntFuwXxHzdxZdJt3FmNhRg6+vrUkoUxVPLdJgtapzSjAablKYszhtB0HvkN0vq/g9OiCEOSHGaUda7DPvnWwnbsDi/TnWM7ThBJephlCDHBvT4VRxgZtmqlWqqBYcnClrOQJY6a59LXqMGhp0JXOophCzlI9WnEeM5fniE73FWI1hGAQ3QaGYhGx4RbD4n4UpGlB9hzLeZqwOSMr12Xkxtu2Xvfb5RKRaV64dpCZfK6rUJT18SgOclQci9FmrouQXXuEaZRzun0D3hqaIBkfW3bmCUXy4ImatRTlmLFthlg7WeQxtCU0wRNM1NzMem63RSiU+6BNbGHVhUN48PF9gCZYiVIgHVoEU1akL2K3zalanCagBSqvca3oK1hjmIqFUZD7IiOhRYTAvrdhFqT214hWtBVKVNzqF1fcTAPCftt8GTtjxoM/9vgtfUKFhGHYWNnCZamaUNrwE12wxxjWHtwfJbFM0ajQf4PuHFHg06mcbwqmR+duWGXDISxjuCKMMQ1Rooy3j+0cU8Da3ZppXdo8j8TKH8tXPtwxwRd1fRo13KUrd6jWkQUuJ44Fooqp8GSo947EXVY0heVsT9bN7/8tunNsAS0EkbwtO29YFuzZA4ZjIJXFVHsa24RTvlvzeIjrHF2Yhd8a6hqBeBm2hrGo8FZ5gWeDv+eKMZqRH0EtpQuD0zH0yY8SLJeBYT8Kh1BoNOiJBJY+6ytYJwnDwGThIGEo3akm3LOV0qzNp9NPnGxf4itAJwnDgKZOaeYyOkzchL7Q0Jeh5LiZ3BwErGWEYdCuTTnvnHkrtwQuhYS98OE5Yxh9Tzx3kE4xBnRanAYrxegdyRQuY9w8kMqbZ1cIVuM5llOMAQ6T2/JkZ00d2ZNQcY6i4fReT5uX8iOUVYQBRXJzAgPnUmeacJ6Ftw5cqOFvEzsbBwcX9AWkM4wB8hAt+NJHqVCFdsx9cusmxsOD240Hr/wdljOMAb+sGZe7eLLGP7MbY8CdV0O6nUEFH7F8hDHM/+J+drZN3YK9TLHmA4kVJkCwW6CWTeLyHXhnGQNMHhI3yOa4KbggtVwbeLTZw96N+sAYnkE7yxi25eqIA2GXiL+D7j4K+Gh7eh5Fum4H+dNixoB+a9m2UvTQ9swPDjJbVA2QctbprD//AXmN6yRj4NEZJHQlZ76y3K/DXqSEyaMHHLDqa0gnKQNsDozaX397IFHYKICyD5wJot2Pj3X37sanKIPHSQ7phSchRBhd6JGNf4r7Beqoxg2h5S26BZRBmudpuGByh1Q72giwf8XrQ1OoJvp1itR3uM4zBocyLtwLYbCA5uo2Km1QZSixrA8d+JSfoVrMGPxCVjo1pFiVhIQFG5YFtTxIupOaIkZksXfgzhOG0T2OzyPfmjWOPOMddsibMU2UjHKloe9AnWcL/hE2xCPtDfNWDXIo1vf0ttkGSxfLI6jlbCE6eNCvRdOfc+DJ2jbmnCdDGClUsAdxayynCqlwLVlch9Ih25w/zp42yo3hsJH3U8UPgBZQhRqCTnyILXPvVkNrFCjxWDo9HOTgJK3lCimEy2xn21bqROI1rpt7PZQqbpoizwGdZgot9ndgtYFnmfDyV6yhLlc9fHPuiZro3cjSDst5plCGgY17Zl4oycSvpRnD/PKNCoCjg7OSKoww9+MgUkdiomn0qwkEjKfrXDOAG/noTS1jCiP6O+gaYJC4JJb1QeEwapmMq+bGi6dzlinU3lhi1mL4r44PKnNzKgp4OVY21YP0bXySKfiJFtpZqzWaCWDfSuJaS0zohDW8kmq9h7eEKZjQjnCEaGZmnTSIgdkJtqsXz0Qryeo3kC0hCiPqczMw+8fOcrne/Eqxw8d6JJvjyc32AaJgtfPQ594KahUsZGIvBF5gh1VZ669BLWAJNfqN9ErvTELKfFe4O7gfVFlT1zePaQVJGMLpbj/4PM9ofZbr65tVhsIhva+Asn2sr9CVKkV/YQNZrecCkBxliO3p6xGmVtg8qfYO3Yq+Qs5l8zNpiVqy0r56qEKOoUn6pT64qB7iWkASml9+TCYFvjkN9YMy814QrfBeZ+iVlJ6hWt1WGJ5lIwKEy2TljDi+wE3gDguwvk0Ri7xFt6CtkGaTG209j5qGMWu5DfLhSflXuzlLlLewzvMEjZldbNyVrpjwn0eK8mq2RoVjJ7vifbbP9BTCBLvAcStmruGHQFfsfFMEpJ63YpC8wrWAKbRpCMUV6y1RCD+PF18Wmgol0WHfXgFa0VTofvNibK+32lAD4paWbZdN8duGJk4HsXQtUShJGrp0fvOipKh0ff4q4ggDfZRkzZ5DOk0VrHvmjV5iMcOPDe6zRGsROzcr7SZfYDlNFWppbH35lYs9oCKquzF0Zc8xt0coa5sKzT8u3RpBmPGEaFRQqmbO2do2Jbtr/2RbSRX89EL8MGrZ7GrKdXgRlVbx1F3omWTPsZxuKozCpQsxuIVtWbneDL1gmTE3dlPQ9gDlc0xhZA6bOwmeMVAHLgx8c5PllTmejTTh6PP6CFGoGksoMrcvoUJQ4ZI4+UKl0Nc/yW1AXb4BbQlTCOUASjjOhtGxErn5OmMm0B+aYWzc+iOwT7QUwroDjCVCZaZ3+tUh47oe1Vjv7PIa1wqy4MkaCrq5CNziPAVuV3MKXL6SBz39a3sNaQVbaNHqQTTvGOWwCnUr3SLjT5y+wL3ivgw9H+En2EJuERjxuWXFGHiuVm6kOJfGt1wrJcnd3oFb0VHw80y3Hk2wLY62cb6WoDOGFrT7lYjWw66HdoBrBVnQxg+/+91jWC5LIg+nA7QUYlMSZpx21bIvsBazBQ9dhZw9mQq3gQ640BoU+bN8pTGfzXDxFtwKshDWNZtpBfSTE+FMiSHixjxPinVEnAd9A2uBBCkZTbC1Zfgrt1rGdSqgQs81Ys0r953LI6rlfCH4FHNzfyzGpLjcFsFPEu/8mUOju8LCDtSStsK4OUVsS53zZJ9YFwMxUMyJQ2/ZXgFa0VYoSVmQbTEtPC+Ziadc59Fqioo2KrOPcBZ3FaLuSQckQ69MNbdrA5v7SU0pQ60vEJ1vK8QekYLuS4b7dQVnoShxZulxP4Ifp+dYVgiQbNu1aQYtMEde9Co5UGcLl3TQj5pYlrYV1LPzTH/dgUcjHGvB5zXPUJ59jnrQcL1DdJYrtFTgptmaIBRqZe0czQ0M4DlRb49d1jskp5sKlrlhQisLmZa4A/G2YrDGnmDuVH7E8jmq0Ma4bBuW4KbgJwmJ5ey2YCAv3EHZVGj9G/DWNBUGS9KjKWIxMjuI7NhUKK22676abyBbQxVGgtTOCSkWhGuxqxMaF+6pBwYOEh6crk80FWKlEleZpISsSek6MG6iX2cMHCGw8RrXkr6Cx8tBk2AoogQTTBg9ScplC50+SP01pCVUoRekZx4a0I7CGlv2OrFwJKzLymPUnNA/0liYO54wYSqeBdNDAFNFvOgqStLZkzy4R2rN79Ct4ArBLVH0KaNzza+wt771OuZVUzyGISvYseMDYOfJwlxvW0hdUqHAEwqffJ2Rk5heh5VNlqePazFX8OS3M6wWFWQFYc5AkwioW+ADXbnCUcp4B24FVxjNUKnzWFpmoCfBghBQM0qcsZCe5o71HawFAqSQO2U0WuBco1gZh3IQO36pUgJQ9RHSJ+RHg16Ko4hVmjled44x1fMAdymPUvMdpgU8QSM+CKaui20+aAVWbREjMJ7W2Wt7CWdFS0Gz0H63aNkkuG1by3bdiUuTr4NDtLilkG1cMELoKQEGHjXdmkCFhzmosu3dY3aIzrOEuXQRIm7HhVkv40QCvqmgdLXCVl36cyznOwrVzw0vXo+S7Obr5n+ExxPbB7fD/ohlKUuIYXfUm4rTBJAkQfvOsNQZR6mPy9P4s4okaGz/RjSsKFH4tZZug6fY/5vCi3fbZvIUy2maEGemcKsDTi5adBleSJvCvhXcFzsJxsTyMZrQk4IoZVNstLWS6KM+606wUA73BU67jG+gW9JRsNhphIaCcIqT0iNM7ENCHikMN3F/57mtYQl+gXCj/IDhi2EtN1eVJ67L0MvB3NTE9QGSoFa2DoxnmXCwsv5liwdgzbxk1MeM/AHXkhEFzzYwwJW0J/qrXG9aYWk4tj0caDUfEC3hCE3oMlZA6jJiJuq/gjp534YZvzyinLDSbQ1HuP4VavI9hT5xBkjRllhLwGJYXHB4ld3DBFdDlK8+iMfgfkIRdsAkzP+pMi4wYAqh6/wCMV5lZJwlalb4b5DfAfsJRbgH1j2cU9bWFDqablPkUAbLhjQZ8jSO0/TjGayzHGH3zMrQDO+9nPrYlthh+y8tSVkx8yC7rZMs78D9hCPsgPl1zLpi14FZ/pwrZMsoTyv2/QTJAUmo8g7XT0jCPa7mhxuRS3Ug1bQ00k0zidyqiaWHmt6GaQFL2B0wrZtHRAtvMvod3WJXRiE9YVjnFaIfcYR7NCZbHcUTBUuY0jNYCwi9diPx9BwCi5T7K0A/Ygn3gEqsX+RZli3DwgRo2Qr4JZIw3bsxbXBOsoT90W7+uwrWFeSB5k+hPgzFAp72MEGZR609h/QDmrA70bFt3CiowxRA6ZKv7lkN9eurkUV+juUHNOEeSw2DMQwzF2S/gthY2pVdWuLcgByEoXMk4R7MiIx70PsTfYyK2QSINA1um9Uyt9nmr02fPaJfZwm7r6qFwYvAD4NNL5Ti5ihe5fSgp8YX9qLkOZhfpwn7L8oyZ7W0cIG0XPdrw8onh0aLcwwHQXAhS9if5zp4oxWFrlfpZckllWgsjJAUEPo34P2MJtxD0xamK1PE7ulJgmitX2lC7RiU909u602NbyD7GU3YvdDYYy2oZyrCYEv55q+Av/bHST8wOzjpS3jC7tA70UNGl/2ctXyr72ATG5eEl5iZzftR5iNcP+IJuxiVNnOXUI8ZqpYde36RHk+JpLI5c5QsneYJ94gibGPTRSt0wFeMcVKTPUc9uBJuRxNmpfUTNCGM2IT3iocCiCs6jPc75ryybV6XseUapq75HboVPGFo2VoJwYqRgkPTw8XEjRYIpXAarpV3wM7zhHBHZfCWjqaUVRywyrVe88x3jyKy7zXeg1rMEmqMS8JSIA0uyIr+OnWS81khwg6/GLjnOb0Dd54l9BySXwpYsKSmFW5u1uvWTT9nupWJ8ztQ5ymCHyl68FaPpRh9UXY9Ic2C21ZVRd5g4xHUco4wig7MoGW/FGHlbDZrVViZih2Wzufxoo9e31KaoOFSiMtQKy13h14VPtAlxMohCt5f4lnBEtQqRg9C7QqDKixcmUdpMDFWeA0cRNGlJGG0aqC1zpMKLAwowipXAUmP5SozshZ9juc0Q7CqBktNB4JtxAW2g7xhZt/aP32KIV9gOc8Q1C9WlFZ1YLBTDLl5vS3V7leOYI9YlnKEsDhrrKca+DUHJmAgIlDLNRlsEu/o9x2isxxBZ49gzh4Z120k4dAbZgUnMJVtYl+fYzlLEWrYp1XsteAkjWE4F82mxsnARiv5gw/qYxTBKAGto+HfJ24nyNcdrFFwzduKjPoNbCv4gX/qHW0pz5AUvoJoO2NDySTnMbEAu/u7LTxPgS2hB85yQZa0YcLOk7dMw99rW6ikRBepoxvtA/RAW9l885ohtXTSqbdlM/k6qH5BjHoNaw07ENLKlLHELz64rRkNagxfZVbyXyJawQ562AbCSnbAxLbmcfMLmWq7XARmAuU+PE3295EuQrOYg8C+vqrs1+mMkQ2Gg2kyzT43CoGFjvEO3Bp2ULdtScr1zALpn/KRIRv3pHzgVZcdqToAdp4djOkXzyLvwMoprJjHhdOgjh7D426R/WaHe1TL6YEpGEm2gs5sVthGAtvA3mFngXzn4cLyBtuKHkJ1YomPr9SKKn1CAwYexYaev42+7dWp8g7XeYIQ62tR2PVspsOicWB7K75Y/HUJXXDSR9YyQa1vIoTUiPvu+4BdYy/waGvXrkvvYfdTHgnCDtSKPkLZ3Fac6KrASKjrF1dnDn/2S9uNJDziWUEQWqp08RgevBAh0E3A9BQ2mujW2H6Es7aNkOf4Q8VoDRyOdKBYBrVRI03399oPrr87SOfbCP6SoAwrZvAejmkzdC+27lgolXHGyovHc54kJGeNshngIx41VO7HVqcrraYL1wc8QlnJETxNi7FApCVJcM3CPhpji+ANJdW0ISrjOaTTjYQeO2+wqog2UPS2x4S30bfaP77Rd2Y0eyyn+wjNM0YwyU1J0LG3UK8RJ1drRmv0g0PzMZIQRZILyzYD14VmRMKOah0y4xybevYzCU/RLaEJwYEbdXM8PB0CRC4SxFuttWzug+Mb0FYQBQmDgvmlm3CHQr65ixXsEa0lc1eBHjyyT7QReqIIKmvLUPskKEKgOu7UNfiZx0xXeo1rAVEoXY322bkmKLNKrVdfwY4FLPGt9seu/QOiJW2E2I+AKbKimy7sfqe9ZWssv9yT4hn5P0IUhsYkIIKm8X7zrAk9UagBM2Yqrxue7jYgH4NbQBQ81004LjFMwup4M/ZHv/j2hMUmpz33wbR/Qm4kW9ci5EYzbRqb6B/ZAeqKYQuDEC+7XvEXWIuZgsWWRQ56x35NVMIT/Fq574x1j6gOj70T0zG481RhqIekhmGqBDlp16639nrBKtDWE1qz/S2oBTyhZQRTLZ5dTcJXELW0Xst5fu0MEr7eHjGtpwk1Czf4qCcs2FEDL35Om2N8L5cLQv4rTCvaCGFu0LaBT3iLKHrErE5jRskochF9BWgBTajZH9B8CL3nkZHszg+Pk1PQWcea2UcRy4SzmCbUsGLMGFYU6DESltmjkIdi1dx7e5Rk9aUsIYazoPqyXqGBbB0c5raqL5xKZ2GxvHg6p1mCeo574b4pNZTqcK/oTc+nkaEyY3jEsrSVELPCY5sxgnQAbwjvDDK12BCwmdL054AWqI04RNf6lvTS5Ai71mhfG4vFsT/lOZbTnYQWFS2MY2Uuo55jWf22K7BEZQmb1g6OzOe0RqXTs9pZQMXudxTDi2D9Bi2hGqcq8rfgLdEaVU86ZkQevdEqsnBD3kzkoDVKZXCTl3wH2ZJmQoj/sZ5z09kb2kEzKsHyxVOXwRXl4yDT/ARJkNYvNMyKSxX5UvoyuJy4ud6jRn7UQD3gWtFNiKl9kKakSSBPne1wrrCf3YSrZ95R6F5MEjD/mDFxh6p9abdWMMyPIrBiz8sXPPm39AmtUYbXk9C4yC+7LhiGVyp7MAWYoH2QMGK4YEq3vUN3jiTA3kW3xRexL0nZu8e8EpserXGEk3tOgr6/AXaOJGQkvHqdSWhYg9FQmoIoGmlKHp7wGs5aeoZqHUcAR3J2R/2jM7s+uEmvY44Qukhsrx3DaGohd3H1EN05kpC5MoVbmUMGVdBal9RvXnuQ2MdVUKnkGvIO2DmikK+7jadqxxJMIw0283lb/4ISaDIUGPsBqKVMAcEgZFeUKnuaTn+lzE5HuelKczjgo5I9XgE7SReg7bluOio9YThfE25MvdIFk0yDvTthzQOgk3QBqp6iyIidW27aA4wwo0aLMil3R93pjghnGV2Axjf5F4+G4jDoSNsms823s6Q107rt6Cwt4QsZBbBymWlBbYMhAH0fVslmIhgLZ3Q/k7/HcoovTPok0W9B0qlwZhbEAERMWikMkL+7rgKhrKILvMk8QUIBRRM2klQqyKE5hM69x3gCFo3d9Vx3kM4QBnxXwl2PHhoxSl0qvExGui2s76UZ3ufdwvo9mjOUAX3Vwta8bcZL6GRSzg5LzZZi4nO/nnnD8hHSAK4dK2wouhygvIYKQUFuB9V0jcVhuu1Gfo/vLGvIsJFNW3i0hK5hTVSxQPQAu8+UNm9p+Qa0s7QBhqODHqSeruCzq2AuUNLgNh7V6PZwdNoX0wYcfP/ikZnnUrHiRbjXZBt9nR6chctj3+E6SRu47CpdKHGrSM8LVJpjM3mZ0wuhNhtPwuZC3oCxjXADxvyNcZ31SFc5K95rit3a+fHWzflTxCFiFHLNKkKFyMBO5s5/Smn5Gc4IsB0cb9EtIA61pG1dj1VQv3DxmXVNYRsNhnbDePtJy++AnScOnsB1RQiX5IdaGfLBP6kHxgLLIUbPj1aeAVvMHTQ2mxnXYxXMycWjrPDem41JzDvFQkLMMYi+A7eAOsRMPJeMNuWZKgm+ENh1BlOUoQ01//thwkNY54lDDx8UuO+3jn2VHVNyWJNV4SuXPMFA9fy+6EhU65mDf2uZiomREhxQGvacEBG6bTGKlR6mrB5gLeENeg2puSaUGrEWCqPOaJxqL5eHmeYHPAtog5+hbTg1lZhegg+a3toeDW0PoQODPAJaSxw8SaEThXkcyJxe6tdCLfR1Tgrtsk2nPUV0njfkRMlvFozgKAzBwdWxw0tHQ21D03Mop2mDeTqABCHmOGaWIj3dFvbBhklEadF9cJKX8oYoWNA3Xa1zRwq00zQhwo5dD0icF7L8HNJZ3uARiKKDkbg9MNMCSugtOO08cqF73o5X5byQNmhIfhKl0kqXz20rJ2S+s+Fq3NPVD0L0x2jDyCHnwaawWrlEECkmHPQwoTNK62wQDfkGvBWswUKmgq0t2c9N/dK7gm4KBmMWfjC0n//Ok1vBGmq8Ukx1Db5SVBTzFEGUbbyicMxsHJz1T7CGptw/mf3Gx+q1rTqstzpnt0qlcO+vcS1gDRoOL+B+MtDFkla/7sNBulRTp8TrNaQVrCFM5ScL9TQAqSY6Rhg+AZ+IDa3YVX5fPMz9U6xB46rjvsxi1CoacxLk7J3tBi2pcO37rkSd+ydoQ4tZ8ALhfWdvtGNCly6zM4j1FKODMJPa57/9E+2GqPugwBpFRewTzDfvtg7+EBX2TbrUnqFaSxk8ua2NfnEe9VHk9GxufPkMc+Wa3aifNyr036BbwRk0Ndbr1aCLGtxNg8cF92L1aHoZeyvzY1TnKYP1pLiKVTI91SsKf/ABxWfqqTG97kweQa1nDFIrm8r+JQ4VeMHjHszlyzavqA+VtrO6e8S1gjL4p8YJwulYrCDF7bqAjS4yfkFB//YS0JJWg590cCkViACL8CPcWsolBLzoyhwcprWMwaN7pg9S+FNQp4U1gzN3QPO9lP44vbcDdJowtC4NYqDSB2yli/ZyM+TGpluF1lteQFnTZ+AKTetIgAe6C/2ai2psjEeKdRC+lxKGEhc+DHW0Uf/T7NbzxAVYc9j9QMfRxnNI5xsNJdHrzMlUoUPq/MpmaIR3dPGontDBuzdC2qE53WiI4UoEQUG7g/oMMoa6MYZ02W9V2KB8jDB053N04h/WIDlAxQK2GF3RM8qevHML8PgGvCVthtq53cWfUwMHle3x3dxE5vJaLrtP34C2pM3Qe6KXUAzkYBN4uqqTKhmYeSSAxOv/03YuSI4jSZI9UYX4/3OMuf9lxs2fAgyCABmdcK6syNbU5HZqg4C7qZma6smp/Q3CkO2sVPZrC6x50N5kZsxFMzhOk5dwe49rxZjB/NmRQ6TBCnDMkN113OeQ4/zegipyeI9pBWMILWC+UnOiy1Fb3mOMGirqlrBJOLTp5mP9CmOwTrmWGGyno6rGxDWKitMxRB5n2ua18RHcAr4wSiQtMcTgGPgNDrGF/vFnuR9HcczSjm2LfQC2YsxQrZ3oZTUw2ZSSrpOkZpljY1TsTLHCYbL2C9fiKcOoA4pOVuN9yhNzLGATlhG1h1KSxt25fgK3gDFY8tKPukGxymPD+bovFeN1Pr7SUQXLEvfjQ1swZqiDlDbyKpPMgcndJr8gS9loR2+vL5YbQvWFMUPoikgeZbDLs1zoqkCzVGUW/9ADfZHs36FaQhks5ASe3jN3zSiN67ZejElTJUPnMPM4oFkxY4hhy99wqTKjjRVpeticXMb/wuH2emCfE89iwuCDhnbjJcIxtXoNs/NuNuBjCeWnH7XgB0T3RwxTxpzkwY00qVe/+ZRqedV5CyDMRxPMA5j7nKGMGr3QeYqsxYVM+hkUmKprHJXY2Z2c4GuHDK3Jctd8o8u2BqchtRWiCDhs/E6iV07XkG4PGcw7dT6InrFACT2WfcuSLz7k1iPyg6eIniOY20OGcaEiOTBtEtVBedlFrbm2H0IgX6F8b8ZQbPMG119C7GsUxdJcloOn2EuNh2P/A7wlM4bJBfTrEI2cCP6WHfgcW4VuttL8trn9AdoSypDH3zmHd4OtR9oqLI6rNIeDjQ+TpvFhLjOBfYEyNG/pJXiSFtQsyUlcgpkd/djxLfLHWnuPa8WMIeeuPnDMrFaGTHH3cGUZH0JSc/qsalo+Yxgv1rzAeooSm/N5yvN2Pkon2L9Dm334b56mqxkDXZ1g++GEOpnP1SyQErJ4h9kzcVCjconJbba86RO8e5yB4Z0bp3bFMa1Ur/vX80n2Xw3zPkPuqjLfPwC7xxkwTRuvjY7PgnSlVbgUWmqaH82cCqXRrVeo1jEGlixzjpKPGLIsq4tGVGxRiTXv6D6uB3n3uU/o7lEG3h5be0pkm7RMs9MxUQ54NGhFcjw2WLwPH3HdowyytsrsPo+rulPy4VKCZxhBt2UcISoIT96vpYQhKPVwy5wf7J1Jd0UqVcuumrJwjx8Vx+9Q3SQMGFilIr3boE89ss4g31CJ28ixk63+Ozw3KUNgMTTzgHrJpH+mONtWWtxBpd+yelkneJZRhiATeg+jKs3VyvCF9rE8HyXFG18dDhdvIN3iDPOt7oMzEGZdW9ucgB5TBkySuq3N1COjOmC5RRlm58SyqivN8tCli/cPXVLGqizIFz6cfGCrKENQ4Itsk8cRySJMprQjh6bQ/PG2Jyf/r3gN6Q5l4PxxGxN3LijpobeHxw6VQrbAv3hcUj1gucMYWNe3wCVys5zUhoq41qyD9vQg4jRZTl6br1AGisbuZKbu1Jho/GAogPq8kLNrPnLpPtsSXsG7SxmQHRUJ3C0aKlN/ergeenOaBtE0w+oc/AHaXcoQkCUlbtPqaZnbYu0v+Y9MTYsM4fsJsMWUAdsO26Ntm9WJLAr7Iy4ui1kNdv+6A32C6yZlmI/KlNpRBDmzi9Lmr6pc1q4QgYre4KnPcgLpJmUItOYDLjZVTXyf5RbxmBWXcYoTbPeMp3+LMYQYtbuTQiUMOQS2LRutFw2vLFlIfpcp90/oFhCGEu0w1RJ0khk0oeDbkMGxSmj5852knfgJ2H3CYG+NV+Kaa3Tue1GNoqxmSmBnruOFhIMrXGspg59pl/IMb9HLgIgmUWLq5smNy3HLJA7hI7oFlCFawFfYMrf1AQSiMzDg0cnqe6fu9DV+wnWfMjSzzC/ISTwjhcrAz+Olzbp7z7bIgzHGK6j1nMFPx4R5ppqOGZVp1+Mj7kvWkG6To/d3uBawhmYGtDTJSmhybELtoqzL+TXaeTKPj/T2Qa2gDZaM2mUvuwUMuC0duKnwK2o6nLxLa0lDsuWKIvcb2boUzfuInd5sj8vPRv4uId0mDVYZVwqUPD49hY9TaeX91xp/yrxV27FpdkBznzaYMRuHTemdwWvE8obtpnllj/qgXf1WS1lDqLu3ahx/Kz0o+oqNUOCEPWaoMvOs6RrSXdbQvJcl7/g5gvKqaDVJwIVJpmkoazvrpfSFvCGlbYuqarciyHBhi7dG9GPKknQcNQjL13jDOPvi5pFRq2tsUqFEqFjysdiVe1QCTEx/wLeCOIyzsGzO06PUZH8dw2fKPK3LWHmuA+MPyFbwhmiek53UyogaI/EzJozmWCl4BAefXCVf4A1tvMc/hED0niSU0rYcVHAfKlE49PQe1wrekAdrVtRSbDQ0e3yYC+PHFcI4PxrWKe8hLeANobvGhdF6kj814qSwh7TU7Bn8xeejc/7KX+ENxRYounwBS1G6R9kUErz1sOgaQ2f3o6VP6Bbwhjwez6YtqF7JaHWW6ZlBLZZmpZmI2rOkUj4Bu88bugWKeAky+nzHemE8hOaG/dBBncfFzSKN61ewFtOGUlErhkEZeMViQydc1QVl7cmpa+NL+oRsAWUYRbDnRGq1Baekd7QIDpcJHJBb0ef47A9yimvBlKHZvsl8LrXQpzatkjTMdl9TDrtxvKlid6+ovsEZ3Bam5YLvsgdi5zDueaHdcsWR4/R3qFbMGUxBQf0Uas4StKB+ifv1U1xP6hbXd4BWMAY7tOZf2rv5syMwCQfzzlFpUQCFkwe0ljNY8onSbmvCSS3Lz7vKYtlOiRbheLFdA7rNGJqtoUc9JtJqUqsPLMgDbP25vUQ6H7Dc5gvFmSCDzeYgUseSlV4ckjZdkMvqCZalhMGbAViR8V2mY9gxI/Ow3vlIuoVvo6ku+RrS7TGDtS1pUTtb5Edq43RjWAsbtVLfrMZN6HaJ5vagIVlOZiDNT0YL2n+u+56xr26QdcJgTg7D7w0a8nhUPINWeIMqy6B8ZoywknN7u/gpDPgK3hK+YASd19nVKhdlMlgi9lKsjeZxjcgzM/4B2pJBQ/J1DqhqrlE+DO7BFxgS12gphgQOvOL6Al+o1quIbDJ2tGWJTSdZm0sTn3yETjf/HtcCvmBB5uokDFKQZaRWt55GkHd+z/LzzOU9pBVzhjz4wiwDWlYoVC0oB9XJsCeT3Yn5Xfhv/v/7CmGIXZtWkUW5AU2ejvRZvYwtpok0E8nDwzrBtoAuVGN8DlLclU+YYQhVS8U8zDCDlvET/fjQVowZRskr4a0zRLPRSXzMlI10HKhG5Zl+mE+Gy+e1mC706U8r76TKLzfqXdq+8AePlKWHJkOQkP0ndCumDLGrTz/IQ2Ji6wMN2DBZc82M5W1Qsk3mP+BaQBlq0CZPLokUp5Lar8hpxU15K4UjBfsLqC8wBov9Q+JjLXT1jekMq/egZHPnIX6lvcO1YsrgfVMXLVcjEPOZzUdVyi6trDaLlAPbO0BLxElmqUbhErOsVpvfrVapyy0WLBytVgVnLWXI4xJGHjnqmED3h3TCbdouRYDvnB5nr9Iy0tCdzV41UGxSLlfaobvxvwHVjNlfY7k/ZHDbzRHGV5YUP1i2gZBQdilKzn6ppZzBNsH1UmSFuqq+i/Lh8RhpjG++ag/zGtLtIUMYJZ2GDF36VgomSCZrj4MzmE2RfzFtO6C5PWTI1eOKW2qTu9Z2JPGBsXdpqycnw82J5WucodegoF1v9lLsU7CGmaUYnjOGcRRpthjiH+AtESdlq0FkoE/UbUZeE0SJeXyDk8n1KeY/QFsyZBjlOdq35kgAi0nBG+x+uV2fMI+GevJ6fWPIYDFa8xQKPmVl7dRXLydLq08vXk4nuFYMGYodQmlPQ6LN8WsFusg9IhblnIf3mFawBhNFe7EGbv1OxE5STCGpLsrheW7/zgbNN1jDqM5TQJ0/XuqGiDohAsraCNGiY9uCjs2Q7gO4BbRhfG/tBzVn0Up96PIFjKgCVbpE+WOF3D7hWrDNUL2CRiwTc7LP1tBGsKhKcLBvVbbIwV8+rcWkIftS1Ipxo67TYKaRSTIhlgINm7E8QXPAD+AWcAZnto+VbrmntTi+Q6zHGTPwpFIdhExFcv+EawFnmG6UlRSnRHJQY4Nh3jpJ5g22N4C3r4uvqJaThhbrttIxynMKmtL7o+SrMlyRDi2Gd6BWTBl8LJsSN4yzS2HZ/WETXfFmlBwm5neAVjCGQUJ/vL68KTSNab42inJziC0zv1o4OUrXMobpJ1Cwf22OqLL5/0jDOG89yyjED69d47m/ymCGSbgcjLIga5Epb5swAVu37lBIpHgN5T5bSKNGYqjfIo8loCJLD14+Cpmu0Yt7xbKSLoy6W1Nr82MIbMz2tBuvF6oVM1KUUWfI14huTxhcUQlca6ETIJ/z+XC25VR7sWhM9Wsst7mCOYKzg6NVS4+6nB9PJucpJPZSyskP9TWqUFuWFNiPMmB+P6VDFRCNIAt2vmSlbtT+B3hLqELp8k3tNeEr1UPVKsW+oBdr1MKoD39BtoQppCwhaWmlqjTaEswf2QejNNAaw8mL/o01BrPRUN6ziztS+l/sOVGxbGKDUt/jWsEUmt9VDxyQyCEYdDS8CVSU5PgezgopUrW5EMc1tH3geeS4YUqdaoN7Po7M/J/z/7m7WqSs/+e///PbP9GDNkXpD/KxTSZi3mVzqRIBY2JMZdDY6Hl0f66w/Z0jXOIKLetQCqnEuEWA/SIJ8sLzxopZf3rM+K6A/Z0kXAGrVsIpn7u2xPUS3b7iVHSCjR9XUfCpXKH6N5Jw+chKcNpHG+dR8yLJQVVUIh8XOylLcdM38Qnc30nCJTBnudezSBk3Yu1oITafvMnp+Z3Ntiz55/v5CtbfOcIVLHN4xSh4PBAW+1Krcet2BirOYOpARAsnn+Q/M4QrUN1Obi8rahe3fWds4mX/YX2Wcdxm7DvfgfofGMLlU8pJIndTlDU0d0gVxPYUNhUUUZLfAfofGMIVoBi2Xe9SAgvh49/or56SavsXVnrSCHqF808M4fqgsloYMdb4yGbxmVPbArf2vNxg1TtMr19D+jNJuDyebHO10KF2+GNGx5vi922KMkg5i78P1dgrlj+zhCssKbhtD8dVNuGCskHDZtoUbUsVH++TY/JfSMLllxWDnsz8pvHYwQHTh90SzRJiqg7u0K8R/ZUkXH5Wlq8glU3mKG5ahSn7lDr4mtVYrPUay19JwuUX1cwAgzkG3d0q9z8sQfGU6sqwyCdf1G2OcPk6zzdVTrh5NlJzk58UrRJ2lvqoxKE3j0SmN/D+F45w+XZHs2QqaslxCkY28zp9AlxlnAleGxbLn5H9Lxzh8vf0Zh+sGIgsWz3/S1TG/qx5yqT+tIXyAHaDI1y+8tP3BCKXC6xKuFBrUZmb8oDR0MPH/BzX/8ARLh9VdUoxtx8RRTSWP5SeJEGYb0NnTvMe0f9AE64QheIqSpkSMvuT7Jg8uYsEhQEejigfv0UTaqv+hx0ml1gAH2823yNcZt4s44/FvPk2hU/YVtAE249g89pC36tYJgsLeFY0BIO1dBR3obVPwO7ThFatKlCuArZb3ZPz45QFKC9HS09UMvwVrMU8IVp4sbKBuwtBAzP/KxpNo1A3KKv89MMncCt4gkvSvLfci5PluNJEMxnLdDxsHh+VkPsB132iUF0rSIYttinTHPcPEX4sCgLZ3AD6ycNazhTa7Npp2do1x/IZmaEd/jDnyRttj+UdqAVMofhxTIq+lZjxb0UGyANqSLe6nBDeA1rAFJLJpivr154MokiDTMMEWujjAFEq4CuetVTBlSqnsXExh0ysjnt48cny0dRHrDP4a0T3mYJ9REVBnFgERzYvKZILlt65MUdL7hrLbaaQLWJASketAwU1NOdLXLYfCgvMk89rKVMoRQuwftx7OL9HaaP87qARk/2aRKQlf43oLlMYtaWMsmxpF5Mq2mFEEFK02E4hyzC/JpmvYO5ShWRHoThucDjCyXbX7ZHF41SM4pfl5Jv6Hllolhi5S1nR/Pz2yJglVBxXSv3Jz4t4b9Ct4ArZ5sxRfdT5rcfM9aY9qi4VV94SUv/y3BZxBdVrZbBApwJ0N47T9no2O3Gmwie10xe4gslC0KiOMjMo1tn/whVlQGDb//4pW+gc1wKuMO7bIOtk12tga5dmZtg3BM1TRMv9ubyHtIIspKhdk6Lk3eIfI4XIYW7OEO2VKwT3Ja4wyIntgeMlkMTquhJQUEpuVt1llO880lzjJ3QL2MJ4bdKmHCh5K4G1rqdpFSt0JuXsz+5DV7hWzBRsSqs6u7NvUlhLILFqlgpxFFCRV+uXW/8R1WKuMErLPXghuM6icMQGOmqM22mljfceNaUrn8Dd5wo9mjmqIqIyhjGtP/zctBbezWpj/s6tfwK1YKLQq4LBUytJWWybg/ZseyohfnwfDK9OXvrlRMHywz2wTHWACYnCBWRnoxV7mbHn+g7ViplCHVUlP5Yl/uDkj/etDgb4+/a6Hwq+4JbPFKziQ7sxTgPEIiTEoVmWc77ax/kVzXKe0DbxasN0JJGpTEMINWIYBztNhHQN6DZNKDlF2nFxHJF4i0SkPm1vKWab6zNQePNw7g8UivmrUwEXdKHF130SxZqA+T6X/OSE9ICyliZUBRv6WGmcJ3yq5I/PYlxJg86pKq3XiG4PFOZJh2ZVPkgKvefHYkQdm9Uw7WmT+BXLbZZgwwLOwe7l2oE4hHa9Bh02pOsXp+DXSELJVjIWRgVcrGYOhVcNjJe+sPnPl+ecjDfwlkwUzD01kN9eu2wl2yNnj/XdEKPXhNj95cEtYQlpPI35UuXW+M6jOvd9T2Dy0ZaH52lVT16ub0wUus9iCT16GXGqnel/hQHadkV5Vh2d41rBElztEpEPouk5rULfTPW2ytc2K1J4Miw/h7SCJbTuf1gK7k07um73ToX8WZoNv+Xhba/fmig0s7TFKm6c61UuWpOn06YnRbZ1k1NCk4+FZf0KR6jjwuNyaY09F/MdjHQ4sacQXx4FE3be+SOw+yShl1ZEP1utJA760PZYEZYCUknmxpCfl4aPqFaTBLPuZr/Ep141r43tcdijvR9AxzmCXLGUT+AWDBRskxrxSvdWkisoqTwGHSiDnSmnuMqL+4TrPk8oPW994PGOkaag8xQ8GLu1PTG811dQ66VHFj5GQk3vzrP3yUZC33ZwTBvVFIN7EAIcQK0YKMyE4Kh1rko2sIJO2sO8P6SOPjiWd4BWDBSCq1CkwcSpwgddRzayrQREs7FBoNhe4azlCd7yszzC0eTYOKPqVKEV9mkMn2dJ15BuM4Xmc+E8tGzSJPE28Xl4i7BjlZCb1mso94lCdcr0DKOqY7rjZPCxKekGn+v8mOHkRV5JFOy2J7Ng/GKe1NZWfk01kUibgSnJrtdwbg8T4qYcaFniJ9x2PS0mGtGjbEkISY/dr7pSdtSrNiBGWaKVYUb2WuR04BrFy7PL/APK11iCtW8U15kqAXajQnp8UxTBsWa/aYB6+wO8JbMEGzOzn2xTX/SY8aFWyUpZ8UW2E8fZ/Tm0JTTBBWUi1kw7Z8tYSFBh7G9jrJiu1JNn9gWaUKNT3po3U0tWhtMvQRR+ruO3VHhFC+9xraAJNr3vQY73jD7T/AblXqldT2sMPzkNnSNaMksYdJyF/czy6yh0+2Oli+F9TD/+2OYJ/7lv6I4YqkRMKFoutOsLK/v4Ctl4dnY8Rj0MfUnlI7J7HEE/2TiUcGIKGbGk6ceqYhT4NHEPHyWcvJTdJ2D3OAJGFSZehfT6yuy8ad6oYF2iUPxWWPVLVOs4AiqoMm6epOinmuQiADNWiA39uzC4Fs2jED6Cu8cRiNQtMhAv3YJpWHwp+5WYFCdnXi3zB675E6h7BEHmn4l56zhH6XRWRgjqcnhG7xbekeqxmydQSwkCJG5QS2heGScnDy3M+pdlYVLgEbg9FeMviG6yA0w/ixrTliSdGnHR2AA/8nNytHbwi7znBdBNdkCxWwNTvNZcSgiTW958+qlqYk/K330aagjPMnog402z6Zpv0bgB0bG0qfCRZU7GzLWxFJviNaBb5ACbpSIDuFE0ld4kO8eeBinGfMerOir+GsstdhD0lvxssUYotwNB9zTM8RozMYm/gLKKHeACNbgKP8i4gfFCrVXd+skOaMv5cSTkzebnEtEdghDYqZE1efON0NMuU1Y2tbCzTRvx7G+ezh2CgCzG5pZecYpInrQIiLSeiXnxmX5dOXmBv8IQ9EL3zZHc4SZUyf9mexkL8BTb4N6c3E/k+wreXYZAY6Ztpv/NFaWbzZ9y9pyIWwrmTqp+YvgLsrsEISgVhIdWtiziqsAl7eHh0GGlQjsKaQVsMUFAntqLFGG9zbZOpGraxEaa3nWpk89+yYX8ICgETqa6LjU1xHvfDKXZX56G0jih5feIbvIDdra8576tMcvn/pflA7FdfRyapR/3l8N/3n2NIHTrwmfGA4260bfJNzGZDrlJs2WDBEIdvf+EbgFJyLFqBXjcvi6rUx4pNRFFBVkjWh5Mkf/nB2ALSMJgAfrwSyduolYlm+B3jxBjMC9tVsTLx7WaJNgCQNUl7GVZ1X1wmv7QS5sHmtWiRIzE/AndfZZgYWvlh7ilpLUcV8htVPI2ErtmkWK0Gj4+tAU8YXCmH3nw29o+HqlhF0NsK1Vl0MLZ7Ssnz2o5T7ANIS03jjMrYWLet53YSYZlpjj30P1x1esF1wK2UGwGLNOzkHMhrACxX3iMQce7xrwovQW0gC3ENj76zrKNRWHg6kwturXMY9p7ePUVzlqyEIOZvbNB3eOUQoy3Ju6Zt0EuI2G8ccz4/TWk23ShpRbR7aVQaFTH/MsadcpsRn0amdqlN1hu0wVTiuqo8TVjueboIhJIihNpUV7JyS+1ki6Yej1KwBKDbKMjPxESMWyuLWTwR87I+RrSbb5g+37Mn0fZSV5n7LuVWUIAYTI2DKPdm8dzly+M8jGgUjHVpZZI2n4YRqcWcFEmwNkJ/TW+0Evy262bi8NoDa3RxFgVtu3G0ZnVWfwDvCV8IZkFTJLz+JQ/ppK6OnCbWWSwtph2ZX38A7QlhCHYSgSSIqerQ5I7t3vK+nH5FnqL5eT1+gZhqLY7jc/uIMwkVLZtc2PumNBALCIyzb/HtYIxWIQmdaVZ5mnTNcCirEwqciPX+Z3de0gLKEMwg6xEqmelfd/m82F8j2/lKAyUVHwAVL9FGULtm6LIXAUkqWH4oogMZo+uJNc4RFMtn9AtoAzRWd9Xls5Sr5kbOXYD/H7z+dnyAoYHxya5r1+gDD1YBGmWkNNr4avRr1dMAOldtshH6Rn7Fa7FpGGwuc48cdyNTYGMVjohvZtNLTzIjDNIgu8+gVvAGcZb5Ml7at1rpuD1ZQY6MVq5Nr8GKTo+4bpPGqpV5x3hgeVW8q/ynoeoPavxU8p4vudXUMtJQ5/5eNprdCRHl4phTtnrieZd5L2P5R2oFYwh9SBTyQENxpI7I3aOL37CVpGgxvAO0Ir5gu3iyo2/FnkRw4bzbu1jqanyEzh5lVbPF0zmveV5kTZR+ZmyotFtvpA190vhGtB9wmAjTZw/S8s6soO80mfHesIa9K6G48rEAcv9+UI190UaP4NREpKZHh4e82/L2Z3POnxdzRjc+Ha0z5wdU80cuGWUpY24LZqNe3+2jn6FdJcxVNMQJNYmlTDh3MMfIHvyT2cyD3Ozcg3mLmXIIXgmqIPYKU43/qrjEGXOLfh5FLST3+prlKGFIIM6W8PDibkzV5wXR6dENmOkzWok/QHeCsowTui0rZsnHDpij49sdCYhYVCbxl7Qccbg67coQ7J9efb0gz6+DO+CMmAlW1yQDUU9OSe/QRms66pejh1WbHf4XRyF69C4VEzz219H+r6upwzZZorYZg1SiuUYNEaCX0oWWxHHcO8DpBWUoTenFCc1NO2n2pcV5ts/k57ik932xDNHhF9hDNFyBKPyaYkzCSknHU84DGRFd6VHT7N+greAMtTB6GiCmeco+smIHyIeWx4XwFqCRTsjvEyfgC2YMpghBZ2gXEg1quQDBLZ1tXjZrOMfX/asnlAtJgzdCANPKqdEppnvQSIIrTXJDy8E0axD5/wE3QLG4OfUb0qUa+1wmsGz2u7VnSntRpWVtzlJ+YRrwZjB9i5x4x5sXQmu6g23x5maiyXbvex/CdT6MYMlb7Okbw7mmZR3/ysKRueX3fHtdfhxQLWCMvTuds1t3AzxsfJJD/fN8S6p4xHfAVoyZKj6q+yY6Nx/XuxA28QxNLf1jV7hLB4yuHEGsdrhAopSdWiRmtBdNN8xNmZLv0Z0X5JkZTr6rJpRwUcmoPxYaPP75hhx4HdPWO7PGHoOdMrCOCyZK5b6y6oKbtf2jPJXLEspQzDyu2k0I751WJ4F6lDS6vqo+WTpeKiMnyDdpgyulK3aLE4JxIzt6FY3rTm6OFcFerjGcluUZInNjS4AQ8NAG18rN5KOxsrWQjn5pb5HGGLZostaKpPWFDqaSFjYczbjJsVJm+H7Z3hLZgzmbQS0ULDNywQc6hyguT8uFy+3ad//AG3JjKFExfbVSDrWOKbKw90P8jDqlUg9U0+qzi8QhnEK6NINrkbtVW3bcOQriExUdnVqfY9rxYxhXGvYB/g4HlIk5ZRA3T1Hz9vKzE9/VZS+IFqhSnKWdxVlzI/vodwIUZ0TRZyVp/T7dY/fWVuI2wIlLCC2hJ2J+bnP678rnxETR3NyxxM7h0/g7tEFGVbmLYZuVCMsoBRih4tcGudsvY4zNUCynpab4/rFBaYJccvODINwTpFUx2UobR7LFYsE0wbiNFKvcK3jC/LUikm+S1bjJqWrxbh7Ntb5akdTV/9oAvcJ2z22EJVAHAn36daATZtP94SFIxL9xZKzGnvX79gatkD8cnbAKhYcFnnNO701xLx4gHV1qm2z4QXVUrowu2WtF/jvuLBDq5rLPJwZ2LT2KckVM78DdZMtzAMr7PvWFs7EHkVWAtz8EudtE+zHOx6mcfH+AgPhUV5i8OXGJ9hxyKfrkdWInZWqp3h4mtfGxQsM7HWU0BmulFjk1ZI5pVQuyILIHBuOjntx4QbDfH+mycFc2nejJu78Q9uCDEJWQJ3J9F988uPCFQa8hSwEY1sbJo6Kg1vcBb5b1XKMJ+/yKr7AURS3EMGCHormRWjsxVeMkBptO3/2O63gCpw+o04rsAA4gpLpFPzI4ROjrXOV56jmVzB3yAJuBaM6yUjGozS/qpHcI6s297q5a568M19hC7zQsWmDoTTPbhsruvoxXULalppj7hh8+AO+u3QhIisrP1tLjMEm1UCQjJXpmskSvKLSPwO7SxaioiaoU9q4fxWZ6/ekZup0360TRiP95FVfTBbQ13j3s2V3NLnCkIoM/5P8PJZGt7X597hukgVW76paJz66LQY2181QL/DqOSPtrOq195BusoXIhRG54rpnljAu2fDwE+lMQytdzPj8jL6yw0DLx9Sj3CiDkTN7SYhDvJysnCLHQndK0Ks+fYK3gi+M58NwMdSaWAsPTNOzojSR2ORuGV9B+08fgN0nDM2+w6Ildf4NawLyGwp4cbmWFTFZL0GtZQvB4jSFrAxaQ5cqUlKi4XJEDgbTFYf8kkgR168wiC7o/h21b/HUec6XXwFILGSN/0lbviF9gnWfLVQf+hYslCt7fCypeij7pkxKWypMfQW1nCyM69DcyZCOuPG7ZRZ1+l7uIW5pvSsZor9DtYAtlFQ2g/dgbbLZ95Tnl5JvJ4zoT5K94uIFBhaEimIK+jiUyFJwqJIcY5dZPDTlloeTw3QtW0iWLIGHY4iQp+K3EfY8ZrmL7MLpsiW6hHSbLjSLqWO60BJ60lhmWc4LzVJ/HOcTQ9FyjeU2W8jmzYztdeuZEo8vP8m+FHvJ/urtEdduMOjbyirRR91GcECmRxaaxmhU6uONlynbG0h3CUN15uXBcZgJfYyZAwiBK5blhf+E7q6R3GYLg3b/yBHK0cZxWq78LSof6H50575i+RpbaHXLqx48GH+Y5pKI3TwEeJ9aV9Sn73+Bt4Is5OnvydEYe2dhXKYrcC/2UuqWPOPPDqOv0IXx5euCsGgeSQLbTheSFnRM6OV1t7wA+wJdGJXJvqBX8Wsc10t4ODUx3K+WkFovTsrFbCG18bXLuMOzKxidPku3txK8SVy4l3N6j2kBXYgpbn5WbbNc+SUAZsBmEyt6ZYcjvH6LLgRLTeBzGwWm/KJYeGL2EYi3nMHXHT+gdGhzLN9foFOefKEmiDElGuWNl7yqbKpMi6yrmaVq/gRswXhhFAcF5/AQY5S3FilxUiZof93G/RhuHIvf+q3xwvRNpOOSfdYKu4MkJDJ22K5PM3EIfayPn9AtYAwxjoPVb9HbXSKRyLS9o6EQ47MJW1WX7QOwBROGav6plbVeYogqDjK+5N0/NYzrtG0JnSdv/3rSYP9Hbl+DbDn5Drja9+55YJg8qKEa2/ktsAW8oZkfNV9iyS7RjCRjRMr42ZGx7QvMwd4CWjJmGGcEeyUlEFIXseFNaX9O2US8crF/xbOYN7iwbT53l2WnpTSWrAHo7IS0SM5zbdeQbvMGP5uaiKhjjToj5//MoT7L0d7MJC2dXIN1KXHotoaNLjd5Yo60jua2gOCBrSlY8wTKUuIQLIYKN6K0DYRl8oG5LG5yLW09q+fV57hukYFTyKKrOV4CFXFkChQ80ewQrZSrkgRSuEZznzxE/ZeunqDksI3HuM5Uk1tzM1+8xF8jD6NMMfMYGQHi5FEqzyfjSUL/IJvCrciq6DO+JaOGMr43haO3ro1/sQcZavCCZS2N+pT/AG3NsMFltGZtFCaIMTiYFMlIqdBsDYvz6xXYF9hDM3dl6VxkL5lCUFzUQ7ExFeDbPPk9sBXThmA5ntpe4p0P3eU9xpzzwLRnrICWD5DWTBsy/ns9ZykPfi80IpMf1K/lV/rwlWUGFCu2BVdgyYkdgfHrBemmGT7AS8d5O67h+bRq/YRuAX3Isch1eYB0+sUqwyGvHccpFhy4wk+WK8kHXPfZQ6+9qo4cr/ucx3RJa5oa+lMgW1yXg+6zrjJ+Z5dBpuq2y95kpqpl9uIrCsHKIgZ2TuZellTxfQC3Ytpgm+CcXXkLQTObzodPtWzo7APA1OVQpC9fZZjdvt4TplzF4lSxCfOSzOINyXfa5CpmXoMvqL5AHfo4mDphZzHzBxuPiGzguAVaaKvmIC9Zu8ww78VW+pY2OOrApIq0POIlZ6fSlcQa66FtvHaZgQ5Raz9QhFFO8FaXWQNraZUkYTuxwusAZO02A+VodgAar3CAtlRdkJypmzLmR2KQa0D3xw2Dif8wDLJVJv4hbaEUYfaAmrXzugxpL6Hc1yaN30aLZillzFG0dRwfv1OPkar4QPCW7jJogm6jYjwNHNPq3En38xocs9gX5FGU2zWi29MGazChLh93LdbcleUX+gFFwjYv45HTU3EZacijQvFZezi0DiUgQxmPcGqc0XSL28lv9cWJQ94F8IHM7RbZm5q4eiaZO7qNX7X0B3hLOEMK28r1dLhjbz3vCeGFbJgWtyxgf/bFfWfiYM4wtHdGNcDLxJSPLW2RsPHvWJU5qTq/oU8y4ZH8agpaluyVH/4rntCZr1K7etNWMwYLTxbxi2zLbMMZtkDo+AcEOSW+B7Ri3FCbWnWtlLLZEj3kwJWaQPOP9Hy/zfrgK3zBWixKtA4NH+agGBvvM7m2UUFDPSiTtMT4Cd4CwtBsEjJf9nHLbhbRam4yEOxYmpoojvcvlfYJ2Ip5wzgHZDFuIytaHNrnI1CL/eI8CE+UrPEC1WJ5kjNkTf5bPWyZkkXmMXLUnneDtdG4FGr4hG4BYxjFXNcEcDyyzowtdogWj5BpwxyYsAPi8idgC6YNucRNhR54n6oWxIqML7i+neTN3r2CWs8YwtRyYi7jd3uprc+Bc72ywruauGc/49phw7gL2cbytTjYaGEjpTqZ4trFZKl88WjD8wJoBWew0oXmeRq/Gd4plKS6ZezY7RJp+5OjYS1lGHA0um3JszbftD6K8mT7MjcTiVauIS2YNbhcNjfAxnNJqePNs3u5jD81mCD87w2a+8OG2jaf1Zb4rULBG8U/BkMm3Mde6uTdWcobknfSvfuckZWmuqVFzJpGmrekLATf/TWk29OGlJ2CBHzo6COY5jEATcQR9Rj8mZfcAc1d4pDKFlVcx4XqKHzjI1ErKs7NK3i+nByJX5w2WBmp+1/74jXNUyjJU6Mx+vdVCrNQ4x8ArqEOccssTgEf+KzfbnavESvFaLk1VFU5/wHaknGDLRFgc9WqjkYl3iJWqrQSorxw2kkF+gXu0J2tOTLRMkkL44a+j0G2nYu47xM6/x7YCvJgyvLNSsrRVIncca7ue6HzDHlt1r0AWkEexs0vDdn47aR/KHs0Ezwix4Q476k6T/+5dVqlsKNSumSXn9M4rKrfRI2caPxZNX9LTCqZ85NJ9Cm6f+EOz8i8WeD9bHtErGb77FDo0vfgJiyWhcvg/3nacArsX7jDAdioytsPRrWtSL9cmsynJMthvOwkpAhPY+4nXHfZw+HndBa2GzVuiBkb/+rYMWLrzhPA6o1weYXXfwD3L+Th8NCCGcbXpLU/bKGD48Sa6Eri5rbcRc2Swidc/8IdnnGNg1TjvWr1epcdY9z7w9TtFsKqqC4fTt6xBezh+JKZi7zKh+jSPDcbLKs+ZjR9XJQ0r58c9l9Q/RN1eEZUS9l+mDKOMjQKjPt4XPSR8ihFkWW7d4D+iTo8A8rmSCBTtxCTTJixGG3ajpmyi0Y/98lvVYBukofDbzZKO/XMS2wkcRWvbbZf7hul1Z9wXBg/APoH6vAMpteS96YQiX+Z3XWw5G2DtFMbZ3cN5h+YwzOY0qL+mlgyr44iiiQKVKG6CXVPvrB7zOF4GJl6TTH3NUQZ40oNNMmVI1ly1BA0Ep7aPwdI/ztzOJxBdffUGTcZdd1Wy83yk6nwuJ73FIA3aP535nD4rbxJHwseYNon2CS4jyWHaX06n2A7udoWMofjWz0IAdOYUcb5oCPwYYqt9PnpIE9Wtu9/wPdvxOFwQFo4YtD6QiXABtvuMAWmeGVHs79BOelL/QO0fyMOz9CSxe82emXNka8sE3GMmLGDNs5ISRBOftQlzOHw5oewSRNdw3I9qa+ofUy6PrOnoMXkt7j+iTgc3n/nG9Wkj1V56zT72fiJes98RelY/HtI/0QdniENlpd4s3ruNDxarruHUiLb0NxTXjyU0n8+fYs6VDPDlFd2LkXtjShVEAt1XQhdcNrpS+UTvAXcoRmrSai2ssq62sh9jFozkFKhjiqiMW5qn5AtIQ+mjJI2j/O1qe85i/XeSAvLQRK+ZxulJ1iLuUOwxTWNsnxq2mVBq5+0cDyRjyea84+swcMndAvIQx6nuKz+ffY8Lqv5An6Ms+BC3mvzrbq1/j8Au88eBpHXAkPOe/yVWEJGVsFZNmr51I5DSoFazx2ivTxZAS8B2mcTiPxraRuKGGrg0GhvgS2gD+beLk3qeFaszeTa6iMxjBqwSoyTwjtAC+hDqklGQNYFRbbQeIvmSVvptcuFJvhXOGvJQ/XjyJp3oZleBaRBXNJEFbC1Pe7ohlimh2tIC+hDCmoL1fFjEX3F8i/X8yz9RoX4M5dCDhW7TyvZw/iw2g8MrlV21RuJCPGR1mDb3KwonzyWpeQh1l0QWT155hknY9IIWmLRdnyGW5D4G0i3yYO3BoY8YWltJjJDg65mmo89V0UVhHSN5i55GOTOK30wYsYQIJ2yxFQnuDtZJdSTz+pr5MFbUi+ireBVsIyifNu+tLuXaATf849YcvoDvhXkoYSuFJZRLDWmH73Fx/028YwL2julDof6B2hLyEMwD+HCPnlkyWHf+p++T4zWWkQf207KqK9wB6dV1pAiR1PqKe9D7EjTx2XDFY4pSSe4FnCH7CySd/PUx8chkQeN1qTu1qyyKP6AaQV5KKPgnBRhvDsMQKgxy2YLbdeuU6xqfH6rgv8WecglqdhMWVZK46Oc52WTPDdvq5ipQjNSjp/QLeAOpY/zXSOb8V7xpnPhaAW/0Y0d/H0L0y7uE7AF1MGbMYqXTZcGpZEghMwNgDh1PLAsr9aY/RWwteRhmufy/Zs5QKIIbkVe4IwJ52nie5Qn3GEoEvw3qMOo6WQ6Y3EERdtZTimQEELKKzNFzirFPgG7Tx363GqbNW+tuSAdhOKwaodoKVhaSYsvfttCtZ47mEuPDIpmDs4U8qb5iNTEljY65fkrHuh88MuJQyyq08cLYynfnP3p4euJV2LxP1o4fQdoxdyhjfJAcYbNE2eYcHeQUGiSGufctOaIJ2/5WuZgTvLa5DE9Ku90+hXCqjZRDko7LP0a0m3mMEM50XzmVmtTgO28gJCr8qcGj2cp8lBjBb+SO1RbfkZYXcYPEyTBeQR+4Fa5eYmd/VhryUNQJIqvAS97WwqjpnpUoKNObUry7f4a0V3uMM6gffBQGHpG9uY0kuXB+eqSBFQpXaO5zR0snCVtkyBQaGkVqQuFe2lZx4E7qQa+Rx5c6RWGOdh5dnxl83hMruq9ny2DKTdrCk74DHDJ6GEciD+giAm701RRDjOO9PKoHEcpEoXyl2e3hD3YqTN/uh7pncckL5W2L2gO1hjV4W4nb9gX2EO3tTguNBO2cIb3vq/9JmUNppx/VMD798BWjB5MjqdKzvXSflksYXmDbnBUKp4WUO3vMa2gD3Y2SmY6nhCOJLlui2t+CgB6DR2n4uMB0b7EH8ajSGHer2YJRDJeIeLUBwXVITJJzuJDsNvP4RO6BfxhnA5xM5xyla5dBqLUQnSKR3GVFB8ZD0PUE2D3+UPv45Xn8h0/F62qKAsMvxtAjQ8yRmTy6fJprR489ObVnKrjlGAT35LuyaWhpc1s2vQufeu1fUC3gj2M309iUOcyvbRRIjNCStgUwCTKKAppzOT+CdgC2ZI1F7HOc25jo/FhW8dDGwdaQQPS3CumL8wdTBhXWUixuZojJKTsbqNBJoCjhFbqWXiHa4VqqY0fkLd5HKV0RAv2/3l30yu2ZdmOEWIvcFYMHWy7VA32nOZpkCLJ7H73kUwmlSO08uRnW8sdcm4K0a726akaDjsWBF7jMY3XmzO0XEO6P3UYJ+YPAuLaOgZrRGYWWaezKxaU3lyvsdzXLI3fBQKXKtGTkW5Gfhi8FMu/0KTvFcpS4pDMu4KBh2VwkYiMkiqiDUT1bB1IfM0OI70nSLenDm5cEkVaKu1nKyLQYaG7BducujQc0NxmDtWCWmh9Ye2kZAlW2eXR14olx/iTsql9VbLUo9MaWMw+00ipmEMqKQUFekpZE//o/oBvydQh57CFu7riN+XiIwOWGjRZDw1NZcp/gLaEN5htZ6IBRNkZA2ISpg6bMihUeVyfnAVf4A3THgAPz5Jgybu+hIU5fmnX9KO3/h7XiqnDnn5ujU36GEjjuXVVFo8SykvY595jWkEbBsH6YZjd5XBB5HfaF6LawEjJ9EQa7P9+gTRo938znDQjz9kiC7kTZqZhW/Zb2raTXUf/BO4eZ+CsNtk07LjrIB08gmkIrRBOjtbHg0WxkZ4o/Cmwe5xBfk5Z7ZYwOAxx0a5WulRac6V5k2NVllG4/DnX8Qb+Xap548uj/vayKNAQHN6MDe84cTsJg+NBfkJ3jzdQVloIFw28OZ1EkcQwKWoHajKwZP+Wc+7ZUe8U2T3iIBLftabYXOcH7akq8G3epdh72QFGq+jJx0D/MUu5Q5aFUcTd3iRLSc4OtNmJy9G+udvGmU+BIS+4bnIHouZC3MJzR9GJawELwNyRODq3oiTep+7CC6Cb7EHh4kkCPddz8DgFzR9PAXDoF4JjBSicvFDL6INEW5YKybp0hel1Zms0bZXWXnNUnfG0Ln2AdIs+aFbs1KwqM6R63nUY53m3u5COQy0pJbX0azi3GETGZKbQPIxxHOsomPCEDXsgSMlJHD2eHEyrKIS4bnZbzGTH1mVwUKcj2xpSyLzMioM5aevXkO5QiK2dWKSEHWyKRlTYrBrmBUfk+NSutxdV+gHOHQ6Bc1raeyWdDdHMR8UgnX3WKYtDyXnyIn+FQ+jF7hoq+N77FJY0ErsS81gd3nbbSFBfwx8A3iURLK2aLxckNTeSghLCHKW4MIScvibsfLc/QLtLImAJoWB3Y4mZ2FXLJb3Hx5A9zxiBrIL5BdpiGsEqga1aoHJJMljq+bH3wMKN9ULVsXXxPa6bNGJ+AaYtQylRQkVDFbZ9fRJWJC5u9GjKh2d1k0Yg6LaIGZ5AJaAx8CkyQ0IvWyX+foIza9GvsIjWrMcicaULnBUVQopJ5ZYGl+IgYrJzrvkTvAU8ovpSsOiIZgNA/UbYRO7Ki5u6y9Kd46O1dJgPwBbwCDejkFHDuro5LzoMTaiTtevmB4+Q6VG5AraYR8y9zaBKZRycGmyhOdPxgQlLtCsUdIfS4QTdAh4Rp8gxI3Bhc9t7FpPlYc6CmX0CnPve50+47rOI1rwuy9JrmSVFj7AFpKuyCO8hySPDnXycXyARaQuHtgDZ7BEJzfdLJq2yvrVJ2MkRdoC1gEOMoriqyMlJo/nCjybfB4VjFArSGN8BWsEh0nijulZposdyDQ8vApJx/7Sbp724tArQag5ha2TTA6YkOqOFMtnT+qCdnUpTCktx15Buc4hedj8Mi8pCGED27la7WBtmG3TFN4/nPoFoNpxRAAdSpeSw66m74WBNpkKtx417YVlKIEatooAui26hBiiMRuhrc0iGbr0zeb5cQ7pLIOYcyGnfttF9ZZ5NUrwcI+ewkZnN2YWyij+U8SVrIbQRYBT87+4FJ894scNsi9YTKF+jD4MwyJQ6xPHQ8EfXCIJeFKN2W9P8SfJy+AxvCXnwJoPViL8GutOiyvNLw+kztiYrlWfz3ytoK8hDdj7D9Vqp846L2mVpxKrojht/itgJf4LsC9zBdCNaLBrMq7CQqcQCWX+xHz9+9B5eey4vuBZwh2KZQSowc2ECECg//SOMys9gND6S9B7TAu6QQvQ/rPJVSkyiu/gN6UZZZmtkzPyMp3+LPNRo48AtfptNh5ajzFrpn2PONt42p4dajidX/wZ56BZdTdHrijif65gsRLEcjgvTD2lp+tBmOEG2gD1MUkBKSCeowyvcfevRcCuWbl7uspu9wrWYPJjfmnZ+2iBVpB0lvCmyV6zQ7LWVYGFNrMn7T+gWkIdiIiEu7pbUBk1oHdnSZ3A/zlZOE+8+gbrPHPqoYyCo1ZkEfDLj9DCBUWSOd80rgdadvGDrmUM0D9Yqs47xnjvplPIevxu13JK2H7G5d8BWzB/aqDJpK/Rksrz5l87HRBAFs0oXc0M9V94+qhXkIVoUb5UcDvvY8frkfRdXF6d5T8YT8tCXk4dRP2TOrG5uZw7C9whwRc0wTvvNXrqHa0gLBhB1vEZsZPXacWUUqrRnw9nor/OLZXeN5j59cNnJQqzVylwPUd5jw30UOU4d0vYKZSl7yKYEp0xxbRYBWXlwhah2BHK9N4yFQvTXiO6Shz5eWy3xhMSnNa7juAfHQ9FjtCgmVmlSv0Zze/iQbCA1izvLKGLD/SGSR85pHviRzms7KQe+N3wIZi1DMNC4U/DXrqhwtuZY5bLzqjjD2dn4Jf4QkzYfbDo636rO+vt84UvVGqQZzsar3/E7wweLAir0nhjZJFqKeH0m+lQWuMtQ7uxH/cboITlZVwcbj8htxu39hCQn1+72dKH4HtiK2UPuXfd9za4jk0ChG9TN5msYdSDWGB8wrZg9mK08X6FrXbLCLg3sNv3vscs+KD6/V5PKfoVBdNdkUZ5N/E0Hu2R9iVTJRU6V5tNDzzF8hLeAQRR7ZNguOddV/DbPL6zdFez5bcGtbvYGH4AtIBC+WfAv4spx9yg8j64ncoVEcJ2Lm4mbaQUugK2XMXm1yW2PFKo8DjasFnAI7CRx1z2++CO4FdOH7OVb5L3zWx82uLofr6y32DGiKsx8Pj4AW0AictTl3cbVg8FmVzoSTItBYS/yBfbBvaL6hoZpXNB599KTiIhzghucrrbpilo5RsS8wFpAIWxRWoG841rEurw6hPxYQTCbbOphnf16axlEs//uTZIFFI6ZvXd4PQ4G47XneIjlFdBaBpGChWcxqxnH52zO4iIrQfuWqp5kqJ/fQLrPIMbJmBUc3TqKHNlkSasQ2DW1XJp+DK07oLnNIKplUkrPW0ORiTqGE3tiVTGBTu2vCqaJZe0AwiIPuZLHLYglR55MkyUIhDuDQ1gwWdN47RLSbQ5h7mBFcrwqF1L+9DwWCyEQwVmipQwlr9HcHkCUcSg6ci/oqITkteMza0/ujWDWM8oWeQXzPRIxdac0d8aLRFlc2XxCVcwoMpvdPJfh8xrEFcAlJMI2Q7iAoy8ysvLSg88fEjVT88qh97n+AdqaIUSR6b4Fh6DJodQjDEZd2hyCQmbdSWHwjSFE25awxjXbMFQglNvLRCvtlrKKSfTvga2YQqQatEeaOs5GMeVfqSdpz+FlIljbe0xLphDVyVR3HO3IcrGsa2UvWGxWo/26p/FW+c99Q8Wkxb5GikEZJ4F2quUawi0YydUbJbtLWhyuT14dp+jusQgeSRh/X2enzBwY2fyj50qLRjx6cgyW4vKT+PoU2T0awRJrNrv97SCtdGLZkcK8NTMZtD3+qPiPK1jrSAQjb7Pnr/IPKp2Xa9yNbOOpl8SC1zjUUL/Ep+rqFN09FiEj1lGDyqDQZQ77VPHNytLZo9X0m9nm0z15iuseiZjUodkKtbxjcVmo+VfiZexaZ7SN80hM/QuopRwCHjqeAw3ZURw7mcmOw749vFuZ2Y+jP3LYPS16vgC7ySKmpD+6su3nD66A/pmXSqlx6KaDDLSehCgvgG6yCHhTVuxFS7W2X64i2Bp4GT//6G17hbOMQ6CTj14xvT1Xmmmtc3BpW1FZV+Nc2NwALyHd4hBFG6WD0hB661k+SmnmCmBlMl+qbqMKzk53DeYWhUDNsSWUjJcoM43Af1DMHG1qqcyVwsmDWUUhoMHFfKf40RylSnQchmTyVnkDF3YTrei6RHSHQRQMdGWEOj7tnNCbSvz6CJuOthG4edi9eT53GIS0pJqe10qCXij94ZKwWfVYrZn7sQcrLF8hENy9g21q83a8SRjmIfxOalHxKmUT5KAg6v4PAO8SiAIF3pIIS0ambpvovPQPa5U+rma2PH0tf4B2l0AU/BMyC6O9Yr+bQtBpRMYygjmzfg8vBELIFhOIgqdgUuC0LSMxQGqPKLSErj6YgF7xkvE9sJsEgvDK2rVwUQqiuFg02WaOyh096hflbYb3mG4SiIIpeWTmYbbgzGZmmaJVapbvzGSrH2OgBqD+LfowHpVEnqlGTqvxXpGcKp0/cc9+FFcF5p/dR3T36YM3IxPcXOqggQUTPdxmMidYQxduGhNslXv7hGsBeTDt0o8sK8flq4gzWn2R1ZqKoVXzUepi766ALaYPrm7KeatAC2VdrbJGrQ/71jJ9Xl8CFk6xLSAP42wPauVZHC/ak0ygDlFErbIdnEf1ydZi/QjsPnvwbtCpH/l4hc3jmUxzdf80hS6t/2wpKK+41hOIcThsDhXZJ9a5BzJ1h5D060Idrxny0fAO2AICYfHuCn8wn/CpQRmM3u05xjREzKACJXt7B2gBgRhFoNxFTP6BTUZiNUq7uXKKSkxaY3wFtJZCjMsva7Q9uDF0tGkzyj8E5GmOmPpRQXuAdJ9CeN+3TPVB3yerKqTIMRWJMn+wUNMcP8C5TSKqSf3pd47LxD28mH6HUQSTIKejlldQlnKI2FyUJ+I4x5lYpVkayKTAkfhcbbNlG1dcY7rLImy3NW6Z0h6TrIgDdyDbD7lHy+NkQBkQ/TWcuzSimMgbgtC42Ma/KA8dJf88ubBmlK9Yvkgjgo2qYXahzkp4QJk/F78UGZvGhYJu6+L/AHAFjWijXpEYLzmMnDNKOXo+bEXFOi6Yny1Y/DOyFSwiWw59RjXYSXwpeAyyQNakR41NiZxnB+ZXWISRPS+DHHa6UTVDKSRQm56WrCjV97gWkIjB6XdTrda2RXhZBM/HhLi4khdV3gNawSBM28y1Nk4mtITYuPPGK8vHJPbxmB9X/vPlSxQiOgtpU0pqp1M9SjyVwg1tMU2iMmoa2eC3w9foyzc4RLdBM+LUUQMnjZKlwHZagJui1da1vJhD/wRsxQQijZ9JY5LxW+q2SdhQcz0T0ZZs3grfuQa2mERkF91W5pkYk2EXjjkKkCOoJXcXt0WNED6hW0Ajsjfvey3/5toV0UZGGvULbjozGTa8uN+e4lowg4gmnZjHwPhIZ2HTENPKPscpbDW1n81z+QXUF2YQ0XzhWcILHmG2FRZBJ7tVoxrj1PojF6R3wFZQCG+xqU3mWo5PrlUtcW9yf7NnoqqIbwEtoBAmU5XjrzNbYvr8FKCPXLKBNeIBdPaer6UQdZyT/F3NXBzn81Cvjx1UXEXyqAMZVjR/Dek2hehlS0xPtvmOLfH8n9FhFwyoa9fie7rGcn8IkS1+lF56jUpALPlh5ppVwv/oZnrFspZAFDuOsjxeNgM9gp/nD4MlqDNfbOTYPl1Duj2FsOyUJl7Q0JWk5PawW3WyLc1D+9bRX6O5PYXoQR2fWhpBNEUKxmmYR6vRZa90vXbyZL5HH5xJyzCOTBE7hx41haB9joypmrklO1BnH/6XphA1K87DzBIctxpiXf8wYkq5Ng0rDvN/X742hWhefQJTpM7zGQWA/EJQ17s5BlS3/QXYF+hDG5fbT6+bYTkLrVxtjXAj1PV9cMbwsox4gmvFDKLaZS85vcc+busW0whikTOFCpkv8T2mBQxiHN+Jmdr4hXheDiflsGdAND8oIhkQzw9pfgXfmUFkc+dnytW75qZddKb+CpCxpmjhs00HZnqCbgF/GOWA14VTS1bCeUobgZkrGrBpc++YTZrU8idgC/hDtJRZvrYSgiT7LlGUS9PLdu7437KXFA+zyl/AVg8hTBzutQUUa2OMVDE+SfoEcO9NsdCZDYe76ATdEv7QcCcdtH2LZMl00yPCNCzIiu2ZUaW2+gnXiimEy2GqGWpz+N821zf3980lOwSLtOdiONQRE9UXZhB1lJisPORcK9JaD0AvoiXDJh/RDJXwDtgKEVNoygsdNZfvU3rc0uwESlk//1RtmgDn8g7QkhmEyVDFiktV2kF6ZFOQwWXR58wgTgCtJRDFRw3bx8NiNaQHyAy1lzpro2YV64vXkBbMIGbQAwwvZ+wm2OfmClKwSMwZFX7x12juU4hxvwEmxuaYWjWKhL6nZRTvZNh46LlMLEspRCo2g1A4aSP8gDlNbNtKAj7nGb1TCO4a0v0RRLZRmXbgORJjl+k6bU622cwsgwdW0jWc2yMIX7bIYl84A3P6Le3EIs6um9JO6roJ5oszCKsOUte/TLLiwHy3PiIhTIVWf3zXQ/wMcMkMYgaj8YqNmphsdTKz5w1SMGQaD9IjA8jxD8iWcAg7LyXGCYXj0qExwQIbvZ5pmbDKPTudvjGD6EkWfyG0nrW10fdViCR3FdsWyuVExPcCbMUQIg5mUzdBGmHG4UEiZIQ9+EVGhNXce0grxhCW3JikCUL5HXg2U5q6bUJUW2VJx1SI8t+kPV+ZQ4wSsvIUylyJx+vWy71fSkLdgtZfnDdRLfUTvBU8InpdKNFqFv1oROzIclmLGcZkfTrRDJ0AW8Aj3KCk2pP2ocmTvmF4Is6VSF6INkf1EnlcAFu9C2F2mrTXaq4+ybEQHsGB74u49qiMcVh05RO6BTxi3M1abRln2DguJKLghCA3GC/4UJrTYZfiJ2ALBhG1yyFwED9ZfoWmsHPKCG3uacBzUMxNUOt5hImiVU/l8UJtjgubHHQGoXOhDvj5tQQ8wFrAIqpplOQYMLgXZqnd9UegHJWY/Sl6l+8ArRhDjIpYM3cfHPoTS4CY/yssBcjjapqTn/xwi5VMpW7v0iAvcmFBIMfsuepBjU8hvoQwHCCtGEMoGDy78QLhyFTzll8alDvn69HC4wBkAYFoFYexOKoEH6Xk2OdXGAG72tDkxZMXZ+0MYvrxczLiylGyGv2T2rGaH00Cx+V3kFU+Ibo9gqh1yzewrEGkXowg5r/NnZA9u37zq1H/Ac19BZP1VhNeruRZIqcSDWYq26c7bz5mfAnL19hDHyydEiQMHoOnWeGJyUUyyFGnNJWlMf0B3wryUH2uG3lIxMGUjStn0tMoZZJW1Y/s4RzaIgWTk15348mhl0feM6KcGdaXTja0JrBvTCDMzJUnlEOWmStDNmK8+QV9w/crvQe1gji43LcLLpMgEHNQ0uM+oBwfoiVrNCSYbzGtGD8EyxYjsR5LDLvpHhHUWa5/fBZPMuv63/yvsIY3xB0VeRitdcpMm9nwTjkvdRcHfORsj9WZqwej6PgJ3r/whmdovtdxSDCMcYkgVd/AtOmX5p3Y7Rr4qZvv1wdg/8IbDsCCxXYTxBYtXZ3TC6keZJq1GjeIaeCz6Few7rKGw8/pTbenvCrbfNiGvI3aQTULuaslnBndnaL7F9ZweGjZSocm06oYNX5g4BXlMMd3Yoec0+LUJ2D/whqegfWWmYpUS/dBURJ/petguJXGWbplxZ68YgtYw+FxzcpGuRhZiURmL+IeRhC4qoauufg7VP9EGg7PqYyqDtZn4fAksKDzao9VvO7MH3NO4tI7QP9EGp4B5UE91eivOUhQz47i7jSUorkH56NySXBuUobDL2Yd7Jm22UNBf90rOkJUvKhpzV1ZwoWnRbIDpH+gDAc4g8K4H+kUkfIP1uce+zNF6YQhqEqs12j+gTc8oyn28rBAHRyhkRo86KbBTr3S7osnD+YebTieRfZxUbsNYKzJxF8RB401sdTMUmzbULyE9L/zhsOXVVOnMhg3S6aRg1yJ5Cq2MkIPXRbJz73XA5r/nTccPqvxTW/tVMeqe9FJ02S3MTegTMlI4tYrloW84Xj1hm0bJdj2GvO7ed3KI0fa3GjEAb/3Hv4A8N+IwzO4mrat/FFzzoFRrtqf1v3CJqx5nATJhj4j+zfe8IxscAW3ZW4WXvSUJFcgKSezI9L91tg7ed+XMIfjq2+3XEOlR5cn6ZTiQFdxnFrdDs3wHtg/sYfDF5BqQZY36Etj34fPUgGc6v1EE3q8TNlPMP0Te3jGFNN4a6BUzlY0GdS0PQmCjAzbf2Vz6vkwnyi/Qh9qiyrWTF2itQwZvjjOMGIUTU7RosReNX2Ct4A+jL9FC2XRKhZkw6jli9NmC8aRo0xmQhnjR2AL6IM3JxqvJn9EKuTLrBhSlYEbHo2+Kek75HYFbDWBGIxZ3paWKIlotRb8oZB7OYxPem7aLfPlE7gF/CF0r1+p19qphwPxoXSwS1Y6btZQxx/owwmuBfRhvFtM6WvuWQbGmYFbCPssJMxrFQIWTh7XegLhu0VGIZ2qjTydjm6pOzkTMgOLP9vO8BtYCxiELUvLYLeMmmJWgdUrR4OiAvMaAj/OzrC1BMIs9CRm6Ao1TpR++DzjTRpy0Xt+8g2upRApjb8LO9Lk5kC5QLTkMRK121kJekz1GtB9AjHuGYcZwShn6NGO0zOwJ7NN+iwGom1Rc9dobhOIGS7IfKNta3adwUNnhXm+YEVmAOnky1/KIAaEsgXmZKwjC4RcMdSFHyib16sEZ9eQbjMIb/4MNM49OqrNPhUHLVZbmyUQSen1Bs1dBlGSixDz6hEkGq2Rr/Y2mhmIY0G41E7Ow+8xCOfNS0gN6RaJU2nKOuB6xnTMdPz6c/kPANcwiCLbC+uRIRbMlSiNqdfAJW68ckmeveUv0FZQCHseTDrbeNsc/ae0z9a1JxniqB7S1d37BQLRilM8fTCP4s7WaH44MGHI5mype7Y5eniPawF/KKMe0a+YYuXn607uqUrdnZ9gjqRIlfQe0wr+ME6FjUG5jHykz2Kg5H15rLnNguFw987b5jv8oW9ijDl+4PUmoMIzpYlbiEwsvvDW2yD+A7z7/GH80yDNBI31qrFkQyXRFC/SNqHjZiyQi/uEbAWBMN2SAhJLmidDz5Bn9n4kecw2QNlOjwtYi+nDYHtOGTXjCsTr0/b0/f4teuyoc3ZZQX3h0Ac5Qbdi/jDYjIIUBjQEqz7gKMkPWfCGTz1vEs0WPgG7TyBaNBd8ppaOmC2jVrt2PqL5raUy1K0nmL4wfqgmQGU6FLcIuYDiw5OXAclP5h0Q8us1fgC2gD+MIywqSq70QlZGwYsXZc5s+TezVa39ldAcAK0gEK7LMbGbcQeBP13msTT450qUEn7DyUe4lj/UNP67o6aw8xJWWtPOZRQJMZhyYMHn7MtbyCBSRl893hsN95DFyPGI4s/JmvjszlnGH0YVlX7kgG8GifPFnmdACnvAa3a2N4Ok/RXLUv6Qmm0zoZnSFmlmUTNmjOqY2MZxnEalI11DussfWivtR1rhjBxx/GB+T6HObAFmQ6MgOX+N5vYEIhTZ+LXAilVgoXvzk+CmGUcip0E9eTLf4w+2vUf/fiCoGDZUHBixJJ59lXGvtFcX8CtwK7hDiTYZUbADM/6CMSOL07jgxuJ8l6N0zH+AtmT8EIpjSaxVp/4001DkQTxNF3tEpddPvr5vcAcb79HKSPgYpabLFovZqL3DrOmcj+9xrZg9mFUsdhfVjun5WtEUDvim8yE0c3ipr2PbF0wruMN0OQuEuUaZpMo7mXSAqbQMzNvS4cdr36IO2e+qn9QZJgeHbxaRnKa/UYszJJz3Dm30E3ArBg/mwSEq06AKtgXPiBtqSnjV+GTLj4zfPz61FbxhlE3yc0gpKECOpd/MHD6jZR68VXHQ1s26ALaWORgbLVScfhwIkjI2J0OR8hg8jPN/2ypo7RO4BcQhpi1Nz3vXnO7vjgZnCiu2GeEomsX7D22ZE2ALJg8zjAhnyUSicutSgDb0Z6w7uK1TeWj6TVRfGDyYkSOmVGazTnAwMcvySW2IIDMSjBTeoVrBG4JXP3KUnBVFb220acM+CTGrL9lP53eAVvCGOg5L+dfWiLt66vOgYJU6yczLY6YaTwAtHjz4rqXpajIm/oGTi013L+/LlrgJiruGtII4jNqOrlCzKSgSBRT9aMaxrdNELYdrMPelS61EipeYW5AH1fbXblZixRwpWCqNr1jWTh5a3XLhbN9+CruI6YDdsbCcch8/lTz/0jWk25MHC1OnJnEJT2bbtpB4094TNDglqdnv4xs0tycPuVaSIsdnxT6axlTZ7xndwVtuK0OZgwRvgvni6CGPm4QBaO9p/mUtMXpQwqt8YKqvWndPf8C3ZPJQbKeP+268MB0tNZYS+IqhQetRmkuf+x+gLWEPo1bBfNxm7Shff7mvxa3D3wLd9H7ym36DPXS7V2nCDurl2DEvu20Jo9Lxv3NReXsuvwe2YvRgljJY4IwiSlvu6dfiAyQ/hb5N6Mp7TCvogzXk5CsWgxbWqt8iqDHP6uMFhL2m34jaf+4b0iWm+Sk69nzGqRHgD4VTw3u1iroihItR00l5fPsE7x6DwHaHyy6ayEYelZOBFjn9yRXCmXiONbOPD+0efdgtWrX7XmvDL0tAMaLxyv4Z5KHL8vYK1jryQGfV2TWkj28cs3TMgrSg2uWiS+JC3JbR+yd099gD110vgZgVe/uzXIQSxymOL5iR2gK6rsinC/sU2D320Hh7tjZ5G5cRPmhd3AbjE3SFwbPTWE9e/KXkQYFw5vg7v8VaM367djbsXqQankZXZeZW+jtcN+nD/C9uBpacX6lp22IcCI/l5Emgy8D7U46mOS94brKHOeOrdvGQ2ljwJkUrFNs+Yh6PMWuhur7CWcYdkAmaqRCJW72XWYmWznCIapmV2FHUkBvXyjWiW9SBJMtxqCssrvSK7x9ZVm0XBbTug/6Qu8ZyizngMuMIJ422nUxsQK77zkPsm9kS24Anj2UVcVDuYpPjlek554mdScWJ/Hq075JlBvirY2gFb6BnH4qWoEeZwqDMRfdQpKu9Mo035suer8HcoQ1wyy5T2GIxmrM/FqLICt6B00zTxo/luGslLF9hDdJ7+00ubD6CRGVRKtEo1q5BipH9o1DaH/DdZQ2NHfMkO7rsWyGHFLtRkhq5SnKy/quXkcNnaHdZg5QQjSqkteJYDuO7m20NaFewLakt/dy/IltMG5rOSCX7pfGP9BE2p9TdPCv4Gl4cjU5A3aQMtAktB05tJ19Ui5THolhjQyvHLWkzvMd0kzKwwBcc1iP2prOnQlyc2xVntVVlDaVnQN5/izFEPw6teZul3BmThvF44PFVqw/cwQPjjzYQyyd0CwjDuHClfI05F1ld9PlC1aRTVeEr2WGokHz+BGwBZ/DdksPlPyxxUtI+pJy85nE/e+fYBPRLXGtJg2/VQglp4nXXuk55oqHmydV5UuOz6HI9a/4TuBWcYU735IMxCsukMqvvW79UNmbLm6S26u0TsPucYRxXSi+t49QIxF5D6HG0xbwuN6fyyh8olvdfIQ2juOpwrJBiahhSOeThW9IXrq12riDvbe+ALWANze68qO2ZjDFqqZxcaRcr1erldp7iO0ALaMPMZoM8ufE+09YvGD7wrk8UZtY4H+QrnLW0IY2/mzWG2kPlmUkaTtWFA2i2ZSnq0zeQbvMG24uUfGLUv+y95oxXFxZYfI4W0Bj60er3gOY2c6gmxCU8KPuoNdbS9qgH9g26FrxjfYWymDmMKnwLKEmbPD7saRxNYSXZtjRfXJYOiO4yh/HfehMhufEa037C2Y1taRa2m0tJbCf6azS3qUOIspaqGn+EsAXzzOdDVvm48mghlJNz54vUoWwjsgGBkrexRZSUa9uRKNp+cNy6/Z8BruAOtVploO+9eTmmJG1sb3Q0mk5YTcce/wBtCXcIJofDVLvwhrHFR1s4zao9JDeqQYoYf/KGfYE7dPsbWbQwoQvqRbWEsX5DFTF+Vi07lPe4VtAH81BSheKqguI8Hl/Ux7xnSYaoOb6HtII9WE4C1UkPhK94piNoXJBMjO82H2NyBp72tXFD3zwncokyI65aS2a7Zxz0TZsOozBVtlb8BG8FezBSgH98H2UwU8Ds66789Kz32JBwy5Jt6ROw++xhTo2TqvJZwXVX8RV0mMgh/hrvlgIX+hWoxfOGYOuI9FdLK01pKxgm0zqiA2on2mZ0l/0ncAuoQzBRkNa0Yk5ygSMzqxNhh6XHYGH0HXv9BOs+cajdpR82nTwkoUEf1PNA9dJME+1eZOnC9AXaMN4mVCYh2K5K4oNze5hCUCC2U/+/+HewVowa/O4NYtt1LN9mdxQGVbut6Se/A7Ri1tAsTIEuo+uVfjrrY2kL0ZoNrCin2JOXaTFt8NVTqpRxORMZ4NjBaLs0yDZV2uZqd43oNmtoxcLqoG8VJ8ZEv6w8LN2r2SXD3cM1lvvTBl+i5GKxY3MRGS1y7SECr0mvfMyvWJaSBr8vBlknKmrO7vbw5BaQvZlYlnvv7CRaNm8wFZeyNgQjsSUXft1z0awbfraoyGs0t1mDZT7x29SYtwn2Y+WLK7jFgBtAO6lRvkYaugUwFnUzK90mp0GaPKuZmdhp7V9Cgq7gLRk3xFF+MMcz70x65xzVjIKbGogWkhNeEpyvoC2hDKln9FNVqXXjx0t7MHGSa5atR5d4Mm7w7Uvjhpj2/iuHQo6y4GDaF2WlpRKq9fewVjCGaG0C2WejGRmXbtztldSrC5ZI4fLFtbt84NAVGDKOdDlKTEj6Del5+iyB8PP3OP9TvzNwyJZnTZXb+BbHv8NEltXajFWPN5NIjbR7/4RuAWWoMfofratlnHa7YzeaQoC11T5OCZ0mqX98agvmDcGZ+0/RierkZYYvgCz2sAkfxHBrsR3mR7+ALR449LAZP5ndE+kN41/hxxboUDOEb24Pvj4cYSfoFtCGZI9N9vYx5M0bkoEMo1y+kzCzbiFbH4EtUSmJOHhLWp8Tetr7iRhJ1l7tRJn1zYGVzv/cLxCHaoyTeUMZ1EGejCE+1rRka1nHuTrPsOreAVsxb8i+MEAbJ1elv1A6lZbfk2maZV2n8DrFPQBaMW8ITeGxvSfS52PVPO2hUzKVOumuJ6fWYuZgRxEr4r75TuKMerX94WyZptfgy17pAdKCgYNxPXJJwvj4HU3Zui+zN2U6BFT82V2Duc0dTGhHrW7hKGyIxZJ2K12CvOrmg3UCZe28IY3/1iw9jluDIEMmDWLn7A0lNypVSj6XriHdHjiM84WP2MKB8D6IW6t/shonI34voedhuPiE5jZ1sFKNxX7NGxQGlOLOHGxntUA528kh/cV5g2lYvVbztABC5mHc1n/JVuoeVVcI7Q/4lnAHc+KC2cWMN1Z26devyCnULBobwWIIf4C2gjuML01bVW3U4+w7BrVdZ6sV65lxPjEIqf4V2DemDZY/WFhiGD+YZC9cuHAH7pUY1RP2B0XJC7AlaiXL4GYUGSrPh5pp82ZFqGsWAmzclveYlswbclOnwzl+rUGd3e5NN9+6VntjbPm0ANX/c9+QK3XFvzXemGT3Pr8kxykecYFL2JvEsO4urp/Q3WMPdDn6YOiUvynJH9ZjUCDhJQHAOc0QG7rX/ROwe/RhaiCsT9231dUIEghNkgd2wFVsXEFbAsQlrnXsQT6D44KpirxvlHZmaJt3VVDDeiLY05Wba/4E7h55UGRX1bi05cHamTmg2Q8KFcO+stVEAfbcXDvFdY87oJ00gSBdT/2IrUjkFXY+GMwNinfR0theUC1lD3KH7XJptuyQlggZm90GpsmN8Y3FZcRjt+EF1U3q0HEGiRpmxfEL4sXvCAXAinsOP3KWUWz07wDdpA6dvMWoFVeXx4fYMRj0uzGrGEwqW+zhK6Bl3KHLsywyvx7EHZOQ3Nhj9wqnorN8NuU+ILpFHeZbbFXWnHOk1nwiq3VedvgaBRIGt8WCp/bGAcst5tC3ZG9EZLEhm4qMGpQkyG7MxvLiCZZV1KGrAg2SIwxejrUF40Wq5coRaXtNGGU9t4gPkO5QB46gmH9iksUoutLwyJbJeE2NW04hZxaKegnmDnNAdjD+Gs5D3+XPgGesfj9cZ6qVmfk4dRCWr1CHvjlQ0eAcz4wwrMI0S1r0yO5TqBvL6ukP+O5Sh/mO2744ziSjHBEb53qjl0glMy6Xquil5P8A7S51QGvQNnVkk3iKaCzRQabG4/ortBr6ycu+mDrM6yyN41IFgGfcl2DOynhQE7ltP2Zt73HdZA7Yq+0Zo+Nno0ndVPXN44H+a0hOoQ79PaSbxKEjcZXfamtOChbeqP7wx0u2GF2P/tod6vEV3pBmMhhsYJynRIipcnLEJVfFI5fx0sGqzYn/A7wFxKHmwevm7R+T1cBcMbM/VXAUK/Nkq30UVhCH9LRYdwpsAXGw6CJqk5pdRd+IclAfBL+3BXRAcGq6QrWYNvRsoSDovELuvOzjmPeEOHD+o760C4K2TI2f0C3gDcn7LUzetZ6YZAX51M1+SFWK7C5qel5zOAW2gDgE+5XwPWyc9wMUavT0aMh0W2jFfPfky1zPG7y5mFVNuwcBnX+zoplkpuxFxzwlUMnvcC1gDoPkZUVSpVpbklEPnjS74XsxlUwrxzzgF0ArmIPPMsep2TfsJxwplg7v3KmK0RaXP3k+a3nDYC8R0ec4kfA+Hc8p7xwmslw3HlCWw567hnSbOMwIv7jFXGCuQttMG64s2kaPN0j211huE4ccN/V0GEe1ctDLL+/ctEkF5MH/imUpcYhmHSQttWchOkUtQLK7Mxuz4xxwIg7VXUO6SxxqqdoLspkDJDf5/Oi9shNSLOtmXi2tX4O5SxwS0bnjqPF0fOWRkvbVceNa5HDnky/8a6TBY4+L+KDOx1O9V+72LOyqktLVnw01/AHeCs5gvmXKlokVrU2WcS3dFP2m9rFxFqX+B2grOIOFZGrcsHn9Fm43ykw0/L5YsFc4+jUI2Dc4g12nLPGNGyxB0zWwab9n/bYafMZP23rOMD6ziE5vVJkJl2rPCDLI3HdqTtxuRPoe0grO4GOar3ztAbLZpoZanTrYQ4g/8bXb4vO3GMOgKkFlebeFVdTwmMrQ3cdTsNfx3v9oieYjuAV8YdYDdJ9rlo2M7e1gty1Ll6kcDNjFHYioz18gC5asJN4X/Pa4XGI2mpRcRgpVah5LhwMb9flbdGE2O7CGHVwK0yQfpTYrGCJ6FrOC7LPs+/wAbsWUwagf+W8he7VjMJ7a1J8YT8RBmBnXX7//K8mCc9uUwbPt1HKNex9/mzKkfSfax1dUy9nCqOK2n9GGMpVlY5RceV8GaeahUOrrkMHn5VTBmeUcRbFPxNsWrLnQL0x1Vw3jpSJrsL8DtGTI0PvP5nNRClkAjvaUXv9ZKAev2uHkJV88ZAijmuvYiZoSHXugx22j5K6YGp4rh4aQz0u5ggva/Ehd9XAOte8WrJmge/u50lGedMByf8gQXduGDA7nougml/sVKzZ+wobCP+ZXLEu5gmUASOYySF1Sd3H+8VlxyghvUKuuQV9+A+n+kMGiLeYsKuaOIIGbjvEhWUXj/GmysXf1GsztIYPZ68kbSJ3otnn6MutA12ImOC/RV8LyNb7Qx+f9g61AHQVdJh6lPBrl+Pom/wjL6vUP+JYMGXLTSoh5fmCIldFskAk08YRa7clRkf4F2pIhwyi9p9a7dorf0LTwS0ynBlopSAbkTs6CbxCG4nVXTGE1v5zWVf3DtqvYNjRLiO9hrZgx5C3rx/qYflsT38fE0ra0GDg+cn0PaQFfCHbNoRDuGvdVvAvLbkJXTW3OyfFcMU0t83dmDMnaPx4JcMXzKitSyis0vcjv2kbMmHce2tIn8BZwBlOLMDqINm+guylVBPVC6VphbQoiOJKZE2ALZgzjiFBJVwMGouOEpY0QEbdMAjFqKO7kcDjof6FaPWMwwyLF9A2KlzSrkXxlVjAifc3Uq03VzAdwK0jDqMUZRLamCXyvMhT7tQ2de9iafyF/gnWfMxivImA+NZcRcHRfH4187qiYN3+qQ3U1/903Bgxme4F1rsUSYDQlwRY6Gyy76mD79SiQf4G1gjTYJKZtfgQ08jNNDvki4wDriszP+jtAK0jDIHJUBuYvwzghsT2Qtjo9GdNBs3jy/a2lDMm6YRhTR++VzCDd4qNM99G0wzhIp2tI94VJM9IRdwgsGiLV57YNA+dLP7JUuoZyf7zgTIyR5CPMim2Tucvuhp5q2nToJx/YUsow3pttPSdbeAyNVijD5OZ7UNap280B0u3xgjFN9D6uZxKISqq/3FdpdZr6lg/Nv3lAt+cLhU2BhN1ziFqkwjuU5sA4vqlQyskn/j1VUklOiyjjjKGJQueE9Prm8VIyfVt8TQy9grdkwBDq5vRvRuecjMyrAgZ37O7F3RzloC07h7ZkwFBzR3FQmjJ8CcPDWVwK73lqR9K6XoF9gS+M4i0gm7QEkK5ua3g4nqsxZpvcNb7OYl9wrRgwWIOX+60RRRtRbumEpCQZn+t1HbB8vtB1Ao3TXCF9s1Qpj8C+GoOn9RsPN1z/El8wwWL72TaJCGwaBWYlwJq7li92HB6B7fJ4WGU4AbdiwpC24IrQc9LUv+KCniQ2jwTSuM215TAkPQG2YsgwKmz02oMHqHfoYMYp/7ZeHeVcV01+GKn9AraYMOQeu2KDgk05OBHYPIzuscsQx8NryqU5li79O4Rhn+87Z6pv9IIh7ZPbSqxat9OEevjIZPo3xgwWI0NK9ahmKBk2FaW0CiyTtwyzeDnu+1fGDOabgIish0A6T8tJq9hsr1tZPBh8b8dotRdQSxjDIJiIE7M1+biF0j734J2v9iu7eLRdfQG0gDGYMh9qPN6Yjgi+zbM05V/Bw2aPd7JbMfEsnjJkv0mk3ADHnviW3LcLFsel47SeXNw1pPtjBl/0eyUz9sTqYp6S2pAhXTtoKTO1ayz3OYMFJGB5UIq8DzA2hvFlwqgcgq4QXqGsnTJYjo4EEF6PprGAjZMnApxxTWd5lFziuT1isLEcjtiOjtj41jVcnDwKrhk6ndbnoMkDlvsThi5SUiJer6Nkq/pbDViSClcekPXk2vjehMEc4hU1mTBzKghqIDWErcZi/EsyifYHeEsGDMFyDGnmJCZ5kWW9ICsGNHjVmtN0XssfoC0hDHE8Dum2ocPR5b5H68Son3RrbJaTZ/YVRZItzCiLOUDQ0b97RaSjqh7HJ6dT+4BrxYRhfPuK7x7/RJs368LHEChqX02CnNLfY1pBGQZRoBRqZh7GW+12yjCrpjZtvI9u1d79NxvYayhD2v6JTfBUS8EBOpmxuOqj+UbhpR3i5txifi6zBfHb9vwc3L9Qhmdgg+qZy2PSyEOWMoR3ooD1hIrmcZqouxfKx6f2L5ThGdiotbu6rePNmh9dJbdXjsyT049v1aZF8ObLx3WXLxweWWt1y2A2wkW5UjXgFt9ButHrtvX7tMRwju5fCMMBmbcXm+1r23Qig4qjlHZ1BEvuTXuJ8eND+xe68Ayr1FHkzf/kUe1FgnlqrY9lP3nXmkro5ZjYQC1gC4eH5WpqLMgGl9M+gafb8FCgW+ARyS7lHap/ogvPiHLNmnyO43PUL17j/935Bm/PIDcVX9/h+Se28IxnULomI75xgmMh30kv6g+DvG5plP7Qtt7w3GQLh18s2MAOiWToHKI54b782241mk6xHGIRjoj+gSw8oxkXsjZuYmtJvcbCMva+nTNt+trR2vuI5R/IwuHNCWbCq6irvmVeIbjZu9fZRras7Jy8OffYwvHTGlWdevXjyKFYacw2FOBLP8VswtgGO3s8/04YDudPibJy7lERoUHrceGXg35OnrFUe/N4/nfCcPim6ngycuOWJ2dTtDl2k0VKYekTf29NbVgWEobDnettK5UVhlGUa3FQQU7wY9aex5uvYv0v8P6NMBze8HEYicuM+nfjXmXXvROnFnp16vY/EYZLaP9GGJ6hxVHQTUVSaZ1zqMoEi+kjc7ZeI72pdnLjLuELh5d+/IQ/D6NX3KB1QGJ+oEvXPsF6MDY9w/VPfOHw8mcLfeRt94ikAolqre7K6V5N890vLtzbbOHw243PHjOImnD5sb3UfaKfyepsEaFefAY0v4yvsAXnNtu/5JLk7q7JqZqkt0lkzMww8Fmkz+AWsIU007TgWc1puR9Hf60OlHk/V+ftV8RQrH0Cdp8t9NIzPVSTSyJ859eL1e0GtaNaHyxMlrDhCtVitjBIXmK/YtQvHTGlrwmt1CwS+izx0niQMuV6cpM4B7eALJi3BWt9fbAFv+nbyt7T0554aEluvv5AYk5w3WcLjd2qEn2v2zbMvg8WGcq72r2OeXfy2n+BK4zPUOR3HKdu8oHuJlmBXqFAL1X5Szm8Q7WAK9RRyWzS29ZwwsvyHigaUM0Ih8IlkN4CWkAWonkVzk8/O8eWbOXHgu/Rddxs709+tMVUobYMxR0FF3q/iveHsrCSrIZjVe5buoZ0myt0mwOzv2A2I/wgeG21x2AhhUofNrtrLPe5QuyJRmIoPnhWB+fkBZNs3KkHbfEHWdSGZClT8Dl7LmATKSP+6YSEojTHwdjP8smftHmeIN1lCjXWipagB68tM+a9+SHKMNudhNdXz9dYbjOFufMyyVKQSBRNiMuP5Pliw6h49c58jSiMI7Aryi33xA+1Wavyv1fWeQ5inL79Ad4SojD9BulPFJdwceR3U+xHgCh0p+2LXP4AbQlRSONdp4hzkfEmJa8qFd1tIastVU+AfYEpjJPSS39XexE5UB5ufkQg5FGA8qp9wrWCKSSnmfh4wUkiG6dVehyY7A6ZoQUZXO09pAVUIZi9CHuBucrUrfZdTxpxKGxecvfnk2HKNL5CFcKUP8m0P7GJ2vF9b+i2FOtmjEuLYvYkP6BbMVmIQQ6bIQ0SI1NClOb8fqFiymzDQOyje/wEbMFkwZaKk0ytYseBFrGPyvFA+Oy4jhHftHaFajVXaGmbZoQU/WbZ0B+WgXL+SKZXlEFI+QTuPlfo40H9sJwjN+hWVWZ6jN+oYoJcQuvHB7ZgqmC0hKTnmmJTrhLTbtZgvBb+Av377l9BLWcKvQyiIL19C36yqkLfTIpOvxkM+tcWxwHTiplCT16F0zjdq4zU5tuuzLRJV0zQyLJFfgdoxVBhnN0/vEE1s1tFy0B57JxkJsvHy/QVzlqi4CxUjvQmc7ehZ46JodsdbmzJHx1CLNeA7o8U8iYXHcUfHZ5xomMYr7x3IyrVAzjmaywLaIJZe6CuiWSwBAQ/6SGGyKaCCOV1vDGxrCQK3WZjiN8HY6hKO+ZcZOMkyqOlbGVdvEZ0e6LQwpbx0uV5ze/kySab3ZKQXWwo8Xu9xnKbJzQvWyqTPFGX8AQgChw7ae5lE/L2iuVrRGF84klmeeNgRIfRNemYhwD78y3HjPL80Dg5R7eEJ+RMYHlPmK+kKDk+VgfEjtTQj+kLl6iWUIRu+8ETQQ2+Sf0n2ruNYXz1rm6R0K/AvjFMiE0Lsr7lzKZsKI+6N6oYKK1jPFnde1wrKMKoRX4UthBkBoYIquU9L7WP3xaGkP17RCsYQjOXdMa+UAPPVh7DRpZ2oS6H7vPE+h164AfP5f22GAq6PZzjhAJbNj2VuRufalI18AndAnpQRoWLKDKO+l/DA8azlcZm9zh+tZC2gdBHYPfpwai6a4LE+d5bxf05U7vMd6orTNmqXTZ22xWs1cojN+oQqss8flg2T5osyTb7mK6WR8cmOgT/Cd2KYULctvN66Z2X37FKp0YeroqtWMXQZb78AdcKkuC8lpsHrXO4tKTfCS2bC5caCSW+glo/TvAuyhXV9gvZm/eOMPhN+K5NZ3O0TyfXdl0+Ueh5cwzPOSIiyWIu8hKef6oqeCG9BbSCKfx/bVeU7DiOw040r0SJoqTD7P2vsaQAOe85TtJVVvZrqqa3GhPbEkGCgP+PUlaRUTGuTQ8FPN7zYUxYvDga9jKFEhnC8E+2hlJKbUUNzY0r8KnRudEgrxHdpgq9+otdcBFXhDcWaNdwLSObSWuGNutMFdpOqqB+fNNBLhvMEjNtM2TtTpRRqB6VCyhbRwq5VgY8+CPDqaiI1sMjag0MK4KuRK/6O23nSKGlRVxSYm5lmnM6xC5wXaHbYuCSy2s0t8mCRigI1mzIUqi+pG9AYiOHIXNXF+73pgqW5Yfyem3QXuDbKjkf7o3+JglndtLtH+DtYQuFUvbO3gnaE4ipwkJeuL2ybkj/gmvPSCHcPrE/dZh+ddoNYrlzroBqosPVBbBvjBSsGT/BYYimKVT8IgoCrgKtt4RsqJPg4QnXDr5gUW/S6h1mGQmiwP7wAitJOBaq9T2iLXwhvDnmXeaPEVKt2h7bzUhbz2NVyb8AyX/pG+IjjHzDyqrhLc+GBVPB+nBH4AKiCv0t9/qAjo2f0d2jDOjrRpAeHfmXgWpVCC7QNa9YEhwtBkOoo+QTsHuUQWgHKmB+2U9YFOjZBhLOcR83+iBY/+FSUXkFbB9pwBmVbPzQiiy3gZPTMGSHowXMwdR6l5+Vwf4J3D3OAEuhWDzDSNuSQBfo1VN95CPBR6eEDwnzcOsnXPc4A8KqCk8lv7uF+eYwDEyQoqI3lHth+M/vDcOFaitpEJqj6PLS0pJgf6nwQMDkGD4RiWPKP7tNT6huMgaB65Awp9taK3BYNitrSovsr+4FGZPq9R2gm4xhntkWmldMO1sZ7MXOQoJWj/C5Sw0mCVeH1jbOQGKZuHAdlgsYYCPiFZOODJO5okUxAa3tNaRbpEHoLdvwJVUzXXKgdviorjBsochTx2s0t2iD4Icw0IbSEwhVYfjLOBYobEbgyovXeRdvYH/u2LA0r0RnZQc787IoF9po/se4TJheQ7rDGwQZbWs3IkkHh2okWdB34/2xJrSkKG/Q3OENcEZtA8PWRnfLjOE93WpWvqZwM/uP7eYC8xXiwPc6HJkMN5dUrL9me+zjoU0dPSB2aHP+F4B3qQM858vyb829Q9Q9cDPjDW/YXJDYWzW++J+h3WUPQo0Duif+4DCJyWvGhpKdaRYV5+W4OC83swdBMDem4zlFFNmU2KA8blygRakcC6JP07ULWDfJw3z/nYHyqtOKvnRJqPNgrMrsQlUmOTZ5j+kmfYBezOkyPsKU8xKPyUoWwihypJp4lv+tNyV9iz90Z+hQJNWucOmPXAH+WB1+New5jMgeKJiofoK3gUD0yKuAZZp/gzTMwTzLCi8dtIjKMsUsf3oMl8DuE4hI9qJnm9ecyNARKH0QPYYs01GUTX35M3L4g2oze/AKhcte4sUmgr5ySb0dznwCDZWlHlrq1a75gG4Dfah2NKz9V6trgQHONbO6gigAtk3I3Uj6Cdh9/tC9wASNssibnOVw/m3txvOrDRqp9Ysvcz99KGihOwMcldbYOLvAvHiCzZ5EY/zzG1Qb6EPrx4aadsFMsqJRWynOn9ejU2voY/UdoA30wQmwQX4TAkps7fZl4j+vmbkArav6e4azlzy0OU6ff3VqDbI7dBx5Pw/h/mhh5ZDya0wb2EPqjM4LDwvsxGOP4pe0bQS7GnYeEJ3A3CYPU+aNxOLhJTDe4PmrKO3kJskpRmHpxSe2lTxozNm5lm+jCCMs4aGIrZiJLbb3S33apTpBukseutdLbPl4DWXysNcRuL0ODh28XKnn9usJy13qUMs4dpk7OuWl/vZUVUpa6JRh4xnLF5mDH4e4ebMzmvlhdyyHa6GICnFpI+JBB0fGnwHuYA4WtlGytizyeITU5PmBNegme12k5swcJH2POfSO7NjeKxwqBvv96Wh65qJeotPZ9+Jt/wJ1aH780GeyJqFFNzqwk0EUjm1ihIRF1f4e1wbuUKdxMTQbCY+MJ3cqh35RshP6HzmvDl4g2sEcmnARr6tiIXUgTasdvictcuBbO+9WOKD2LeKgEeKF10tp75HF5nvfuXlltAZ0Iv9DWwn7hG4Db2hiYz7CUqXStQE7l/Tvx5iyOyyGO6rIJ1wb5g7+j5yz5eDyxloYYtDMCfgsRMPTEQn2p2a1tC8xB3HiICuPt2TEEDkDQytLUWZB7e1vH4Yi0vIncDvmDsPWloWfmAyIiAnE/DRnR4H9D+0MbJD+8VfbMHjwygGHavObaP42A8kQeXndwCUhXGjlnCm3UO1nDn77GCQtTqT86mEkLkfd+ZERIQ4aV319C2zH7EHDWQulgzMpbDsbncMes4cWfljt5NX5DGjH7KFGIYFxUBoDBmrC6KRHgtuwjJFvvnihNs8erC4HF4ZEZH3Yf+C2jukI8NgbPBuogx9KfDO8XkCgc4d4Fy8QreZMvarvZzeSE5z7kwft9LwrXkPRaRwlaj4MFVu4Fo5xCvJYWLaSh1IkURTZsk3XjAqfc+hiITZRjfEWVdj5NaTbkwfHwHM7NUiVSi798OasNLRrXtyhq5ff/EC36UOkrpBkKjoYqH6xxJThl9Z6o214u3hxvkgfuihjv7yUmoOZjr4wkoYEG2Cqta2Q1VL/AeCWwUMkezETtcJBuGIOkunRMg+C8Ppnuve5EdW+Rh+qGVTpQweieuuKA4PpMp5zGmwQpYsq7wv0YXhtwDmSV+oVeRpcfwaJxk6YDKa6DnmPawd9iAW1zOWYVrG9ntiQgeIEKyqFDvunqaS0LxAICXNqSjeqMugjHwzCMIEL+lrO6lP5b15DX2EQ4zgh/ZJBEJmfU0rzHbzuyp9SE6+afhoFXsDbQCG8GGb2SamOAYO+Og92GIIIlLNjeudBumD2CdgGDpEi9T2RuyO7ZUDLUQyu+gj7SLF2eE6h/Itq9+jBikKx5689vG38lJ31gkLFlGhY35eSIFv/BG4Dgcih6U3YKR4ZY8Fk6G3R5xQeHbUafVYlfcK1YfAQSpsEAaEfnfBKR0Uza3ZFedojJ3e2cU/n/QT1hcFDDDqUETLacJz6v05HnzZjzb5YF6ZD5nfAtswehJtqoqlDAl0N+nk5ukVe4Qyut9o7QDtmD/FQGsKyO/T8mivntpPVTxKjDJ7KF09uL3uoUSMXKLpwE1qt+dG1WsaiXiRDL9teI7rNH3r3V0hgy1BgnaZo64GMVqwA58Ob7jWW2+TBcqcTpVdVDUPahq9+HHefX4oFDfhy8aT2kgcp65DpXubh8kOzc35iSOKMA7RBrpivzqJ9kwevDDINOLH9qBCZMrQUGxClNA7+/Vp8jeY2eWgrwc6GQomADEDsx0AclOfVxnXkZyxfIw9DhUVwdgKIyEbYDUCS57cbhuzNL2ioE05zmmt8e0YPYUSCFhN4QjUcPPODw/te0nDWxVCQ+g/ItlCHWDZiJgsUHAUTNnx4ir5GHyF0ZHbZE7CvDB6ysASpcYJj+vg7lQRpgiMW3a9mtU/AdlCHeQoJhfHYIG9MltWjCys1NXbJrqqn3dQhROY81CtnD4JEPNR383ZuCcO2P7aF+b/553czh8xjoWKzNi5ZUEBFNjXzGYxSE+euCdY79c9Q6xLdPeKQ0erxTzFjw1cQSu0nFmZvGD6U2SoatfphByeoP750l8DuEYdM9ybet1l7XQFSnaNvnB2w8JuzU+z9yCtg+7gD3HKlLzmlmdESPUMir5QIFFyMWpfRyZ9G3yW6e+QBzcWocqEgkcHSM6xfjcOZmeWNDNQQx+nTuX8J7B57QCi8n2DC9RmsjzlztsNPiZfSiBBrlBvp4i3bSh/wmnkZ87PiZEZhAnSjZ2R6HGPZ/DaaU68/vPkJ2E36AGe1lvloeqGBe8O+D5ysM5xhpUOgVss7QDfpQ+aiNqUCMgPEH9ER5FkImNDx086LD8SzjT5An2jOZ3BIOYuCrT5bolg8ooNeEmrAuryGdIs/ZDaymdxY/XquVHu1Y1qE1ZkW/rT9bBZyAnOLQMxn1bxg55bTKPQ6xWprQ9DrBKe4jvIFlF38gduQ/t1jWOw3CJpnhX69c6jdaCgR5Dyfw6DPkO7wh8xlB12qTjbrChMa8CnBVDz3LEv0Yq/h3CEQ81n5uQyTjzYUf6oeNrQzO20+ojDb6K/e4q8QCKqpq3AEE8bi88hGpwBOtYNCJlvaqlz+Bd9dAgHX7nAxxQtWCosCDJEqeDv6yJIpxBH9F2h3GQQyv5quOBDs8hUazkA/iFMqVLJgXa09A9vMIOZtEU9poE6RAubckGuIL9CoNOk08hLR98BuMoiMLSP9WZGOCSEISALCe4ameliQZ47f6ntMNxlERhGZuGcvMVjG+dkfa5Agz9A4/hEvOZ7+LQLRemdOVA0vODivaucyFCd/6IvkiPJTo7v1B3gbGERtIWPB4C9hrUAK7KiWESsbfLE7Wuld9wnYBgaRbDD9NXRe1JDQ95Bly7weq4QIHBIwfQlsM4NwHBxfiTl5RiXcbf5gygX4hoqiO81Gxy19RLeBQeThxcw8mrwcNsxFvJKCx/XsPmaa5YS1ZX6KebvEdZ9AdEvwxzEvMwfaWdi+m1djzY0ZtvTHkXQB6gv8wT84BunmSBKc8wVDzYnaD6ev8iLS8g7VBvIwVWWU6EToB8JTIK0YRzfb2d+VUugJ0A7ykK3+4Dz1urNg3FfJWyZjxammP09BZoSzlzuo9sQAt5ExurLCgZ8yf3KOi4T7byavId3mDkP9zUAhFQtQA+4v9bhuaIhfydX1zc9zmzpY3ByU8BZmEiAWnpbDWDCXAq5T2jOWrdxBbBiL9egAoWLA0hUWsGC9Fqp1JshofQ3pLnfwkrNxByNpQ7HSRj6C1itIVy/hyMSg09do7lIHS41aYDNsEeWMficsMyuFS2EXZueZJ7F8jToMLdj8iNFDwwGIe5d9PAz9LRaEVRie8BneFuYw/BcBs1Nmz/pPmegOP8N7ZxHYlp2P/csPt4M46AiZQYdsHrkkWM+k62/FH29G07W/oy0i+wJz6GmtheawO4fb4S8PBcU30f2hQ6Ha+ntcG4hDHceAvcRe3SR79WG8WJZtZKWRstX3mDYQhxgZoyc8nDjTYpTZP8vfsIfJX39SDOf/pqLjK8zBIruswk57wF0/96w8YEG54DNYyogtszmpOdHlC3gbmMOIjQy6riVUmP6GTbLcmVQHf3SNSEg4QY32CdgG5hCOv1Dg+dE+MP9IJHy/kyqbGre2TufXL1ibeYPE46QZeJhlQC1hbIFg4IZu7Jje/Mot7w/oNvCG2iKzHqt3xf8Zg/CBkwz+XhWNY3/E+Cpz/ghsw+ShWYHURBouxw52KjAuMHo7K8ni+dqeoPYThymsgGig1WoMUZDfgwcaNno9CGlFS++A7Rg8qCkHDw6oZbgsoAjWR+rwzKxGfPQ7QBu4g4bz2YCYrHS09jM04w/vzyb1h2uez3D2cgcL8TqUxSkVeGRV9okhy6aXbe3QLY3yGtL9uYOEh+3kwrU5V8fu9CyoBtbb2Mbyp2pYa36N5j57iOgNeEQKWsO5wc2yHL7DMyQaL319hrKVPNQ0qJHyd7nAGKejrT7bBvDR0+yM4vCSfA3pNnlQa2i/il8pcM9EWxgCcAWRcKKHJkf4d70Ec3vskGKJviPtI+FpoAEFNWLh6NE4irWLz/x7Y4ccTXtG0o0Ot6U0CSe2DAQLNNVLgYa1lr8ujK8A7mAPrSx1hlTJFecjpjTg7CBfM+l61TP/AG0LfUida3R+8XfuFsixcFuhq6zRtCtP4YIE9o25Q9g74R0rDboSrdA0w3UG+8mjakOuXm/vce1gD+K8E9KDhI5dlL6Tpf7SnoZ95FOI0gWgLTOH4E4DvmJYPEoTBQpzBPP4C493qvx9crPA+gp16NIKWFb1hyUMNkY0ZILxBTqdoa32/wI4EZ4+xgt4G6iD+YeFeXFJxdCxq0KnIARAJJgYeJ2F5lDJ6ROwHdQhPLpq5SIZiXrHVgEkLnCUtVSqkWOcejO/gO0lDxE4sRyeNMIhaa4Jyyr6iQ/EgufOddOTuOQC3Abu4H85c0Qkxbwbxk+6Impm2xHdYS1rl/Ekp7oAtoE7RAAAeo2tdWS+dH3UVoz7LE7FGJyRLz7O/eQhgg6xtZWjJp23dB/YGUvMH5+9kNBBj3N+6xOsHdQh8l2YjxexEvNlwrANk7UJrteUoZhWeQdox9jB+qIFEnsq8y/t/Tx3iFVBqPovPsK95KH0IstNPSPBx7rRK2uWy2xaFYWAp8prSBtES37DwRfBf6rOdYd5yEOKzZSVIR17ylcHwTby0CKTDwLeUtjBngc4zbAK9mUUk4erl2crechOVNYudKxzQ7MOm7D5C2FwnGfNhUb7a0R3uYMfQoWj4hisw5UH06HMLHt4ljvNy1zaeI3m9uDBL7AfrEIPeiHgokAhtWygRHB/9ItT+nvcwb+rhKS3wSlaV6Z+4993WpGHvIuLuP+Abwt18PeHJozZj2rYPkEY3BlqgCJFKU4X+5efbgd1qLHcO/U1I6H9WmBUwg6ZQh9XHBkWReTiR/vG5KHJ8r0vWiGKpxoXEY3YUHaiX37WwfUW1w7JklebP5w1IhY2Qh0eiU89Lyven3xeebhAtIU8lEqymQRTolB+H9vS82XqsWuINN1TJTC+xB7CnLzy6YWHCoToYA8G2UiHd51ZND0622cfwN3nDqPHem3lui8OKRQDigKK71Y7Ekp7+YTqPnFQ046KrjNkrfT861ytFAgJzTNMX2HazBkkbBnnQo1ZmudBH1grg0MWvPg1BnKcIn0Cdp8v1LB0AvtzWoozvXCn4OFNrDZQbp1UeheQ7jOFMjOsodUbAl/3+itcdxKFNpSfRLl40bfTBIsVmkIPGIUdqz+vfligzpffNKzB9cXRsJUklBbzWKyC+T0H72bsP7UViYzgi3y2QH2Cs4EieAGs6OY53UXzwMs9HE1rtSEcipki8oxmKz9o4UdQYAsrxjE2V8ePyKWWIp0qn/1qT3huk4MI6Fu2zGUwoA9lgK5hUDk+wpMQ4Q+U28wgj2jW0dO0G/O7xvHOGKxGj3bFM5SdzOAhkYpsFLzAtJ576EojqyshU1RO8ro/gO4SgxJGETCWEgXvT7jzmf6BHyvltJZTXmO5SwtiL5UbqpFCROuPx9o6lmGW9VO5eGO+xgq89CkQXUgy1GxKGTc0Bfh/hv8NDp6m/4BuByeYeWBwgB0235dc8UUtwxkkb/gRhPiW+g/AdjCCLOFDDSe3vkx3IE2CHh7mJCy79eJ+/QIdcOqd2STMMd7Dzl4+Ipkxwgo7uh8aWL+HtYENZPXLiu35ZPRnrseRTZuPnLH3lT8A2kAGvKa2H/TXGCfM5MXV1im9cdQQq1//+z8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Week\" = _t, #\"Channel\" = _t, #\"Region\" = _t, #\"Channel Group\" = _t, #\"Channel Type\" = _t, #\"Super Region\" = _t, #\"Year\" = _t, #\"Quarter\" = _t, #\"Month\" = _t, #\"Spend\" = _t, #\"Impressions\" = _t, #\"Clicks\" = _t, #\"Conversions\" = _t, #\"Leads\" = _t, #\"Revenue\" = _t, #\"New Customers\" = _t]),",
                "    #\"Typed\" = Table.TransformColumnTypes(Source,{{\"Week\", type date}, {\"Channel\", type text}, {\"Region\", type text}, {\"Channel Group\", type text}, {\"Channel Type\", type text}, {\"Super Region\", type text}, {\"Year\", type text}, {\"Quarter\", type text}, {\"Month\", type text}, {\"Spend\", type number}, {\"Impressions\", Int64.Type}, {\"Clicks\", Int64.Type}, {\"Conversions\", Int64.Type}, {\"Leads\", Int64.Type}, {\"Revenue\", type number}, {\"New Customers\", Int64.Type}},\"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Marketing performance\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}
