{
  "name": "SemanticModel",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Acquisition",
        "columns": [
          {
            "name": "Month",
            "dataType": "dateTime",
            "sourceColumn": "Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "Channel",
            "dataType": "string",
            "sourceColumn": "Channel",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Plan",
            "dataType": "string",
            "sourceColumn": "Plan",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Channel Type",
            "dataType": "string",
            "sourceColumn": "Channel Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month Label",
            "dataType": "string",
            "sourceColumn": "Month Label",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "New Customers (raw)",
            "dataType": "int64",
            "sourceColumn": "New Customers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Acquisition Cost",
            "dataType": "double",
            "sourceColumn": "Acquisition Cost",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "New MRR (raw)",
            "dataType": "double",
            "sourceColumn": "New MRR",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "LTV Pool",
            "dataType": "double",
            "sourceColumn": "LTV Pool",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "First Order Revenue (raw)",
            "dataType": "double",
            "sourceColumn": "First Order Revenue",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Lifetime Pool",
            "dataType": "double",
            "sourceColumn": "Lifetime Pool",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "measures": [
          {
            "name": "New Customers",
            "expression": "SUM('Acquisition'[New Customers (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Acquisition Spend",
            "expression": "SUM('Acquisition'[Acquisition Cost])",
            "formatString": "\"$\"#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "New MRR",
            "expression": "SUM('Acquisition'[New MRR (raw)])",
            "formatString": "\"$\"#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "First Order Revenue",
            "expression": "SUM('Acquisition'[First Order Revenue (raw)])",
            "formatString": "\"$\"#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "CAC",
            "expression": "DIVIDE(SUM('Acquisition'[Acquisition Cost]), SUM('Acquisition'[New Customers (raw)]))",
            "formatString": "\"$\"#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "ARPU",
            "expression": "DIVIDE(SUM('Acquisition'[New MRR (raw)]), SUM('Acquisition'[New Customers (raw)]))",
            "formatString": "\"$\"#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "LTV",
            "expression": "DIVIDE(SUM('Acquisition'[LTV Pool]), SUM('Acquisition'[New Customers (raw)]))",
            "formatString": "\"$\"#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "LTV to CAC",
            "expression": "DIVIDE(SUM('Acquisition'[LTV Pool]), SUM('Acquisition'[Acquisition Cost]))",
            "formatString": "#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "CAC Payback Months",
            "expression": "DIVIDE(SUM('Acquisition'[Acquisition Cost]), SUM('Acquisition'[New MRR (raw)]))",
            "formatString": "#,0.0",
            "displayFolder": "Measures"
          },
          {
            "name": "Avg Lifetime Months",
            "expression": "DIVIDE(SUM('Acquisition'[Lifetime Pool]), SUM('Acquisition'[New Customers (raw)]))",
            "formatString": "#,0.0",
            "displayFolder": "Measures"
          },
          {
            "name": "First Order ROI %",
            "expression": "DIVIDE((SUM('Acquisition'[First Order Revenue (raw)]) - SUM('Acquisition'[Acquisition Cost])), SUM('Acquisition'[Acquisition Cost]))",
            "formatString": "0.0%",
            "displayFolder": "Measures"
          },
          {
            "name": "Target LTV to CAC",
            "expression": "3",
            "formatString": "#,0.0",
            "displayFolder": "Measures"
          },
          {
            "name": "Target Payback Months",
            "expression": "12",
            "formatString": "#,0.0",
            "displayFolder": "Measures"
          }
        ],
        "partitions": [
          {
            "name": "Acquisition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"rX1dsyzJbdxfYfBZHFcB9fnsYPjJQdt8VOhhTa0shmlSsVqF/r6RSNSc03N7pqenGWGLh5d3t3G6q4AEkEj84z/+VpKU36Vs/++3//Db//HTn//5N3/8+adf/vSv9t/++OtPv/z68y/x5/Yf+LvxH7/7n3n95P9kH8n+7+g68q36X5I65DY6fuxt9Hkb/sdzSLlptR9zzkVv5bf/9A8vrfhvv/ztP3/917eMKBmPy2PMNvBfU1O5lQnzWtKRbvgHa65Dbx1/OrOMWz8y4Pd/tZfwb7/8+d9/fssI+3fi2faLlnYrYj837W3eJv9a77WOW8E/bW9C8m3ix2Im38YzS/72pz//9JeTH6RlPLpKruk2/XXbO8h8sP3hzPYO/DO1WW4JP45RyvPPsWw48TnUH5ZzzdO+vvqfpD5uY/hLKcN+e8GTS2mqt4S/0e3z3OqREWc/ib8LGUV7vvG91Jbqjf+jfZGZ9Cb48y7DfvQPmGe/tR8N+a9/s2f/9dff/Jff/PH3f9h8kz/88n9++uuf//TalNH9oNqLGLeEMyj2C8ut4kfNyU4sflD7LDc/R1lqecuO+3d5y4zS8dvOmu1SKB5Z7HC0mzaY2LTlfEv+nsZM7db8PSVt6ZaPLdl8nLesyXEq7cYIbeh52C1p/scqo9r98b8zdRS59eGf0Czbuby//38//Xl7Wf7wn3/9+eio8lesI48bf1mRefOXlKWP1m+p+c/TvlvpfrPMpenzx399j+OnZ/cNKvbb3bL6HyS7BgXXVu2kpvBiUqqoO7EiWvfu6nr69hscW+BvethVaLdc/ChO816j8VW0Zr81j4n9I4PuQkoqt/mjCf/r53/5+ZdfHvzV73/65dAG8WCRczfX1PDmR8l2HAbPnh8B/x52S+jsZ7rJy+ffv8E7j88Nv620au+g8w/gqTv+VO1erqAhYv/DbfiFrXPsOatvJmw+xDtmVEaMVOdN1P2DmXGr7jvMV9sbcW+uOC1h56y69yH+8B+//u+//cdf/3nzIf74019+/vff/eXwWzCoN0SPXt0RqL1/fIueZis38ajaa7vNyW8ne5fxmw33j/GmCdndY25dy+SJy6m5k7ZwIppu7iqzNoucbpjo3PVP32zYfI037fBzb24nzRpmtIKnuxPQks09e2wTM9iwjxslLe/57P/+0y//9+df/+0vP/3p54do/suvf/WfXoIbf9G9Sr1lOiO7K7fmb6nMZPeV5lnAsNuKH1tquy5ya8e3iP6GGeLYzdAFflm3SNW8g3hUa9NeEiN9AhLsBFwGBPORFQ8h/Q1L/Fzm0nIbN7+N5jju0NKOiIVQf0/2bnK6VT8iAJ/f3aZcwb0OGPwUWsjsha7K3IM9bfjf6qXmEtd4WHS/ZaKRbH5+HFnxJtASgk0GDfMbfEaxc1JvgnfRp32gxgNR27BX5LFu2nnanA25iH39ZqoHp6qp663i5beWp3kGXhBt9j/RiwNk2Pdx14Kj+9SSs9jX3ac/utZsMaNWvpqSlpcwtBmoG9irMMrNYtDw0IgT30Q9Yuds2MEAlLvsImPwSDadijDjb6sMZClxmNKRCWe/CGO1eQ07if5s81n9Dn2ldEPeHlEsR7PQzg+Izyc/WnIB+/Kb+79cuzbCHLGrKTcG2N6QIvo9FnwVZS5V7d3MY0veR79+X/w8zpLsX+5Xp/RiuVEmQB+GOPn4prVUfiUgkL7nOq6hX/9EtdONVvPbk3HVPsyN/4BlSYYAiL4MilkyRbdbR0979pyGv35Y/YXk2oqBboK+aWGGR1jFot9t+t8odVQiRDtGW+wjn+FfYT7qGFz7VyyFy3YkOkadkav2AnfqGaNlKM+ffQb9Em45uhILXrypaVrIKkQhadSUIqiNaYCH/xq1nHbn9X+Efv0TEPiLY05PdZJlou6yLKDY22biaiHf/rjScRhGbC9NeBsA+7+6Jw9UgDGeohsiNmzFjNQMM3Q1+LUScrDKczP3ruenANhTTt487YE8LQEe4gF+WFJiV8RPpaq50wj20/y5/mjEp/hXvvBvn8PApXtNxFPHfN2yVWX8MEem/EOZdmHzSxvO4F9+aSYhds+Fhz4j9eEJldQmKimEQCgvsZhgznUPWVyAwH42HUZlSz+jRJD7AOZTfzGGKcx3MrYmQD23Fe5y54V8DIGFodLftZdxeF2mJSg8BZYm2/1lutimooqEvLbvvpBPEbAwC/d/s1gurkTAUzKLEqX0hDjBcg5iroe0qqp79+QKBGa5yr+/CC5L9y8l5j+EdTd7IymKf4YxLFdwkCFd+gbp6BUMrCyj0lN2ifKNNLE44YE992JAz4s3hrwMn3oZOIu50k340AsY2M8hv42MbJ8l83celoK4+zJk3C2geP7eBE6k0eQxtvmAXgTBDKOFlVdDEsQRlkfb05WHp1loy344J/Nnptdjm7vqFQys9E0sJKRJjCMAU1G6sc9j74Du1Yz7yq9HObLhxCcpyS+mJYJ9egDX2S2gsHRgQdVOi8eZas6i8j3YqZDnh/MDDEwv4Q+XhEDhfqOpQU+mzoLSUo0q6FBAkEpI2GUTXfUyBg4I56cjAe4yoZ4jVfpPS4kQZniTCcfDwWfdOx2fo2C/MY1BpcJ7FP+TWg2aE3knyxIMa/qV6YYE7KCy6FBqeceWczhYv/CH3RXzoH4YileV3KFYmiIOOB0O2f9ym95FQEK5c15Oo2AWN901WZrSGE6zpBpl2FxGMbPigltGHRWWrHnvlJxFwcqOmd+RrJG1WoBpnW0AS9ZLWrW2aYD85kmDXaK2iSv6ORDWFU8sV852HRlOgHVWOMlzRuJWxsQ9oas3F7rjyD8Cwmx+9PAakxmZOY0Z/tpgjx3QGW02NK78qhos3ABA/RwIs/rOClZryVtB9t9RPYhqfLFQTrRTUS7vxEZj91J8ioN1JSW9G+hjFqBIQaOVZ76zIP9wmDGnwaHIIeu2JK7XkLDe630WSS0D4ZUbLQLsEJSj/V1MMWfuLRJDOnmDuPQSEtZ7RzXPmue4MaZINefYmDa3NiJXa+biI8L1KXsX4wIQZkTz3LMW84wtjEJT1T2Rhc/CgCYFjSzWqqvOPQf1MQ52P51ZmP6CU4wQbPPOgnpBlL0MhnnS1g187V3TT4Gw8iX7v1naKnJ6WuCVVoM/Bj3oIrQlw2TS6C8PX8Y5GOxh2z9FLyiOlChEmwsfBMfJEjaG99omsrh4edurUs6jYLkb4fk6i7CpZmTH/rcMdBZSIOxxDemCo2CwDryGks2/b4tK5TQK3hpRpa8aZ7sFDu25e09zjlpT0DC6BY7KTme2Pz2y4BBwba1gJLe3XWaNSN7gPjyo2afxRk308ixhivqjB9VnlrwHgbdmdC/atJod5DM56JE/W2pvzoS1DcvYJgFQtpStb/xGOY2BtzYUFu7sStptUDJDUM/ytGA6AyaK1cNSBO8sT8vnNle1fISBHz6JpwNqb3tGNcGgpp0GfpM8pKR+iyrtbPHnNfe6d0lOY+AHW5IjXPOi6OnWe6rsDlNHSz2KLmZTXxV8C7zbtLV8hoEf7gtBbfZWM+uqU6UuyJMsaVDijd4mukvEJsk+Wzu25R0M/PBqBpt8Bq/iWsxiYS3Sg5QbODNMoC2LJVOlWxa7Z82bGPjhvLKfaJBisollDluiyJVbB/zyN2ZpdlBpmh2pPR/2HgTePl38OcXykEr3LU3h04nyBNHMvWm5l8orMsr8/OnHCPjBZ9CJ2xkoq+aLKkKJboRd0hHVhYk2uF9Y+y5l7wOcgMBbI5RMiNpQXY2TaN+4shzfkwZ3yAIb0EekbrJ3Vd/HwA9fgobomMH8MOxlR4LIuNdud6RFC6dEc9VA0dwgv/IJCN6a0cKPm0f0F6GiOI0RaQtSZPpUQaE2s8CS947jOQz88DLolytOunsAL/J5t8i8ZeVJHHNKdDH2wtgp/Pvou1nyrWhpx6UsSHnIH0t54f+MxhG9u8CJv34N7wHgB/fg/2casJyR/tlByXTR9iYamEpurP0caZK5r7bnuE8i4Ae/HdlYt1BKn2w/5nBTU7pdzcl/ArXxGk21N+w4QsAPFzUlP5+9rWqaBW+90UT7MGWy6qdDaxRQLHnYPZ/nMfAD/GT4MIfA/lhHQGO1IhnsKUGaM/saMwKzaJsi1SsImGkpL2aeE2ShzqTVQiWbCMPrBzxG2aE6Pxw6Bf3IjjchF2upwhqnR+lB2sMIIJ5RQVj5Shc0PNlbkY6AdmTGCdQVnFu+9KJB5xrmO1PUtIal7kBj/s7slYSzt4Dann+Ys0DY4bd7hy6zR1aKtv9gRqbJnFk0/DQXuFHCi1GPTDjxTcqIBF3AZu1suSNFFxKPwS5jwRrYh5HXHLzk5yfjAyBMIOkhbCYwKP1vIZpJcPssbXJChNfB5rDoSpQxZJst1stAmGWMxEuJsivRb8UxcI9WUKPP/EilDRRgmeYir+7HtrwPhN15E2UrcGX0SQz5TL4Js8neSvBhLVXASe1Mrme/1WNbzgHhem/AqiE+6az5mPNA/ctBQKn2/++dJBCBPR4YaN51JaeRMAGex1GA3nAdBWUMOq1uFyXxRuc+Vluh40zl589/FwozT3YeV7U0jedBDPN23tNix3FG/9WyZnPu4tRR/IX2/PFnsDCzdiZrmhcEF0WrPRBIFRDvWFep6OWw6Vnqng0fYWHWwz3faFkidpirRJOZ+NdivUTdq6Ahzly6P/QW6+dYmHV4VrFAoyPoNe84orGa7WZOFnYSklitUZF++fxTQNiPNoNHM0ThfDWt085lJAcGKSxPjsBvn4UcHotoaYPH6zUkzLqJrvwo+mfdg4ojEIMcJcqihgQGq/fmadNLG86g4Xpvr6I10urqx2Q7+KTHmjPQKPHliakST00Uwz/y0oyzaNg/MznAloJKvHLDMnpb3OmM9x9MAPBOJZgTe5Z8jIYd8Xi50ewAwhUyd0r86oaCnHZIWlWZ0epzOuo4suN9NOxX1e+JeWz7Zf3WWq7WgwzRkhogC5KEpfmDOUN/rDDV62iYUFT539H294tRMVgQLLZWesU78XZGB33ZI54FvG0zsV1BxM4qjUx1gqPMgkYfJZiG5kHRMfALo7XOe1DND6SqdgEQk/FJbJMMUdxIR8GUk0ZQBYGdxCak2Sloqw+Tce0iGiZriIQhuxrBusVgT6b/Ns8yB4ocBBwe4NysBnf/1JSzcNifyhzeIht5ZVIshpIcK2bDGnlQi/1hnJmj2+ygXQDE7U5lynZXDEwx1Bcw2tjPMH+GiRv/eMNSKLqR2Ut/fjA+wMONqIaZdAKXzdP4aRFEWTDXiUIDz3LOSCm9pTC39OB2GQ23KHKRlpCVpXLNYAl5DUinqn2uym5rRoOaxYVU6t6H+RwNt/vwZBZ7fmZD0bz5mpPM2TCXfRMfvrHUOkVunb0fp8e2nEPDjT/54ZyjBZk+W55vvzmr+vY9HJC0ZUV0OXpLWyffPsTD/tZZ4Ei4mHz3isEjsqMbgj+b5X502SiW3eN6Fg0Ty7A4nTA7Sz+6zmuZaGyxAMaC0OTkYnv59DNg2J1GsOnNjUYNI8F78xpbMG0t+29dU0rBwLOwP/fOw0dYmP2Q5E5jggQRZYMWaC8DaC3CkAWWmLitwEDtpQ1vY+H2RdWu9U7VtuCW6C50zAnSBqsvaKQRJD3kq+0aGm5fZWEUeEqMK4ICG+OKBU0bEkbzTJVBX0rZ9eCfomF/GZWJKYpZHtK72KH0isG0w5Hix4wzycK5lL2P8SEapvvOBHbonnKoQ8GJpX3mxyzkK0uDYjeUKSMIiK/NOIuG21dt2NKgGe1W54w4ndtCSl4DUrO0mKFFPWjPkI/BcGMy6tkaqPqcINTFCJVk3ilHZdjwYCOBegCdyZEZ72Nh8l45sVkWutIEyoofmNoabiXzuDkslvkNbqgi1yMzzmFhD9wsipvvmpwIK6OgrcqJ52ZZa6T3TVFw8qxf29gSlvt5KKx3K1h41aAbltLYurCTIuEktHkZmJ9uIpNfffOxzQ/6aSy8NaN6foRhBpXg0FUE0hiWKgU5PIOn1xbYc5OatnWu/hEcfngjnI4clj1WDx2jobLWSNI2YD6iEmi4SxBTvTjcattcmX4eDW/NGP6mO8b710DnbAsAzob5VmZ3CQ1nVhzMnH5sxYnPUjoj2xiIqV5rMv+Z2GPrBgg7QbJlSSBnMsUreTz/KG/D4YePUhM7nECbTOQLuOz9/mYw/OHtwJ5iplK3WWP/EA0/GJL9INjh9AyZvVjhxSnm7muheZgCioYCWLrtHVOOwPDWkuavxDBOtxwoWOWYBGF5MFs2he6S+9FS5r0y1/I7pryDhR9eDCkrYE0LnZhdIMPmPSQ0BhQKeGtl3CvDaMvtHNg3kfDDYaWqjT2qLULIxFlled5CTCgF5A6KaouG8ZYV2c9g4e3jhWOU6KXcljdrIQsAkgSiPzlnGBxsbIkBtD9//DEYfvAZLcaRisTkd82ra6Ozd7yYwdNrvo0dFzDud97ACTC8tWEVhjUVUlJyhWYCQVFN434S4c3iLTxAwH4WCz98CGHqbKgixI0ErJgZ1KVpEYbOfBbMwtPP9bEXz86B4a0ZLA2PZIicfLYmSyXCnEjF1AfnBTuSRDLL+0M/q38Chh+PpYONOYWsaftNB8PFrBmJIgvD1QA5MfvIee9KngLDD66BKikycxmRDRTU1aK+BDI/y6MDCINdacFA7Usr3sPCDy4ihjxUg8AveWB2z7VtMIy06k0DI31xktvYex8nwfAD3BlBP+g9ysKLNpIUvKaAwobJWJ4cJcme2z4HhR8uaqbYlWdlkRcD2ng8HxU/e9HPrkwjUbNBZaceWfEOEv4Bg/K/Q8+mUZsiafBgDW+0EQU4+xSGxCTmj7eee1xBws6Vb4Qvw5Bn6BBYoIj4oYZ78MDJjlML1mwu6YFcNS4AYXfNHEfTAULooFbY7AEqJq7sJKpoE0xZAoyMXL4dWXECcrGGRxiV+aaBSNHD4nBUM3AxV1fD4k0L2kh77IKPKzjYn+re3NJGNN05zdpWSiKWLqToP2oaQfm31/FAuhsXYLB3Rji+Wibkfzh1ax4i0JWZYHCiMIOE28rU8JpbBzYuomAWtIg4nS/vh8My1nuPLVuSZNiDmkRdwKPO1PHYDsGMy0CYIWMmpmlLONBy69aDxGQIC3nLICBIAQPt8D6wrMZVJDxYi4+JOQ1BBNQbO+ueCQc1hdxg1dXwyQLemR6bcg4Jc/iEsnZJFlHDDsMixNl5LRjPKTFBg4hf2PfoZe/AnIbCMe/MORMSpvFlYgS7+mQMuzkdZEDWOEpJe27sLA4eXwwJnRC9IRVygulPrCMd04tUYgHtP1Mz7iHGjs9xsPuMEMYbi62tE4O17IHLMAtjDKVC+2aNG5S0dzQ/AsKD2lRsi6clXAa9iGCEglC0mnpAxczrawHF/qUNbyNhohtZDc0AmAkE9sZB1olikgZGtCviR7WASq4vTTiFhL3jQL2jbne/kSjkOmGksaCUFBI4JYPJ2yivkvcOxKdAeHxVhQc0RIK7gfqix1WDOKElMnX2NR7Vt52KcQkIj3tTzxw1WhTsYCqe7EVJqU6d0GAMz6/6Tn1pxFkczIDGadHRa/RtzCb1nBFzQJYtkVYywFFgndppAj8a8jEM5r0nuQ7voEWAAGOmhnxeCvaMpDlDYcOyl77nJj9Fwhzg8E6SQb+Qi5CJ5gknwu1m5EWiGsDppAuDjpiPzDgHhTmw6XmQ5QfBnyoVSUmkz30aGOMHM3iBVg85R3n7aeYVKOyceS84gis+FnsfE4QhIJc0IKgKGplSo6izfSHzAhCedzEoqPeZx6J7aBXjvCHspj3KsBZdOoUbskXcbf48L+LgeS891tSBL0dUrWpIP0FtE3TyxjA/WsjoVm8/P7PkLA6exPtBFOcvKw5954hZg6wx69kwIkMnktAA0yMjznyTUJND/YgYQicQndcVyiwgcLcYbqzMJAdx8oENZz9JKEcIJtUoW2x4PARx7cVM8LqpHpW9AUd1sdH2TugFHEwWUeb5gPfIMWwwYtJX7XtpvBS1KJOiUF8gazePbXkfB09i8WhL1OACgIEYXWCcBoAdCt3BuVLxAyN+u6fkGhCe36Rb7ck1VNwycDn/dCrKw0EpL2CBDUpMza000PwQB5MZS38qqcaEjmDK1+M7uvEpVNHNQHS/PP6lhwAzP4PC86sSOZCAcAIdU73MFUsacwl5SHeaAhu1Ul49/gwUdrfheLgn4YCgFsXNDL3ehmFjf08VpBCiEPPjO8//CAZTESyHzxjLS4ouyWDLwSR6fCKQP2QftG715+fnKHhSOYQzQdAHphJ9uYO8IhZIY/DDPESlZfZxdgPJpyiYrtuzPBz0ToGZDNDt+FMFE2KUbsOp0Khjt7338CkI5okcoYsasaNhAryy3Y5CgdBpowvLwb429xzVhyCYDicman3QhJcSVHbOx0k38BVcKgODwTiTNraaevMyDKZGh+fKE1M3fKQBrGi3opSjd/02CEeMJem791E+xsGcoU1810vDJBcwVvi6egFRgmXzgQwhOldjHFnxPgqedy5Xzw0qbqRyIaJRzyZDMbcQresa/m6g2+mRFedA8Ly3sRqmKYIZIU5gYh9rVMjpUv3PvKnyHKuL73zZktN5EHz/ySP6oERZr+aNAuuhXZdjfg7j6Gv2tQaZJBv62giX7VvxEnFtjWADHmQuNHmZoNfFRjC0eacnt+wSPFFOT5v6574Vh5hra0nm6P+YUEnmEcQCgEWwL72UeuPEI/oFJMmWuensbQ15DwVvreiUK0lNQrLXXg144pHgg6LKQNuLhXyJ1yHz+Ud5CwZvjdARxVgIVLD4bGlpizpeQkLC8eeJFQEe4Ye9nyMLzn4QgovUgP0HMyEsDeFM/DT3lWNMzaIspJo4DD52LslpCLy1xOBN/LZB6pcO5bjGYrUPAFFh5YuYqkim5NiSIwC8NaRKaKQVQ1l8JRkakCSG1Iq0zf18GxDQ4mxd9m0vx6a8g38fvhA1SGFN7AQYzoEkO8D8LJquGj17mWFyy9vhvWXPmwD44ajGcCIk6UsQvXSpNZUMVdsovNg9ChocoMh4/vzXAHj7eHHwpwP5Iu+lK7J2OnVN8B+knCFlooTw3LbiHx9/DIAfPAY1pdHxbSzrQca6RxteQM4d5MOW3ELPWDcsqmXBCQj88BEoVQeZRVJPDXprNHAM+2Bmi+0RSvaTPa1yYMMBBn44ikF2bL0EwmBpjwLoivLaUrtua4Iujb1jcA4CP9xPOkjJQTQV72t7MXJiiUqnn+jJa9Dend95B+fw78OBzGynu7YiYV5rseKoQ0GNPBqoc5Iek7cV+R0bjvHvo99W1vhASonVVLJ6BILlBDELlsGqi9SkjQ1ta8eM9/Dvo3egPkiVaIJAo6ET7RiSQQhl+a/KPWcr5h12XshJ/PuAcoh/IRUW/rCAp05xwe46yqSpDExkD6rrVNnzkucQ8MPhaNTLGFAR4SKCmUPYuowsS2YZlyQIALWjvHNkxjsQ+AF8ciCuwm11WdzCwHfmT0oLiTnz5hbJ2OfJW9WynK9AYCphJeoAzCVQIBA1jLvrozeT7rsa5OEnskx/o6yX8wUIzE4il8u4iqBwr4Y3IzJvKsRI3Y8ZUO8xfT598PnIiBOAizWMQYl77eGl22g9VhWI3WFnb1EuF51oattJefoyzgJglscIrMFMIT9pIB8QDkSPbmGDS04KrOQODQwblCMjTnwRrWykmiNfk7R1jFi+1JorS7OsBDBMMzu22I0jI85+kRgONCgeonG11zHXiwkJTm/8Dw2yTEFXqf5oyAUMzBYiWb8+7BN0UI3dJmofZoYSjfrGjyh7zC1TOuerIJibqhZnHjorwaZa/LJpUUejn9IaGsCrZtx179ZeA8H5Luxh92FaFkaiHY5F7J4pFolLkBCn4tuRoje2Mkk5f4iBOepOIXrMoEXdUXPMA2XlXBxLO3Z24/lN9fnT30XA7EaELECK4R+sQJpkMim4mDn8hwt2McOvW+G4nD9HwF9L5BTUWyr52rVdfWbLjV03luo/rgtZ6T107/1/BIGpGFJDpTrkFgeUYGO6Y7o4/rjvYPKbXCAhXV+a8DYCjo0NZNhCdZTnoX9tBOh59dK8kRnDNrMevIRTCNgvJ4dFoNpCQa4GcRCKnJtBEvR9xfIliottCyj5GgSOoTQOBcyobjZMsbCi03zOY/FCGVXMX27GJXO+BIG/Fn9izRHSoBAPh6BM3BgMD4e2i5dxloDcSyPOAmDO+nOGWQyKk4/S0K90V4nemYQAqWTIJ9fYNZn3zuXHAJgYh5BqjrEm20GJoosyXIMSFw8x+J+Fsx5573B+in/z1wYNhbrnfbHljHVYtfnqTQ21v7y2Vm23PeZ8Hf9ybzEFRLRFH1kH9vbG1BfUwgLzGQYtq58im9UmWa7AX7mPYKGZHLJpmLuPMqzYTyNAKOSQ+pI9SnlbTZIL8Fe+KsDZ/r2FOSl4EGOta+uoAHfu/ksS9XpUgOvmzspF/CtfFWC0SGINLZxpoVYDBIY0Ju4NfY/1fcrYjNZmuQKAhRNxUersiwcBfrJGA6/rmrGFfxvRoRd5fjJOAmD5ovaB+Bskee01h2SdgRvs6eW9Ht43iZrDRp0hy0UAHIPm3LzTkC4XJqQjUtYM/bYca0Z6wVJULi3A5s6dI3oBAcu3KnBeIA7SIWtrRgFXY+mroK3HBLeg0NKPTXkfAfuV8Ug+J3jzgzXFWoL2iNMrcXwhGD+jHJZAqZZjS84BYPkCHmV4PZ4CXr2Hfob0JHNJu0F9MceETDOn8qM1p/GvfE1kdQmdEN/8vdS5ZLb1MXwvYw9CdX3+8HfhLwsG5JoanontDFKRrxNvDtcXDLFvsyMcjCVz5fnjz8Df+zKmmcva1qw+0kzWml1hwaxcpooFpOA53tB2Q8lH8Fe+kSAkB29somBSI4dFyIhiMAY50l2eQV6a8Db8JQeGrxniOjWmICXksbCzzfBvCMf6hulMWYu+F0Q+xb9yJ0GgtRxdkIkl9J6YW2oKWgYjam9A/xqMgD0X8SkElq8qMEjYIYQA6RzqiXcMqZE1A/1oigf77oCXNpyBwCFiQxctVXjuoc+ag8QnWM8VZ5SizjyWW252lssgWL5YEOYWV3dugn2g8WIQWqjtVsCKjfm9vm0OyEUQLNQ/4MJFxIQc4aHfyIdGhzmEBgfIczKDq3xkxPsQWO5K591niSis0zBM65enTCeMjbgyGjJ31ey51SMzzkFguQ8xNMVac46uQnOd3ToBjT0IIqjNN6YpCi2Juyn1vtL5GALX+I/7Co8QfJsSsm3wiCwNuH7Q4LJzrZNNfy2o2IT+kIImcWTFDtx6ZkSZIfcI7ZbBajwkRT1dmclHnQp7FvhAIXWIUcF2ZMUTvPXMkly5ClOwza6zsugumyFeXYbAczn7PCWAebV86pkdrxDwMyO6F/iaQE+K7Kg0euhPWnSFkDXbmNB5iaHGWr51bZ4ZceaTxDyaAe4eE3HJVXTinWDHXmyTgJgIlxXN7/2JZ0ac/SJsYWoFN9xrma1BJE9ajMRBU8WL0aPDEu4yTd/9+ZclbyLgp7Yk6r0mSTEqKhNghqoqjdtryTsDUbxG0THlvTv7HgR+Zkpl5pOdTEA30dEboAJnapYxFJK2MbJHn9KmvvNSniPgp++lR+kN2Rm5hh20Q2YJozgvJA7q1Cl0cq2XsXdcXmLgp+e1RBe8RbPMoNaIrWlgQaA2yirxTHmFviZ7buwVDH72eIlVrZgqD51UMUTMMRzznbMsnXpM51OjIY/86td/BoOfeg1359gqGMp91WXxeEwQ2QcxqOEAzGlxNj+V247rOoTBz2xQNhsKsrESGz0seMYWj4HV1bHbupbo4lRJfc+NH+Hgp2dxxvrTvkTZZp1BV9M2MYRJ1k71liY/kIFjeWnCUxz8zIzYItfBwo/R+yhjYV8rjsmIgYsafHlt3wbNv4x4BwY/PZUlUqMeAgwWytbCz9pS4Jspa++QOjXhpQ3PYPBz901RLIXEUqwOXlodUlijXtX6qAnLTPWlDa8w8NOTGWPe4IIReA1MjHIDlrnRuQYoUQeNUdpSd4PIWxj4qd/ORFO1BSEaHydiuzmEAk0wpnPezXKwigmTQzv2YfDTk+EZWUcLNfaq95KCJ47FJmvNj1ZI+VRyMl0u68CM5zD4KQJN0Sro8SDwtaOCAE6EQqssNkTllT5Chum7LXIFBzsYdzPQT86LGuL7eelMGkrBkUq7Anw4tLENYHIBB8uX9L0kTCRSm2Ni5N5/tGuDtXaxpn0gO+HYj894HllxAnXJNxysXldzPk5ttSwcbCkrl2RNFDyoQtCrbmKJXIHB7qxI09eUYyYTamwLVPRs4W35CxTeosqHXK0cWXHmk4SYkfpmc7rsOUK3rjeXIKecnWIhjzuOmUt+fjo/wMFyZ5UpZvo7s3jDm7q63FjwbEA01u+BsxTSQ9J+tOMCCo6F443C3ughj1B/lyBKg7IvsYQG7Mtou5VWdk/p5yhY7mIq9tWRKlF+VhxVdoqpYAlooxCmGjiOmiCo3P3YlHM4OBqeJNNNCbLr6KhltFjSSYZCDvk2LMJk+77svJjTKJinlSy6dFeOgfR8sFFqTnDrseIsR0OrYevzeP78d1Gw3FGwTqwmpo6hhf0Uq0GTriEczRhOpA5RGrL3LT4BwX4jOaAAJW3yjhvYJyxbmPsEC6BQSg7bOwolH7+Xur5M+AgEc4AmhZx8bHzCBOkK8WKng+UeqL7PgOT2xl4a8DYCJpOOPcu5KjrYrB1laUPjcE5kQjgrOJS9W3lpwCn8Sxloh5vYa8RMfVSA0KCrYZA4KBhofZfw7nPPQ3wKgOVrGq7ju3P4E10In+oZaSxZTbTRwmPBj8hLG84AYA5TJ27xQysx5uPwZfhWimDpKPMU174alGUor404i4BJquS5RwWLOktpVlZfW/PRDnIUOjQQWDEwKPyjGR/DXxZmKP6meW0s8Q21RL8+zn7fOR1BpGP5Xj4y4330S+meRrEgdKdYusCSUS4NkyFrk4k2KF1LVB6/jcI9M+Mc+pX7KJxFCQsTMdEMknSOFQG+eIbSMYZ3enDWwYb8/kr0CvrlfDY/BgT6KCcPQc8AF9oHCJ/UFYHW6Yon2AV1aMabWIuF9sWrHKFPUrtr9IbOUwcspvSiBfZ830dfZQM89SL+1Xs3reUClehBUOedtRLLBufKlhBWZuTPhjLGptSnVzAwOWN+UhX8kxJ7P8EM58BzM1Qaely+mJ1tJkEJqB9ZceK7FDK4oJIcq4/MjaTYGzxAxQ5o1XKzbJErtlOr6fhdnP0snOmeFavWSTvuXuplWtKGj9qQIZPQ/CM0H2DE/mjKBRzMSkaKLYM19lMZ+JVYcYh5JLNRQphixAgjGGeyiTB6FQf7QaXqhE7vNFMWwHzoopr1Kku/b3hdgYTZmmvaIB/9ewBhjvpyiNbi7hJShHzGEh235LFkrhSGcZUQsc/vmyC/zDmNhJXpWJAR7sPmGMyPpqy9ryhCW2DW6Hb1Wsar57+LhPVeXykDtPAQFk8StGy0wS3SkzmOAiAl7Voe8urxZ6Awl5aRiDnqGoBTyLRRDgN8ADTYRiihryXg+lBq0gtYWNk0IrSp80sZd6zwZgewxScBOWMtAq9zz59/Aof1jgG1tRoq3uLzf1QLxqqhFBSmhOvAWLthLe2acAoQey2YHTIcvMqoCp11OpI8OsYrOPmR0uLLC4Tfy49mfIqIlYpfDKb3ToVrp8iaWoT0fjRq6lj6sC2/NOIMJI6ryO8ydNVtCtAxUWlvPRSH8kRNiUIO9sebLoFexsT6tUjOAIcwMRaovce4YNVeFyieX7MFIM/unI2PYbFS4srjmtw58x1KV3xPWAoWs3LmzyAATw2Fh96NXsPF5P12LpKDTHBslkOTnVoQWHHM8is2ZhU2XXv+zuJ/ZsY5XExESl24oYuEa3ATiwfnGndeCiaGCpesScFyie8gvZwHxnI3g1Kzspadzhhe9U3osSETSzcDF2OJWNABc9/Wl8ppXLw1giNhdnOn3ZfgBqDtHKKTPYF851yJIVhImWIaWfOxGYcA7OF9hKZMxuQq53rHHEzgLNzPAi5NbLRtJSTuOhqR9Zkl78HirRmTTWYyg1f7Yu38NhTUohGuPus+Q1cktw3aKadh8daIGosHKqZtCAXdafoXmsWF4ZlGOK8lpJTl+26qZ1ac/SpebSmGeFMckD4T1JvJGIGuicbIMajSa10rwn770ZTTsPjBGJkULoYxXG9tuLyFDn9tSF5nEN/RJiblC32XcWzLESx+uDjsLens5iEqt06CikBepkEyUGkm67Q+9xq7AbVvPGv5HBZv7REqm2sSu5otzoN3EGoc1rHWD0KvISuvsiFU+dGcN2Hxw5kNESbgsTg6XoBjzjugwsQm+mzE5x3sp/L86a9B8fbhGnQ2ZGy8qmmivkL2SgUOySNkYhc9Efts2/PHH4PiB8fBnANELibRlptNqpdAuQ1jL+Sm+AIzVltweXdMOIGJtzYUQvCBeY9FG9bofQKOluXBe8vR0mml654vfx8TPxxEFsFTwWoyaphgSQMLUKUi1pUaXM0QgTeU1PYc1zlMvDUjysGtrMZAhxZqiBZO6JjUqD9o1I4NmfQ9P3EOEj+8jEhMFM13r7eMMvothmxRtq4xxgh2IpVN2tjzEKcw8YPX5LQAdvjqqgdnKPZKSFeXcAyWWofCoiLAvn4X72HiBxeRuAwUla8Qh7hvOh/Jd0UQLPpi4UVW2HFQJxHxg+smdcr34bb1DK6htwgK6fEYYBsgSXYyWXc/yjlA/OCxKGhYLJwS52ktIXbUmviKk0rJgJy/yRe3IyvewcOPQDTUTdqIQfNaILNCvh8Eaw2Rc2PABKMqHGndtlTqFTwcA74SIm1r+FwbyoJMp4qLzoSYL7rTofAxazm2403oVUkd5LVAmyDgBhgRURE29w6xWCoh+hwyh5F6ks23qRcRcb2XugzKQMQkxH8EeoMcPVXzrLqUTtT7S1z6DEavPrPlLCZ2LkaPHcs99HAtYajBbFeLH9BsYEd0LlFUVzaeR0ac+C4hUDs6VvtNbvlDA5zY1+A6SO2dbR1sN6lrX9iWf1cvYmJGz5h68AUiFL3EwrTBV1Pd2wcmR/+LyVsD8hg/mnIBEzMb8vpw64IF7Iy9ecnaQeqjxBoarHiOpfEWAPvua/kcE9NBceOfgnpXWUKH9mCPuiDWWoSSWHLyAC884sE7xpwDxZWrcFifm/bqa4zJWcYUchoDZuiaZqs+IcM5v5r2LtBpWFzve6exx2IET7k34iLzoOZiSOBQF5hlRzlvaQv1M1TMGotwDU+KC5odCE9OnrRQM1CXgy9cGWmRuT5/+BlMXL8wcYXYI4XbRrfUbTVcJvyFH9SGdcsLqe2/gI9AMcfhYsdgDeRlSWOIzOQ24E5YJ+51ZUhtlm27oH6OiTn3olQi1QA40gDzuGJ3dq+M0qWDCjbi+6SXBpxCxJwcZZLuQ++0B62btuZu0prMrhXwmGWXh3S1XoPExP0hADRWNXRi/3a0FLyS0oJehCabUtSk753KDzExLyEJCVx9TpwzwlFDDhY5LIu2GIvy5qdidF1fWnEWE9e7qod0UCCpvmQwjDvT0EtC6yIEMMHFZAesyZ6//BgUu5visHNFN7hGOU5j6TPwVovpwgqJXxYuU8Lg55Ed76Pi2PHs4+Ad+52ZIoPDzBA3BNo7Erm1YZHBxGGmPX9xBRYHmY/1DKzo4jY1jJnG6YQgv3kRbv9I3XJoQtMi28mxdgUWc7QzBAOkrzXGdlnRo57BruojaHBouzHr79CIPDTjTfTFJU+eEtmd7UHXQMs+L54CNqzFZshhV1huIcQndfNl2kVQzCTVnz59gXCACcWyEZLyFNKgwciCo4eIrhAUb6fY2hVQ3KLtzIQ+J45ZYGUW0YRi/UkOXtzIpQU108Vl55EVJ75LpZyaIRY7gSRLF7QvoiIrc0hI0vSMPD+HZuTYtqPbRVTc7loFRX0rJslxinshMVAI7ZUogyaI1ke7ATNbO2/kAiomA7Jx9R8GgkkHHJ6isehTsi94prpDLAE0h1fG3qX5HBS3+8Ql9MFqdOPtHmuU8jOg8qTOnL2TEVpKqM+MTaxpfw9IzFkgRpOEzVkcmMoDnR2KvPaGrfIs1FaHBGz+dMl7t+c0IqYAISFvR+WNbBG8eVbrUZrLN/4DqAN0akm27XxI+wwTB6YhFS+V4Dr5HjeCLkgHxMrdIlDKycytWnn1259BxfQci102o4NUE2I64y6YYSXUKlv1KS+JAubenf0IFrf7kqTsm0TiznRoe5QYmbLoFtUxyEWxctbbOLDhbVxMoR2yR3HO2COvJXb95TsSVk056OzVJ8lfPv8ULPb7OVngmCEcoD7yEXQ3Cx9CLFYTFpiSY5Q07fmJT1ExCXfEv/bWYxXRGIvvhaXkMmIhtsaWu+KUzZdGnMHEpIoyNSklrfnGfj+WmmeHLip7PCCAVTqM2Q7exVlQ3L5AcXVCRA+tu9jIPaCbG0RRLb3GqlDBjMxOIPkYFTMRpKgi+F0hMJczGSRSvOISi7Mwz8clbBjUPjTjfVDc+JKJNzDRINQ4SUs015AQOOZR7gECmdQfe6C8t+uoOE4g9RTstNy4OGroWlJpgcS5zMQbqOErOR1QkvpmSz8PivVuRQ/lc0Z5jMOENA+0MbkHyZJZCLXylaAClSPnk3JkxUvstTWihYAbVkR5xLQIL1EzNohl92iEOmPBkMAITvqoGxfaP8LEW0uEKdxsAljDEAM1cDpVc6CWIi3ZInWZzEq9mrmNa/08Jt4aMr0kbImjhIgZ5jFClxvzIbVHoRhde87Kgva9cWT9NCTe2lCjb5TB8GKtS7uMdT2zy2KHmDz0foMmV7bE5v4RIn44peQlWHxLIVUFLkBsj8IsgKX9980Kc02PtKZzz5TTiPjBGI3tFVjwEgPi0LZjVc4Su1gqUBVbvojTzZfVd0w5QsRbS3pw/LurnHCYfUr4T0uRClwob2wiDODLxNSAHBvzDiZ+uD6xb6+j7EP8g00Xod9p7y1jgLmF/gAUasiCnQ/Ekn4KFD84E+5RqqCTsF7ZIRQfoqsD6mKE75im4VqYx7HHfgYUb5+uAa9SXTzqjL0jXEc5K0b7OSM6UasPdl6Svc/xPih+dB1rqTV3oxf0VEKNu2IWOPaAN0Uex+3gfezGlROQeGsD9TIzuZKExMgHKKbUXVlWWSvMEpsOUOzQlyYcIOKHoxi5BxxWyMl5CzT2JxUQnEnu9nohRxDytvXYPwHFWzPcNRsoTiPko1ztm1y3JBCub1RwjaGrpHnvQ5xDxI9HMqTOsJfJnzZ1RMpm15Pbrh0JgMVZuH467b2IU5D40YOzfN+cUM2Gsy+kDFJiq0E+w+xlfKZnp/I0JH4Ia6xAQmE35CQq6PeOtQyB4YpSvsA9eXjvPTtOAuIHNzUCEC9hpjyhg0kErqPWsvZpYSaB8ok4n/nIjiNE/HA4qEiD9mK4guaOk+uZWl7V0ZGxGmgx0fXIiHfg8MMBiSJxH4a8WEOYabXGLbdWjCSEOCCmljjAU2Q7Cjqu4GFO1wUsrnY/o7uZJyZT6bVB7uAlKsAB0fyqc2xZmuMCIuYmXdb6vBuemcOhf9Lj0jbs9+CaPhAWItDpVklgXATE4xuXWDEY7hWFOaBhS71dw4aInRwHFZ8ECEUrEKSemXIWD4eaMQEPGo58N+CF8siq05uZRGC8LdbogHt1ZMOJb1L5a/bpJU/qxNRKZzG7b8hWDuqCc1QC/eT2/GB8gIYHt8Bzcxd8B0U0fYY7Nl4k7xuQoJoKFAwcx6MeuQFZ4zIajs+eqOKrfQk49RINwFILnBpTaru1a7HQgI+XY1veh8PkDfMWjAIV4Ur+V1nbjaVadh99Hwh+rg4P+djHtpxDw7FnmJek3Eem09Ql8WVZ3MDu5ZAxav0ukZceiqTjQzRMATOO7deRFu7ud3n7YXA4h+8Y2HXGEbuWdRNmxmdweFAUm9IJdiM4TD8x/cnKFAQuQsPS0rmYZuG47POnn0HDdBwEP9jyt6CpRKzziaYasp0tY8UCBxKk7nmvj9AwWzmsmqh97rokhtdsYy1tKRugWJyCAw/2eXlpw9twmEU2lmTtTbOuItpXXgJpfYjRcKK8Bqmh+vaklxacQsPji0uMWSASBDxR5GI+EVVUOLh/GxwCammOsW1Kj2uImFI4seakL7H8oaDKsBkPdbEljOeVMC7i62XvWH4Iib/cuBSDxCHKzl1zgxLR2FFZg7y4lPq0tl2/eQERjy82cUOvOyQvIEtdOPDbcDiYtNqrGTGbu+chPgbEbIMnrr+Beu4M8bfV9LQs2lAwD26ZI5o6dpJ2L8mngHh8sYkrZFtjzxbG+WqMy0CWkZvjq1M5uCZD27EZ5yBxCGUxiqApz0UOWMwdLJvsY4bBtE1odlDOPW2j/LyCiEMdci6F9Fh7rQmCZy1oJpas8OeSIJyvpPFCTXMe2fEm+poku1MQEmJmJFdh1UgLC1OOoNYdqVLPSkqum+syLyLiec9kLWVEVdoLkKPhWjJbGyljfz29PLbattgn2x6oxPMKIo5lxt4Ut3PI+yKYHef99THpKNZrRuGYUA3lmHZkxImPUtjXrG3cRYoaVlOGaopipC1To2OGjqedz/7io3wAied9Wlm7OZHO4gGKfom3RooMqA5zLQoqx7egc24EleZlPBy8WC8ydMgPswKoeDvMV7PCj/Gm1qRBVMt2OrZs0XkVD1O7NySsSmmhytzF9+6x2oPkhes4ElZks5deIFKtx6acg8Pzm95E/RoXSdl8RhSHlVT4EklFDbLR7JtIMz/EwvO+mBo91xGgtyJZjO59EdAC45+VpcWqfeva52dYmJwvLqPBTHisR8doMstRaTbwuz3IF2iJKifc2u5d+QQMz/tC09TRNGJTD9IeIfqg1ZVeuXtE+qLAqXxfQPFlw0doOOR0OUu1qji4MilORPFNeCxWF7QsqCpqecpLC97GwpxNSsRSuYSuqk8wKWOY5aYhQWKmLNXXMkp7acApKDyXErQ9q8QeSjPH0pKQmjA/zX5vbyOaFNIeRDPnNRw8WV+iLn1NEc4tfEUeNgdK0ewdwaVToGPOuncdP0TBVO1k1bcA98VyY5QSYhEEiaJMUBcD0VW7+0srzqJgBjPOdnhNh0MPsuhDKGj1aPZqsmR9UZ3z3jf5GAez7BmZWsuLQuQiyGxgJeyCY+KQXUy0U2ZC9+L6pziY6xipVZBWFFXQ21hjqiOj+8rKcAIzVJZ+514Uu4KDiUD5v+Sx9oVX8dWkzKKGD/F7T8WcVo8cfupmEnathD6Dg8v6ycf6ZjRMMobQQ+wB4mpk74BUviglhntakBd8470cmfEScW2tqJU5UAWVy3mimN0a7KwZtIKX8G9kfyhxcyTVjQTyvhGHiGtryBJfyxNu3AvDyVeKhTp4n9jbM2KlTgt9kDa22kVbU96DwVs7Bsdtki6AJ5wGZhLtqxwXdWOhDvFR2SMjTnyUwnEtiydpSSg0SHKHuKwiZxOqc4+gV5tTzZse274RZz8KoVTzDdT+t3pKLURkDQLPtGYeh723pd/na8x/tOQ0EH6wJVOovHttno3IgW2A1ICBgBKH7FyrhbMADei4HJtyhIO3lrSlBH7f/dZ8S7gG+PDQ6ke1QzJ7NayH9mNL3oHBD++Fe3SmCrT3vNjgIxhsX1guW1NMLGcspQs9su4K6z/a8yYQfjiv3GaZUECIBcyeLoYMWFmCObn78i1SonLa86fvAeHt44XVAuxC4eOloZVGGb7hWwLzjAp5TIlUrAnOzx9/DIQfvUZIUhu8YhgTVDckltmkhq0jnUwOTEiPUETes+EEEH74DLHsRNtYumsQ8tAFgkpb833Q1KcUM1bW9Jc2HEDhh0+Ro6wokQWgUB7LoS01G9iVQyjs9zWEEuuBCW+A4YcbyhoshFVYaFSM1caaHPtTzFtIzET0u/T/2DuQ5/Dww9uoRL4dkrNe2dMW32PaZQl1vIlNHZRGwfrT8tKGYzj86MGZkEzM03KcVltQZARj8qFukS3a3gs823G6HSveg8MPp5MyiL6lqYZOcwlqd1cXEaXQZ4KKEadyfLDqR0tO4uEHxOPOSn2fVGSOmCcYgQnTiGFtS+JGSJSM3MeeszyHh7dmqFCFGsxhEofy13qt0XsNHnfJvvqVePgdM97Bww9nJMVUB/79VKuZ8+4smljitpamwIVGzRaI+fspyVcAsfe8uc3JgExfStndbhDhJ5Z/ZIlOZ4XAJ2+zG9SPzHgTe1GcPge2mdF/L1MxeFM4EFt6TOc0rBwN8AU65Aby5IuImN2bSk3TnGPypQ/sUydJtaJFH+xyC/J5iQLXsW3p5HwFEfvl9Jvbata1AjiXGr15ac2y51BI7ij1xbaI0duRDSc+SuFRhLpuSEwUtNWCLF28scOXhcEdT6wGiKuHNpz9JHTTUJ8O3GuB3X7keHA2HyshLj5m8qOBjvCPRlyAwpGYUXnOgHmUGOd9c5BCUzbyJp0uwB86KOnYkPeBMNEDxQjVsCcrB3XIveoE0XloMLOlhUwhpqvKtrqQ898DCseYQ6xIxGyle+4xlwozCKwzL9XTLJCIIS0t1T1zTiNhbqRjPxOLXmNvJjpJGvs3EPCo2twhusvcQdOLp7+Lg7n5ix1P7Gkn7e9O8S9asf2V7EjzsCVSNd8O+/zpZ2BwvvfjB9pCpO50XJRYgJAqVq5lTpHZeViCNWM3jnyEgqPwSdwTG0NFgwWZxTOEyMYksRpZLSt6+fS38W9o6JEh29dYyUSzNUYrUDLg+uNaS11kie34c87X4C+Xy5C6P0MXHNFhUQuT+YdSgrdsqUkLJQFs1/zRik/Rb77rzU0nJXOYIDsxYAy0dYW84RlaRXXb8s75EvINaMCh9DruaqAZ68hpWkH5e8YoXSwmEYi95ZdWnEW+jF6UCyv37dcJlCFKthfUpAMQG7xa0wwWbfcAxcfIN1OEkUt9Ic4UXXUpi0KngLsjJBTWCek1zyMr3se99M7KNjOUjGds9YrlnBWLLCtBBkBeOOic097ZvAJ7uTaTJfcvTk5D97BHF6FBem5RZbErMqTbt2ULuYJ6WawhsRMYLhhKfbKziX2BsaEQNFSNU1zQrmhHNryJruQuVSDF68yde0ck96WAKI3zPfhqCV4zRGC2u1GyXIS85PAXFmegpuzNm1Gx2qvxvVRQQSOY+toSpgkGTTf6kFmuQF6S0r28OsBX519CHy9kxKY7K42lVknWYNLDLHqWC6CXO1upTGuJVghWlAoBGjJ0q/YZWWudILAHMNzux85yEfXKVxW4UwVdojxOorIo6rJBqx+zYBzKa8Cz7H2SC8A3VNsSJZh06XkoOiKxB03A1qDLVTBEWZVrrba9D/M59mXtPXj9uhYD1pl8PtDRpV2lyutsUNAcK+m62Ky5yeDl7wF9uf8rwFRekgCzebVNo9WGiaG8qsA5tsB2QMWdS3wa+/K8Mra5PjoZAF44CCYqJvV6DOrMJWkOplt+/vx30S+jJwE4SrCLuZ7um9/MlcYAsBaQzTjM7svNnz/+DPyVLzpEQ/ubONdS1lCwgN4vGiPLv6bIBLCybe+mfIR//fcj7qx17RLIUCgKCqT9j3dJryqWnVHkog7d+wyfoGC2krnvdqJwEVvHJFYnqQFCibKf9DTuPK8pLw04BYKp6kgBqBkLwdVVFuMLNYUYN+tr4MiyPw/9kx9s+BQCU1zQZdS6zhYB1E4+RSQmFs9E/RfLzlj/bdvurlxCwUGAYRXesF6wY0pOa6dryxC/pqTGQEYUjYmc97zUBRjM4Q2vWRRU/ukqBLlPJ3vFMtEacX7WsZpmrW12a2W5CIO/4A5GvINkiSVX4RwM4PSlcgNFAGKgAZ3scWTG+zhYvtV/UfdmQRX77xiy6ixONyCjamDHbmbUHXvH4woQlrsW5Cz3slHprlXPCV8DHboo/B45qDoC0W5zGf/0/wE=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Month\" = _t, #\"Channel\" = _t, #\"Plan\" = _t, #\"Channel Type\" = _t, #\"Year\" = _t, #\"Quarter\" = _t, #\"Month Label\" = _t, #\"New Customers\" = _t, #\"Acquisition Cost\" = _t, #\"New MRR\" = _t, #\"LTV Pool\" = _t, #\"First Order Revenue\" = _t, #\"Lifetime Pool\" = _t]),",
                "    #\"Typed\" = Table.TransformColumnTypes(Source,{{\"Month\", type date}, {\"Channel\", type text}, {\"Plan\", type text}, {\"Channel Type\", type text}, {\"Year\", type text}, {\"Quarter\", type text}, {\"Month Label\", type text}, {\"New Customers\", Int64.Type}, {\"Acquisition Cost\", type number}, {\"New MRR\", type number}, {\"LTV Pool\", type number}, {\"First Order Revenue\", type number}, {\"Lifetime Pool\", type number}},\"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Cohorts",
        "columns": [
          {
            "name": "Cohort Month",
            "dataType": "dateTime",
            "sourceColumn": "Cohort Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "Cohort Label",
            "dataType": "string",
            "sourceColumn": "Cohort Label",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Channel",
            "dataType": "string",
            "sourceColumn": "Channel",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Channel Type",
            "dataType": "string",
            "sourceColumn": "Channel Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month Index",
            "dataType": "int64",
            "sourceColumn": "Month Index",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Cohort Size",
            "dataType": "int64",
            "sourceColumn": "Cohort Size",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Customers Retained",
            "dataType": "int64",
            "sourceColumn": "Customers Retained",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Retention",
            "dataType": "double",
            "sourceColumn": "Retention",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Cohort Revenue (raw)",
            "dataType": "double",
            "sourceColumn": "Cohort Revenue",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "measures": [
          {
            "name": "Cohort Customers",
            "expression": "SUM('Cohorts'[Customers Retained])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Cohort Starting Size",
            "expression": "SUM('Cohorts'[Cohort Size])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Retention %",
            "expression": "DIVIDE(SUM('Cohorts'[Customers Retained]), SUM('Cohorts'[Cohort Size]))",
            "formatString": "0.0%",
            "displayFolder": "Measures"
          },
          {
            "name": "Churn %",
            "expression": "1 - DIVIDE(SUM('Cohorts'[Customers Retained]), SUM('Cohorts'[Cohort Size]))",
            "formatString": "0.0%",
            "displayFolder": "Measures"
          },
          {
            "name": "Cohort Revenue",
            "expression": "SUM('Cohorts'[Cohort Revenue (raw)])",
            "formatString": "\"$\"#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Revenue per Cohort Customer",
            "expression": "DIVIDE(SUM('Cohorts'[Cohort Revenue (raw)]), SUM('Cohorts'[Cohort Size]))",
            "formatString": "\"$\"#,0.00",
            "displayFolder": "Measures"
          }
        ],
        "partitions": [
          {
            "name": "Cohorts",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"nL1drwU7bp75VwxfxzuivnUd+DJwML4M5uLEcyZjjNMOOh3M3x+pSBVf1V6r9AHYa7sP+jyutUqUKPIl+V//699bY/0/GKr/8/f/of+H+n/9lz/+9f/6u3/+84+//sv/I/+p/jH1f8mUAH/q/7qUfPrx/u//z/+whyPlFEqN/5N9+9di8f4n7AOtAlM2FzBd/5rLxv0kuw10CowuXsCQr3+tGP/jaBvoFRgif+VwPXWxqfz4sg2EdxGoXEDfuBSMiT8mbwOjAn0S4PXU3hXb3s8uMAHQBQZePFPcT/0Hu7wMPGKeu/6ZK3T0jQsAr/9WBV4PXR8x/OS4v67BTlzm3/BaPUSlvmWzv2wITMUlXoju+hWtqc9I+78iWSQaJMbs2i+6TQRjcVFeDP8zS+aI6JFokVhS3XEOvjWYiwsFiGTraowH7zoiMQLRGhd/6OBbJyTK79i+fEnR/eT9TYwyAr0CyYSYf8LBcixIdEgsri5wt79zo8kEC0RKLvyEAyJ9I1py/iftvxiLJhMIv7Wjg8PKfcUlsj+08KL//V/+9Y9/ex7PYjX8p/1LJVL4Kfs4Uk6Kcppe9pOzzT/RbQOtAqPs3PH6fxKyrys7bQOdAn3iX9Bf9uhMyUv7wwMIP503Ts8qinWXXTmdH7ygPHc5DubnOgJzsrb9mLu8CDwLlpwt+R9P27wEvH70Xbjq0IW8jcuKs4m/rk2XM1bop+z/fAV4UXjtJ4je1v9rf0Eb5BHwAl2n3zYQTMTK5m8vZ7GYsrTFPIEWgaTAZNqCOQCCiVhfAOhT/IkHX9kjkD3YayVGE83Szv8EBgRGAIZ6lNDBV44IDABMwZ9sW5S+AFN9520BbQPRTryHJyRfnbl9M6byDehyXPIOnzu1+QbMOfyk/WVj6QuwHnXxZGFb++0JTf0N7cFXHizFAdDWhf3ugPynf//L3/78y9/+7j/+3T//4z/V//xPf/3vf/zlX//lPpKjhT+Xw11ibDv3EZMUVoh3xRyvLbfem9tF44gKj5jl61/XPxt9rqfg4fd3Sk1yQid3Ua2Z7T/fqV6pUW5D0fM9n+q5n8+oAaiOV9T1s7qS3I8tZ9AIUPEowrWf5OjMxJK+U5NSQxLq9aPUBUE/ls6oGahy+EhwojpUP4ertQC0Byiuf1ZcSJND98UGwLCC8Rj3cNV5Pv0FCGzLFwceZayn58Qnf8GCcfks2Gu5xWCvaMMZFqzLyx2eYzXJ5nS8ZxGYl48esdH7H3O4wRDYl5e797XRkL/cw9OnjYgNgA2uXlPo9LdNiJXf9nqN0VH5KadYsDEv7pNgU0ztwDnDFsQGwFZPOR8vMGsQ6xAbS/g5PWnQyDwBNaR6LJ7utBaNzMsbI7bdlH7yKRaNzBXA1lPcTKLU//g//vjX5mP80//3lz/7DT0Y/bw4xRv7/ls+MXQD+hfN17rKzs/2vifKKor4BWe2yfpvTDyUJ8rdKJd5CabLiDxl+1PCDsorSiKJ1ylHrgT3E7dQQVGW7e0ikqsLemJvT1RUVA9f8FO5utu+hy+eqKQoY29Xo0WDaGKtT1K+SbZYzVBUVHUG09YLLIrK6KqQTzSJ1P9aobrGbSzgoNBli1vfkAhY8lztT6nLbHKf+4XS5W7lCLo8nBKrCZa8hXKA4kMy9EtOmZy9v1i63q1nj54Py0r+CWULFQAV1N3K7RvS1nKnCCgHqBxLM+0dVAKUbM3texZf1/vmaoAF7zKgktn7drDaXVIHst4g/MQv/7WHwmKXLCGjfMotGbCDgrXek2XpuuhVp2NvJVhY6w485HrcxIkn+wsFa905RaVSfW33+lT/x5//959//et10f7HP/6qpyA7P/xJfB8ybhLC/MQiZUkA83KFkmtpsbxLU7fMZa83a0qpbqZhG+cUJ8dYtpJKTZMr9SecV5xcz64besXlk6cLipNVy+F9n72ZJCk/4aLiSJ6OHVByk1D3J5qujh6YjnwWxXrBffdLPuHyjbNFrvackM2RJomCT7iiuAzxB7Lez8z04yJWi7DJQ2KkGm6eOMQfeWoVPW7O7oWt93iz/eORBRyv48AXjtCi0tvrmBzwCHyWusmFyY3tI08N4z6KebHY6iG8+3gfeQF48nzx2jltXXvbNDWMHoFnWr2kT86+j7gEOFGQsLPgXTrZQME0JI4qvJgnV7yPODANb9HxczFPAr0fd2QwDbkrXrxio51oMz7iwDLEEWFcyXmSW/+IA8sQZySI5KG5zNsvw7ovvAosk2DZP/3vv/23f//ff2mYf/7j3/78X//wb/dh64x+EkeKW/w5HuDoBvWd5RK42BBD/In2gGiVaOXcuGK57SEnx9AXolOiMXp21IOoOgX2hOj158u4P8dkqsNx8lqCEiVyx1tWddPT2YuOShRJBt9HQnB5os77QkxK7FeJa5sO1TVtid19YgaigaCtDdX5CydvpiixO7nX7lWPefdDRyscbMVmiCfaXD2Zo+VDBEiMzjlfD9D3yNQ3pAWkg6iUydW9tyevmxwgCcQPgaqPdAIEs+mhf5H0lEma8xsRzEZSX1dIrjpepTpeJ0QwG9GgOsmmmjyRO35Dpm/IEs3P0ZIEu6EIRKru4uE+Xr4gbf1hz763BcNBYWZJ7eQ/AdJnYHVNmjDzxGys/YIkY8rEAfiGdN+Q9f4/8bb/8x9//X///Nv//Lc//uXPKxP917/95c+/9jjxddPmT7kM1FujSSc8uknesVOWebNoQdD3hM43pL2Rd1y1/ddzsH5y3ftG1K/bxUNXbC4FQxPP4hvRK1Fc2yuZF0K2kxDPN2JQopj2tesGiq4dZQfEqC+5GJUK+zxN5H4jJiXK78hvvgkpz751VqIEc69V5HJLXJQTYgGi6EcvY880U4N8XeJqM9Sldo1Y6sFgj741ERBFEFI40GQnceevSAtIftuXi+Fc3XTd0Ron2CW6wOtCVkufSBa/Ij0gEyBjrNfzI2IAYlRhoEtpVpfxFRk/I70JZuJKfkWC5XSd1/WUvvrk8WiXpPwFGaKZBHa+IssXZHazkOfXvRxsp2upLmTxZhId+4qkL0jnyynSfkH6ulXS0eZr3RdkkwoOtweLSPtaIEXXf7P/ueKhLtnBA1qjAabItYHro3Kotk1uG2gVmBxpGNS6aojjabMGdAqMHiJ59ipLKftAr8CQsD4q1mvyuEOuAQMA+z2JL7E5x+YO7AKjAr2kuVkcE2z1KmzeBiYA9oQWh+GdGXOSa7wMPLl1iT8afBh3xjVgAaBI2Lg+yppgxwjN4roGM3GStOb6KEvxsdMuEsFUXHd6pJrJUisC3CZaJFoktmKFfdsjsBUXMxYz5WrNbv9Fk0eix2Kmei8cbsOLwIBAg8Ac6GTpEFjLXQDBwRQqNJ78i8SExDQU4fhLvLJNzEiMYx1OGNUmi8SCxIDFTE3uZ8r+xo0WM5RwUc5lVHgvEukb0Zj8KP5YJKLFjEVhPpTxdvSF+KGeKV1Y/iTO7No85pzXYHRjgjycqJO88S0hs8vTx/LifrK8u26KeWlT/FDLxDyHGoKSqutg7DbO3zhbNJaX62V6vAOu0YLSuoVcZS6hXnvD/sNFxTmozKtnfFraCD9UMQmuB2AuWvSjqnSNlnW9FbhPhWIeuc41XAEclBz5plTP+zhSoyBJPQsvxVFSsMgj4FmtDwrVMH723yyBtSYoN6q+V/yxB4/ngJeU511xo8+/yPPAg2IjH5py8uD7BuBBaVB9HX7pePtUvNR5UNUSTF0uaX+XovSZ568Kv31c/oKrnubRply+8FJaO3k/1S194pX2dff3PQvWkaAmyNeDfMnX/1S19InnbF3Or7/ftMYowJ/LsU71WuwPmaSwIuq4S2Jcr55N/e7PqFapWbzBKw5tqwc88zmmNUbc9cNBBjlmGyZ74rTG6DrmUONjg6030RLPqPCSogfhb7F1Yz8iRiASZpJL+/Y2nVGTUkMC/a41jsYc1gY0A1SU9JyiLvWuf/yTFqD2tGXhVHrrB3JqAGBVwYDOtFUC5VFns4MFw/IlQIFRuvKNh6+LwLLuri2BsWF2z5oXGAUssOfgxHWen/62YFs+RsTG6rPlw4VAAbGElUCxPCSvO1iwMC83JcbGVpQdTp82IRarYJJJ5f1sntcXsYKtoNQgt5YIp+urIBbLlnyp909ziLUGsSiMCL46AKcHgkUjk11Wiqxaof+pkVn7Det8cGN/g1/Yj5VALt+f13+bsp8d2R9LgS6CzwR6LEPl0X1mirKKkvV4RZspUnVOTNhBOUVJCDJx0DXERy53ivI3yomD3dtb5bHZ05QUlCSXWNYA++Qf+bwpKiqqn+LSjanJ9LZ+qqQozKM3KWycuNQfS4EYZSJ4AtYkM9YhTFHlRtmCIlNLNo/V9fMVaoAFCk4yJqbmVe6wdLlbEeJ1vaW9HnGHpevdJqgFquewf1TdzFkOWAQFPIWuPWIHpQu+Kyy5QR6lyQXwcymQkKAUqKR6vuwtB4qAsuBjGeMeArY5S1e8DehYmdguQXvrIQMrKSuHEnY3UljyAStvbJN2bL1CCys+YOVNyGbUIsxRsOCliRUrJi8pf9nb3+03Vmg1Fa/P9bWM59rX+ZP/jVY88p4p+FrGwywpeyp8M4huEob6WsbDNClF4TKekKoRvR8aX8t4LpyT4hEu4wkx2VFZu4TzipMQFJfxRJp6EV/LeBgngejET+eqB5C330RUXK8K4jyaCwc/XVKaZLCvPY1ssmbi6H8t42GcyK/4CHe+vliXdnHlxlkJ9UpBL5EfS/zXFrEBnoecgMmtz972Mia1CpuhjKfyyiT69L2MJw2HJ2eqsis/+zg1CyuemVTx5JwmwazvVTzCs+i+tHMh7/96ahh3CbK0hmqZ/22zpQi8hLxSnVqz/30T8AL4WNXFihMxxvdCHuER8lrw810t8r2Sh3kBQkAlVnc5bxuHBeOQY1/cwKaucttbgQXjkKO/V5i3Xn3by9mCdcj5L6U37c5Ir8vlrfSGhdZ8gb4881z9iff84FvpDRVYL5lbKYU4u3S8ld4wse/13EWoeDu5e7yV3jCxt0jgbkel3SHdAdHrz1ci3I9yTGlya3srvaECMXheOKk1JH7fpd9Kb5gYsfQm2WInO8Nb6Q0TA7ju7aCLZ986K9Fjn2hXMk28jrfSGyFi6Y1vuapwQiS1GOpJcNbm2XqvzidLnAiQHmI29THd5ObyWnojSILSG1u98rEf4DJS7YYsVMpYlybR9tfSGwEmBTqq39odEcFsLBaMOO8fvUyXkWA34h1KWYtrpX9HSDCc3iCVkYmuvegACZYjCkKplGl1UfHotyzfkK1qLZ4sSmu+IMk8ix6XkWA61qKQ0DVtwNGBY78grW1q9denfK2VuS5S/Em8BzU5xBGPbpKX61mWft4xTTbK11qZC9blYNy9MaaJkvC1VIaBBnyVmMJsm3wtlbmId6zo6ozrUnhXLr9WyjDQYaVMmepeXitlmCjhTcfVPC5MpCCvlTK8aKTZn+PoW7Q//gSYFZhBAeedc5Nw1GuhDBN7339WCts8Seu9F8oIUns++1CP2HL0YkhNhmTxcKFMsDQRgb8XygjSQQlKKnmSyXsvlBEkAbIlxlI+QqrVUACtmL+SrkfvmwIgoYW2b6qDs+8NW6NclKQEpX7vfPZ20hdky6T4s6cE0wlDOQ/5SbD6vVDmA7I+8+Qu8l4o8xvpQqtbO9qDLH1Bxqlo9r1Q5gOyhIcr4BDp3qtauDmQ/OHvXMoYdFvDEXCM7OSZXcHWHG5wf9aIVompB94krhLsuAOtAZ0CY4FQmXWlhDH4sQb0ALSYuMqVOF5D1oDwMkLv0Zr5zpnMyVuJADQonoiB9h8vKe0WjrBkIj46yK7xMvCkcFKG/phwtGQKALsGme/DxoajVQ1W0ltpOuk0aR8DdRaJYCheehxzCYoLTXSx/6UJDKXe+4FYb1w0HoKLRIdENxR4+CPTIzAVlxMSW0LDH7yZgESsk3G23oZPfseIRPzWJgU3xj4WiQmJNJSMNKXzPjAj0CCwtElHB68aTMalggN1cv3SZp9oDRLzUDHiHvKfRSIhEauD2tV6FKB/IX6qQbnSffzJWckUH9Pf1mB0YyJZkMVEk+zP/rPpU/mM6SaXDI1agTWeu3l9Ipjkh7M32zCvMNKpb6nVuvltWLhhNkOThGRdHstZ1nBRcRK5vC5VMZtHSHkNlxQnsbbr+lOdj7S0iD8VoDBOOrNwAUqrL3VlG1cUZ+BCEVpseqh4WFzDBnhWC1BCvYePhWiLPDWKHuDnipEmSsj7L4PAVsV1syI0feR0F3kOeFAg41ufpXDwfT3wCCo8qud2slooAM8Ar8UcDl6v2gbJ6ELGxbpcDna89BnnY/BLJ+/HAhTh5aE+xp8YB5UvPGvM2KJqcUs2X3ghhx+zv1NZ+szzqUUYXq1jUjDCWaD+h2s26zOWfMYkgBkLnQGdLXWTduEMaxVbJDFyeUeubo00Jus2qE6pWToESi/XYn4OfwCvzNQ1oeE6Enwsk6U0qRcRau9lSNxgIebJRWpSM8LU2FP7iZ81+VGfu0FNQO36U+6U1Ma1lcNnzUoNUqAY5BdID7ngBhXWfkBtZHUdrZncx2dFI4L1qG3Mrel2PLRXAuMKWBzckuCPwXU7WDCuIN30OINbqjc+TozcwTrE4lSa0KIx7xe4WdGIYA1OpYmxmkI5xYKF+YLtHpOpm4E5/W0jYg1gq4+ZJxGkWdGIYPNQhxGNmRyos6qRjvXDRJZWzX64eVNB7FCH0ZzPcPjbWrCyu9hJSj5tnPigs6qRjs2ILdm/X1o+Vnc8cpL1qkFxEhv4WN3BHEnqsiw2twYf7xfQj9UdnNbsre09o5IZxYRTlCZS+sAlFrCmVJ0wSjsoTaB4uUxwF9xsymRv/1jdwSnRfhmWeF6euR8fqzsYFbG7u2spsrD1qyfI/DpQL7k23DJtPZUmSJz4VyyPrE8Vxw4RU1QBlEElYxtL+35Kfa7uSBK+H/p9t1E9W1YDeUSHDgRR65aW9li63rsWN/S6Gr9rhQ5YBCxr3UPpOmdBol02cBn1Uo+FsGU7kCrsel7xv6tLMyoV5ixIrmcsoiVbr820tbogO2gTFGXUvbWa4t5jZUBBC+rSHPW99VCAhPkSc41p3/qCkAXs1T4SKEsmjW3j5iwCFgbdWgx04n58LcrIdH9yXSE5GlVfSyyleAmTFT69638cFbZLOKs4KQrMvNlTk1u4XZxTnOSrWKcTk3/UvS/h/I1zUuHEGcqryKNs/3ZBcQHmnrbpgX6yLX6tymCc9Ijjvd+lMpbQLdGS0uRSzVUZ1wFH2zitPnXyYqWwsj7fxDH/WpXBOGk3J1UZuTwkfGurWE3CFuzU1Dr2jZ2u13gEPIKqjNZvY3/dkZpFnyUTRL6YZy7C97IM5vU2yiyxqyt5cvB9L8sQHg5XMb6kSQTme1mG8LDMw2SXD9YyqWmMZR5tmuTkRvS9LEN4OA+F2jyKSNu8DDynvFJMHlvcrOEK4IZqWuv8JMv8vSxDeAb9twocxcxrPLCOocyj7gWPdly/eC9lFPbap/iToz9155pYx0sZhYAkYc1NVY21fhQvrRKtEhMeHf7ZL3kV6BQo8qrIMvtrfz55RK/EHpzkVGF0hz9jUKLIwdlMnLFmcgd/qaIQIkH/94qvXlU5ISYgDlXLtiVI/QExK9Ek9PzqXWAsElolwro22GHF2Lr955PVQ2owQ0DLNM3oySOSmowcoNcaytH4yQ72VkEhQK/a4EL11p9OeGowkqLjEVF1bZsTayE1F2iemFL9vv5kByM1lt7j/4roFxcmsea3yonfwBwKTYQYb3UTDJQ0HQNzPaTs0ZrJH4HFh3i2O5AaiiTCLkc4VYd6chd5q5j4DczVK5mka97qJT4Aw3OSwy/ge2lDuj9JBiqGsZxzmadttXuAU0obYpMW+BOkvZH92nQ5OaU8h00sE50SMQiUmp4sHxH9TewdNbi2IZhZWuq9uIFtRlt2h1Ivsu9pk/fahgQiDa5tiG6Whn6vbeBOcEGVft63VmtHxKzE7LG4oenJjr51UaJcLXj+XZvAe/SIpBbTJ5VIJcKzD8s6kgAZFemSL5ME7KS4If0qbmgd349WODkgQm2Db8HveLZXqNU8ahuym+QLJrUN6Vnb4EI9ZcLZC49fkDE86o3XkWA5Q3FDaT0qwxEyf0Z6k2gSL5wUN6RfxQ2tC3o5ej3WfEa6NuQwHf2Wlr4gWw/9wR49Iv1rJYKV4Hu452uUa7Bj2cYBp4gflVizYuu7TvtAq8As+X8uRHDNmw/7QKfAJLr3yJIK/yhaWuN55cUIlYPW/PJS1oBBgUEK1LifZf3+ZswcrwEjAB12W8wuP9qFrQETALtugKOTKY4uyhovK69nn7kUwYc2gzBtAwsAI5Yi+Dbmzu8/IYGZeJmzyaUIvng/CI0XgWAoXkrepW6g2MfQhUUiWIq3WNtQ3e9H0HiRCKZyzz3huLGpJzUdED0SLRJTGS+qi8CAQJyvUR84naxFAmvxZiiW+NWbdJGYkIjTMGxrchn2dwhCgzE4acI5Tz8HuzYajMFBEy61xOf+i7FoMMZi2UAbgl0WfsaPZQPu/uSygRIeAxzXYHRjYh8DxbFGU8b4yxrO3rjeIVb6LDVFc9l/PP2WvZ8Z52jbIAzy2zivOBEnXMGh7OKj6cAaTtuC216pc0mcY9v9t2lRaVg5kNrQVLePS4qzcF2Jpb2Jso3LiiOY2xdCHqXga7SitKFwoJU1EO2vYgM8LBzINN56FnFqFVRgMkTIkUZNxiLPAg/rBgrZ8SaxyAPjx7qBYAKN98ZFngce1g14CmN3tEVeAB7WDYQUxjvJIk9NY1T6p2ej3kVe+sLLxS+55p8rB37xgs2PYqlFXgEeKv29K82n3t6VzWdedQLjWKfzizdR+lv2/eQPxxli+jlEErAIRYkupdk2M9H5C9VI9SwXj9VLgJ1cFSdCf8bmnppj2UOsN2+Xz6geqOJ0sdT/qmo5hMI7SpKIjTxwidJj3sAGNQKVPAxovAbexHRGTUqNAZX+1ZU3xz9rBqozILPLpfmy4YxagNrV6Jz8bRtJPDQCMKzQU07X72qabOv96J4J/QWLoWprYus7cPjDElhX6G2SZTpEjpPNeSb0F2zvKced9GJ9Yaf7i0cqZkRzig+l8g4W7CtIwb+Xw7S60cdvDAws9EZrPHOi5Dy5Gc90/h3rhwkG9TJ7areUETvMnGh9dU5PGQIbC4RVCbnevcc2RTtnAhoZ4XSI0sYIvF+XPyvy8/3JF7I2+8/YHQ4pR2QP0qiakp/c7T4r8q+Yumwh1zzZapJt1pfbQTlFOQcKlBSdG+UdU5RXlHj9iWSrsO+X9c+KfG6bbVCRXwqNFTBTVFSUCG5FkZ+b9n3rp0qK8g7kdtV9MZOb/mdFPrfKRiWbS8WMecApqihKfCoRsXljJxv0F0U+dy30qMBqpW1lazGQLncnd7YgTSSCGdOIc5au967DlEA+2bBrhQ5YUBTYfMdZDPaLIh+7bLMb6s2jrfMcFQCFVYXUGoqbvZ8rAsugit7VC5XbWvOki75rQjlE44ub5E2+KPIZFVFH3yZwbD5WAVZAVitgiFv7uzXAwuEG1HSR7/GAbzr6wEuWet+PehSZxxjBJRbdFC8Nh1lHn314dDlZwulDeRnjkLnG1DkzyQl909ELrtdti7tlzeQlfNPRM67v+r17YUijfmMJFxQnEgHW0XtXr1rvftA3Hb3gJPPOp5v3xbwnRr7p6IUmIn/WadZ/VibJtG86esFJkoWnOV7TMNP2Ei6Ks6ijv0Zv7y87UpO4hy/0xIAdRWJrPAIeYW2cNWly5n0V0gtPSuXlZLdmdrJ/FdIz7z6veHdq5aDv59VXIX3nOXAX6gPaybn8VUjfeTj40dYTYuxLvMZT27jHQ8ilieLP9mKmBDiLAuFrOP22rVEGngGeafMI9nFqHRYHXLYC4Imf+1VG33HDNILsHnPYfvF2ZO+udcZ+3/YWZO8ebhsxufT+fRdU7wE2+pDIvb+PTdV7aEGld3ubq94dlta4mMpkx9pUvZuY0yQXt6B6H6aQte7i+eRNo+rdoeo9t0n3B0AUvePI0uoh50m0b1f0ntqokpNnRNF70TBMjtWJpxPeZ817MfV+4U5WDmreA2jeW91vjifAz6L3WH3KI9wXzXtyEydwT/OeXVN+Hb2RL5r31ic3nOw3XzTvxVbDs0fAL5r30OYXHf2GnzXvuU2ZLCdW8k3z7lqlxOsTvknU49VwmD+J+xlWX/89mvgmUY8yi8fDqWJbpxs6Ieqz9ZanV+yotLkIdPSdnRJlWN111mdLk+zPm0Cdgd0zvO6uqTnWuZwQgxJlKNz1/6Npq97DgW8CdQFabL5vqjP3HuV+E6gLsWuhuJNbMie4rDgD7U6DqdYcjhZO0UXdjeUCttzp0TcmA0Snco9gymNswzpS7YUSCt5tcJMY8qs6vSOh/6S/du4zpAOkB2Sb7FbOvrgHpAVksnmsjllHBkASCr9bo/yz3SwC0mAL+ja982jzIbWbu8Qh8UTqNAmFv8rTPyGbJjge2Q6Vz0iXc54EQl/l6R2ZhwkBebwSBUSGNy15vpRD/MkV+G0q1GDdazC6MUnSdVwCXVd4OuHZmxd7SwW+adXb0BhlXeO5mxdkzjrHWqLL+zB/w3zGAWrX1jgEbtZ4QXk9exhlNNmjLmSNF2+eyzhFzLn8GAq0xtM14iKUq9bbSksZlW1eVp68DCcDkFsPt/3frygPz+b6fNmeWAapafRInyhzrsnYfh9IAAQ9emnegz+wNjUPh43xS5NRHywYUvPog2CvNGppNV508HweeBF4JafRz17kBeBBA/t8TRY44EXggbC9mNagcX8BUgIeOF/FUfk5eLz8GUfGtNv8AVAtxGboXJ+pDTJb+L4f1N35Ml3+5FhBJDdWa6zB6MZEEZMlcZQWF8sHeTfzfAHFF/lUX0bc5znlGezmZZx1Jz+ev3kuGAyENFzaxulbcDgV7Grl67Zp8abZCOO2Um6Dw8s2LinOY2f4eu7+7NOy0uTeebm80ZRHX8k1XFGcBT12tHUd5/0XQWoVd9965oUy9qpc5BHwHAiobfXwh0KARZ4FngFem/Y2CLIXeWoYtz6e8/8uHv1+HngRBMU5P6Y2LfIC8AIIits46LJvtwS2IYeuNK5/DsxZ5KUvvNAa3x28DzAPqQpiXqI4CogXeeUzr27zs/UyEWRzOrb/4QlE1o6Ctg0mAayvnMKFdaE1VElnWAtYI5U43JYhtac9fFj45qXPnOabV6k/azh8Vq/ULAGGKL0s27zbcEYNQCWY22mze+pANqhRqclBwzIbQ04Tb3MiyRaq8dh8vd6iJst/IslmauxZUu4o6R9a/w1oAWiAvqWtm2qeXAdmkmzBWoiiWmuKHUeE7WDBuupBC5JsRzEe/7AE1hUK9l7Pkexku59JsgUrQUvOrJXLgznFgn2FrtTiQi5T/Jje3sEGxEKTdNt6PU78rZkmW7AxYEt3W9wozNzBJsRiN/Mcw5hk3KGCiYWAXceLrQvhcOeiglTQj1dPoG6I9LrNfpJOR44RUr5byubWRtntcOgmBAmvFo7+Z5cmDtMn6TSjvNT+ZZ4f1Ea5hh2SU5LEdlg5XZLdfSivKKlbYG1ZaGXOdocUlNSVVtI75NkJb4qKN6oPqmPRli/VK0+0g0qKkvgr6z2882OjyClJ15ITpYe0KG1XD7+1qIqiJNHFwul6RvtRSTBfn7rQe5Pd3tKw/uzvYZaPwmlhdUG31LxHs7muSFe7640ROf4Y68XPbL1DcsBy2Bbdt36aZYulC97JySiNUsnt/lwBUNipsZ6ys8veR+F0Z2HBl209gdLeT69r3pYh+BGTnwR7PiqnOwuV01T35Emg56NyurOwmznlVir3+hq/qZ05ts2fJN0U/Ng1fIlFypJtsLD74OnR8HYJZxXXmx8UKf2YGfg3tTPjemiRd57WvPn9HXwTOwstww2pKaNmu+s3sbPgJGmWWBbl22ANt4uLgDNwIJl615rY+je1s+B6D9l4K9X8Ni4rzkERbWt8Xw5ebAEcQSPC1uXnPQfyVewsOAtNw+slNUz2tq9a546zmn8rOabJ9fSr1FlwBOOpS/ZmbMW3hgOjECV24FaYPo2J7zUcWIWBBiO5aezztlEQWEVvCJk4eRQOTJbAKgzokgu16tL9pwOrECnjhUtNh1D2N0+1CpJMFONa65i8jyuAg27c1XnP73eLN1EyVzr7+y4Qvc2TVfwmSmacrOPMzcOijZOX8aZK5keTzJZ0rGxVvmQPiE6JIjThVHxstYe5HBC9EqVsmh3p2EYaHvCC8rrfysWDV2eVfECMQDTYirsNKj75EZMCuzvMTxgexVmrQFiCsnJ8/85xFD6tEgsQcWodpZzHqXXLq1ut5e4WzmnlbCae0KsquRfJgSy5tLIAf0IEg+lSbJL0np0oV16FyX26jjbcM/XaP8nwvWqTuWSx3MBcTGh53AOeWkzR9r3lmgdyglNzkUsC635TM5aj76vm0uUDhYPQeezptgzMn4G+hLH3zTKwfAQWaj01XhfNq5D4CnPwJ3f+aCLd9xjrq5A4chFSgVnrV3fh9xjKq5L4QvZKST5ZDbUuu3SCdDfS9XacIoyxk0DWq5aYib1nwuV8uexGxeEyMdzEnhO/KgNa+v9drPSqJWagd9jsuswyQK9aYiZKEw7WEofmrR89Y1ZiVyxd9YpherF7lRMzsbcY5DGxfnJhf5cTs7GUODS7TpOA3LucWJAWkE2ZFs+eUq3m7mvFI3Gqt3P4lA6QqFAuqbR+uydID0hUKNOzK8Q6MgDSYYdmCqe/ZQSkBWRscwiPjJvSF2Q2bnKVfJcTC5JQqNsmFB3ZN5UvyHpJGocKRUTGLe1vSY/6jTUWSn8jSH+NC2EMn63xQPorPSFlCbWwiN/GofI3gfI3WW/HA2GNB+LfABnhepNpHa7DNg/Fvxn7NrSqKbf/alH8C4WARBTDeF6t8b6Jf+vF6KEUX+OB+NdlFP/mVpNqt3nfxL90ya7238c38W8u/tFZZZH3Tfvb+oMf4FD6C3MtSkyPgpdF3hfpb3Pq4ni7WAR+0f5mW0/lwUlc5H3T/ubgTtbLV+0v2cdVfJGH2l8C7W9Kj3qURd4X8W8qdXdOC9vpB61uMeX+5Ml0Tb6St1l0U6JkQLkZSWmt6W3a5tmbF3pEnXOENo2NmNdw7sZ5P3Qfcm28D23z/M1zGZvFmeZW+21cUJzcTKQIgB464jVcvHG9bdO1TmKJj7zQGi4pLoJUN5m6zRu7jcuKCzDiJTYx58Eq1vVrRTPG2tpS79vmYCEb4DnoxRzco2nhIk8t425kzb0xyS5tep+0up0XlRdbT3G//zbIAQ+0xLFpF8LB7+eBB82YYyjh5+DxAuCGXszFnODiF1w2j84rizywDYLWybG+6yNe/sKr29bY5PQXb6qszfDn8lFDvW2lQyYBrAfCM1dCkAujLmEDawFrZD6H9OtrE5NjOcM6xRZpDJake1E97cLhb+CVmmWfjeItpcc84Q1qUGqSTnnXbcImnx6t7zeoEageMiE20zMTskFNQJUxIMGLcM2NF9oNKizU2Oc+c3l9a9OS6YxagNrH+XJUrOWW7KEZgG1FC5c0Wx2VxyyAHSyYV+ydavrsIBqDDztYMK/YxUSi6TN2zAHuYMG87pbPXBxArWHI4ZIlsK+QoImyrRfWUf+5Qw1IdSiBTd6PWcsdLBjY3Z+aO9bXTWZMQO1gE2Kx23GJlsbw2w4WTCxIrEJEsNRaGbxRP2pgLwZ/ch7OV2fufQf8qIENqt4ScZStHjqNerIpyt6oIIIXjjtRa1dgtp7KKUoMhpuuxNJKZ3ZI/ib5hBrY1FyFdzf6owiWUT1Lzkl407QLbgcVFdU7DXIbgdaod++p0o1y0saJf6k2J+j9iP0ogmVSr6LnBZtyadm0DZSuy94emQUA9Vr6EHvPF6iudBewuN+3+IXdW+y62m9xLjfv9M+SrDnLAmuUJFSnce/nIl3vTkbMSSdiW9LP3mPpgu/hNxGbFm/HfuBzVgAWNm5zbSSxCVusCCwzdCIOdiyRn7NgzVNGsWmwfhJC/iyCFRYKV6vbM/N6vrbp9Rrd5h0wxUeF4xKLlCU/WeFi0dYR8n2b/9qm13MupahwtT3do0hhCecU52lIM7QpYHYX5xVnUScVr3e6/R6C4noRu2dcG4kcd3HxxrlisSbetp7c27+drg8nGewo83ztyZvNipPpJ6xcdU34nrZxRXH9oPPS/uRyMXeXsQGewZKP5v7umxipXThJrkeeTlmdKNp/PAs4C005m+Ny8G5JDeOujpCJg8/Oq2s8DzyPXf1bdeJ7AuR7m17miWnI4RzqTmy2VwuBbfRCzyhthN3J84FxoB6Wyzho23QJrMNgn14bCk1ilW+iUxGgJO3FTmZs5rOKI8XJ6Z9FgWrjWNW7SrRK7LsfDwPykd79iTfNKX9XKbdkqX1q8dT3HeZNcxpxQLi0WPL25+QrB+VJF4++qqtrF0/eclTi4OC56GaJnzfRaZTZluhrlKbAOCFmILqhE2710I6ImnDo7X85VmFCKwo6IZIBZBwy4Ha2gb3KTgWJmSAyLo8lVctItRnqZdWcV28ja9zJEiewGgOyTt8Sr0dAMJqu3+XUcHW5/InVEJiNiUC8EognVkNgNr0VFvdVLj4f7o/pMzIXSmf7I4Hd9IG93Bm3xfler/LvctFyf7JctE02KPaERzepTwfr1xI3OaTf1aJX0GGobzL1OjB5Me9qUb4Dw701l7oe39PP72rRgrWSPNbQ+0mk9F0tyrF8FX9HcjSJj7yrRQu0sr1+zth6lZ2966RESVayWrR1tzt6L1mBBBKIkOqd9v2m9y4WLdB75prXHOreSEePSGow97hcDtO1k+uISECEbrY+P8eBrCPVZgataDB5plWbaEXLUysartvG2U/pAQl9uOq9nCapxolWtPySn4YQT3/LCEiUn+aUD7cfSoAErWhoHVjt0TZO+TPS22etSEJkehN2lqSfxE26w2PY6xqMbkyW0hgZ1d3GvA4xkjWevXlRvitfGXKxzY/cxTnFGbznFxP3n83fMF+wx0Bsw/oGGeYaLyivTxxltzmRGQX0a7yovD4P00vh9iP8tcZLN8/1wn4OAfumbdpfeFl5EWWdLbMzHlNrvKI86d9yyTpLm1wyRKwWl7KaRHcdpKXr1bR+//2SGoeTPl4CdCEfGZtah8MajtZ09tG3chHoAOhA2VmJD8HZItADkEA56VrvgP1XTGojPXLFvLa9mINXEoEXsG1qkyofrGkCI5FQmABbee7CIvwkxeSFw7l/vhWYR/eLNZhiYsbGPdEW87OPszfubpDNkYg2d3mb5m6aD1Dualvfz7z/cP7GOWkRJXc858PS5vJJick8CTqwErO5l2X/28YbN3TXTa46L24flxQnXTCurnZEbsnKPgkxSVS/6lkl6+IYXF/DFcVJlOpK+yWT/Bj2WlzFahM9GMlCzBzNT9zHEeCwx2lrPB3dPk/Nwkr3FdZNtrY8tP/rkQMe9tT09ZS0+zsKeeBZUDr6WH721woFwIGsM8RoR2HiIg8sA4WY0dTXseIEfRRifuA5EyZ76EQ46S3+4Zkk/tGCYYNJAOsLMXPN0DWuKZ9hLWBJjrjEUgWKj/aGG1gHWCPRn0s05Vx+d30nsklmlj4blIt+6gE1ShE3qEGp2WsPNkfGP8ZEb0AjQA3IR2y9yT/6FGxQk1JThImI1rem+iWeUTNQu3TjiiSH0NSoh79AUWrsw8844FSe8e0dIwCTijiTuDVhtJPtcyabFGzvGBnlIvnIAO5gwbiiXBGkOfgV7j58YQTGFcWvZ32jbZtWPt1gwL76hBS+EOa6WY91kjvYgFjUTRbyD9XGDhZMLJqM/VNDPefp9JUlxEJepr6xNHYk/UX9KHCM9v5kDyeVONYQTjl0E4JEnTi56q6i9LSD0ocJXfHCAumQwhhumqKcosiMXYHMZN/8qHCMPKCuoDQlxjB2aJqigqKkCIczBKlJ7bbeXlSSXNR41LNrwb6y9VMlRfWoEieK69dLfoeUb5LrEn/evls4zm+tqqKoiKOJvW0XKru1QHWluxBQ4Fjco8nenKWrvUt3WOBI14jordVOFlgWBY6pDRPfey5d705yTxzNc20aXtx7Ll3wTrLoLHaK9VRwW+udAqCwQNGUZCeb62eBo7CwYyilUnb3rAQsg0KBq/vD68/1tZvmpevmT+4CnJ96lSUWKUuurzwT2Tk7cUy+NtNkmkwQ4SHQ1R/xkyjq12aajJN3kHnJVp9hcvP/2k2TcSijqa+hDVB1u7hw43ohNkeI6p5hR2HYEi4qTioqOG1hTZtM6ndxSXFdk8j9rZoIafvFZqWJSyjJ5vZiwy6tAM1io6NQZgGi7800mdcVidxjzLdY8b5NqFHcrUMlsGvH9tFrOAs4B900bc6TaN33bpqCM3rulWDtJET0vZsm4yw2yzbUSkbiNg/MwmKxgKF2e9j/umAXBOMscpP7vYd0vvfTFBw04c65TcN6/bav6sF8f3JwLJtZwOlVPcg+bQQH18bqah0RrT6alJRIV4Fruls4IDolygRXlg/mTA/J6SrRKzE6sOD6iGWyXb0KCC+i7DEss/XVWZzciF4FhBIhAGfMFZcmC/tVQIhtMKUgI5k4ymNWibAMLbatNDHYUdmxSixABAUPtVbgZ++a1GIeAkLbemseIQmQODqDog8TL/JdQDj06yRpge5GGcYyEuwGBYSlvu108rYJzGYUEBYzuba8CwjzLwFhayRtT/YKArPpDXWkUsi5M7MhsBsUEBbXOqm+vuw3uV+6HpU/Zcx8052kEx7dpD6LRNrnhji5xL/J/Zjohz23XgXj5F2/yf2S9KsueiMsTZJx9pBeif0CJq0n0s/R7xhuYE/9XdfFYtw40HwZqK/YSkNMVvuFekN8l9y8qf2E6CDLHut9aqxBXCZmJXalAs9Mj3lsB7BMLEokGDXfJuu9RyRe5X6dCN0mKaWxu8I6UU3mHifIctnyENOvIy0gYYZ7CIYmeoVXuV9HmmHSfByLWdaRajS9h7pMmo80STm9yv06MqKQLk9ua69qv04MQGxp7nK2hNJnpPcVOSjMMiLzmzSvHgce/lzbxjX02m7jSDk58WvJfNxWp2JsdbEGtApMHgbx1ktcfMzlWwM6Bfagf+CyIGseLarWgPDThSFEGOo1fVALrPGC8vwwkcYHa8ar6howAjBAroe8b83q9r9xAiCBu+OifYhY13hZea435+N/ds1X2P/GBYCi6XRcJtP6hqX9d0JgJr2YXxo6hvCoj1wkgqXc8iHubN+ST0OUepFokeiAaNtsXn/wjGArPZLOWricy3gbXAR6BAbs6xjyw8VbJAYkop7QtM6EYX9/oIhEgwrFWB3bYcrMF+IngV1K9ydvsNk/CqrWYHRjUhhyZm2SpLfbPHvzQu+cwYHxVjFo0zbP3TwfwqAwLo8OUms8f/McuLKtrDaMx/waLijOgz42V39pHJa0houKk7w0T7BvPZXt/krRNXI37bxoMYwRpzVaVpqIny9PIbWG7tFt44ripG2P5XbI1XJt3l/IBngEzRNjvdeb/YVMahn3VPcrs9VaK6X9X48s8KzyUptdnPZXHjngoQgwPQfWLPLUMvoNSgZhtwG4+4ZLAXgJVWxNQ3nwfBF4MDg9Zvf6400kcYHPEPnDRe125llOJHEC6/JslsRdgXcXz7AWsL34XKZ9Vmo+/AEcUPt8ncROTht9ncoZFn7QIpowGRRYt/CJ6UxEcUKVvTFyK0EXxtj0BjQqNEvBfOANrlQrN4ePmoAq8V8WxaVCYzfsDWhWaIqqNrcx1RUQD6EFoB4lcRVKYznGjhGAZSVMtVvbxq+9O1EzSZxgjcch3dec8kMrIDCumIfZ39W6RmHADhasKyYYNWV9WwXmdIMB64qyZBlr2l2knP62YF4x4OxvanMf6dASCAwsemjUX1eCpckd4pN4jd87f17/7WoLNHFmPonXmBC7noETNrZNmqIdlL1Rtw5OBqbXnS7bHZRTlOgyk0yRyfSTd0j6CwUaMo2tz1/ceqhwo3zEYaCFSp5485/Ea4LyKF67ykrd1lMlRfWpnbw1tAEpZmstZEURtikKsYRRAzFFlRvVbxasXgvFm4mD91G9JiyRH7J6LZrngMg5i4A1JEy9N5MI30f1mrD6ICvp3lLC5AL/Ub0mLNE8sdjPGTsmpOYoDygDqGjTOKxkjtIV3y90fUS1oTE1MWdFYLlhRHWyk1DjN8GZv3x8/uSWm7mJd2mXRTelB7SuJ0vuKZhYolmlicqJB3wmqkvMbD+cU5yUP7DgrNrVoxf1Es4rTooJksyWDjRxR78JzgQnvk0SlWoxYw31Ei7euD57PEmXuTKxzm96M6HlBO1UWwX1+ynyTW/WaQaznf5ZQriEK4rr2jq50VCaRBC+Cs6EF1FwRq3FR9m3CTUKG7Q6tOSQJxfqr3qzTsOjxZAzE4fqq+BMeB474JkUHsrhNZ4HHkpzTE5mf6mQmkWfXRF4QEHOB3sdgVk46KdXXJpFh94EYuzoZZ1pnPOjo9cqjhQn0XYpJapf932LetOHSYs6p1fx6ihnM9ml3vRhGYckS2e48mycukr0Skw4ZSza6EfZ3ioxKDFiG8bYJP/eHxCjEj2K4oNpqlZ7QExARH1YvczmSfLnTR/GRDmRJKhNdSN837je9GFZ+t6BPqxujH7iML7qwzIOc2Z9mPXBTK4Rr/qwPKjYOMlkw6PsZBmpZkO9a7Fkwko52ygI7IawaUj9Me3ZKicwnN4PmbMOaRb7fVWICRF6rdXftcRJOOxVIvYbeSXnyuvXftVzXRcF/pRpvy1zf8SjmxRlSWa27Tbl8P368SroupC+z33n4gZfkfEI6RRpsMWlaXGfQCdIfyOd+BLX5STXe+pYDrtM1JfiulTz+nXbIB1zRIw30SboZZOoOrLvuatXTRcTA8zY4+laR79jVqKH/No1ECu5E2JRotMWbiG1/utHQFKjuXVnV3ypibrPiGo29yCmwmNT7CRl/K7pEiTO5s3+Ua2wjnSAdNjCrd5cDr+4ByQqz5xPk+D2u6ZLkAYUWC0A4o7WJIHhmILjfs1DNF0QWSYKrAB/rlorCo8JCms4Uk6WUAErsFKbDzjcY9aAVoFRbrwy0zv4R/BhDegASFCKI7N1/DbQKzD0eBLHKiM9equvAeFd9L5rLMEKLc928FIiAHtoiSv7r902bwMTAAk07N622shtXFac6/NWs8jNH5fpNWABoDSCEgVWa+6f91chgZn0uKgosGKm0YNaJIKlOIlHiF6KAo1b2CIRTOXuD8dp+qeYZhEIpjIIsMjU1zRm+ReJHokRiW0OwZBGXyQGJFrUS7Ume2nhGT/opX5viHW3oUdF5xoON0SRSHOmpunilrabD5Kpvn/1di/cbCBZN8bF1oDwln3Gadu+vqKfuM2Dd9zHiPA/arGdfRy+YNQ+lib3LHmbB5thr4Pn2cQmPTqarPFgL+yzEi5/KafwaKK4xoPN0GK/29x6oPv97wt7oZUwDAuxTHr0iVtc0GAgvRcbtzur99Of/e+LG6GVqA5LnYIPY0n2IhAs5NaKiSP2CC4uAh0CUUzUJsUm2gd6BAYAxkgn7xh3wXu0MJco2EcJ2C/gVPFU4A+PDvSuvfEjJgGs79fXKveu9VV436+niqciA7v0sl937egn2+xU8lSk0FHjrN60vdG6M6xXbBEnme/WMcRHz7YNagAqaR8wW0zIZ8SoxJwg6G9zzHFU5W1QE1AtNgErzuWJKzUVPF0XbNHPBA4g2uRHxcAGFdZ+6v2veEB20znmw/dPYFmp19xx9bhPaSzQ3cGCcSUDDZatT5TGOM0OFowrim6Fdxqf6u4ST7FgXLGPI2VpUusiQ6cbDBhXFNVBn51aaOwEsYMF64q9jEUaf7vHRK5f2E/SJB6qyZ8k39r+5B0M3QAv907uu2+Kfz+HP+mSBGThzk7BJjfG7qcod6Oc9P9PklxJZiwQmKK8okSh3VubuUmg45MuSUi9p1a8mwCUtIOKiiKcy0auntxlaxUkRRnUJZGzfiwZnaLyjbJ9bDRfd73Jmygd+GoTtNoorTK2lK3laQAFI7JLcDTxHz6qkgQVcWioaU1Tw9ZiJ13tNmDKzzRp/bun8FGV1FnQ09nE6lu7PZQHlKqScqx3902SLvdeiuC5dY2deavLOqKc6lFt/S4LdUSSBmdZUjJuEhycCIl6wb5cXGOZbMkTIZGkTTI3qqTqQbzfDCdCokH540przJt2cSAkksLRZO/2BMXt4lBIVHR3bU83FlEu0VBIhHOZqdV4hu2fDpVEKCS1raP29lcFIVHvquWkK1zeXsGoIoIMYMnkJ47bVEQEXauMsTSmmNZwqCJygIuJRmnjGg5FRGEQEZH52X6rXzVE5IIZBflrPBAReZg3WKKh96d7Ef2wcfGnZEK8n+xNL6IfBvV3y3Lv2OTe/oRolSiXXJ6oW79xGtPPq0SnRIOGm1tHakcHRK8/X8EJNLm1h3/fp15UP0KM4JJQTPlRn71KjEoM42Cblm84ecYExKErVBut/X6jf1H9CNGj6sfFugfak3ddlOhQ9eNiHju9LC9wA0QLoh9XQpl4LW+iH0F2aZKVQZVukhV5E/105KDQySlM4oFvop+ODDgpqMXb6GRJEthNF1DxkNI2oPOICHbTR9MU0U+lyY72LtFJ9yc7gyXmydn3LtFJXOgJLld0LkwM8V2iczkkfUwu+0kmPzokLSOdInvPDp5ZUe98Zw/pb2LvleClP+LRAwbF9Y4Y1y97dRw+etHxJlr5FVme02ZoHAF1zVjsN3EpIZI/IWYlehhEFNpoKHv0jEWJ0gnXERPz5LyeyHNYsOChQVIpZRLEmOhzEs77YH1OcZNbykSfw2nJhGIaKqNkdR3pAAkjdoJt9fD2COkBOXSGKmkSpZroc9IvfU5ywywrMkC8/ovftTRkLfzhNh5Np+u3caScIpHMzJ5LvZ8OrZQXgfBgqV9exD0NeYjnLwKdAnusNcjYxhyH9b0I9AoMovbhQE/KdSlitnIRGADosY13TOjdLtKi0nqjf3Z4QhPJm/3vmwAYDJz67YJl95dMBp50J5WRgy17jEfBIrAAsMt82Q0lM7QlW13TYCNOWr7wjEBbr9Ani5rATJxEP2VIYKqXaNT5rhItElGaY0oOQ7hxlQiG4hJ2HqL0UIGsEj0Shz5B7RkXTPmz7CXDHy55qXtXcts4Uk5vapB4FnKuJ1/a5lnlRYOxg2TdWB25CHQKHEV2Pvk0dN1dBHoAWhxeb55tpReBQYFOuoey8KX1GaC8zYvA61Jh4rjw2LJlkZeAh80fczFpuPIu8mDp2QJtGhPlMYa4yCvAS9iBqHWVKAdLGkzkbmnETnG74+//gEQIdKh8SaNKcRVoEWhwNJ/zQw+JVSBYSY9hMTC0CbEHQI9AkNIkQ2Oq8TdwIlSJPPlI/lwpEO/HRNMOkwDmgxY9+9TGA72by0SnIlQnY+FZpxJaQ+nszrAOsD1swtfVFtCyhw/rgWokk8Q6lep/X7mWI2xQbMlQF+go1I2jHL6vCFRp+BR4q7P1XkTljApLKve2Axz7CXYcFbpDzUCV8BFrVXyuF/ZySC1KTQWaEdhgzJh737IDMK6UUKtSN5Uy8XlnWhXBeihSsrF1AQiHa4vAwBKWNtoUop04gzOtimB74aDW24bD1UVgYcnAwDrrkjND1O839rOohO5P/oHrYfwTdzAK6N1ai/RV93byRT/LSuiXrCSaejXZ4Lib06X3nPXwsXpq73fCz5oS+qUpydWJfN/TP2tKCKYmcUCU2qjBvYeKiho1JcWN9Z5zVFKUwZJrKm3Gl9tB5Rv10JSUuveXraVZFJWw2N8nu/lQZAAFmpJ6JlMeBjwssHSpP0QlbW7sntHoUu9ejWhKQstabC0scsBCTUkKNNSDLqA8oFRTUpok1r/+7l+FICHdn8RRs9YxP+yydH/xkuwoHEfJLblld3H2xvX6oSx9AbyfhKG+CkEYl4eNi+qJZ7dx2vq6dx1mIUhomby8/dsFxfUGNVJulvPQUWYNFxUnuzQ3FyjGD1L0NZouj96Sto/KaeKjbVxWnLTwi5IErea+/cuVm9YrK2QipmvLhLYXsQEeVoM3rfh7COa7FoRxQ7+MSx7h0jbPAs+qGMS2eY95/9uqVfQyjSC9Gep2Yvd5HniEHWVaDvV9o3vVb5T7k8/BS1LtDnB0g7rUJ0sVTRv7e/KAVokiRE1cyNu+8vsbftVvFMiJ8ADC0lRhMR4Qvf58ouAV/UarZyonxKDErsznkbYppHcjfpVv8H0HWyb4pvB2/oCYlBhwcKg3FM5+xqxEj53IvbfhJx8AYVm7YYwC0TDWeX15GyBiy5bmoA992NaRBEhs2UKppPcd8V28UX6JN66+MvaE6IAI3VVsm00YTxYPgcmgdMO0mcbx9Xd801lkDhDc8SxrXOutbU94dJNij8ZHyYLlIVm+jrQ3svcNjTLWPYehmf060t1IL+2Fxbn3rWo7nyD9jXSZ1AyLC+7HnQCDAuFd5+Bp6IC9Dow30BZQWuRrWns8Ieqy6X6E42rF+oz5aPlkJcpRzcOtnMmTa/Ob1EKIXtuWRF+XoztajmSAiLIIn8Kp0ajVdD2ITLdKceJRvCotOpJAw+BLOHw3pFbTO8AwMrujrYc88ILyom3zLXGJEyLpVRRhOSRl78hUtcZYxpveGg44RUpnr6O2VasPBZmLPKu83KsmWWDbRnkNMe41oFNgsup2W1PMWF++yPPKi31XlK7RyYyp4zVgUGAIOG+0ntGPpM4aMAKw9yvjo8DExx62BkwK9DnAhKeWjC77D5iB1/cvGQlLo4J4EVgA6GDTbtUTZejQsrqqwUp6RIRlEdfYLbP/iASG4snjhKc2XA2LAVaJYCpdBykdS1x1ncL+eyaHRGzeYWMMY878C/GTioFb+/U/l29mnB2jD2s4Uk6W+AOPf6vfeGzutwi0CoxDRUWx2Q91N4tAp8DQRd1ZhOd+zHKvAb0CfciDtLlehQ5+wwBAg7bSuvuMGc81YFRg79/tONjq7Np280nIIMB+gl5S0OzHoVGLPFh9rrfokiWUBu3jIq8ozxYQMuRWRxL3eQRW0mP7l5ChegxxjAwtAgmBpDKB7P3+z0dgJHfHEpl9ZE6WNDkEBgC2BeNef8CJ6EBGYer84WqEdS9Mh0wCWIiQfguuNd3I4QxrAXsXD0Y+DesuQXSGdYC1fXYEH7LGhIklTmQHgu039MgDj9vVMpYzbACsCdA4yQXfrlr5DAvvvxTY0V0o9pFl2aAmoBLqDjw1ZbI/o2al5gRpKptakQkdLtoC1D60hRsMmzYa63DNEthX7jdt3gJb53x7uGYJTCyJysxLm5SSx7DzDhZMLEk/U+mRQTmPko4dLJhYH+MkU4FSa/Lwiv0oEPB0f3LtTvW7RmXYlKMETi323F2uvvrQIW2OsjfKY4SdUktlvb+LjyIBRknmO0mRYBgHfs1R/kY5aXeSWALh2lRit4MKioqoEnC2FW1vPVVUVG/7JnPj7NgPY45KioIbaj0aHh2Y5qSsJMIcjjMt/bC1PIuijFORAJnszOYLJF3qPabGGQdT6nGXtn4r0uVuZTVwsuFq07H3FUnX+91c4wpktKJ7t7XcyQHKAyrW84Fen+prbr/oJ3EExKWW+d5kkbIkvMD7Qyrt6Iq7OKs4SXfnIhUhD3XMEs7dOCdDTvlUtGWs31+jeaUljKunNm88b+OC4uKgdGrB4LiNi4qTLYM3Mm+iHaP+S7ikuD5ISzry0Oz6/zW3zzgCcWkb6RQnR9vX5L7gCLs85OqQvwcavyf3mdelBxIAKWbi4H/P7l+8fonj7H51k2jiznzP7jNPVLRBsmSxnDyfAx6m901sHbVfX8dbOt7ppxTDeTuJWr6l452BO2aWzhRhHAe+TLRKFKWVDIxtgtl48oxOiRJJuNLxbQT6OOF5mej15xNRL7/m0sSB5YQYlCiqFZk8F/0wOnAZGBXYNXncMs7l+HOycJICI2bjQ2tjYk++c1ai6D69NDesR1w4WTtFiX3ym8RCXZi4Y6/5eEHaYYRKiWcLnNRm7pYPXAzfhHHm5GWTBSS2PnCu/pR0ZNgOkJA/99TGCr8+5Gv+POb7k/2Z1l31ffm85s8vUq9z5bn3PrbqsyOkvZEhJBxvltq8dXeCdDfSd6GNRPxbZ/sTor+JvY/6tcpLTmWYMrVODEr0qr4owdjJ1eM1f85AijhIpI2r8CfEdBOrU6hpjqsOLR99aV2IXQDteDZmGud+rBOLEmWLdNyCOZ+ucDWZuyXxdSWLwUySgu/5c0EOnQqq516OXjap1VgPk0Ri3TEP1w85QEJKPvqWDUW/zCLSTvLdDv5c5hNsHvPTazhSTpHYdZaqA8rjqbAGtArMvRumKBLb+vbbQPimSW5okffbuqeffGWvwD4FmhsEG58fhUxrwKDAEEEFRKXNtLH7wAhAwj4A3tnws/8TJuX5jLXDPvrHPXINmAEoYl3u/eO9fSji14AFgL1rfuQnJDvGLhbXNdiJt0MjgPqax+TBIhFMxfejgIlt4GA+IIKteMnkccbbGRqnnH0jfsxPF4I/HIWrXzm4bRxwsihhk3QQ9WNTyEWgVWDq08hYXGzqLXCI5a8BnQJD9qisLeWRyFgDegV6OZ3F/6Q2HS9vAwMAu06C/1nOeaxjXwNGBd51+5LSjPln/50k4OExmtvc2rj/SjLwUIOWY1NxbOMK4Pokrssny/Vanmh/TYON3H0FLmBxfryrLQIJgVAVn3zIo4u4CAQrsXIp7wMmaLIXzvLJ1sEf7o/VmtTZMyYBLEjE+RruGmLbcd43iFk+2fbaGb0P+VI3islOO8snM9ZayLy43MIn6Yzqgdrv1ZxOTq2vrytn2ABYEyFA6JKrW2U8/A2iYkuvsols+e0M82fUBFSCDnY22zjO0t6hZqXmjGXsufWn8od2UIDa+3Ozob3vddNUMiP7+EoWXLcJuv4UC9Z1F9xHvkYYM4brd7BgXUm6D0kqOeRxFOpv7Mecb3b3J/+3W9/LUHY4pBwPOV9rijOTtf4x53uhepCCp7Lm7NIYB5+i9Ht5jx22/XMG7RzlFSXJCO6u7duh6HdI4Sb1/lZR2sIGv/n2oqKw13TLkIyzyOaopCgPfabrK0gTx/NjypdJfdQ6exQtT5C2VlVRlIWp7XXzrxvz3lORrvReRM9R7WqMaUz5zlm62rsDwgFt20qwY95iWWAZrAyvJ9zQ+PI363uilu5PMR0zTihdYymlqy8uh7ppQuLkJ/ueqCWwRm4FWBwdPJy7aX2QCPelbj1XTdmleaVJAE7itzbFSQDge56WZR0O87TZlqEP9xouKk6qD2Xzqe7UZEv8nqclMCvJ0xZjRynSEi4DzkCelnIwY2+DJVxRXK9Ylfo7P9uKXvK0hGNUxFjrq/Xbq5jUKmyBFvo88Gn725JaRZ+MEGT4maPJyntLqwZ7f/KjplZA5A9wuuz6Zpe50Ktdf9/vb29p1WBBmpI4UF3PwLFcbJXolChNfWTidYwPRdYq0SuRoEjHhmZxBzydGnKnabnAspRHom2VGJXYnWu+ILmcxoaHq8SkxIShmFiin1jKW1qViRF6OFVieqRKVolFiQHTqi63iXMnb4YMIO1YneQnzv9rWlVqzjGt6nOiSYjiNa0qSAxrVWQeNeq/kK9J0Osk4U/izlLlkXxZ5tFN6mPgkkzdi26yc78mQS9kSHi21Et0mFzNX5OgCVv0Bgnx5dml7DULmixoxmQ8cKvNKnSCDIrsK4gnNZtRjbsMjAqUU/ryzlOoV6F89G7STbQFyoiTozD2f1omZiX2JriWG7VNkiavWVAG9izHxfNh4pi8Z0ETDgfr/drzmOdfRxIgCbOgberG0dcmNZs+l0dSls1x78RQcTcx8P/10rZcGjX4u215bhoRjeIs40g5BUex2tgSjAdAeLC7Co+3svqeVSi4zINQYEQpnq3HPxZULQO9AkPG9l+lGjfkaJeBAYBdESON6tox6LaBUYG+h6r4EPQE7UiWeQl4MQwJS4O97peBGYBuKNE1FlvTLwMLAFEX0v6ZO1k1BGbizZAoCgGLQdeJYCmPXugtOGAXXsvHJt6sK5U/HHhoch2/jQNOkuQd33PzFQjZ5lnlRenRyiq87A1k2pZ5TnlBJtz0tj3eLhnyxx7ekXOBGdLmFOsv6PZfSFCgk1npsmZMxGraZWAEIE6vz23rctu4BDjC4fU2E1z+lnlZeXdmjJuH1I3Q77+QArwEs+br1z16wWQQaBUYW6+egy9MYCM2YofskhIEWz4BJ7lAUzz84dCVM6CM2GOSwooINzNLgcPQwnaPapV6KxC4Y5qpJ9X7DzrJBDI1ZQjHW58DhOP3oPBr3jolnkfU6p7ed9tJHpCpUYosWDFhizv8TSMgCeLi1vnWptadUZNSQ4ax65Stcz+nz5qB2puochTEeDNx9iY5QKH2NgkXNLXRB4dGRWBVoTdxZhmYN2HiVc3SgII1EaMg5AhUsp+wH/N13M3h7l5RHy9h3m+FQzfB90G7XgRvaeKqfMzXMUqKsbOV7n14619BuRvl5HDgainX7tGUd1D6Evs8lT4Nt4kY7Q4qKErq1aRlaRgKgldQUVG9cF1EEoNeegWVFNXLmbgVmstw+14h6WpyfXIKe9vVLZwY08eEnTSisBDlbBMdQIq0tEJ1qd+1kDJJ3WIMZIlFwLIQK73GD+fXX+trki3G+1NGXic3WaRfk2zMkrje5elTDrFARGEVZ2+cK9iaOMXq8Ra3i3OKk04bnIxPLRnzvja+ptmkV4MZ02xucon7mmZjXK9flArBeg7GtIvTF3qLliRqSwWi1au4pLje6linj5ttXFac5GF6mq1uQ5l2ceXG9eidpNnqDgIdP5aXsdpELw+U8kVvzc/2lyU1i+7XRxlThsXen3CvxYb2/pQriImQQN3A0Q3qWcDM2wu1nrX2gKiPZkOBrFjIQ9/RDaJTYp8bECUrZifXhNdiQ8vd5fSt1N3AT7bk11pD6R8MB0Yy0UA95AYxKjENaTFbXcN4QkxKjMOEQGexwnKDmJWI012rO1jyxGV6rTaU3QpHN9ucJnvNe7XhkHCS2c1NEnGEVKMhl7HasOWw3v3rtxxW8Pn+5D2nukSTC9tbDotJXh6RbzDWG1D27BDtTXQBrLCY5Cdbz1sGi4lDx4nkCceM7RC9EnuxKncmaTe/I2JQorQQ4Y4wNNTu7xCjEnsrQJ5mYgtMsNohJl01GZoL+ljSz9GrhmWYnMbefEup+qNHLEqM2ga3+mJp4uS/JrA6UQsDq1HTZC97zV8JUdpmXSFC3yaueDy3LCIn9XFU4A9HoVrjEtrGEXBMn6jG2ubyPGPWiFaJWV6z5CxNeBwxa0CnwIQ3sJZuCuPFfg3oFRjFkxUpS24NV/d/xKDAkLBbfbSt5d42LwLPQd1wa6FEY6R/DZgU6AsWyIVUj9T9XzADTxR8nG4KbfrncPqtAWE5e4lY8ZxcW4/o0ZYX1zXYiZccoPSYNfTIy34hfqw9c/iHr0L1oCplG0fKyWEYZhGyH+OJa0CrwIh3groZhjGSvMZzygu9lIJdslb0Gbd5XnleTlEnkw5sOXnAoEDXFRYiVSlmzDatASMA++Z/peHbGkxum5eA19scX4VY8RFVWcNlwOG09VyaajZs84ry7r6oXHnWJFNpf0UbBBIMeG3hu/K6Yia5HHZA+p8rlpqrm53SGZMAZmxW1aa7wko2n2HhGYuzkMwpV0+KcEZ1Ss29qxUf0LH1Hjx8Vq/UVDCbk1tr5nL4rAGo0ihVhlLWY+Z9T5vkcxgaZW4wjz0yJc8cikk+R6huqJKvXstk+U/yOUIli65FW1jOnlGLUkPC0aTVZUvHS4DAtEK/unOpmxvKWj5hP2ZertcSYLpd8dgxZoVDN8H3wFHhEU8tx+R3UFZRokVjiw8px4nb+DHzwihR13Bgtvr1abL1fsy8MMo8xs/htJsVVLhRTnKHUaqSKMDsuRVUVJToKXv3t9bxcesN6hroCot7hmaAxmorKO3u4yx2e7fepske9TH1IpPwEtY3tboEn7aWqK51W2DnIJto5p1/r0nK96f8G9XnMG6XRcqSQBd3O4sWVcurNKs0C5IHKrZuZqHs4pzi5HAQg4x5Ztvfi5K4uVJBPXXTk72vju9FSRyIypDeCC0JlrafLipOLjQ8WS60Bufvzun3oqSMVsWmkOoW67dxutruGie+HNVNaeKbfi9KyljjxGUH0ZQx07S2itUk7uaR3KQilzTqoH7xXvMb/v7scy0yjInewJHijBbrVa83+jFRvQq0N9B6OBZsPbrSTzoAOgVaTK/l0qY+0wFRfzw7vJRsWiFbPCAGfR3SS5x9h1wdhzFLtErU7OQ9K1EGead4tnB0UOzYTDFVp3ayB76mNzxvVZje8EOr8w1iASJUvJMnH8bc5/L6Vnu55y+y4Ll1cXv/2q+5iMup40+SOr6ZD/+aiyhcCR81F0GxmFHltUy0N7ELbNhmTKs1yOkEqV/39juum1zrGx/jCdHfRJugAX80FEcFwzIxKNFjMqKJBd8PvtdkBBOxmiYESye4pGtGAhVXRC+0ucP26LVkJYrA67qwB+vj5Jb2mooQIulUHd9m/NHRayE1mJ6r5f5hNox3aYdE9544sB7+sGYrPq67azgCjumdxT3rrVpprtsmWiXmXmV+3Z1zcAbmli0DnQKT1DBw4sCbgE3XloHw20VJf0qFKbXZDfvvJCgwZBjSUU+X1g0ibgMjAIcxt4mqH5H3v3JSYJdCyiz3ZxBzjZeBJ5UvTiacuzAeLGvAAkC5ujqZoVAetvwF+CHOn3mg4T1u0bpizJg8XoMpJopkVgIHyRioGV7m2ZvnxWMSGVFpki6/zXM3zw2JK3MNkNvneeXJxn9ZX8z2Z//LhhvWNVNXFD21STN5HxcVF6D0I5bqvtL+q02Kc1D6EYNx46G0hsuKsxDcj5HSGDpewxXFEdRp1APYjrfPX7jtULyjEka91AZzCMWLp5n5IulCGO9SG1gMxXt1DuttMqYxvr8BxUh8gr4ldeuKjzDsBhUj8djJ2qam+kyHvytG4vt86WsxtPEG7xvFWiS+T025wmBN7D1mYzaoGImXuy9H4q2pz+oPqRCJD72lxPWoVHe2cvirDoH4grfB1qvXv/6sHyPmJd2fvJPEemjFssMh5fRyYX6kptPxeQdlb1Svcs0iDqyXPrP1VE5Roszh4Fyq5+DE9foYMWeUNBjlSFpsUQK/hQo36r7gcalJrC6rdzuoqCiRfnPE3BYqkx32Y8ScUXGIdoU2t33rC2ZFBTO0y8ll4gx9jJgzSnIeQXpLkBkvw79Q36LcweinHE2ljGWcSyy6KV5aAnCOKPoMzRpWaVZpcpBnXhQm51GCuIRzipMsPZ9uMSQ/Oc++RbkZ5yRPm3j1hyY+3P7pguKw4zFFG9zE4fsW5RacrDfWPbkW1dmFJYW5jJVEvr3X7RWXAWcwxh1dGmMvS7iiOCmW5hi3t3WZvK6S10ZU4f7sOj4/OQBeG1EF6OBXuJAqxB93wLM3rzcHSeyWpJbzTAdEp8T+fsV7aP0YT35Cr8Qu4Wf1vYt5DHKvEvV1dBmtaA1smJ1br42oAs4Lkq6DhX7yATApUKq1RF1K3o1x+FViVqIkkvkWGKikySX/tQ8V68UKRKRDokdk/xdxK3zs28SOEk54ED6WBmFZ+tWbdPiIED+OMCG3ZJMPiRA+JqjMSy1Y4o+IGD72ED72tkxuwSvhY6fh41jPlIn3vhA+JpBuhurI/xy9awwgwxwC74kmgcWVADKMpPH1cHk/DHbjx62j3iBW8Uj0r9FengTa/1yJ8jYyZ7j/ruEIOGSw/YHP2Y851DWiVWK/TIsALQRzAoSvmgQosxecj6Nrswb0Coy9+oqXUDp7wgBAybrzzl18Gd2lNV5UXuiFUlzZldsYlf1vnABoYZJYbvmvso3LivM9byNNiQYv/QvtU1w2xvuTLxDt3j1oh9dgdGNiwkrb6ts89E5rPHvzgjTvlVbTpf7HXZi7Yd7gcVwvOG5sDrXG8zfP9el91/cPhsaM4RouKE5kPI5Dq9WfMfuvQt+olXbt3NWujYYbIu5ruKQ4bBeXWjRxOIPXcFlxohK99MKh9TUf6hx+4SZxVMuyP/lz7c1tnoLPZ0wCGGEcyMUUH7XoG1gL2DvLx4NIS6vmiWdY+OpZXnrk24qpx122Z1QPVAs14I7aOJ90+BMEpaZE0O7ON7kfHT5rBKrDoibv0iPrvkFNSo04udv61kU8pTNqBqqH/nzVIlIaNau/qJ+inqy35k9u/BRMGS+AUw7dhK6IZqGjr3egd7v8FPQUklg4t4QorZRpi+SUZAhinqUVWZWyg/I3qus4WRjlbILxYyukoKTeU6WPLjCjez5FRUUZ7Ing6xYzOZc+hTwZ5YY8ZqChq+cKKitKEsosIvPJPhoD/EJ9jVOKvMRp199I0Ot4lUU35W4jxE24gwmjQmIJp/0svVzTM68Km9LY9WEJp9/Ri+yHo/3ZNPl43MV5xRmHs9xTNe7t1xBumusdzDgVEd9djK9BSmbJXiFz3IPJo2pjCZcUJ7WPHKb0IT4K95ZwWXFyfRaratL719/tJa5oOYMWuszHXsGhEg9wpDi5jGf+D9m5ySXjJbIojyZNeJJkYeo3LvaA6JSY8JWE2Go93QERfr6ABRGhrRkXDohBiQ4ba3vjcfTABjECkUCNRFQv+TkfEJMSLba4b6XhR2sxK7AP+pTet3XxvN/b3uKA0esn63tbUe/7uf8WB2SSl8BLksk3KYw9LZaR9ka6AnHA+jOmNDlG3gKBgvQYCEypTA65t0AgEy1O30q2ZVXtCTEoEZsax9SWYzohRiVKCsexE1Lftjt6NUmJva0xa9scvUdg3gKBAjTQlN1X93E8WwISw3vcjsts5A+7buXRdXkNR8DpkzUytz8LrbfTNtAqsHho9+fa7I9RlbUGdArMsudw2M61C+awd68BvQKTxGJ4WJ91j0zYGg9eRS8/5TYr1Lo4HzxgVGCQGkcvoelM4769BkwAFAWRHFzOw5yz77yPkbZwf7IozZtH2m8NRjcmZsxfZ1f3mbiNszcu9Hlg7HzV+8woUVnjuZvnCZNp1/Btt/98/ua5AHtgaTUyxW7j9CX0NpYca7MuwujVZVy8cTZBkiGluvvl/XebFBdQAtmSDOn1XUyCY65n6qOKDIMb+4BsMAlgXazJ19hW2+fsGdUC1XhwZF0shsZelxtYp9gi1ix6nro7DP1UN6BeoRmVTza1Kch0+K4CUHtDem4N3uZ7xzMovPlUMDKW6i0fZmjvURNQJbXBp0KkVlzw+qwfY1gPD7T1Dhpb/Uwx6nj2qRccHTDNFyG3g1KHs88XzSxhSOUhS5yi1NH0omtjdzi3SVx7T6UeZlfms6qgzUKnsENSz9L3AWaCaiP58g5KXUpPKOMJ9egcr2FTlPqSfSoii+186yDhX5fU18jT9b34k0Oj3piJk/E18sQsG3XgbHUxShpbCS7h7I3z0mmH23kanx5V6ks4p7heucdlpVdB1zbOK05WB8cTSt2GfvIuLShNbgjSoKHlpdP2W42KE4eFg0/R2ji2jljC6fLoRe8ihm1Ts9/38Z1wUWy3QHOCw3BRgq3Ite9rwgHxW7goBetHSdYqEcNFWJsfQ06TW9ZmuCi2Ng5Hzwjhon6L4XBRymbMkK0Sv4aLUoyjbmyViOGigOGiGB99g38RX6M71+bCn9xO29WbVsgnPLpJwWIBVnUo08Tze43uZO6BGvVdl2jCGNxZJrqb6LpyxXNjLz8Gd5aJXokWJranNoetHH3rcBNtUmlIagJue/SlowJ73R7vle4xRGyZmJTYO/5J59Y4ZikjEuN7KKbgH+5dlx6d59dwBBzqynC+Lbg82t8a0CqwiNQh8qDYNs96SEyvAZ0Cs9MOgtZH88ikrfG88tJQ2ONCDKNUZA0YFBg9dIa2ZMo4vmmNF4EnhzNHYq56kJVX8iFyUq61VzR5GFz1LIdo5RqMbkwcZnTUy6VdWoAfQifM65eEII26fViyjw+hE+b5gKETajqWwb9f4/mb5zKOcDU2PWpX1nhBebIHXuWjubg0dnNcw8Ub14d3OB5NWa8g+fVtTIMdGf5cP2fTpb7bxzTYkWUouF4s65HXZkrZM6wFrPFJj1KXU1vfh0/rFFtEzZ549kAT3L9vOtNwxyXeKtjbv7RWlOTOqAGoHmal2xzrKRgOf9io1CQlOTyuKrXWTq970MfARHb3J2sX6v4zNuGbckg5ovliMbaLrSI176B03HHoKnsZslAXjd/6dvq9glS0csPc6ss9QrVTlL9RXfsvl7KWlqQdUlDSIAZIl5Bt61ePivLYRKuenY9b8S/U93BCuT/5Xtcq8XPeZZGyxOUtXn76MjHS7+EEFkoFbPJYWsq17OLcjfNBa72taZ1MB83bEs0rTZr2XtdNW09d+742vkcTWH5FMAK0Ln8as8tLuKg4Myzcpj2xry/i7fovlV339T+HNFsmb9d/xnW5qEQiyf2cAK0CCVtvFk95jNuuErX2hYYQSk7JjOmyVSL8ehEqDyjWDb25vPvEoERR9vPgF9eme5VyQIxK9DAVg2x5jgL9Rdy6q+dW9pPjCQ/u6g5F+Y05OV4X7uo9W80TJ11T4IUTJF7W4VJTL3FljFEsE+Gy3vX+19261F/y/eDevKzHeiZROgHCZT1AHjIkZwYXJSEwvd2sy0Ur98KpC9uY8Zhbg9GNyf0wkebDbRBP2ubZm9erfni/aYW5w6V6DecU1+eSsZ1E60dfao3nb14QmaV0OIyts8k2Ltw4Hy2WfubWUCjMeR9HaBsLf3jj8WkcgbWGI+UkD+enrXuCH2v914DwYKFnFzlpQ03EnLeBToG9YzUHQW2mMG4Ia0APQImgc1VXvc09XMo1YFBgb+7McxJMa9QWX1/K5OrquwC8ew6+XrfsmDjYYBLAnIecaJtb7EZ3aQNrAdsnayWZyPqcCLyBdYA1ASYiOldf3OiNbWDhFy1dzBp5gwxl7Mq+QQ1KzRHmLDuT3SPv+Yv66ZqZrgJG/uSbhQuPyu4ph25ClFQzXzOjr2to75HsjQqitOdDwGWbRs3AFOUU1VtaRK7XD3Fiz5+umYKSCBRH8Oreb8eei1NUuFF9l+F7ZjEmj1mHX6hvl8N46Rr5k3Q+9i6KbkiQUkq+G9bbV/7JuzSrNAPVONbSs0vbEs7duLvIX6IPZiy1W6Lp73U3NZKq0TaA2e7iguJ6kQ/fSlrNd3n9rm+Xuavwiz8l/mwec7RXcaS4PkEh8Wx2Hyb729ttjondxZcheKaMrfNXiU6/rJzn7OGXFub1Jz+iV2LSGSZUyDx6iqwC4X30CqXIxU5kJ8S3q1e6jjL+5H/LBTeWzC7z6CaFLoKX2UwxT9zAt6sXI7vpxd4/7tHadBnpFDkMcTC2TTErJ0h/I50IA69GJcU4M8a0l4nhJt66+qstZKvywHeTEZhfk5BG2lDfsiAXicoQjFqjkWKyRNszyytMfozMWgNaBaYAASlrW3wr7AOdAmOA+5KttvLYxdaAXoH9PJeeva1n4RC7/AJcu+HU39ONPSDXcMMNx+Mp0MaiDe7eGhAeLMoNkXcb2yqX9nnDBQeLglyTXA9WtwaEC44DC6E2qntsdfKLN7mOBKnRik5H1RJNXvLkOiKwXnWTueNZO6Hj4aNawHahwrXbupSLmazxyXVEsGRhgolLLZr7btyT64hgTZcZcK9CVy+45nVBfb45lPuTYwPJufGMmXLoJkSHjklo2+LWE9mbFErGDdEZPybFpyinqIBSo9JOp7z1/byiuqJRut9XR9O+or5OGOJM/S1LoBTrfYbyLouUJd04i6jx6p13CCYs4eyNc3J74GKlmJ0fGxUt4fQ79lYnWfIj1b/cfjivNAwbkAst1va6znYc9NgaEgZ7gAMHPRLocut9wk/e7YKDDj0M6j4VZuf5goMOfmBLz6Wfk9/wi39eHddHcvoX8NWbvnJB/Mn2UUIYW8st8+gm9fx5FrV6/vEnQHsDgx1aWdbfYXJkvvrSmTOJBdyiq/ogHP2M/ka6AGPSU4lxjFsWJJaJ6xvgDzvV+XHsrOFIOVkC+zzoup6Oj/mpa0CrwCT9GHhehTf20VpjDegUGId5FebqyDDnffRU2Zs0d3LXWWoz/dI2jpSTKaDOvulUh5LhNaBVYJQTk3MjqckwBnHIGtApMPT5HKKZfsyW+MWbepYR/lyxLm8f3YE3mASw3iryWpOBcnw0tNzAWsD2dlWJTdzEUbywQXVA7cOgksj0Wlbn9WE/eoDXG0q6Ik1LNg1ygymHbkLP0rGEJLfp1M7voOz/39m5JcsOglB0RrcEXziYM/9pXA0q2EmIyY/+dK1Kd2xFwb0F5ZVPKGLd0/3DNyQvJKdPt4AwrTnxE+o+bMPZct4w1I01vkXBhAy9nW5i1uTu3sLkiWbM1u80/worb+G84KIWYvXUjMYtmiWsfEyg3Pb9ef2qjj7gYIKwH2TxSHP1pcIHHgrPaz9nn/BHBWuX6IXYLzF3rz+MP9UiJ6IZEhVpe22Hj2tYuc2DSUpBm/Eml8vDazGDosLCHV574YTwY8a0jfSCHAsw76ejW7TAwCniUct/H8FASKo79hLNA0Gvl5s4EM7IDHJxVUk62tikodAIdfiSoe6VdIH0HfAq3ICh7zITg9S0uONrGgiGtL1rnZVTXGaZTSAKMC+VGCXmtFRpnYEP0QHrQoyOw7f6it1HJijY0KThSD01ebsYv2FRYf2QuuNbTO0koFjUa7tvabtvUV6Lqp45MAnDcYQL59peLoU3JBRSv4HHJdCpaZhHc7jcrr2swSpqs66dkuu6/D0WCKungUsfeLg4B+zRUGjdhpVV4CLWsWH/L0xvXJot7xKaBzzhBxxMEGb1JrhKPnwAogD7RRMu/OZ7TubMZy1vFHC2PX/2k2LY58EkpaLyKk1Lz9vf2VrdmBiHbiPXsbQjTv2MoInw4P5YVMdnuDEuQ3CPBoIpwxyC6xczrc6Kd8DrtYNUx0PG06IksokD4VAvl+DFI4CLD8CHuT5zCUfveKcZcKkbfsMEBYv9OGsc9EBal5AT9mpWJvSzZaHeFrtkeMOBSRgpqcKiXnF1kT+T7p1/YLY9P0huna22WEIJ/a4Ma2bwRQS0cG8mv7qToYdh/Dz5kTJFxdL8FbL5gOZcVUS6hX+/RKv99D4PJmmUXQ2hzrjWaIK2qj02Fm+mFqor0nLV6g53NRWcfWrRFb8ckp9xj//cpLrjIkXLDpL5iNeubVI+yp8+jtstzK4jVt3eU7JR1jhOMFv29KzvdA1tTzhr1PG1Ym67imiJR1bm7z8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Cohort Month\" = _t, #\"Cohort Label\" = _t, #\"Channel\" = _t, #\"Channel Type\" = _t, #\"Month Index\" = _t, #\"Cohort Size\" = _t, #\"Customers Retained\" = _t, #\"Retention\" = _t, #\"Cohort Revenue\" = _t]),",
                "    #\"Typed\" = Table.TransformColumnTypes(Source,{{\"Cohort Month\", type date}, {\"Cohort Label\", type text}, {\"Channel\", type text}, {\"Channel Type\", type text}, {\"Month Index\", Int64.Type}, {\"Cohort Size\", Int64.Type}, {\"Customers Retained\", Int64.Type}, {\"Retention\", type number}, {\"Cohort Revenue\", type number}},\"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Acquisition\", \"Cohorts\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}
