{
  "name": "SemanticModel",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Social",
        "columns": [
          {
            "name": "Week",
            "dataType": "dateTime",
            "sourceColumn": "Week",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "Platform",
            "dataType": "string",
            "sourceColumn": "Platform",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Post Type",
            "dataType": "string",
            "sourceColumn": "Post Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Platform Group",
            "dataType": "string",
            "sourceColumn": "Platform Group",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Format Group",
            "dataType": "string",
            "sourceColumn": "Format Group",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Posts (raw)",
            "dataType": "int64",
            "sourceColumn": "Posts",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Impressions (raw)",
            "dataType": "int64",
            "sourceColumn": "Impressions",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Reach (raw)",
            "dataType": "int64",
            "sourceColumn": "Reach",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Engagements (raw)",
            "dataType": "int64",
            "sourceColumn": "Engagements",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Likes (raw)",
            "dataType": "int64",
            "sourceColumn": "Likes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Comments (raw)",
            "dataType": "int64",
            "sourceColumn": "Comments",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Shares (raw)",
            "dataType": "int64",
            "sourceColumn": "Shares",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Saves (raw)",
            "dataType": "int64",
            "sourceColumn": "Saves",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Link Clicks (raw)",
            "dataType": "int64",
            "sourceColumn": "Link Clicks",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Followers Gained (raw)",
            "dataType": "int64",
            "sourceColumn": "Followers Gained",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Followers Lost (raw)",
            "dataType": "int64",
            "sourceColumn": "Followers Lost",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Video Views (raw)",
            "dataType": "int64",
            "sourceColumn": "Video Views",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Mentions (raw)",
            "dataType": "int64",
            "sourceColumn": "Mentions",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Sentiment Pool",
            "dataType": "double",
            "sourceColumn": "Sentiment Pool",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "measures": [
          {
            "name": "Impressions",
            "expression": "SUM('Social'[Impressions (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Reach",
            "expression": "SUM('Social'[Reach (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Engagements",
            "expression": "SUM('Social'[Engagements (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Posts",
            "expression": "SUM('Social'[Posts (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Likes",
            "expression": "SUM('Social'[Likes (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Comments",
            "expression": "SUM('Social'[Comments (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Shares",
            "expression": "SUM('Social'[Shares (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Saves",
            "expression": "SUM('Social'[Saves (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Link Clicks",
            "expression": "SUM('Social'[Link Clicks (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Video Views",
            "expression": "SUM('Social'[Video Views (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Mentions",
            "expression": "SUM('Social'[Mentions (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Engagement Rate",
            "expression": "DIVIDE(SUM('Social'[Engagements (raw)]), SUM('Social'[Reach (raw)]))",
            "formatString": "0.00%",
            "displayFolder": "Measures"
          },
          {
            "name": "Engagements per Post",
            "expression": "DIVIDE(SUM('Social'[Engagements (raw)]), SUM('Social'[Posts (raw)]))",
            "formatString": "#,0.0",
            "displayFolder": "Measures"
          },
          {
            "name": "Amplification Rate",
            "expression": "DIVIDE(SUM('Social'[Shares (raw)]), SUM('Social'[Reach (raw)]))",
            "formatString": "0.00%",
            "displayFolder": "Measures"
          },
          {
            "name": "Conversation Rate",
            "expression": "DIVIDE(SUM('Social'[Comments (raw)]), SUM('Social'[Reach (raw)]))",
            "formatString": "0.00%",
            "displayFolder": "Measures"
          },
          {
            "name": "Save Rate",
            "expression": "DIVIDE(SUM('Social'[Saves (raw)]), SUM('Social'[Reach (raw)]))",
            "formatString": "0.00%",
            "displayFolder": "Measures"
          },
          {
            "name": "Click Through Rate",
            "expression": "DIVIDE(SUM('Social'[Link Clicks (raw)]), SUM('Social'[Impressions (raw)]))",
            "formatString": "0.00%",
            "displayFolder": "Measures"
          },
          {
            "name": "View Rate",
            "expression": "DIVIDE(SUM('Social'[Video Views (raw)]), SUM('Social'[Impressions (raw)]))",
            "formatString": "0.0%",
            "displayFolder": "Measures"
          },
          {
            "name": "Frequency",
            "expression": "DIVIDE(SUM('Social'[Impressions (raw)]), SUM('Social'[Reach (raw)]))",
            "formatString": "#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "Followers Gained",
            "expression": "SUM('Social'[Followers Gained (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Followers Lost",
            "expression": "SUM('Social'[Followers Lost (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Net Follower Growth",
            "expression": "SUM('Social'[Followers Gained (raw)]) - SUM('Social'[Followers Lost (raw)])",
            "formatString": "#,0",
            "displayFolder": "Measures"
          },
          {
            "name": "Avg Sentiment",
            "expression": "DIVIDE(SUM('Social'[Sentiment Pool]), SUM('Social'[Mentions (raw)]))",
            "formatString": "#,0.00",
            "displayFolder": "Measures"
          },
          {
            "name": "Target Engagement Rate",
            "expression": "0.035",
            "formatString": "0.0%",
            "displayFolder": "Measures"
          }
        ],
        "partitions": [
          {
            "name": "Social",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"tL3LzmxLkpz3KkSPJIAnEffLmJAAAhxIYIOQQGhQJItkgewqobpaEt9eseKziMjIlcz/7FyLhcI++779j4yLm7u52b/9t3/njAu/Gdv+/3f//O/+5Z//8W9/+E9//cM/HN//hz/8pz+2//6bP/3jP/3hv7bv/Ou//eFvf/r37TvHH9F/fvvf7fhe/wts/8a7as3xHWNsye07wWZ//L5c3fGjGNu3PqTjWxP6bwzHr9ty/FQq7Zv+x2M9fpgfyf7d//XPP4T6L/7w17/80z/+8b/+crT8K9H5I8iaTP+nU3XHf0IKR5ixHr8zm/5llOMPFP6+Hn7/if63OH74sO5zrP/6P//lr3/7Z//mT//hj395Dnf8xKdoe1Q55NR/vsbAb3XGuP51uMLX0//TfvoI2eZi+cXjJ7M/viTHXxDbp9J/Z+B3+If5YZ3/9d/+8tf/9hz1//J//+c//sMf/9q//yFyx4dbMgtuUwhHxIk1DDYcfzCa4xdT3w++HF9r7T/v8vF789gUjg3j0iO9Wel/9ac//5c//od/+een/fu//fUv//GP//iPf/rLn3/3vji2Xa6l79loQuzhux5CqccfqrV/HX2Bbd/MfATG969n7t8eeXy0r/9TpE/b94tg+5Hxxfd/OiiQ5Pt/bN/YxGH7Z2/7L/gc+5fY95Gi7V+tt4+YPga779+XeH/PLu7fpOAjPzKpL2BIfWG9zX1L+P6tOWLz/Surpu9c3yM1fXOY5OenEMOjfTyf4v77P/5/f/t+gb2J/YZyxkbTQzs2g+vbtK+r7987fqsNtd9x/cvU2vavLdRHjecY//5P/+Xv//JfTiv7ek/8uLCOG7cd6x5bSj73qyuW3D//4FJfw1D7Rx4dC1dt/8XQz5qNPe7Ut3pMLtb+RVcuCPt2jVf8uh32yH/vFdFDa3dxv/NdC7J/+DZHAnPG9x/71Be2WH7Eiqd+jyT+RI3jpuDmy+kR39wU/8c/+5/+/v/909/+9se//s9Pl8W/+Muf/58//vUf26b4y59/5/boSxVyv+N8qv38JRa1f1Gxb+U6vnHl+Iv6V9H/yv6p9b2V3KP9zA+B7ov7Eu7vOX6RR6GEwgXRjlHfw30lne/PNY+y97wO/drre8b1w9m/gJpjv+xs6PvbPHL8KXSdwC+WuF8DbWcQoutJhO/PoePP5HGR9ZebZCP0q6/OJS7cxW9ut//zL//09//07/743z10v2NZ+zasOfUEor1nse/WVDhxpT8Jqe/HqA3So+PFdv3jL/2TaakIC95/oaU+b5b1f/3Dv//jv/tLP3Nr3/7DP/zTn//0t//2O1e0f8rJ6VIt/d9uN0dfPDe2pptZh+vZDSfQjTut/1R+eP8xwtcNu+L83Y+FzbnfQ9l7yw3rjiBqWe+v9WQWSpHmoxc5WJHd3i+36t8es6eQ50b99TV11rFqIXBR9YDL/Frq/KLYrl4XSM8reWgezn5eUF2zz+H9zku2B5McZ6G9rn1bxr5nybj62xbJJPoZc+Px8uNj54Fu78yjna1PD+6/+suf/9OFPKGnLLUYrinW0XPQ9W3ffuP098hJenrMvvRfJ2N8ZPdxSZ8SsF/90HtYKfc1a2e3JzVBV5EfEfaD43iqjm87/rHjnerPQov0U4TbYv7iISITLKkno6QsNQ+clceG7JsgjIXtGULKbIL+pT38y8ddbsGL/eIx3oIMWq7fL8akk+wMj2fHBz2w0F+f4riw5nPU/zQ3qI2P6D+H+jVe5Ic1kP/7dnHHfrz74xkBjKlHlXsyknqKWsAx/efrOke1n/mHLZ+DvQAYe2KaU+YOTyZH5VR9Wa2zqbInAy85NxfokMsy8CZETlyptR/H0gFSS7nTD6F/ixf5JhcST+9BrJldEk0/4ql/EcCG1LFudevSAhb0S4G0sMSHcedw7wGM/QaKGfhnqs4YqbTS8r5ixyfeb4UeNeh7xMkXF9yjfIzyGljsh6udLquiDNkgD7sFkUXuKS4Gktr+bJZxn5qRrITyaOv+Kdh7wGIxFF7aCpUeRrsQqCBxSxgzLwmf+1cIbOkfQKW+5B03TD+pbS98jvsaWGxpcuThManvwH4LuJ6Q8mKV8cHbvsN9eE6sLNl3PeV+5U602LMRE1KPKpl2pgAyjocz5QRY7FsgRD7+0n93S234cCpfXX8sGnTrGNh1uG6NORUSyn1gscPphln6bepKzKR/JVUqHXwRVll2KlxzXN+23weRguR8hD0FyHapvbuPbwOLlnvA9n3RXrTCYvW9mXrmXfPIrbNl5YG/I42gsMSz8sj1p1gv40XHW1W80lkAunc9vXa+ZxWcNO2cntPmnsw6Kmc9rFoNmYSlanNGjOVGxNhPWdC/nzKJDTszllFucAsQ9wdOX+K8jzuAaHnum7viBgjGW1Zy5pU2fNxU4VQN6XfsKC65CHoZ9wXXWX9S8iPUjzFeSHApEmWqBDmDXhPVcD9y2b4LUphR9lt4QYa+0Mk8/McgLyHFyjkiSWxZLjVt11euJNKdOPIvnmMSNcp1EWSUSdJ7/p7io5aPAV9OyluSBTwc3ZKRlatOruUnTzB6XVqKXMYdaMMjfgzxEpQ1fTNaP+rHYa5f/yZMPOvn4RkfOaWOeCoOlPuwLKcj913mqu0ZYjA8r3nglr4N/Mpoego2S962P8y1POKbD/quqlBLsiwgtu3GSO2HPLH/KLL/+un3hewEcNPhWX8SWhIZxl3g6sN9Tl7uAN4l9tNiTeSNtwAAO4F3nMDbjRUFRlZyrwLwNvvC9sv2OmikoGdSAlEVHp7MBZS4y3tIxM33U19c2y+tPK+m/hBX+9pMOgX6LWQslPmCIRcFhcfiec/7f1IvUoZ+Z7KBK7XLvlnTfou2nNt+jvR7vNivmJZwUO1ry1qSaqw68JWctVDIdobPIdBudMDe/kdHdyTxAJN/2fKo4YfYvwSMHLCWdQcuTlup/gF0PK9qFB7uGyPrHQAQl/EEmAXUzaP6c7R3NhizskBDYhJ6Vi2I7fwsWOp+5TJW6jtzlL5FysO5j6FeA4390mpBArCKYGLVpVZmF8BS8qTa0f+2nJ+v20Ln7GHSx2CvgsYKivW8+ibVXq0JPPee3kbwrCn9Z9dvXbpHYWQy1Relqpbm3cu1+xr2xWu3R57phNNzsb4M/Eq5aVWgxg/5UvSFHoE/wscYv8e1vKi5ciGo0U0y2vcFpeT12sY4KpsTYlFNzI/65gK7F9bmlPv5jgfm6M9rBRmGtl8d3eZC87NvScpH7Z126xwGmqch8m44fS35lSTxEv4lWNtfgBbxIMsocS0VpOKyUdYCVu2Hv4Hd/gLHnCZ9wpbJlsiEbR7hze69D9b2p67BcRCBoXpkPPkqGIUEvacIvZJk5k+ESaLpW+Ro0qWfgr2Ma1nCGEXuaN9hDxRqNVST+pXh1Hck/aXQn0YPt4Fb8UBUA36Y8FPs38NalQhNIdNJlOH6Zy70HSYhgWaeHRDNLVZKX2T3SG9ys5uSXuddpgvXjlH/eDPFokiaELlmHVVdbQ2/tgXPcsvjfZwFhLaHfTxHfAMS7zdEjP2mODr4/T4j162zZkfG1r+4/jyIpzB3ruchDuFjiFeBuA2WT7iQfPfjzQbgxg3jPHnvRvZox21Aa/fEp3sN8lrLFszYPv6eWXteAgsvol1hYRL7LEXdfqJS7+85QG7fn16VL6vdmj/HfAXoxpi4VwvlOD8LLTwIZn6jxHj8mHe4HzH/iiFPi3oB6kKaTP0YtM/VijU3OS5+lltAwx06RjDEDBNOxMP6j2FeqWn0a6d9tiRSTqVav9oJdfZ2zOyNh5nM2ERnN/FSv1Q2+it3HTqCRyKgpd0zXJvaAb7wYfaYQ7HzHrDsUtcrMWWVYfuhSq8d+1Ool/qNtnqnAlaGhlr5hxPlzWLZrh1T9FMG+FHfy0w2bf8dJT6C+xzthYaj2sb8U/5YZZbNeyXXdEKc5SJSIYtmCf28QiPfiwyYqS+zpYp/Ye+cQ/+24SgeDJdWu7JMR16FaJIx8H7tbDKqA0K1k/uXdL1/KZWCXdvC+RzvPQiyF4cCzLxQlJ2SiRRrxv1FR7z/AZaUdtPaEtApH6Z+jPM6QTWWTM3YQ45o+CysFNHyAzAvwKZfVzk+N0ipRMVH/Bzs5Z6j5/oKo8lVPAlCL+E0sGXm5RBBkSy+cYve179pnwb7h+5NDo9SPkZ+setYMk+tumCecmGYFU8qYqx0nt+Ns5QA1eLxZsvehs7ozB/EA4qx7Y6iwJ17pt2OHQx8V6jA859A0UxtaujtkD1TS9vg4FKutOWRw6f4L8EzGqQ2sxG8iaBxH7wVLOvLbMSqNyQ+Sbywfh777+RmfqIRm/CaPfSwb4NnVJhj/2fDAXV6rgpXzg7qd4cFcL/shOsrweVYNtQQfgr0MjQLJIy6ImxIkNEy2Tc5r4Mtl+m3w+10k5Jdo65DrhTdNenh00/BX2w5JvWRCwhnkAHr3m3Mqw+Z9fGsat65QtLDvAGZZThqdBoP0jSFL8ezTW7BhE7qa5mKX7wgJyIFqM7n/jWpUPHuzrgJl4UkZnXgBCntzZOuFibxj6uOHbHfarG+NqJeQ7yKy9oP6ZOEwmJC4fCjKEaeIJLg6XAB4+tr2eM1yOsN0oPjQy+EJpOFgFBtnXnCmGpJk8BuQx5wIlZT06zxZv8wn5f1CiozShoDvG9qApSR/ABgZcI1QJndKDThxFA7rehVLm0knWl5LpRKZlnEVBxYNqR5YUE+8WlSFq2GmVz6mBrcUFxuSKAvUrKQY7LSmwlzy6QMmnFJpadqdL8rXqmV/au/B5UdbCktR/CVYho1oapuWaUg21eU4gZPv5vUbzMJ7O29eiWnnWL9FpbBJipenHPD7EyietEy3H5SvOrMk2FNisPIXU6vI2I2fo71AihTtaAwUtAOPmiyQn46OLc8uHTpohr5kKx5VCOjhPRXc0pUnJl4zA//wzJfa+rloke8XQS0yqMGrkhnmKxhypSsMq2JhToaZV6o44x+672QrO1GRn0ECjUmqlqWeuqD5uXrEz4bT1aljndKAur/AGply1XHdGNRgVa8P8PMmM6hmfOZlYyVK1ktqQgdm6S+locrHyO/2IQKBoZBYIiUkoJfV65fNEsa6+m5DlYZR36UcI7xNpjDiKiDd5gaTggqIzBqUbnEWj4eyBXoRUaNB5Fh2TUBGY8+ep71p6Ob4+yn8C+hHOovll6M8xH2uvXMNlWxhMm8aa1W6jjcDzAC7Ry88qTz1rz2qHvM93agck1sYsOkCDyKxHiVHSWEVCepeRCctwT8GNj9KdJbxvDa/tTpCxGmRMuroVlzPRSySJUmWcbI7Pc6fq6QmrPbG7h+pPpT+BdH8QJbtr0RhBvBwZMhrinzvQG1RvH6dsn2tQ3R47wN5hznT93cRC3PMTVQQb/wcXrxpF9m4HTlnCREbc37by6Ug98+dHcRQVMo6CHUYsN8y9jGnlmY0WXXuCAjmnO8MZKQv5CuX2O8OOkUsqNNaiEtReJLdcxbhjk7BhrrL4ebUcLUz2+zyJtnBmOucE4ivQeNEBiRlsxKfg1DEQvqsJYNwadZvDtiDh9jvtI4If2tcCttcnkOrEK0oPmURhYOzWJ2hmpOE1S48NPaXoFk7cUlEQT/jRBX1TQ8zWyO7bkGRtXFfZce3ITJ+tGuzDaHkKneUyZgtHHuSchANizVhtHQc+AJ3+6n/DGPuUG2IbAFG87WYJVScuVTlJLc7DJ6tq3xz0cfiGkf+Tla95u5TLVcvc8WpqY6bNYkMKX51N9/z3AI7T34SpyyAt7cXtcQ96mFN5F+g8tWsO2KgkNtG/rqWzfSD2U9+TlGG2Oio8MwvhkdBzNz9Vj2KYU3wX4HzNzItI6oOh7zISXqxw0ogsfBty5amDzgM/iBLgE5lBay8pYhXhBIexE2Mti70L8AZm685DZ7XirrbOkLnEwQB7t/YRx3eteaJqP36zfhHNKGdgk/3uyK68DMCZiVlol45ddE3W/RkuOcB6DmZZl0cMqtBovNTCZgNjuGPIf6/cXg1EVvGJdz1t4CKl69elTzepEYZ7DaAHHs3ZURGNEWTfgY7BUcuQ5dajhcfFADFAt8AQbhJK5b6vgsrThiJQ8uzTHcR8rmB+GyfIz8Qk3MjZqYJbKUkp0XFhI51JnN+B7NsjpqYkm/8/hQ9szgHOd3eNeN4fIG9/jZGKgvUY2fUJcCOHvaTeWZjXQZ3S6BohjvwLtuyjs5VwLFrVioGGSrm9cwkZF4RVLWtA1XrB611JFCgg2UHdU+epi2tiNnP8X/LeB1I5FqiSx6Jr7FAwUwMrZps2EgGi6YA4lbtHVUH4OnifSSmXWdlqe/u9NugbxjRj83BMb0q2iWZN12yiTBWFk8Xa66MJ85RujrrpDwNtIrkNfN1ldNQNyj86DkwaCOAGeEak4UiRC0yPOXB5/cuoAmmIBd3fU83gb/HeCd91uQ6MxBufRziIByzFNvPU7mcwwb7qF0Eh/1zSpfRLzjnmivMAOWh/oMcik0fCPNMmb2kroSes5WL01PoEtM/DMkUTa+jeK9iHidwESIgpIN+JQnPZ8023lzsIgIo91YrBaiwKN8DvFLwDujrBSYfawpzvspwFNMG+uS142qWXydId0U4M5Rfg143YJeMVPzahcVDJYKxYfhPWr36D50kE6790nFsFqSerBdrfv4yznmL4CkW5O5bkxmu5nLlLip5PhJqnb7XC51f//4YUm/g5FzQaM3VJIjNDUVZMxs6DGUy6XF+Pa2P/tXU8zOlziH+W3ZwI1JvZYP9ESWtJpiRv8cy8ZfDfZZbigzcc7C7lmWdbfgRp7OFOyQGaPkDSnUa8TiSffR91Q7A2Cyf1Z8BIodFOD8OdJruLFWaSc6JYWZkmCM4EYmi1UsYjaTFCDMytaiWdYTSLDuNuBos0h/ZCwN8YJgXdC0R6riXFNYUhIFK1EomJwm6+mFUuwHMWWf03sX+5fIERZtW17xLNsSoonC8ARlZYBaoUoi5GjLTAvspE3AEmup2F5JVrz3YEfIGixUbIeNHdL/I7Z4X7pahiqotMnM8+CbhvZfkyzr7sSNnfrp0JtJBpKPc17arnaqZ0omKbs55KTVnUKg3GkP+3lRLwNHUqRUg0SIEPkpRgkU4r896S5sD9VHSRvTExQ+VEPdpouRP4Z+EZEVdBCP/p4mC/sFFmYmsDS/eDrK8xBGpXv9KG9ivAuRdaBaamDMtYFziZ4EZqR9pocaI+1QTqGXTKF0VQ0DBZolKB7JHTH3yy4Fegr/CiBjIZPkjF0pmRJRS8XE9+G/USwB3QJB//Gz5ccchJkjns76V6xu3e2IzCEmEqdgMAey7+0yuB+MGyCuBZ3UPlfJDxWo+lOglwGZJFqYvbGp3ctkq9CHs1lvdID0TOsXCpgXT0RpGiMKLnA/vn+r74JkWYK8U5Ss37WUVJf4gJ+E42pG/8yOp0OyS48Sz2HeAMiIzDPg3dIJqW8zXhCR3aSSnpg/oWjjoa70L6UKy9WYx4+OnPdNvDcAMlqQlhlzX6knolTqaTzOJaTg2A9b3VVe9GA/av4Y4wVEBkNdd5hFJBqlVSIPc+iYFqSZ2jQTikO1tA8fPgZ5DZDxFhV4Ee0i9aouQlJ0tCdimdRgZGBE3+/PL7qBtdbVCGoJsP+8slcQmS06IFBOAF5PYi/+XWdv5Lz9omu7036O7wokCxp4UofhSZofnj1X1+T7SPstbWJJVWhiFyA4pwcXC8u8YTmI+i1WIMTKNNYuTp5EyZtcuHWoHlL5eJnSbbHWW+AZz+HRKuVFrYgp8nS1dCFPYEbWFRMZRV2WDRPqSgfE1H0y502s3wI0idh7aSlminAtUUErXq26frLpPfUzX6jCko/PUpyT5OrHQC9gM2oFhcaX97lqGiRK/xXWmotSWGYta78gVGRMYl6ppgwNAduDmnfi2rvQv23qBTr7VSponiHdUKD1AC1DWk9/4GEKbhl31LkjMkLLb/bufbAsmSx1NK8eIjMJZoop60nKMxckSRjVub5LWiZe48cwr7fzkqPX4UvV26BaPKQTdfLqzKdQ4i6T124mk6Y+QvoY7FVUBhZzWcykQDk4KL2iAem5vCSkE7BMmeVFCl95aC/SmXztQtp6FyKjRgfhwAUjoSzeKDsn4sMUJuk3npTON2GSsk8HKcbbemS0cU1mDrK2le1B1siblgIAppp+7GpBKdL0P5c9ArweKk5WJQoimJfkUn3UT+FfQmT9oFSbJbQ/OKEFrnvbwNTtBrkqi2PFa6EBGDdXn3Ff8s6yD70o7NsQGVMiFr5yKKavY6EhwpOXxhOc6swbyHGWjwvZu3utiNt6Pyazqumi9mRcQVmchMdSCBEwhhrGAE9aRX5kIl3QlAf2MK9laFtvxGNMwBiadkE6GkyfUiQvI+vhDYQtknZmYBbz9s0mvqtD1q4v2vbtrFEKV4eMRJ1Oakl1ykqLE8riisxm4WSStZ3aT7beA8hQJwq8vTm6OonAUnyYYg9edNdJCZ29J9R3zAmK13vxWODMHMP69UnBNA1KqJ+eSNRr42SZLxeJsAsFnoO8oUHWcjFmQw11cZtBYJoOpbUMBFNRui6CSv+JpEuLvWF3QbBzzFfgWDHj+OpGiGv40u6gzCx6ypKF40LbtarerOoFQGZ1oRYlrgy+8T7MT9wvV4E4x+GW4nmhQPaI8WOYl3tkkYez0MOB4ZXds/vBJNKgXoyGbJ7clvio+73Ut/c9MKy9iahNHXpHwrLScqLDDIOKN9hJKMFOfkRaJkIBxuJLTesU6rcoTGNvTnvRY5OX0TUPGKORCGSLGhydpjo1FXN9rsLE9NoWP4V6kVyZ2qMkoT+Hz5FLVpKUGhsFQzo35MAhIcjCAWkQ2NbWSwKGZWg7Iv0Q+7c9MupV1o5hH4qvuQBtqccRG51pEdwpJU0oNPIscTTdzmZWvPeAMdh7EVvHFCuly8wNJolzyaszjm/ByEt9ebZ6oSO4h/8Y6w2IrIYxbiWfMUmOueWBJGnLURKZPKrw3Cc7Rnfrx2BvIljGzCUxdm5EndkHD40YKUjyBIbzuIz9MiBqmbiSGEiXr/fua+QX62Bicom3Exk+ZjqSAkIZIvdxFRaXMVrbLNR3eN92AcNzsBd7etkbjTRplLRMDTU/o6DW4aeX2xxpwt8vvxbreoy39fQoYKRaJG2ZuRDaVYE0ndUkAMcLPcNQ6O3mMYVXJxs3lMTglgi54UXC7BT+JQTJS1ZRUPP2qIshi5I0pZVF3n/mLiX9ffBriptTbmYNwdX6moP3f+I2BClHWMbzEprdBZ3LkocEBrqVfuKearbCs8OH8ZWE+ybQy/hRZz4onc2g3LZJIg1Hu4qkaGxp5F5CnFzCknvngXejPLUbfr0N/3sMCQOBgl5Ls8sSVtIDbEaT1C9J6Vg2iZr+NWb7OrLR47wBQ1KiDzVpdox3OQIjPLLIyKVTP5fSlRV1fLIDrSnJrAekvjKFerx3sSzFXvYi4otZGyZd1ZVlnRimamB9npZud6+PHyO8SLI8Os5AV8jtqM+EkEZLB/0nM3nvxT3DiELJb58vPgd5Q0svSC6wVo08G91ew+B4ap9b3NbUFLejIF0kPCxC8C62dQ75CoLMqhyZoU6VJ9NH3pOz6F/SwGtLLtIMAvDnT/4KgkRABSn8lo2FpasXRESZH72b09DwlF8FVIx57T2+BnqdZ1lF+lJ2FedM+RwEmRavaXBB8CLgjNlHeH5e/W89R7+EIefMZXsVvazXS4XzI2oPfnmRoWcsBooGrtzSrlufu3TxXzj1b4L9BkWOVWo/imp9BK2kGHbYPLMLMk+rDGXs0j8w+XXqeYO8b4L9Dkf68ckepW+6SDlrKjhbAStDp0lOB5DTxsiON2U2zZjjbE9zQa5Z1Ny4V77exf4FjvRTbdU7dF/a+10pwWTaIlJIZ73tsl7P8NMEh+KuI55e/O0V7nUYOasuBqHgtkmVsfIRc+j6cpapzht65SGXAZqnOKu3OwnlHOb3CHJEWlLiaJUMAQlgbpM+3jy/5WbzZeUo8/qS5vjbm+EmCDlHsJ0rLKANxVHkBvQGfCulDAaRIjDWlGfBucprXbO1WFXEXf/rHPh3oGwscbBSlpAZOD46KHeQFNZJtIyTl293fB4f3p5jvAOULYKZcS3hxniqAs9SVg8p8mwMQ4IonUvaMtgaW2mIJR5EA59CnSj30jo9xf8tKvPL8MVnRF9MGHPbFMsOXq3mrGSfDMSQ2a2TOOeczkI5huux7JqyCvsWVDapSEWOq4cilOrjYXL0IdHVOSAfyyzprOwBxy3/O2K9AsyenukWKflCcGKLo8ME68KrUxZmulPc4oIo8RjKPGx273bDwrfBfwfL/GxGqDhWM2NtOczGo5uEXbu0+IJ9ln3IRhjiTZgXUdmM8CBWSEIcSYLK4ElClAD5rWqf7AYQb8OQawz8WvHHq3z/zvFeRGVj/ObQl6YzwqQo+AExZz+JjJqCW65/7rnalPIuiX+O8EtU5seMc8afwaeq0dx+W4R5+4Y01B3Yi9k+O8RSgm4Jw7u37Q5YthiJXrZa1We5OUqyX5Nx6UncstccmXhEF6Qyc6DZTbh6Ozf/HPO3YMJr7LztUUYE/BwP8KNiGvVfOwUt0eVd8i/l4d3H8L6AjfMkRQ3ZSFdZw4BlB4xmXK2+biedrbF7YLz5xL/DjPMWzQbwEFyUg16cAlnwlPM0y/OTnjqHcZjJsC6/zbzvKX/7Uf725AVOKkRJBi5xHJ84FWLJzcIkJrVEEsllyfps5CT/W98Z18EjWUCqepUSXAfBsGDKSrtICakrDo+/MscXzHqRXHmE+DnWb7Ej2bSRUVpiBj8i+BgMHhQcYXSomIOUCqZ79niTq+E+ZfEm0u+BoxqQY9TRaNO2JIu5BYMemaNN5sqYZjCaiZ7CNCINh8p37NCW34f03sX+LXCkBJi9rN18shogZz+io1bSJNpqHkcdFKDDLMrCrXKPN1viHthYcbxIlF/F7SjyEeI86UqrU/kriIlfdzM9ZCn2mtc51mvYEb0FvLIbHAjqQvsnjTIRUsKsc0P/q9uUnrTUTkj3Ndqr2JEzl+KQiA4aDxSrlmcgPnXKYQXIBKaO6fKS7JNoYYw7NeUc9jXk6FMZ2VP/jKMsMMr4vOM0yxIhtDyXvbMqysWfY7wNOcLYaRkzsx5HB9IhVCRtqiCpbjoHXHZJTYdSJTMPvU/jyGjOehkPnB7il/gvIUceL80NHPOEvHNB9IqEnEsDiXR/ARBE7flRFj1/PR9V73J5szXuQ44qcEYo69lYTZWmKZ+iXFH+OW52TC0mh3PgibcwPH4M9zJ4BIU3YEtSWGRlykymoxPq5clrpgu3Nai0wWmyYu34PK/Blp3H9FPw34NHes3RCDTyMpslhu6n+R/ZN0WRXTkF/vOLxZLivAE9qj8TKbbEgKxt4T6OGf1YKtD9NGaNbNJMM+XJrC5nyVgBH8/h3gAe5fHEwsVc1NvlxpsDcFOI03cwSa6zVhQi3qN+jPACeGQ2Y4wWM0U0coc85jHitBzhcdt1U0DCbp/WPQd5DTvy5FaoEbWi1e6MUuHyNCvPY8Z0CZMOfgqulYSAESeq2L1Xeo75CjirMqrTkIBNdbIL7FT9AihSQ6rjx0u+ruGz+DnCK/gM5TaOT8MS6OdR/+4HH+WUOQXHJAlH3m5NnVTeZgg3gXACQi5xuDS5YUw1knfI6mW5iEyLs3ZfYEnpaZK+4p1yCzaj2FoH/8JStI/wkj3SjxAJGCER74taLI1qOyXJsPpK4bQ9y03YTF5IvmbVDVRAMCCbTKepyJyBo8OoAhcFScuyghWP0ZxgTrmvt5flxZ4l9KMnNIoMnjUeWeVoDeplrMjh3FAoeiFvaCRgIk6Tf+Fcvov9S4imsqtLQ4dX7xb0RdVuKI7L0jBJ5MuvVtRiUmks47Xk2cO9EaQlJiySV0lORhQGvihFWNoHcAL88tyMc1+g+WYf+WOoN/T3Kh5vyTJm5ZTZBrE83Jrhpu7Vk8NanolfWJOZ3XPzHOxN7b0cJDdQUUNJpCyB2V0ZpiERmVVDAAX5WX6yh9pGWSNPZp9xOIf+PUwDN4h3Hcj9hC2BaWZnXWY76RV2GxqKYZf/UZB34TTkfZxNglo+waGrNUKpQ2c80Fb3CNYEZmGiUeVUvUDqaJHFlTeY8Tuv7hT+JZhGnb7lsUU5OHOIGZ6adWOAr8oSjOskiJrtJ3XEzSKvRJei2dWMFPZtMI0LrDjVSxFFYJOkOdQb5jwR3TJqEm4T32vPc6w/BXoZoEUZAUpFPmDBGmQrazWEYJcSAHV1uHnchirwR1GaoMrbss9IvI3+e4QGc5FxjeMxQWUrrmKOn6xLO0vn+wCXtfDPH/7NKt/V34seWrY9KmdodmMVjGhrRRxUduKq6oR1t5Hqx6DCsXxE85uA72rwWcYvvaOS7qUeutzZ00gwoV1mu4mUSCjdxI8RXm3wtYcXQWbT32XEepFnxcNqjnAholAmk9sMpn4IpyJZuROjSd4Lzbdch26cH6nlOjjBTjlsOYdDd4IMV8h/UBgrJwRUbmygBQlRzfmdZeMQZlpvZ67jw3MLTSOcj/TDol6AaL1VGxDHaK9WzlNyAkUHlm0OaFBjYpEXcUL1JbvPxZ3zgzt6aIn81BnYlImKnJ2k1TRF2uvkVPG2JoypyN/KPrF1XtSrXd2MnUBLrsJinaijW6aa97SpIP8pC7Hv8j7+Nxf/7jZ+6PEi6RJEYjlhUBpwqqT9jdFi5GkKcUm9zMFSZs6Pkqf/HOoVdqitUT7cDUhJjZhyEeyphN0rszsJZgdf5JT4WGMMh1r/51Av4EeJCtBn9E5VgUOJmSupkhcYvhqGOy0mhw4l5khZtkDAd5D1mRVIZbeAexf6t/CRCArGMTa1XBa4ElE6ZeU8pucUYCWdBPk6zzEos/oN6dQvcfHv7uSGpmwYXyox+OVRWGSHsOxpkYXC2yNuI/H02MtrNdnF+9EjdfaYvJRJeAcSamTsV2YtIGWDyEhoR2qlV/nh4sdoL8NHWBExUOZ0lRJO9DKLl8MpkxppjvhTHPeDBk0qCBEHY6CSH5+X+WKPrxT5pfCGiR265NfDtMlxZN6bDKecd8oj1HOQtzX5pBkhAZd2j2Xijw7qitVZRy0nFVaZkn7kVErbFPpA+x1GWjAgy7BPv53iv04PdQ6/hrYvQOstt64yD5ZDAjpx2sOwARz/iZqMWbIvSaA3vHns7mvysa/baqOxWPTE9jikcCWXHD976ZG0kYRowpusnf1ajnbxf0ybz7U7YsjoaGDDakgrreKdrFSqfHUQRFyK6e1nimSBomR2avgp/IswMvBgHKModRKBKV7LvGoeiFKmKWDZ6YL+4c5h3gDKMMTIOAm39zo/D+vN6bJkRiaJyAt0wbAUFpDifGT/MciLuCxZBOWDpjLTk89p36K80qDy+U48PXLMRryW7ly8HZi109z/2RrxTLGcNyvPMokLplndxY9T9dJCvz2vNm80j/Ix5CsZujjrogIFuuDcY37yLYENYTbLlmjsoWMw7eYP7uDnfXoFQRaETVtCxTKmpxqG34wAJWa4K9symryPor/59C8gSIcwN8YzMdEK67GK2TjLcrEuWXkmjNegGRo7b5ObG8pGUQ5q0vzMegmyKrGwgkQ4sNNRnAcNEp7GDT3JDEyL8jpM4uKteFc6CCL+RKijdV498o8ebUi2SR01p/Ea949oc26R5eAXWNLN8MIcdaxGNQ3D8ILHMlq2e17DuculSgLdaSfP0Knyu/H9m0B/P5J8E2uWlMshhtH//Ryk3oBDjl/FD9JHuev5vBlQMMKzuzm9CfVXkOQe7CSLakEz+9YbIUMDSay96qByOpGISjoJcaJ5CGU/e6hWTrWxvEOzd7H/bij5JvJDN0dtXx9DWgYjgcki2B+xsPTwj5SYT/k9M7sMNe/Dp4r2WyD5ZluYtkxoE+nBKoPD45f+AZcvTR511nfrLBqrL92nc7C/Cib3eHv3yTjpHXupvUmxncKWkdzO/FaPm9kcgpmYNHsR7Bztr4PJN+tbpD7SdeHFEKbqnVfRAy8N+VobuRHZMTB05BB+yYr7tM8PnQP/5Zv3ZR9DYKdM7DX5UtN0owH4TtW9uPy+eJ1ly0clZJ9HVqzfY8o3J67tRVPpdzjP1ZUK/dCQmdeJhqYZIiqxoI8sM5gM1xmzhFzgyEuqKdmHDZ/i/zVM+RI9D28GLBym8oB4SU8fw4WwgejlpeE1WqWK1yt8SwfRzLkpW93bLXIBU+6RM/XiveMoRnnx9mXNshgfaQM817LsHRaGyEi972NRb2P9dTj5EjDkz2TYlVG4MuAO5OkzIvmCoZmGvuXvEJa6YHusDf03DebvjKe30f8KmjxfIe2+0DhZlapRnBMnfnmsLGUV3sd5N8PVi3uhT3F+lV2eb+Ujo6AsWjRTX4AIiS4wFHhulCKdkJEvUQpkKMFpdyXZtb6J+CsAvEeM4i1crGB5rTFgJFVTKW1ZGfoxLrPoFl5PSIwfQ/wl+LtHScnUaGA+PDmzSw0mDeRIewKR5PLcO2Xc9GWE7xzkL6Lfl5OlAVi8Go7kUoq82a2PGcaKIKb2o53c54o/QX0eUDHpEfzHqH83rHyzXT36fG3P+qVnW+3mEqe+5DRRmQ4PRZ5Q8fPu/CVU+bKmSPpzxINxMq5dokVs3TBVRe10LlwKUBD067tE/cu683khfXDyZtD8UFr2lUDJ2eDnYw/lJDbeDtHnD/rXKh17kGCDqAkoMnDNFD3ZeNRldLjpx1rjll+OyzuFsf2/3AEkxZepmdJLrLBI8hAzZLFxtZbGJTuTcRPxnt32sVez1xLexPotloQfE2KKQx5fvmmop7X8yT7NG5PJkJ1ZYK8HAocZcUL7+GF+WN3vIaVqCJluXQjWj5EATIZacgv9xMrvnAuVx5WNAv2V2FuejsYGUrrHlOdrtlXugpTkicWKcC3WastuJbPHhH8tS10NMvSQeedX8iArgInbdXyCleU2WEmTlJHO6LGm0kYoNk8yWq5PBdo4vfYWl4qxk33A+xzoNUgpRz047RWm4jEoB1uFqj07yE4CS5REZxzXr1mp7Yut8Tncq5iSKeWQDT2v6L2QD2a8JFdQBIEV6k/JqkguRlYmMmnVfEs5weFy71Mh85ZAuRPuH0biYYk9LFHxEPaeCJM8+6C6grwLTsqjKsRC4aatHSztnNQs8bqNg4yAgJNWPxlkADEJrinmxM6RS89uWXIK/xKahAkixkLLEdH7aM+EkSc2ZTAQ8nGnrCvvmKbpJyFu3u3BiIKx8wMV9r1o8rgxoNwYNOPoQvkyEkSeFzcnWEEJq9XjmP54+0jfDCZ1FycNcLig5wSzKp5k6Uq65cCF4AHD2ZzDlty7RYwrcVfrfBv791AShgI8EeckpiN77DJuXrecaanw2fPUVHC72orivAFKalgnUE5oh0+D1siqZ0Y4a7/cChqSfBQwn+TWpsGvnOnNUAnepdoU8Q1QErG4rMdWQ6iRQmle/Z9lgsp7bOo2vt6PbrGnwnS5FUymkuT4h9IOrRVYw9xWZVbzjF+Th89mnPGFmXcO8hKYVOWZt794hqIsNmFtG9jlEOVWJzXK9HTabmXlouRD6UUd4hzyFYDBpcTwKeW7PGVXBtExjsDsmLeLwc8juTPbztF9iXMpjktKOiYwT5xqNfYJ5Cwtvrg5ZyAi4k4FrnIz0NXn3c6vkZfZLMOFKXkb1qWqav4i4Mpa8lTnKP8DyuJOORN3jnxopMg5Uxk3qnDk4oJC0T6baOyLauMtWFLTT/IbaOc8SBWIIiwtESZhIF1hU8YIt1sCYGblvNbuo8dvYv0WS1JGTZBV26WIdU+sEjQkQprpmu3EDTZNL4Jkt9GLw1e8fI71AoosGEEmFTmC8VJtSAIH0BtFcUX88NBJBlPmKfnPJPXha6UmRs9xyj7i8C70L0Gk9JmjRgVaVheRlg6o+cOmE6kxz71hIbrL39ZNhqs043apboV7X2PyYNjh6aJ+fxY7hiRd/rD2yYTATrbl6qzL9Xa3/DrHehmVGQkWaZA+aLoz4N9NB5Ddm2yYPiVVe+P5XQvKaZDfS2/38y2gDG2YOJyvaeVIe3wKTYepYcj8enTP9TvmJspOAFKMt7X4uJSyVwXBOwMZW9dGLOKL4iFdSmDUhZ9kDNSxLUh/SjvBGvKi3212bZhT/JdAmbR5cxZZIVH2qMiJtcyPgjMcjIN3TGmPJIzPJNnZIll0x+5BkM9h3wfKGOE1HoId+hpShYTkKsLlhDNBddSyzSh7GoGvb7ON98MyfmiimGveYFShfnqWZhRcwTrtvK2Tau6s7bejKCyBDG14LTrYeHeLz0O4dYUqsMxrjBklJurofk5bS9lmPn5ye/D2HOddLb7kUTg7kkm0rJxaUPwem6eRO6qzFjkhPRikmTEwIUE19cUlWQHfBctyFGc1YUA83NHLqDMhwlOWpDf93zVeX6DlmfwxyAuwrK9fpMjR0I7szs3krSBwNcliyC2QbIZnocn2Gjv7MchrPT45x1l9riFDaDaSRg7LHVByEZx62PluDqaVOpWcVQ2LH4O+AH1adkW5sUXrnwi4s57x9A2qhC+VDrmyFfd5WS9gH7T+Qa8xQrTMcelLIlVQxveGhcrUyzSzOv3fuV5vgrhBroaiZ0ZNIc/BbDfvImf2B4Bqv3wbJe369i69rZ6PY4KH4OWlEVbBXF7uZmZaiFt1zvNaWPNsMR3MrkcQfutFseswzUpZXPKrlWZalJ8pLz6ZGeqMcnvX8EOYNktmEfPzw4fPoV7r+LlD+5I1UxfHqIhBO0dik8a5aR9r4WZKV8HuFNJcHvZzvFeRWtGMzmEzgfhbRWu+ZVtsXLJwRxru2NMOWZBKhgD37aCVwskzEocJP8X+bb+P+mtRXTh5RiMLGp6xMCnArB+ENWmNoz2ZV23MTEqpDelh4zneG0mkB+0DX7IgxQartnScxSVycJRHpakPDLXbkGqJu+bhOdg7boiYmSOBVtPuBF36abKzxQ9APNcsU+z6LMsW7NudcCeytPJWotfgRSaOdN19pUYnkiMTqcQtp/V+VeSRDy9dgCOprR8jv9juq5Cblw19nQP08NUmhUVcqrpZIdPNfNg3q3sbsnQSt5MvZC4kLMVpxLpo+AAblpyUfUkktYre6+cAdg7qx/vB1Hztm73Ef5k8mlomRQe9D2fIkF7+87056Rix9kalQSCFyHoATGz6zNKude7hzmHfhiwLeQ6jMqYKINrluhMHE4dhrrJcBF+8UeNr5eFNoJdRJfURE6T1UzITtk4jtrzSaAbA4+USwZxRUm5yT01oug3/MfdaeHgT/kVcGRn9dhUrd4bpeOjo982j6Ki6x2ftX2bcc3ylt/Q47+r31eikAh6C2HfMG2QySbg50EmKaiHkFdGutS0GsF4hxL7Sn/qfvgFYQionPt8uXF5dP12dKZXVaWKAL4TbBG0wgn+k+jHCq8zRWJU5ZssN5Sc/j6e6TgnKMJVRl4+gKnv+c5DXUCV1zqiP2WDia+VeMhTXn4ijMUz2DbTD/jGUmkCeDEzU3fvwHPOVflq0St01K43KRt3H0dw84uKQb8OovmHK8HlRL2LKlBiaDKZQ5ijLQ4dawiRlMkBdJ31kTXlXv4upn/ODi900qf7ICz0vfxdp06fJflsMzCmGVpT1HoG+zhy9LucV6CthQ8066z9D0CaPD3eKRNGUZiygzkfa2Vf2Qf/p6ygSmsYhAULGB+8gBRWQaOf7Mp2pOP3qrmmSdhY8gliYNn0O9WsUqXKFI/XwkrMp5AHJyVchzPIyWoLIsrhhxThLc1xZJ3he78OQ6Cl6PvyGrIKE/auGcyo1MIhejsvJGVTEDA+YeVI6c8VIkV5aC6f8u96KIVsuG6X+xuBkzTCqaPZCtkKeAFlUK66zBOJmTsgv5vQK1+uthNES0edNThKACAlZQwJF30mXLO0+vzhg7tnJ5BC3ch9DvYEymrAsSwZ6n+ZOrZwgyMQZ2WMyXLN0+dljA0EL9/ZyuJ0xmioeA+2D1CFjTidCXZKOlEdXYQz59xciPbmCVXIdVAuqey3fv4Z+rTkZWr4s/01xlGAClMGo6ugRvWpEfv0mly+3gtP7UG/HkC0fQD8j54YEqNgKl2VTn/RnI9slGho2WR6UqCkgonzc4mExxVw+YeB6b3eyZbFeOWnI3B0WM6n2ecNTLBrfQdRGI+6ozsm0ZYr2SS/1kBp7szfupYyWY8xTs8DigLg5WlTqpDCRree6jM7cZhwT06P6n4K9ZwLxqPdjClmRX5Bdo6elhjw8PsWq91Op9mqrSJy6FNHA6WmcKmb1RhyJS2SGNxqCSrp+WjH6aXVH+laXPnzel9m8Nql6nHfhyFitLIMiYgCqQCU0lKmgAoqSvGjzk3CQCq6DKqC7OeRzwHf0J9mWTHKGKnaTNI3mI0F/Ms6xXozy3DaCeCjw1I8xXgCSUEJk8OHlgIZ1F6Np86MOS8ot1bMhvXvtT70GeQ1IqqtAxnvMT/EY5/RU1JVrjZuS6jkubWHK6kaT+lxs7nUe4jXmq7TRwtheiOK9z6KoVj5szoewCfNElOkR3eclvQAjycILT1hF407k4WLH88uoCfpWS2N6pjfISlj3/na6aZDTaYA4YHxHQ68u0mWcdQa7CK6j4RA1yJk+J2B3AF2Ho3EOUsX0s/2xgK7Ni2s1gK7PT06T+2hD/K0nv5dgZJy0Ge/9cD5AECgx1RIKGQua4jglSUiabYmvip9XPVjD7FnLm1i/wZFDPfZIQaZnmPRpEJmP3KyeshtygpB8NB0Lq27gBSYotxHZN6F+ByLjmBdP1jL/fswHIJvhC9o6Dj8lT1PdO2VWkIgLA6HGLiu5lqEZGiUiFtedR/wu+C9QZHxyPqRccFAaIWsjn3/8ENEYZF/7ayXXY30NA+FIFKcXynYmsaK9DiLjnDpEgOvow1CKi3irpKU77VY3QdObc85ljiRH+3D1Y6DfQ8ihgpzladdwroQAdV/Ka/apE6la4ipvl2dXd18eOX8M9gqCfFLZSoU6a/uEC45VhtywIt/J7Z9We5cHga1AOt6+FKarmdN4KYIr8juwWZzVuBgcHZl62NyxEQKVxmxp61cyL2sKPuN2jCWQV2KY3asOxZYoWxPuofD2/F1HZzP+UI0s7VrWn3X04TLFKqEgQTA4IhmltCKLtiUlZKZIhI1+V0pV2Legs7lhagLRxkw7lBovtfp+eRT4vEs4d5lQm+d6fvox1CvYLC57qaMVwY2QIp08Cddi/UBiiwgZ9RCnSbkysiFrq7PrGczp7Qa/A5nF0eHLsHHaJhGBKS9PQTfr/GGWoph4n2Vf+ihhJw8pzovIbCi7txtNjKES1PqUrkK7pqGv9a+GPm8qi+U/mEM0WKLY9bA089ajVsQXodlUp08kQ0FvMDVe/ZydebqfDKEaNuKoeFG7Nuo5xC+R2XjtjvOPpL+LddoQw3hnTnb6CgY3KWNumeZWMVjqxyi/hmZxZq4pyZ6v3bxWBlJi/Eiuao7BkElK1oqxTz50n7ikGZzwD5M+Rv0FqIhzAlV1uVJkaOMWgfmpcTm1WqmQz7oj/Jq0N/ffrOt3+GwimJY2yHCW+j2Gkigfw7VcdwD7Y/eq6cetbVITPyYP39Vwp6uD1xCRHR4LYU6YM7Yze4/07yW9MBCarMld/riU3yLxOFp8OTLRgI+VdRMl1G1KcjX5uDXdwm5pH96Nv/U/dR2c0RLPRlKmMSPrw0vlExcRqlAME2lCEpyZyIp3UvPpRT2F+i02U49vqCv5IE1LPu+YEEFAN60y3s9kf5lTR3bV7+EtlEf4HOz36Ex1nqRRzsMAzFDWRPE6RZpM6kEyJu8MeRYSEYzzMEnkkq+yBRLfeB+Rexf7l+CMMn3M5K82edwcSmZiCMyOKUF5mjqzECkoMS5CrmR1fXi9C3q898AzOVhmDE2jFcYUY4L6EXUFlevK9K3gOX1Sy0VZ46dgr0G0fsgthN9URvXAqrnB8i9TepI+1JPZwZOhL5m+XcvuHO1ljAaBwkFhbMkSOCXT1w+YliTaZIXhF3JuWj+hLvcon2U5w/Nbd/bXOfRrL0QIaiYUXW2Q6Mps8DHlF6a6K4NSL0a+/t0tcReQlCxMOzBZOgqMIEcNGx4DtVwlcm5Uhso6jzIDoobU0EuSyiTWme6FtHSK/xKMZJKl3WU4D5TKmLKXc0zS/GlhjyMQYqsKkT1qWsVuMrVV9HsVJ1bYt8FI8ihEikIGhSFdzSitVFVmu4ba3+Y6ilRAcG/X92YQmTQ9YNUiVx9BBJJKHRWrPqpUQa11iZJNipsNLbUPy1nVu4dPP4X/PYzEQIa+pEtVWCdOmLvUfPmeW3KYU2gfQYZdslFh3oUiG3ylfB+PIgzUIBWe0DCgs+eX5lUU/6aOYsPR8esPNk3MvFMvFO9NGLLdv0zFmqyRLWhAbt5rE0gCLFn/+qy2cmiVf47wGjijuhjFqjVeC4ZYsg2aj/bLOwV/xigljPHBt0RYD6Pou4/PQV/AZt7QCW8Xk5iYeTb0bN3G+vBn04jvKJjqMa6fF/UCMmMyxyC7kZlCx3CRQT+2n12ekU+qBROasX2Ne4WQry/vhc5UVEsxNPAtr0YGeCHVODu7ovOSBbPnuU3bnuBNC1LesB9X9UK1g8c1wJ+NTJXJDyhOgZhUFxtojhjPPnSSXq+LH4O8giQtrQaa5naK/qAANeYeZrkgjfwn2sUftjt1Lf7Ws4R7UGTLXmW8FgL9pkO3ChHsOpk8SaV9dqBsneusFJo14mvN3th9E+ylHl/D4sNZh6ZzS0vxSgrY3UI2oETEFR/mdW9nk5cSTbKPmD8HexVHHhM4hia9OOpBNCol4Q5/SQlOOwP5PoHPGMxAcdRrTMepDvGIP0T+bYsPczIn5dnUQGRfZ4gTUX3g/uimbOfNb43q4WXK8Jjpv3QQRV9Kcz3eG5t8UTRFG2Hee/K+YS8+a3XFL/9bxp7mcC9FqHfreickYxP45ISmSLGSmqYJakxdA9802UlknEStJG2Y6hM13+06D+fIv0dkpKpkLC7DLMeFgOnfkDbhadKCuI3OZ97phz+HeFtnD4KqT0wblxhxay8ekBDl8JBr3+JKFJOj9xS4IbDi0VBfu1TICaEOHbLZ+VP8VwAZ89omUPVwLU2UtxWz3vYol/PjZwMx+NCOKh9vhptCndJxDOXdlr6vrYeLaIHVYGjYWKr3WOyVdQYh69o8Szqh7IW9+Mjpp2AvYzKaDSFFDfOmKi4oZ4x8EJcN2HWmrsFIJ91B8QPJNfF5KvZhy0/Rfw/JKN+jCuBc0SyZmYNPkEH8PArkGOl5dg+R3bJ7SinMGyAO/XvegOCZxwjAQPBumgRGVRvmvRzW04wj5SP6jzFezRxjQWAl41GAvIKvM+fm8s0zecA2YecIh/TaMn+N8gYo5i381NoyMljCmtJRyTmuKimzTxpFCaMsVrIeG+a8flzZy42TMvzPgrxG5xjGFJmso3i7puGKX/pFtuyKIOcgv4SLzO2qwxglhO7tiE+swMlWmB0zu89n+Nfm0+lzv4AWsU/SLH+m2oyQncc+wcxqQZz5Iazl6fgjcqB9rRG9JgXX6+GHtj/oxmvOBSKKzG7zmgSgdOz1TqdnzpIgxS79o2jvKhW1f1j+uyVbObhDp6xUWnrpIuXJR7GIHAbV29S9AlBwxb2YFJ2X9yIWV0dBBP+qOzTOwWKq4n5cTPRP/NrIYm3yi3Hnrbdg830wsl1SUU4VKGGmQTwAKXgzFegFIxnU9jTV5zgsgw2Htnj4HOs1pqgX57ttSSvLBC7+4iaBMWksFmFplHPrs+thptH+yO5zqBeYohQpqmxMDy8H+TVohpRqovQCPTp8zuNXpFEA3i0mEJOTAgjb46h81B9i/xZFIszrqvBfZOKpUGyIEuqWm52bs2YNOKJclkcZ8YmVUHZyu6K9B0NSHjC5Z3oN16Lnm+nSWLEvn5yIoCnwu4LbOpEe9e99rOUc7HWyaCkoNzTEK60EmagIyoSJxOVkFt2iN49GpJdbb/0Y7FXUW+SrlLWedkigSngkwHldYjDiZKIWg/FzEUcsrKnf+DLncg784gVsVWoCDuIBaJ90i3aa/hLLZxoxxGeafvwY6DV0HnzhoU2U7eU0i2BOHDCAeKjdhmfjsoJ4yS7soBhvg+dezl+omh46XDg4yDcjGU1LUuYqeO1pNiJBcLe1+KmHl6pVvxQiY66vbJuX+C/1SysvglhVLZeATGm86nYVPQ+xQkY1T0ZhPOAIuy0jDacMKb997O7l3R5V22EWJzpT35glzjzXaqfSi6pz/D8uKS4Gok7l6Hw/RCdrrIYlCoGkIQSoNAChIK5iXM6M6P17aWdT6E3qWPXEIj5+XOprAD2koFF7fApQr3F1Em5RbpUt4jyJcXdSzvuYmeK8KxNuNxPTUNlFdoHq5kaVMTOtn2FktVQiTkV7ZiPaZpAbqkx/dwETRXxDTYGrKcpfD//04Ts7MYRqIbNiw2G020RPPmG2fCvzNimXDAE35yyX9zSYt2m2yBmYL5u1FfPIZTcQPAd5raBAST+VodIsrroXpZVyh6HAlCaxFsUYJzegnpmV+CTO59/u1rt6u8PEedi61DWYu97XPAdjgtmHjDmUuyjBm2W9itezaD4tz6W2of06NdP97O5LcHwjLNFmC4/kP4Z5pTRDF8nQHpEHhNO46zIqL0uxNc4CmBp8pBayZ9zE89Nv5jKzNS3bw2CCSsQVTg8jAaH2mLIDsj25Pqm8CNVguV1Kntw8zA/BfoMm0+S2NoA2fE2L3LohQ2VInxlsY3rtiHkdNDuVDz9Nb7M1dnvpN/F+BynTOC6HknmWqmyls9Q2BseriFWn+TP5qYN/ZSFHH5IyubGySWScp+zt33ehf4Eo0+xLHmutaQq1atCAa3cuXiBxIXfuEMitbGGT9vqYS7tSp8K9DimTsoHqEBFPTl7XcYplT1Hk6fGw+JdMzZmtIh53rZ1zqN8DyqS7tnqowsk7zThRYk7qmORpC0bNPEgTxjz7VhWNzzr/MdoriDKtAeVKwm1jYLwwIUciLXIIzoncUZcB8pHoCEkwLI6pdHpWe55wDv07qDaoHb7QeHAN8LiZIKC8hYNvGt/As+SKLs9pQrAP/2Z574Bqab6mxhSVlr3kElrEjPt7JFQSF2wQ4ycz/ZslHMWQlOaDTdQewsVvf+dO4X+L1KYbdzx0m6mL1iT5SrIyG3hrrRw0oI9Y2FjOyC+sTsKQeZrrjPtMrcK+BaiN8ZGGhZneyBHlH/RgZLAxCU0M+blhsjFl+iAI7lS2t2FeAWjzGWnHL6iHmtXso9zr8QlkODLIyIAR6ydvG1h5rmG7J36bzW8zizsg2rjmWnrB1JMPfNB8y+4pU2EwzKB8fR4/kgHe402UFwHaCLBlDZqIbokFCNhgW5KKUgkkC8R4pbxPs0qYjPSpaNRGvhrv7rWLCG3s2+S9ngGaKphrI7JDfdROhNaLkZJEfl7T9DJ2do7wS4Q2rt5YqBy1fQk5EKZbP3BLA1M0rclcmNkZRdS8dybPQX6N0OZomQsWLxWDiIJVn1KmFW7NRdP3jX7NyKj5IkchOtf1Yf3HkL/AZ3OvtmwQanvRPxmXTnrahyPhNZdn7i1w2O8lpTdr+h08m5AiF1BkqLSms+TH87hMuVaBSH6mYEtaOuuD+Sk3uFBvTlPPR4NFzqB/LXrV1FbKE1TWMgtIoGAmKaFi2R3zpt+suQWiMZxbhnKGNwzgcMH7rNFiKoeww1hgkp44RTdY18LgbgmfQ/0WoPFwl8q/6wzadZk6Yhwj0nZyvpKoFmF61BSzm3nnfTT6TawXwJkc4ZggauCM2aKG0odDO8Ol1GvGvLQQWwnYnMZJEm2/jZ68peQeHiX+EPo1cJZlVRZdYcgUVm6EjMlEJfwlqHnWplf/W7MMPW3didmK9z50dlAXIFoqZ5V+kBxYJDn65Eiv3p95VrQijUnx9Qqz5k54hrI9Ndm2nGwDKf+p34cDlLjHYRaagJdT3JAqVdhbJedor8Iz2tOWuaEWp9WEsjyZEU0gjYW7GNUUWtY7XgY88iuJyLg94uct8T0443GqIiHhjx7dmmyLc9ibiScNJj6zXGlL7CIUCvEubEbx3RkrbJashJGF2UP1XrlN5cwxMp9Y5ayqDrU9UeZV5NHsp3v4+Cn+S+Cso9djchaZMPlmHLiLdMZ5PS91WXjbBJuAmbmkOZ6pIlVEfdl72Ar7NnAmu95EjTzHcTtwxoy0auoa18NoHOYoaq+zx6PmdtkZ228jvozTZCrFbrUtIde8DJ1JXmgvmqNbXFeNtfcvsg7FRNlrs3d2W/q3wX8P07CpiMw/ZKlIyZfLDP5CqON7lKYYQpqVf2o/dvdKVZw3ADU6lEY5ubf4IGaUzCN2vwnmAsDd4FURpxIPrda2UXj50piYOod7A0iTIycJ10FNSJN6AwqOczYJJO/y+rBnfZqr+Dhr6WOUF4FaUuc8BAaPIQcFKUXMYBHHDFMwKjwroDn39kK4C6gJ0cSiurfVSddcNx8wJ0feSxDbZJE4zOQO45g8d2uMj88hf9v/SaP/E6JMGpWP59UncWus109Z4eVSYjUrjiih/WGbXkCUR/FIZA8Zs5mlcjyTTZVuy6k8Y2UhtI9Jvvn0L0BKPr5CU8pBvQkiCy+Fmkklh7JZ7Ca0hAWDOaXk+T6Q1o63nDqzU1nUS6euTGnhAP1eeQX8Cj9nNcx80JLf1SrehHqpi2YbNKMF5SxKTwWUHtHzJkUvUubl0LnJp1lcQYfKyS41+ibYqygtuUg9o71TmuSTyluW9p7BQlg1nFplCYF/bJ4C9S1xQ1pGLGlXdlbxu9i/hGlSiDGekmGy1MJLlHy+gYBF0YhhAXlRlidS3tTyVeOqvJbtbL4NpmlsM8nfWBoTRcLnIjbbSS63qji7CXwWeymSFu8jOudgr7fRrMkAsOwiSlaq32VxpRenlcxQq4zw815u8C+k13O8lxtpKr4nmKLBBKACPAaJF8krWX1Jt3yc2cLQ5Y8LMc02a4NB2X+M/I5aWYXv014M5m3JCepUEoN7kZey3VKxLbidMHDrHu7ztrjY9KtQrg9cmWdljBlqJjmmdiCD1DC5Z3mcr2KXelaMtwFLozyWu6n4RGusd//woUVh2wSeA2QfkPuPeBRYDOXgO+SDexfm1Iot8VTly/cBS6z2HExn3164IAa6xLCGigVXoGBbhlqkkWpYMGXRM5UbPeqbp+TWrl8JQdbSMEKgx7NV0OfMy34gjQ2x9GzoDZm378bNeBKk2D59XpCIdMqhH4QedV7EzLxaQJb8VvNgvBuhYZHFMWvH81HDT+FfRpTMTVS5onJ3QGRZ9mdL2gQXp1npk6vn7guiOG9AlMDXUsgmjPGW4jhQEoomOXgq2PFJiA5agVt0/2yymyZ0h9nNOd4bICVkBacBk8wMF0RRN1Um3bSU4aZWzBOkM9hyKvTm2/BkltowE2a6w6Dm+mmxkPyyk0tD32TyyBKUkbfX1714siViBqAOe9jK20FlMclBxfn9WFbRN2OgXTVrh8zc22znOk4jmUwybw60zBAsylM6eQ18mmeFTDNAvPM/feyX237eyp/CqPcgmfpxtmNdGC1M8OjniZf176nlk++D5Rxbg544N7lm5YfPzpPUqJ26qExOVbPGTl4zmP4v3sTIbC+rGgvtf9DqmA3AjyjJm49n6Elkf8xOpl0lxpRdI+5NsF9jSYnSDcNIHzRzxCxRJrtRXwI3ZDTILR+2L2tU1UwrmGJ2IaM3AV/Fk8Uhdehr5A46hkjAkWQrjiFKB6nNRYhscNhEycSFJ6SkSSUIQrvg6LvQv4WTNBnbMkoHbI4dw9NlsJr3TJTHkvzyQWZ2xvrlKqjpzNfyYo/gHkCZ5XZI4TOr2o2lMUmhreMBqHnSrJiTq7tp6+lFeI3zOpZsFxd8ci+lB6uJGLKUYQS/fAS5xpwdKc2T05Z9fI72MpKUOKT6jj44WO0ykXZq96XZF9HSMhblFkhrzx2qN9pA5uHzx8gvgrMQBNPxC5Idi7EDL/q5mrzDryMGVoYxb26Ie9FZu86wkC3tVzIinFHmgRVxGydmJlSmgnaT8bIah44V+blMP6dK7D+ET+FfAmeU8SpsAH+M9lGIipK+gRDYLgWmEiGUG6rShdLPq9gohIhkXvnm/d+6r+uHfJvDfb6woS1ZAs14K7OxOLUhqp+c/rDGumi3/I5ob+n4tUNodROUqjl1sY7r8pFEY5cqBIONcPOmpWqQ0yNODK9c+TfBXyRmSjK35RqVwUmRIKe44Bwtt3XmQy+V/0Pu6M1tcRc1s3i5CNXDEUDVPnaommNoS9QwmUXWmydVRzVTHBwjco749u64o+vXC7qH+SHk3Er1PO5SN3FWxgYzNzwz+sHrOe/qV+cgL4K07NGTCwnlAm66mJe1tps6J6hE7I8cVJ68axudo7yBnpmYLqhmSAIo7XkmDEmav4fMsEGeFpKHlHaYC5vcPvN3Dvk6vHCanjeq58+eqXRCRh1qDmr33KPGsLqBu0vXOcgrHNKEVr5NEp2XwJFdXiGr4zpHY3ZJnkMK4IcP/gKYtLJ11n0pSR5KCjsfgSICI+zxeb7TiuH0sPFjLnOxKo7iu9zfXZXuB5fnNKrwk3yd5hkSyqxuKqTass915t96bvEFpPQzxDw7DqmK2n7IbkjznaoRtXEUA/ERDWuKDlBTFkJHQ2CfzHgT6e/Hk3uwYkEwzFuLk4YWOatsEOsac4BMXkkN0iwerefJ1/15ehPqryDJl5UFKgScxb03EiCIpLRtzSUrA5aALWwRHnfct8Kc0g0KBTisIYSyy228i/13Q8mXyNlwseq2cTIGM1KLk6q7nW4xkvAiIUdpOs3pvjKkkreLVeF+iyP3gPt2SIgytrhI+jBRsKMjuXz60OuReTMbZWUtCcud9DnWX8WSe7jC4+iHZamXVFmS5CUYBxpAWs4Pqcln5wqOatord+dofx1LvrkjXLsZqpZSBkpMnAfuhYjVMIwgycL0Bw7uox4QF4xdOj057Q/ZOfRfvoBfIpf8JUwqOTbGyQjU5bcmGEcGC6k/DjGilxG5c5i/gnnPV5ovGA24xOUaNSPkp0PYmkJE2dMP/oAZYohHY8GdY/we8u5hipGSUqU6czy7yFNQbjysD+lUYytKFz0i+xzwSrDw7ZKVt3NgAmnUBnfBm1P8v4Z5X6JnWMAh39c2JLI3x5lL0ieWViIXrH9iNDhaOklwZ2Je2TDHfZxdYV/AvC8bGPlDEyC2B1mV2Epb2M+Shwb4qJMEt5oSsy+ZnMYO3E/x/jrqfQlaGhFBSWM0lMMMz1nRcFqavtRY58rLh/SzqovhaUsCPOLjx9h/BfSeH5EGd+gvtYjrlN7Bk9MvYFZmuQ+ef94qC8W+PYpfgd7zw+F8EKExVFoo2eP3gdkcCRBC1pJMMxSkeWeGxy7lHnWKH/5NwF9B3vOatmeZpfMxrkEvvX7TmZ5yu5lGtMuuGnMQ9zap/Bbw7lEy2I0HsZcUbYTPVut2/fLxQ8bc7mCS+vSw6WOQv4h33xyrdlFKdN+UKj3PYbBuZs4gW5q+3kVDFG56W3ip0kqD6lHLx6B/N5h887IZTW8ZXfPkNUz2xB1RhlnnsGlzBgj1pwh/CU2+LCpENGbQ2nFnqKeYadRKPWZR3DHt2iSNFKbb9YfPYf5a6WCPkynCrHeroLkkwRg/NR7zE3do9velQ7g82nx7BF4OU7kFSzpqcTmKhp9hrKMl53NZxlD4RZDiiI+CAluZ75Wt4tHYz6F+CybVIUl67dsOMMN7mi5e/6RL0a2JOY1qS3XC4eXRxxBwMY9SPwd8AVIWhokMiLBUmD6uokjsDFbwUpoVbcGpfgtqLsx6c9jaTSIPFvrJ9sd98S2kRK09B8YGbBmW6oYhqMwRqsKKPF7yyXP4LHExrO4kf38+3bjlVlTZPmspwyVQRIOQGvrya8jIrtGCwM8EPwqlZmKOWh+2fgz2OqxMjjmdkPxYMXYpm3xQdRfDNYXBhp9EC162uHeqz8FeRpVUx4wEmQ6XQehAJIv4T7M9kiV/NEvLBJ1JNG9C4mphE2X3MP5j5NfQWgga6y2JTpQJc9YgzEF1SWTOtqWtmyRtrHsbVUHeBtcEtlvuzfRAwJkty7EgBs+cNWZSYpcmHICT3pUk2R5amRpX0Hhwe5PTp/AvobUsICmql9fgtWijR4dSVjxihpKOU3ziC6oUVSfVRZZkR2/nzarfhtZYxCBzSV1tWCKtoTjGpdIsQTEgVXc7xLwb9b0N9DJMg1dnhkZ8QLI4oK/tGebiW8L3Bf4zFjRPwhftFyhSk4la/zuW+XugRmKZ1Z+O8LBEZQzLtGAWdMTNeVa6gOp42My92cU3ADW2cRYX73CBZy4G/Vz2canUAftbR384IjUgySf4Nxm5cEjG7Wp7cynfANQKPsv0oBOPBlOHgE39wlT3ZN45P6ulDj/Ed/naPTiNe6Fm+D5SKA5m3sEiw43EV+YGxjw/brKcevvB3wbUpCJJp7dkSQ7TqBxWymwNkglJ3axeOt3VKGlQVFLyPjx7jvkCTnNefdGkmckwGcurPGrX/NmyNVikm2B3LvabRb0A0zglYNmQmEnLtPIZipmwjB6gHPH8NsUDUrJlN184JwgXq854mhopjlexI8p0gfLTMwQmStzYEy2LifXZe2WvL/bfcw9Ua3ihcG+3Q04KCYfZoxhC8oDdM14BEFNED1vIB93quEtnvwn1W6imgxGqhgrVHUsCuSVOsRjGu5maKxIwLXOLLoe2Q1jwh2AvwDR5TGfIPs4UyKJWjI6AkoWTkBGkQgu5wht9UX6WPX1DScpxhub3T6F/i9KoE8oGzx7le3iPHLHEQkfufj+prhbVqaEnVHalvmBes4Ee7z0YjYQfXc/2fomgD4uurhFUqIwogqikHjc1MaUD6XOg1/AZgrOqw2QnWSO9AFL9MMsQBPdZt76IWRIlMSuvCOI12ssAjfFzk5icD5bAkvRGMUqO6KEC1hgr4H0WTUSygkU92Z4GmcfnwC/iMwc298ZEuZFypY3ce834wcSh8T5VGz2Lm96csdvgmdwRPY2xXCMF25zNSAXgJlFfSBVtNK6NDC5qqQMqpfwNgQccXol91Rc8xX8Jn8GmNFY2V35kLuKTe9nHVFWtJefEo4ZSNEPZdqqwBLGm0z4io7Dv7aZVB2mwBTSeBjttppBD7J0d6EXhDUnADgecH2O9DNF0RxSZyZQIVz4wITeE8fysjkjEmiEAL+O6oYJRlxVNzW8v5Tt7acfsRJCuTZoDBvQBKOFMn0TZoOxFdSrz6TVX63HeBtFcHNPgpDaHpw2y2qQJcAqxW6cRbDVWKaFPrrXKTVJQUXx79m4AaTTOHRWFENiWaPn6OKlkTC+H2R8AzU/kGyhkv9YXXmO8ANNIZ61KvkhC4M7k3SQKh/miabozbjPWWdpd9WOQ11CajgX/fmmXMFLEQ1anLP4o9/Xg785ZNIZoHHf1nJ58l6/f1ATCTtSEMR1e55v6ls+iIdBlpWjsLIU4sztPngP9Ek4yiySN9yhLOZmVmwkln4JyG+lxSgaF8IifP/wLaBKTRmnGZPAWs3QhpdHxlfTCUyUhPKNJ9VhtfC03v6Yzt3CYeFvbtVSWOlxY7jyz0afBpFGMNDU92V7lfUX7Q34TgzRH8bxcW0HU85lIw+EoUFqkl8NBY+wLcerJFqQnfUCGH0K9BCWLY3jlQAoGCZi++SINvuL1BPRNwHFC6A7toLIpDKbdXO5NrN8jSYfOtEHJu0FKmDIN8VJOSBKXTFz6BsJzYQhdltOG15fiXVb/SnoKB2us/BD8tyRSgfYsN45YRiNBBgA8mDQc3KwzWDneFDfYKQzUUo/ajdsU7T1IsuBQ3+/yOOyofV9QnE6sctTleOeHjt/mnc222cXDzpHe0OozfJS+in4rUwUTVi9M0SKBlPMoNs1qKGTptI+bnYO9hUB6OBHzVrWUgCKHRKh154oNX6YDg0ql7AiGJmxDSHmKqh4i5fZj5N9DSYYR4/BTIeeitgh3vMwsJi6/o/I8A0WT5+1OuA1Jyv/QoBHZ8GRSuwDRiRTI+jPk6KwZRHgksbJxSv/rubZzzTE+CUy9ztuf4r+EJGVBS3f/sE1EEabhYDo3sLBcUG8vijDPLdePKJVgkA5FHCqb/pXZ3//m25AkAzrov8RA7lcZYo12lGiwGCrrpnDuLIJ1MDLtT5He0+o7xlKL/HrIxJmSctkuAyQa2WLtOyqCecpwHCVMOgUdYdbwWot8E/xlSqbmD6O8K+rUiYEGEwaSoJsS07NcCOIB+UQh63HeBCO9TarwmiLbK0MNKlMkg64li00b1/gvBqsy8SsOwEwFqu6CtIr4BhQJpS7p6qXFpFNDT8KP9eNrKkt6Mu4y2+YVRL6GeLXXF6gQ+WqcbKyx9Buze0+zkvT+wsbGNcrPQvkY5TUUGeTd6GQrBm/F0bW1yDqjLyfZX9lAmOW+YfVs1ydFGZNeuM6vUV/p9iWjqkcJS76mTi+Ip1m/sHrnc8qLJL6+tlBPy3oBnzEFYWXRhycts9wQv+IcPCStZdzePjNyqVLnuI/4ncO8gsedvIuQ9xHTak5B5udpzjBPFWFJtrxviNNK1ltwGb9gZUnjEmrTysM98xqomcS0fLiKBBfm0KRZs7PptSBzivRahy+gCNeyPNrMIlBEKBzUPjErSFauw2zn3n6cl5NYYC+l5FOsFxp8KFZVEqdjDJ1suw4/POb7jxFadiJjJXIxMm6JRUFe8dXpVeONjS8NknPo3zb4nBp8Ks8k1FKLV1PKStkTcZ7OBZT3t5sSBXbeBALRMT7erPSN/b12tDBKtGLxQGPXXVWfpErMlNSQQcgi/FgurZd5s9dQb+nwZVmYGOn3pifdfMpxZVE9Yo6zwzfDhUvj3l4Md+IyKa2Yom4zE1qFidOIgUhGVRSeTZXTLNWc8Kz4WjQdSA/wdTj1NfSLPb6Y4TEbaRBDnKrTPCqEWVP2YaDHJ5IdyjG7f4WCvAua0ayvRk4J3kP4akcPSBBNhJFPFkv/zquTypcnX1DMVVPDcGZqLPcEIX2K/hIww+HVZXESWqLCb5Bihpdml7IeuU1JPX34VpbZgjBzlMYZ8/DnqG/FZe0A0vgNBj144gmzosTrbKbokcgAe3Yb6k9h3sS/9EFqkV6jlNiDeBk2MVbLgVMdl2l8HpXhQpblQhNFuXi3N24lYEYnAevKNARmfWIHTm0DjbaPEZpZGuEImFP5pt7Y3PNTaqktMn0FRCbJzUnBE4IVQdY4deY+SsZtXjNp4UUgXvHe1dlLFYPJ9pHjTk4dpoRRWHryE3t64/xmeHMImHwM8eqc3EEV4/MXmbVMGQDm76dJhWNyb1PaL0M8uX4M8obGXjRwIdodyjhsFVc5rfohfWcQGdwhzGdRdHUayYdaaHYR+3PMVwBZpL/QcnVe4rRyliffPj+nTHbfviy3+uA/L+pV+mWR95JDnryocTuVgMqci5Q0/JqbVXVkaAt/zhcvNsxgQzAU2+4egxNbnUrf0hEdsdrl46f5uWhnC/2giD+vasG+/RI4m5+da7gmi0YP0SuRDIQgg0RJ9vXnvz9ltPnJeRdVogyex8dAv8FmZeDYOFyLTEoRyhc8IDhraL2LMIofavLzQZp9HHZEbIlt/Rzrd9isDPGScJz+MPwcRKKRPhQXqkMBWdoQmvz3klN3y8eoXXeyZ9LAmtl1TN7F/gU4m5E3DFnlbKcibXLi/DCJIeHGuKCDoWMmzdxpxYUO6HFv5XO819FZmfqd2DgejYe45rOK3rUnRP5EqAIZjVDpsafdRvsc6BW0U6aMScsJ5ZReAxcYcr+e9cUjGwX4oNHz1aeuSr0zbXWk9cPDho+Bf4d1xgJ7ES4Ph2Q3c1b0yNf8PI8bYMg8Z1pk8HFX11CMd0CdMnK9g2GGnEPDZENdALZZMtCFi0e5CRZDorqTDQLUyA1m2icxqtrPJKuJW1ZzCv9brFMGWcLnSkvclWFAn9PU2qBLxocPyLS0flxRukM2Md0KqkgDjzc7+hasUxabsXCnBuKvvBllPsoIPvC81dURWTZiSo0fIf4U6xXAMw9gS8Do8tWMpKSTD2Km1xRXacQWrCDKnDGQwBjueJCzDq25H1f5O6xTRAvwyQwTYEhtuAeZWdJ1cx9JdCU9M4o7dkgvDsAK8yLWKZNwNacIIr+zIA6TJIaqWXZs5WQq+MQXhSbQcJF3Ywa/reu7a+0i2ClDFKRgq3tYgqxRSL8U36Ey2mmFWMNmAU3Olnf8eA7xS7BTRLFoW5XGWJIMMTWMPHWHZctDDXdcxevqDYiClM/r+DXYWXr0Pju1/enhyYfCCubkvKwwTV3KQSqrc2VTk6TY5/f6wTnmL8DO3KtBI/SR0pxG/81iBM67zUz1w5FAwtgru+LZmyX9DurMWzUU4GB7z6ArQf8qs9UM/5rra0Lf1XTm+n2RlzyH+W3vqUwuqG5CT5HW5iVJIUWrsUWghC2VDg8BC3H7uPtanTOY78viZQoTcHjahVPNU2/EahxtcWis8q053z9VO+Gzpq3bUH6z7jZA1h6cIQycMi0RJjB8REJMjjph3gVWrd2V4S4/wQZzQvoc6reQjHJrUZPZxoIoJ+Ie0wcCnTU3fXpROHJMbs1KHF6Er/mhdbchMvBre+6ljuAGeSNq6IzZHBflTGNHTwyIjFIrM0VUoyOW1U416Lo7FLyL/UtEpgqnpdLRsmuEk0qlmgBjHJUVMarkuML8MYmLXYRhtc/2kQbFew8iK9S78WrMMnaHfNtgy/IzkR4IUrlmySMvGqPGKT8GesO1UOGZHe4PUu18yk6eLwQSwGBpSQ1Wwiznu7APdJ6DvQU+du8yyacwhBOqWDPSqgrTxpNqclv2MkVcyXSNh2QlPljc1dfOkV+oh5UxjhyqnFlhnWGy4M18y+Kcx0D7anqhWM2tU8r3+4zvOdZrWDd4pqZdQnAp6sqYE9JxblKRvfI2MwTDIT7SmwvhNrArucUGPyAaFI57NobaQaWoFzG7OdjbvdSYMVEeviZLCi+ZRBENEpM95iPdp/gvoV2NRKLf0fZhlWUfvX+b0T5rASGvwa6pchIjeQz8RWbaP/Bb62sWYd2dcLcwpMdwSPSaYyqzUZLmN/K6C3P4yW/UkBj22be3gV7GuhKcUWcpRupzUcLTAdVyEKxZvEaL8oJUgCVRPN9C6oJml5d8G/73gFdK36Q1nk459QzUvt2UWKH3y9TMnB4307Ii+n0USnHehXiHl4ZNBvWnXNnbOpaM9sJsFryFY9O3spqnc3ZrdFDeBHwD4mVgMFO8d4HnizXzk8LqJiNaY8npWTZKCdDDp48RXgC8VIWQ2jpqz32leeL8VNhA5SpOhjCZXHgeow9hV8A7B3kN8PLJFYq3taiIRBHcIlFk5fIspi1qftMkucdc3DAxZ8Jjlxc9x/wl4NWUqS72pNZkXt29uPMt84JpYfMeDunx0t+x7j7MS7qI3YCvLFlUSmCmCvVSOCNRyJulQk4yOPsY5WXI63Fes8PfrKQpdwmhwo1+Jb1mtywr4AohZXROwustMJLH1KSsMVHclTLQKwIaNWoeJJgNKFjDC3aZ6MDJNWXngr8J9lsgKWn3nLJmShM9DxBPIrNJOjF+sibyUHKe+3PpwORywpL1vu6eICRpgDt8KxiCjRpYEOUj2ScbQRtIE6mQa0yqypxDPBokJ8vuLPgu9CvNvaP55MVURFcv4iEbGKpAPJJ0Bn9vPhcn3DD7C0GzGI/iz+He2dvjtQxJGIzsPI8fDEk7BAjkvLQNCoih8vDxY5zXgCRa6GCFw1VYhQMNxXGQ0jpOzG5Lcjw+l5Wzhk/T51W9jCQJsFJiOoRVxBjVa4sGCHiHlp9EaDXrlJ50vC3aIDR1GnJI+WPoF1uRtUgTHysSWOwgG2iXfqYHzMeVLYdB6fBR3TnG29AZTCjHu9VWmEpCUnc6RHodycmogqHpSrPEMe5PtVeHsdRKksPfHN6u8E3YzGBaU5FKqVZsoDxGOvmULWq/FmlGGyvDXYX8zM2atFlSXemFHKSw721FFpPhrVla6RXLnX4sUY5cQ5EUpm3cnNMpVIfXTqSt96Mz2T9EiSUYlRZpm7gk5UM7QTkc3CSW0HIQOibqnoiXNr42I229GZu5th/piUvUFKhYp62z0PjMbXd/rsTA2i5RojBvgGZgGoNQs233A1JcKCHGXLhlyc46NBsDcHGRQ6wcS6nyIkX5/tjdAM0K1xicCofeC8R2VyevgpSRwdI102m2/q7/GN4FXEYunuUiy3SDBOrtxN709BdtiX1cNr77YccXP0Z5DZipwkJGVhoGK08PsGx/1IEy89uU1xBBYvoEMQPV9+I+sXGO+QqgsMpxIIBMljKv2ugBTwVnM37WLk2VfGrx1PtwY4B2cEhn5TWmFxcIXqse50F3zwf9ODefl+8qamyfH2OWNusBslO2jurWdLaUBXbZ3D0kGuLeXkj31cA5wCoS1IAItuQT0igur1JWmdOl8oTC80yV/tcyUb+nbupANnxFXaIhgiqqn2WC3M2rCeIURMYipePJUoepwt/xQlh/E+olUmh7NZlprlHuEjwvKhshQoZ+sEuzXCvbsEkJ51V7PUinSC+AxuHER0BB+VR75uFtZYTgnJyPg4b5GITHySrLJJkOZZa2pFrAcZdSehf7JUpoCbJG9+pEyhUpoGVJeRNfDSU0EAGd2HZjU1g+q9fycY/2HtDYb/6MXlZMwli64pklFgulPPmmxOXIuVhpbLL8iB9DvaEBmSMdhZlOZ7M8Sca4U5xeDwwVQA4xzzZ8/lT2fA32KmwcjYQq/JcklYLWGxOxw7OMCTM/hVrp3FQNKgdNBJNu+8/b4SJkDLTBDjswANgT0WvK1VG+o5njnh2AoFrF14ZNj/E2yOhUgYPvm41j5qftWycvDW4QeIsJ3kFEhCswg2yT3NYwrZF1ptQ4D5vDj/FfAo0QUwI0UO/arkiya6QAEqTEFEWppFLKfYZYSeJPOL/TV4N7+9DdBxqpIpksN0kzMkhY12lpErglL2+ncEqcOYQ0L/OjlJ/CvQwcNfIvMzVb7HAjoT3Oj1DLoO8PCYTNQg1B9s9qVGGh8DJD/Tb2iyTWnEVEkB0TM1r0chelzcyJJ/ZL3hwTktstbBTnbT299tSpjcOwUFYrEcclZmBQC0vyNvOLM6zhrzCIjuPqsOeAbwCO6Dz4nLjEUAVF7oM5TUb28tJhXMJhwW+Ggcm9dp9eg7zY1ksu0W+OmKVkCRGZUbCNc3IruOkT507DmvFjkDe09bySheqS2p+SMZPzyxKwhWJXwhLMRjE54AFOQyiHVybFa8wX4Jk3HKFDq9lOYXkxGcPq6M3UwafNgsRI4zR8jvAqlTXaKPld8oWgLnSab+8TqTVPGZW46cUm+1OYV2A4MtIk2raiV6hSbJ7FLLequ3VAMWmxUudiWjbsu7T+Zi7TQ+vcnsmbKAsJCoZRUuMClAzviaaqebc0ZT6WtR1b9cXQ402o34CzOpXbpxB3i7p/p0L9T6mEORNggZsogNmh2Zn2+cL+qtW4Cym9ifc7iFbHMYneIininV7Sw7GXF1cu7rAExU46fBDJG2Hb1ylXdWgkIy4sGd+4taXfhf4FQquTImo1xNRuJab5Mx7O0fTskIpWVhe9zNo441A00sxi+IQXcwqFex2i1emVDrUouaJUD3GE+oR57PpWfsLUeeb9hQLjS2PhHOr3EK0qLWi7mNerysWdT1rUaytJOz9v/UAJZ9MC0zDqPnl8DvYKRJsHrz1TSX7ZR38ONw/HnQDgLVMRF45wyWkZYFJrDIbmIMmRe5jPgX8H0sYKe1+lc0k1Sc5PEPbjNvOgNlrYbFqZo7S7FqCCvAOl1aknewjsMYzuKnWkNLj5MeDdKuK+EbcSBamgxJ0JKMYP2zXMZ8Ddl19cUU/xf4vSZhmxpV/Ixru2zGrbeG3coEGewVyi7IgWnIpn3OpxlnMAniXtLSeFfQtKq6NBUihCHnp8/TTRQg9xFk2nSS4iYuymSQ0i2XB7MvY20Cv4rE4K0KGNTpm84rXm4fk1YL9mZ9GYpctTSIL6RcyzaJ1gBPe6Nbv08NvgvwNoY5F95Ep1bQ+Y6aACKveru5eWr6Q/H8JDWuNNnBcBWl06FVnaRomXuFQq5wiwQmZJPMfqXSNY7eLq+6T2p9fdFv1egFLEFxHaWNQQ/RjdKmnNE9NMMzOtlMrsKPovMxiKDh/D+xr21NW+qZQY29WmgiN0jmfZfFvnaJcvq5dGTqEZfIh7xe9UwXPIX6CeuQX8cO8OPs3yRd0H9zTo68b61mdhf+/24cI3K/od5JnnP/ksPXQmdakbyCalbvKRpIt1ZzJ67KN2nsr5zb3QkqpjLMPRhDpGb+1s6bg0T7rUfqZIwvKBN7Gsm8Hslbrzkn5ZQKijCRrRxHcHYa6vXZmDsCQIy7EuzjmNSWGlQp0fP5ykbzFkna1chjdRi+eNMvoKhmq6m1qmFGUWa9O2Y/PykNZboCMQNoeR3DN5mai9hqgt2rMVidnZ2deT5KKbtzyGbOXxQ6RfI0dgiFHzviFBhPgh0CUm9nBsRpSR7jnaSpDZF8ylqlT3kaE3wV6AjSj8ZipAvq0txFSXNe1UREYDweSgiQHmx1DvlnadYyQxjayKtLu4H0L/FjYiad1ucnV9K0bcRR29fmIyftY5TgEji3D+kI1eLC8ZNu/aNIr3HtxIR5w6d3CsnaUuK0UB+ejMhhgmjXUnohhlguVjnNdAI6Kh4iUUqLWODn47fn4qt4hBTt5a1xxysM+NvdhSv8+rehk1crKt2kVHtVPTYXzYSOlB5qIhhvotKK0/FpKLFPt5eDxtDclz3N+DRnX2sCsMVOzGSKHdC4tushPo/4ZtFuuoz785YneBRrX2DlISR6ltUkcBHLumQ3O972A1Q9G2JguLXgNGWeYrHTQ6dXeM1BRO9cZ6M2jMWe+sy4W5KxMl8yidOMaRrWp4dEZckkOGmxZbZhrQNly0m0cq7NtAY/9XW5aPjmxJEg7G1riu8jc1RgY1mJYNcbSelkXCUXmMP0V7GTmqhu+UaEu+tyUIGn10U6CZcwr+Zk7KqULmKa5JjKH/yO5dybexXwSORq9IRXFRhQH80ScP0NZZLAvbfBGaAWXXuVOYN6AwK5VN/FEcY0JsYOrMYQm6+5mRy7V7pj2kRPFh3ccgL6S59MlylB0l+Rhr8/+zdibIruPIkl3Rl2EeltH730yTOo4AQTF164k0a8uunzVkPIoEwiN8gD3ZB0NRXsJmnnAgMMvdzqWvVT6CGMv73G9NprsE1XictTS00BDyXahcL/2AjLWJlkPElHuF9rXmO705/1ctshzQENfPfNi8WJV0czXVDBqrPvkJv1z/WugdbJu1rc+oIP1hPE8pk3sZpg2nhSnhUbLGwV38+jfQLeZSymCX8y7iJlJWp2sSkOv9FBVubAiC4zdd1vnAoIjRX9IIM+4EURJqmYT3YObQzGEzyeLdH5bk/LVlVwz5tpVk99nN3ITjzC0YAWZ8PgZLzV7FYIas0cgR7754fHbv32iVD/X/8+UJGKlka+Zv3Tflt8hjnuUnbj6xT/NdZkdpTSgTOXdd6V7U+SuI5CLvROH0Ij9wNroJMypEK1l/i6lVNUplSYsLSe7nzYIvz0FI8YqqxlWNwWUITeMMFuYefviwDSVUOpASStoDnNvtXsDwQzSFcPI6var9Rwyprm/7pwMbCqkOGXFArFysWLxkZX7Q2gQDP2VKCisJe+2i2uc2jxs+x25kCDZzlElKtp9biQKQkugKJ1thfpHllNH9Wes9FJnV7uNGp5zgoSvVmVBmYA9fXa1jGhoX9swGIn34WuxdECn3v95laICyJjGmj6yNEl579FZNXjRSSw6421v282reg8Tz17qfmILuFy4AgThLvqRg8zpqLOMQi+YVN/SIDPXOUwVfnt8/bm8AL/D2j+auyLqAtw+f0WhnACrGVYOWSZcW5V+DDUnXdKqkwVHo3+q/BSU55bpOsd4cC7ENwEpaIr65hIhDYYhumqkft4sFLGFLvK9N80XZz0FJjCUcTbjjjOuSCq7W4+Qi4NXl1sj2d7fZTplql6XexpEwUzIizu0Xhw2oxAzFMkZZgDhzNfNoOxmv92G8lGfk6Ocw0pcHgSS0RBa7GwRDbMLGuVtC8wztpjXiHSpL1F6Jr3TxkB9oLPHQqMIPMeF4WtDpJvjv3CpEhZUwDXFZo3YxvQnI5Z7vq4Ze5T60fswynYnD94c8yzL5tvN444nmlXzHW3wmXvnyKOzNoQBkc4EfwSoZV5Bi2u4y0wBtOjW5Nf3cn/vyJOrFqT/yY/fYuQMawwKYMyJgylE/TEoY1mv8jcrJFsg5evnyteY7YFI0u71xPNqvWkKs/kjWn4d2NDpllhTLeSzjy3NoUo6FCq7HdzHrG7cUD6a6TKDbQJMzZY/LML9i+9ol3OMnhc5Hv/tneGNQcXCCbWze7Gf+iPkOMDNv5x2pL8+NOFhwSp9fxfqUb6FlswcjBNdpYycbimaTmVBea8f1/tDuryHppnovonFVPA90YubAkOv9ecPGdGWy7PB44+119q31emb/fdR6j8LqutMVKB5Hx3qooMwh0RDbIjZ+UCbiGBzZGNmzNT0tcj6qvQkjc97ALud9EjVdzBi/fWY0XITZEusUWOSFJOv7ZuKb6ComDmocN/zQ/qr911UkIXCtiSJXSYZstWPdzywffg/DXHmmIT+DM2qCXi3U+wcP6V3vM0CS1AX8bbe31Cvs1duJzxChmwokaom9WIgDIsv52jrXeZ+/ur0UfGOiYfuR26HzIBl8FK3LfygwIM6kVbn5WevtRaQiW1yS/SCe/EVGEjR9qdLmQezgw4JEOjOptgOtt+kz28OZkXSu/O794ESn5M6NaS5l4JGbDeSYna4Oa6wnz1umd5GP4Uc4Ex3zlhJFZc+F5iV2yR/FDs7SFeEkPfxScAmDMbIPq6OJC3p51a/V30KPuEs0wGLcNagopcXrq/r/O25VTCMDd3XIir2uxmmEA0DtbU19UdnPoseScSpLgr9wb/OkfsFZhRkWR5JaXO0s9+zQ/lelt8EjkLpUgdiIi1XEACwE5Ug78+ADhDNH5X3XWMcn7nky0Px5y35R++/YUZnSRRotXL3lw+aWvofXmJGIX9tdLpMzl/ld51Ps1eScAt+2MwyuPZ3OsPCGdJOnL40Qusgu4lbIDq/IjP6i4KfWprmGMbGrU7EXWfCYWDpOohhXsrU9OPbFV89fa7wLH2se8cAVTx9GzuYKRlZ7MuO6uoTJd31d35/jLfQoF0VcG+p2u+mO4ts4/LiMYhiWtZmvScSDE0cf8eSfv/wd7OicU9iQrAcsjXsGtLfJB14+pa549vLHA70LHKtjtJFwO8dzPkKmMv2wjDXc+GAmEyyPW+t7S/MIyRaE4KPUzrTgbo6X/RhjMZgxesS+erbRs2/nQ/T9x3pIWthdkaQ8VZ4vbuJR0ca1Wb6ewjblYeKNLXGYfrhT/vJFrb8CMw7BUuRC4VgwFdrv5JVAUe2NwBkGpQ0qrWwxzAhIwmrXflHr3e3e7v0CWdp7KcGck8dBEEGKJZ/8BeR4DyaGIMoWevdgbLan7O71x1P+GZSJh8sSb7eIZMKN8DG1PntwLgUGCDLoDETqBItehrFfzsT793//QUwWESwlOQl7UaTawdbt/YOI4ZFMVTgzbJ0ivdrXQp9hXG5AV8d+pQNQOEKEr5aUiMEUjAVZNHfF95+h96yIjXdf6daop8+6bzIuI8n3+4HWp5TbWyxwMqaHzEnyUSFEeE04E2jeNT5GuORHTp3+b3vALMxrpK9KPTsIR4VYOmAkZJGc4Wc3RJMA+j3ZDBxRlGcZ0rf6b+EctGKB7MGwnXFsp0vUMavpcdHYubMzV4DC/Em8mVuNhJ5+ZgG+q34O5kBFxCA2e6FuwkzRHrexicb0LLbZdJdF5l0/cM5FqbdxDiTsHuQEuJ1Q8P30U/NDMIoW3yZPB9wg7wf+CEhXfVEiXPuz+HtLsu1wQK0bx2pnlgQ8z5ZaBt0uH2fR8F5LfoWLXuIp9tV2rCk6otKMV6+9GIlvcP7kWPIGjSBeqtZIujKmwn+znslC73ofo4eGxpK0sblT2h5XQxq8NhgWiqJecA5nSbs82R4UQRVlSme6rKQUjG4nr5lHYsKZ2mJlBRHg9b3Ge1syqImZTIQWaz+onjUhVUpvLDb4KrDIixk21+aHSznLneC/1vwj0tGORA4EOU3RIGWHBe6wEAt22s00wA+B0cczvQF1koy5SdtFRkxgKTFwxJLaOif6OnwYD4xLIgzzK7evdd7m2G4HKc9LCYupHdiURlA098VohqG9yuuYJC3fv3Yx93lVO2cGdKNZuGSQrhx4VXJQ4Xa1GHGL/Rq00KNjv3dEwP8Ayuxf+ZlEWbryYUJ1yBpHHGAPBnOYCkT5ycsHLIxd/jS2Tm55T69K/d8x2alafcBVicV6uk22WUhXqm5IouvovvxkirbVhTsvApGrYv8FlK3lClZl12QfzxguOsKfg9ePXjJXKbL4RBQRxlAsq+BMbD0Wu8ogu9zwCv2P2v9nWHZR+Z4jMmSZsFk3NIwrRoQ0+B560ZaLbY1KpNbFj1PEwRU1jHJ/hWVrwe+uZQMDaEzH5/U+nxQcALtdCd5liglx0ZhGZUTDvUr/Wuq/Hg1rtbLklyNV1+oXGjEnf2jTmybMxXT1iyE3VJuFHnpR67+DyKszYjsZdCn5RiuAijdCjRDzlsWJpEVyaPeD6byf13XefrkuntcXlf8LjFxrlvcXexqH7y3LJaZi0fIwYjElYVosORtJNsvmf9T4O4w8fWfM61JihN1yhLtcs8ImlMRZGCgX3ujipOgV4QGOOYdf6HgFCvmU+q34f8OQa+n6CRM2nNtbrE1X1utcC1tWuts9DBnpliiV2ZKBggmplY/q65L+Ncq+ASLXytvRKdCLCtZmZE6xVkeMr2YKqElYe/9cfqHaXBf67xDy9PWhM4lFopzKFjqx8QqoDNF9J6gXqDlh50efD/aiwwVgKGP8X8X/C4T8PJBjdQp/E+8OdpBCbS1W3M2wmhVCwr1xl1/gTxByLZF1Xhe/d9eoozTD351jTekNeCyJQszyiRbESZDuJ+8y5kVjNgr+CUN+FhzH3rEVOJV0C25CMls6KQaqL/amiMXd4kVzUeI/QcjPKlPRzMUxac5aOJQxJ8jGtgtSIC5sOygDaZnjXlT5jyDy9GFp84RSejt6vbLiwWNpxg2NiCU3g2d8Gki3ZUUUvQcQPb3695r/ZxB58bIGXCj2921KR5p5pUx5bzLH5Ll5ZkXgX/mPZ/ovIPL0RCHVcoVtDxZ7dK5a1ibdIBlOUHms+6Yns1Mj+bXIf0OQpztXVpHvX5Bk0m47sToemRmZhvH0x1SEJf9iVLdV+H4h7sOxoOzlqCA0fDCSrIwdRw93FXEJgUAHv1q2zx+8frSHH5XeQ2NdEZp+3PhVanhGhRkpMXZq7/sUWh2RBK0skXrbWX9CNB/F/o7GMG8IG6rBEEkJwNsfAEJtlDF+G06ciJ6cUlgRu8x4ta2jIbYEYwof3CI0vaz9VzQmbwl+/l1xmEgH98qObsbkgJbJ+9AhAo50a/NQUb73K168F8+gMd2WicGRBYmTlzP9vTQvmnunXpfMFAY+5eXb10LvYbH3N+MYFafu9VILQMJlZ0wngmqwPOMR+jfmngxwl1DIi2pvo7GohGrZLEU2AgXiWSp8b3H61WQ98SQx9TRv9o2ZiFKsXDs3Lufaf8djeFSxKQ/S8mdR/72RKEz5Fua40V5c7JDdMlwcNT6GxwB+WSqsnulL89ZTY+TA81PadWLrFVmJ5ab0Sra+XH4tZUHi4UeS+7fy7yAybfUGodqCBrYDlyMgj6mj1KfiJgiu0ZY5W6s7y7rc0MfrdCG/y34MkfGK5I6vhGe8x6qMtV4zwy0UBRr/LkRnUHB4lb8KfQaRbceupLKuD80eLzEXDX8l1rLwYkhykqblwnaQ49AEJAv+3PFelP87JlPYHzDBSVLPSwv9p5pjl7dc6diPbu4QtNewgVHmU5Bswwyyyu8Nu0j0mRs6x4g1W9C1pgpM7Zg0aKfSyYnExa8suQOj3gcQmQz5tc2LHLUEtDLOS+ZdyY8f8jjJYly0/62cYe65xhuQDG0bjUpMxEhgDgcJPxtdKU8bpbqQg2HbbeeA/1rkPUTmRabJmEWjKfbDEk7WJIedCYt/XNmSbSJrVYxCkCK99q8130JkjhqzUp/SFGMwrzEM5idEN0xWlSN/ZLRfPdQbkKygIaHJqmibcQdmZM+74MdfIhk05diHQbzfuR1/tAf/zGH8BGZBnbbXKhIsGea7SBfjp/ne5DDmQ36CX7h2W63vf++hdVnN2oL5JCf2XoRnw+RTwWFMRIo702faWkT9cFg8P64q/RWfVRltaw7gmHjmlrXN8zPGkEhpVqRx7nLraWzUF4HuVa034Bm0ItdkXZ0YxoY4LH+x5t4AsYL/6FzRXojSzr8lwUDLtMojBOw8VP6s/Ud4Jm+nqDX07k0FxaCJLc4r4m3iQW/QUTC8X/dS7FvT/8YrxM9qn0FnBA5hV5Ri1Xb8Pb5qAMdmwyWZqynY7thuNfJZFyHDRZ33wFmCZdmwdsjydcEuFEPzbOct18D7Kiv+OE3EtsKde4BzpXeBmW4hsg+2z801+SGQeQCYZUvGk2SypEwdk5u3rX2Y48bcF33hKPsxvAMOrIlFb+1VxA7flehUGStgC9PQcRYvM3RMFnmRFTZQA71klJlIWIhqn/XfAjzY6iVHQ+WE3rf/wNDkMVZ2ApJJw3q2OhHfyGhkK2fLnj0SLl68LQ8DngZYTxm+bYM2AhDrJteq8wp2aZmPRFaFi930dam3IU9QPkNinVRBCfK+b2n6RIrpiMUO54akW2+IJvHt+79X/SJEvK785gZKhvEhsh6lvWH2GIy/GGZ2VW5LoAMj1PDKF3U+AHe44LSC9BtM5CtszG0K7LE3CkPvi1Gyd+2YNQCQDDWYzC+vDkGj4AfwjkSaTBqyGEHkB5c1aoBLGOOafKQzKZGnnseP5xJvwp2tbeDT7klxx/PMTWYxHycjADOufrzddhJj+VrkPbjD2DlDuWoRu3Ff/SFRyysmdFJqkdMSEZelOK3zP7ThyBa+1vwj3GE1zyJiO//pqrwlEE3rvnEVh7SunxBTLRq9qyd6A+ugAXHqFtBpRvn5N1MMFPMCKOb7Yd6WiudNiwTqolm4x0x5b50RFEPWKAdudTCnnJleG9uRDip113mHe36Ut5dkCal7c++f+X0zlnZcklVbkvkx9Ze5A1D94xhqj4AwOZt3+qTtpdRyJhxBGD04cijUDByb2EZOziLhLOkDL7aHUJiEFUl8gYjlTKVnSS1LJcKzw1DNcFl4l2mURcRQ5Uw6+Sj1JgjLOTpuy60XUWKX9gadiz2w0gkwIgJ/pK0PzNOtHWrP1lh22ioUOuHj829P7cgwGNlaUuZDEUPD7SUJbO3fNyt/RVcYFLTFEHkG8DrbP+z1nuFNe5ayGElnyl07mCxrfKVyNyMW0HIrJTDkY7C8+sC4hL5d1HoPijFIitAlU1Lr72TcxttRJmUizw0P06S83KwfNIRzsbfXZPSZrkvClNkw56w4OpmGoiNCU6beqpv/eRMWT216c9f0teybjMXimXdFCSsUilWnNZXRFHMfhKmwmguk+uqfNT66Ieu7Aztzi8ACoXhIySmwl8xcHSnKJJI8DAYj3slnDS2c72I18LKnj2utPQcYZWIcxFwNabj42GZM3ikAFy91E24O8ALBE86Eb7AJfHudqJbvsh8DjIoNZYK/HbuegHbMDI2zaDKs6KeBez5O8GM/T/Av6nxmQeYjh8Xuucm6FNfFSPwbASVQ9lHTe7auCgvV1rqSb+gV2ZnObJaL8u8tyHaWPQ5WvBRKVsWCZlqcRUs+gCI/88M5IF/x4qJ7CjJutxkDgVSLTP+gVtWKwRbODYxHmEuRB5fLmOntpGPgA1TpV7uo9yHEuJ2fXnmEINcyR53RPFLUNxRzh1zVT+kVvxb4wOYpZsjqLSbpX1k2YQulDU+ZadF4F2H/I9tFmcO8hzY9f8wN2nObp6R02FoVKHLw8M+rrIwjYcE5rHbbK5XvD/UGGns3qy3KlzvhhK8IFCNXl8kI5AzAg8ikI2CguNpnXNy7T6yekpddVmXbgSO2s4c3OSrNTHe5IbbrINj0I35MPNujk40UkNzsxu2ziaFBR/8Sbf4S5jUwviYCmetim3JR5B3w6NnKKkHL2aU0DCTLMJJMS0ZdiTMkw7+Ot6n/P3ebXmkr2V3QPFxn5A3ZncBYMr8s6Pb5/bR6mTLdaQ3Jlnxr1V+ufK/1F+hozjd1n28zEII+VSpsg05De/D4Qv+K5ZP4lWmxSNoVN+F7rb9hRz/GWbGkpFyGJuBSpToIJLBvPTm9llNzwKzoXWnicM36mbJmcoj+1y35Vek/QEdv3/D2LjB/C9trgQ8c5B3XZ2mp0bO+D3vYn3VqyZ0ZW/scF7/FUe595GiDFqctvmOR53FlZ5TMaizYkpz0hsVyGUVhXKzYL6q8A8NmTOqGFxSDVWjkcsbSoxE5BhJQDBhrvW65m7rTtj8vum4CBMvab39W/hsS8zbV0luYRyZDtFTdZOwI3nRQ15IUzifYLk+GJ5CYHy1oLwkvibKBK6XlkWqePO9vhp6dSxXowv0Y/K599NByidnMOGdPovla/q9IzA+/ohid69IRgwm3U4GRAWDbI2ER1VVyyE7NbmZS8N0p9nAxcBhFP4LDvAW+ZYc3mmD6nmL/nul5k2PAoIoTzsR6DFxk0tT8y6e/ir0DxvyclmYta31SRxOlu6BRkFVhsBVo1Qw/2he4e44yO8eA+JX/Kv03IDZuvhiy/DWziOxybTWSz9wygCj7scOlszxNE1TmTRzmpx5HIX/ZQzZp8izFnhUcxpMssmqm1xUNTFJf1Hs4n4XFYXwUfBOIjUeaQ5UBCtcW2SihTE8Xg2QYK3HF9YUFVMoS8XJR4o8Nrh+tYS6KJHQ5nqkzlmiNFai3kccME8Dr0q/Eic8qfwaMhwzwDLOrJT+C1MS1yjMwh1EuKfJqfaxVr7kiggBDrrm2FzX/2pV7W+mwQm5jJWKU6jr+UJYmzayc49cfhU/xa4k/YFr7nhJqoT3eR+S1AVUPR5k3A2l/NDdGohlerXz/1X9DtDNNu8H43HoqGX/OBV6cmetMwMLAW/ZyDiMof/mZPzKsH59R2QALsWOwHjwiXE8W6Vgs87fgRpizqrlXZnn5NP+12Bvoe7yZWxeVFP2GLUIrJmGNFsuBc5fRqWVp6uVMAsI7Fur9I7AR+pArctErwzmVKYqyonU+4S/D/KfZL15nQg+2HuuW/qLSW6AxBVrVfb+EkiWpaULO4s22ErRW2oxyy4ugIvklmeOq0huQkX2FwtejC2wNtv9vpLiyrec8DUHDNQU0vW8sEHyQtWnk8XpZyPrF4eey9l8xI8/L18GVZEZQvMQfnVELFxWgIR08MXCwnlOu9w+XVs6Zqn0GMr6Zhb1jvZ4xx/Fcs153F8MvholRu5yZVDy9lmEArvvyz1rvnV+syNnN7uJXVM9N0fDFuP+ioRzAWatHkir/hnt9f653Qa4+uaRo2u09xsaNPQjzGGWIq5VhrD13CBlmuFP4Gjq4lRj+WfbNU1d8hPfnXhTsiRjIt4ncTXFoW44CjDQmRv/j6d4F4vBogyf8OWtHlMYdkGdALcxJv5i4yDktXJy2jwFxviLXhx6lVLj1Ba56Kg6GmQyNPcM6DIPTkOERMKRwr95QPzhp817+W/l3gDjDgd0umLus4qi4sxJ1BBMDL1s6pDm+KtAPzTycELM7jkj46xp5P8p+DoojEuSfnnvUW5vIqy6HGLSpvtHfSWNtN8eNu6Om/6va21icFjoiGNxOMnQLsQK8uZdh00QxU4Vouvnxyv84jPOav7dumi6Lv4nGpRUOMbMX0b1r/Fnwo1ulWH6m0Iz2/OJCfgCOFwkHxearlfikpnDQSBav/NjMu0yZeTlONL7v/udEd3dovuh+noLjSRGlBSutJD+cNg0yximnPLp6tMrgk0zpDBq9fwyOs1twsk6QlRfgC58qb9F5zoIem/+M9InnWaL3T6JxSWq7XOGTWDworqR0Bo5BEuSzAQsHUcPesFjCrqzxXExfi/4R6zJFC2rCGMkgx+pmXDndu6OtFmf0AXjt9b26O1AXuSA/fMxVhm/RfIqTKRG4N97vLAeEzTiBw3210vss885MI0t+zxUV5T5YpqLZUg3oXzgHnDXwHYdbLGHdR8PVHkGPHPqNb3xX4Tp0eNgfMFRFnsBiCZskyZzC+7c2i/th5O4++u/2EH4UD7R7mai6rlQL2Kc4POIogA8g50Gl8fZzsOkOgR4rEfii2hsYEmpUDB4WQYDzu5NS+bcVs41KKRDAHZScBZaoOqNY2vSoVl0xi6u85qr2HzEkclUv91IfS82MN0qbdgIZJRD8LjoVWFQKEh/jL27i7TQ57z98ewxEkkfXYTi54cGLN4NEpnUcYiKYBINkBiCHrq1+r/MegHxfTkUZ7K4Ls7Ob1cq2ujkGw9b6/ZWheLRITUz0lqjfi2Jvr0nJRqlpOFsX+nIM+mNVJrhsJuyM6JKyWaaedy3ol+DTXLXvn4X/Ds7YI0RNOokaIiGHVVycpNVsvvXJLSNbnvqSmTdqfAqcoVCJjWDH7fhK3GWy5N/OAVGQsFnGciAFqJTSEQqQwx71nSm+jDNS/MCW7TlwJnmgl1atQ13fLhOtjqoWCrzLxHn4IqLa+28WsRQGIB6+oP3ynHgMnLHykkVhg/cLmw6tOeeZZXdAvaiLbJdY07SGuVwX+gwu29AAyDU4WRMpJR73QkLpIhG878lZlRNMnZ9fGBHNEJ3jmW/j24O4TEHqut+4NoJ+/NnzmKIRIebaSUI376upksp8aku6qwS8Ilflm1qUIvsmoEJgBuCIy4h02s07ZWsmiU7gzChLBMIo+AFYhmHWaGZQ5LHTVZi5N9rHJNjVdoRlxE2UJe/xosIbqAwyXZYNnai/tLrdbGrjIQrUWIFGU2Yr1f8q8hYq6xpUYLSeRPgiXBVSiralyXZQ4/5zljgQMUhitlfTq7SvBd/ZPm6dIziyDmWmfddz+ziFmCcrFwDRZaP7ECbD/CixYHRYbSteAIra9BpK9sJq32/bJ8k2L7+fhzd6YcTrtmERzY5mKvfNRrqvVi7bH84MX0I4Uzjel+F9WKZ8tKzEtgqzpCRFqTFcYavMB4RjqMzV3BJHB72t59cflf4KyroEKBIzJSUDif7AZBwjD9zHSsbGxxtkrAbLMVqp5wXkR603IVnqDvObuLVROqqyzJtwyArMw4Pc+ovCqNA/dv1PYjMwJDgZR9OQ/ij9V0QmGS6CV58LTNCt3ZLRppwW3399tziw6pkiyONvEoSLfEVX8zzV+xwVdLtGmcB2pQ8SEs1QebAn/bDzgY/W6lGT36uiSb/XeR+StawQzUCmSEBv7WnKOZ2Cn64RA+WW48CeJWY8XwXnau9iMirqmYbOR3IqU2JkH2RrLKvj97/jMNaZoiHBYRzuESA2vzLvP+u+uS8L8rcNhMwlJeAEa7W7Uby4cs2mzM1k9vPM413jY/symY86Rom1VtElO2TwDfQ6rB8LFOY3JsscGhmphW+VTVkkVquIRs7Mxq0mrB/138ZkW0soIWB10Dx28CV3Iv58Wb5TNBCABE3QU50S2XlQ9Pgqn0U/ty6DLgyzqmyflzqtYv5k8r6FmsolUey9nWpjdtUfreNFtbdhGf+8hM/yLsQtY0QnB0vLJQvy+uq21SG5lDFJwn+aP0mN5ybtovTfQRm2M0kU7aqV3jT5jGHudOxOYygZFuPj7Z6rF+fxU8uyd/o69xNmA4XYaEWGc1VnfXrvk0sbvmDr1O1QxGgY6mo6b1Df9T4AyhC9efgVW5Muz8pkTSVi7jCtMaYLY5xBzAWH8Ry/FnmTvJrFAY1ZyQeMFptZzMhqz3xnNFtYdHnlVb/W+AB1detYyWAZ51bRv0m/gGMt3Y246smGpoyhC2ZgUhaVyyP3oTUPI1knf/amQUeYgw4LtvaTviTvbo4Qb38n9tW89rPSOxiyKr61lHELHA7Wuam08dbM4J4E69xe+Y/f/waK9Fo8q32B5AcDPBovIk5zgRmOOdNvGi6B674s/N/7aLgFzMJh69nfZ09vCFcUhBRkmcaxyh/CkexXLBY8l4UKvhusxu+F/oLLZq3Vybppe0Pfj6bKWAJBe1EyMHn1dcqbijuyAJk31LqOwy+K/Q2YWbbVBm1Z6YUqG4ztLGhKCfdaevHtKLNQXRVWNTA0NRhNgDYvX4e69uRXtf+AzIJ94c45BW63Ct+SZJ6UMC9mmYuYMyshkpc4DS9oZ9qG7ZZ9XbwW93HZWN9v8LsovItxPU/QQz6QnDxPixcNv9hR25FArHFf4x8/a/0dm4Vh7lIaMmevLQP5EV4eGfRgWp2x7JnemybYZnDrVxb+Z7V3sNnhuytENvkgr9XsdVCRB4mWnBWa5nii35rn6vbOBgAFCClevsHPDMaC4kvjLpLlqxl+S+8WwSLpioE1TFajTfBzQ+nErPfl6tdaf0OSwZZ7OJ6EwPPSUB49f7E0H2c0XE1zlhR2v15lqvEJJBnsdnetRGVgFEB62UAKphGwAlOTLAtvmkYYUZStAx24l1gS41KxCUte2e8f9f+KJMOkXiYR6nzPMhAQtznXosOVZQ5e90WKSYcha7aZ6qRebufb5Qf4CJYcp1vVoGG78bjHaMJ7GMNwrEiC0cK6DXlnuNv2fMufhd6BkXbrha2fABfmoKuYJWrEjTdJxBHnjx+U7jGPue1vyY2a+WtbPaUvq/8NSdoht7VmIoDBaEr6v8yLeeaGcynnuGToZQzfP6u8iSOD8dicmtzdqQf7UmwUWE1U+Qh3Ynam5F+5RLI4yyCOzqJ93U2r4JtAcojcNvyo5UIE0Kq/MJPSozlsHWedz0uufTxFl36W+COMDOb1pMFdJjEa02Ih3zb+MpzOB83yZHmd1hn/Z5E/48jpLbPnD71XedLj+Mb3ooxiFr90DQhJ1D8WM5PcjuE4BR3OLe5lnzX/gM7GQ92zSbN0O2WqR9w0Y52xZtmIzf1IZA0nkc7FM/0NmwXb8DVoqbtZGrle85cvRreFf6n6/SLSZchVVqv+zzp/xeOjiwmuS4+TGRaUmTPGIsSgbrZ9ucY5jluZc3nV6QbC0++jSK2WlBATBXUKh1XCzyuLF94mYBDl1duNNWM9el2prBel/owjmSzn4QRdm3x0MUtGKkTvh6l2kzCfYyDNHBlneV49vvof5d5AkowNQtV6oYmi5IvsHwml87JuaFUGkVAzQWt98rFD3V6fZBkZO5IM5Y/af0WS7J8zs+Ktd0Fe3mQFhAFVRc3faHQ0SqjGBeEoc1Om4fK6k1S9z2BJvaOSawZWu5wN1YIP3v+qdYM61a6y2XuldaD8WeQ9EIk7dZEAmumm56X1SBxFiyp9zr+gZLol15x1ZFvXkZ/V3gaR2jZmeY10x5q3w6GQ+hBkwSAJo27R4JNlTuwODt0mOC29fP1a+D1cFnqp8j6gkjKN85Soa8sFdpVxcX5Ln9oBlfgULAuKcI3QOKpL/NjbRS+dSwUwysLKIZ0GzOcucy7aX6C69/gqIYHqJ5rNR/m3UFnBLQfzod2UDOOkpKOsNtg1rqv9JY+RtoY+tynqaYwhk+TL/WO40J9EZUyhU0FQkJ3r05umtMNCOg9BOl0FjJBDrISQWe1/FXsbmSmK1DwyMoyVrhAnkq4hOZdovW6RQWcaE5LWSIjjg9h6H5f/Kv13WMYYmkHvhs37NNb01fYQwaIrxQ2pRwN3DZvC5QX9ADDjQOhiKZXGCqePr1Aml814eAqIjMAG/g/+BBtaAkFW8QIuXuAHgBmvriMAcgPhPc+EOm+q3lIHy02XC+o5G5W+/0Tbr3/VUD4HzbafHpjqMLxWzO0ksk1jSw4taQhsJwG1fI37+6zyFjbjY9cLUAuRpB5WCuszvRIWR1gOqnoG/UlbAGxPToYln/XewRMc+HEYvQHSopsW3EdVHLv0NBoODRWUff6twjvIMUjwntiVe+XgGMzJFr9uZ+m8cXHjXY1zLn7wG8DR6f7EvAWKkm6mFlZzp2iSZ8gUYXWRL6sl2WfzcnMATn8QhjRbaRfT65XF3ryI3UJZ71m6LeIlTvPv94V7HzkyWU5B30lkoZ+RusSm3DQ8nNg6FDtJ9V+aeVJjynUexXzU+it05FVLsP02cMg5lAMc8D6nbzLcDsQiMAr1y7YUuUlaTVMuSr0BGzsG7Di7bb8+qWEhu6ggakR4kHeCbGBI0d0OU/KuJql1D4mUvkEeDK+/Sv8VNfKGNvo8n1uHoqZ9TOYMRUqE0aIOMcTQIR03vRIZb6AxX5T7DGjkKqxyLe1RWVHv9rSd2V5gAjhSTJbTwrVsr+C/FnoPOHIY0VGlgHeOZ0jvg6Y5dbLX2Vm/K+tL50pPm8431bnYu7hRtttOc4FcRJBDlQ1NHCk/vROfJFYECE75EzqPAAaFd2mv8rXs31Ejw2DpRXTNykcFW0qLE4ndpNOalB5TOzZIfnGIPYYahxlRY4e3PU/UNXGErCJ3zER5Vdk5gDETAmqFNGCQveGKkOSVrkb8S/G3MCPWXwlq+L4YY7XY5PoY6Ky9KNkFPyNdeOSc5zrpTNMpaDvYV16Vyn4WM3aH8jjXLEc1DINJ0LHvTCqOfLgqbOZ8TVK4qPU2ZJQXm0gpvnZ0nFE4XPEXxdKTcPfo/GtXbfG/HXQxzN11XBUxl7X/jhnx4cMGaCuLraiia93oyqb5Jn4va4op493qz5jxXedTy7wNxYjzm2HW7BmV7x4hQLTGpjKZ3ASKEGp6MVpi1v7USd6bL47jBzAjM+RG2LpyHlOcW/BofIrYDKLXtsihyhCU+K8l3kCMsCWwBt7aGfz3GH1CB7UCYTPLKep49kJxTJcv6GPLvCjlGzYkVd6lXe1rP4jH6ryzqsLfDPW2MOKWMSNf7cU/a74DySrbm+2+EHSd3mmHkyJaNWsABvuKDZW1P57qDVQWZZjBxqmPVE+zGuDQNa1jxHUmLts85vonN/nPMu+gbzj1EgRUGdUNP9sxxpr+b9Jlz3T7Mb9VzHJf25j3f/EZUBacH2EnNY+5PGagAcGIR6FvM1fvy0z1Nf6fRhon5f5FqT+v84JMzeUx0bPwCcETzWFsi4MAtOY2DHnjbMUn6QCWvX+19r3g35GZHmBB+hZ7RZUXmt6BXrW7Y8aZ5R4uw3iifrCv8hj0NdzMxMXP6VX/eC9+hmZQ+mJUxmBU6hwgvGB32xgfQDuIGnA282X0JhOQg03rr3LxcjxJDu1EHTnlwCdFmWtfNkM7wDsjobCO1nzSK3o6TzzPtd6HZ7lWNbnojv3oFLUNbtPp2leLuK/hqG1oMhNO34t9Zq3nth+2cVHxBmSGy7GLG4oggEEZ80UcxbstUre7EM0L/wOlrH6Gn5Xf5FsmLZM9XETUprDbp6I/TQ+dFJbgMbQD7vJQewyjjVQGRhht++iUD08+Sg6cuyV3ZMgOs49C4iavSa4iY77fkMKMis2Oj/WMd07134JpfDziN8c9OZ4DRAKzogEq99nurAB3gdMc3oWSB2yUgzvmqX981/wYRsOglWTQ7R3hkdZgYSmsRbrRvtAn9+P+XyKd+Cp/FnoboGVxhuW41lDPpyKWaz3ItmBrxzTza+RkIxlPVuMpwkB9tfpX+b9jtCarO4gTNJcMIAdQv9qth6Wp5EiPq8RXdT6118tRhmHVQ01p6Bky8oLKt4YgLSvWspsIQnkVnck7t3g7k3Df9T4A0aDZwuzZZYbdeO5YefOM7TmC25S6aL0a9tNruO1niXf5lhllTkxASLSRDHFRIc/MCVbO/cMmbCuy1q9F3oNoQtdMw5urUudwcMrmVno3IFqckVrvn52ghyz32YQmZk2T/qz5DkRLEr40J7gwlRb+hNOajUH8NIACPJ+JCB9P9QZEK5o0OqkFotEL0tQ0lAPj0ht+mHI4KUlWI+zP9uDm5kyWwe86qpfYwlswsTcJsZ/U4JEWWSTrxK87fX+ed7Ak86GmWUwfK/E0cGZVPxnsl0aH2A5himfJyPuDfApBOiVfjVShLOY3unjIBkk8OnYo4PG68kEzWuLwvdBf8aOsJ5oUm9s3H+FRtUPw3/tQL+A26PVxbsZaXUZcLZ+kbh+l3qWChkyeRHQZws6ulFCqqtQJ/Obk23votqFhWuSm5cdOKYXxk+BlvqL/o/RbO73t3eMg3bdkLBbeN2gOSlYMxgeFCdbI+tQBlldfvZrOM/B3uc8RQat6oj3Pi97D4f5YzUTYa/QhUoAducav1BD0LGE4V3qfDdqihNe1MH9Pw7QcUkWdOm5CEsBdyM3MQBojmDPB9lztM7Bxd+QWHNdl0IklxCKjhPk2oDbtzPPkh6AMu8qJXNmfvEL7Wvm9xV5ymrg4XPYIzcSS5nD2ynDpY7jclQN5miC8a3wMNTIX2B9pQDnGQrw0PAtTxj62sLEpjnzd+n5Zih5mxgQI4+4NjMl0XmycV0vf6r+FGnl+vQgFFK8cUyhfu6Eznz4+jFl0214nhsRAg8BYxr8sV92rXpT98HJPWeHFKTCaY7a5djgq8hjPJPABc5GyzEt335T+V7XPaPVqkyvb3jhicYXFCDElSaLvZtNezwcYwzQO9bmUNjPievsfnvVN8Bi6uJ+wlkn5C5KSmZ/dObCwLDSx8AoX3c9j2HFrHuCrNYWr0asVePiI9bqMY/0coCddL/x3I+8z9+MHkfFd8GOc0OroxruyrJ3kO4MTynChGaTsceCIae/cPrh35xpvLvjy9nF59bFzEYG9HXSQNqYz8JhpKvNCCU31PHI+V/kAfAyBKUHrsq5T0p7j/zuYitM/wMWQaOp99DZNot24lr8/2du00Mzgq5HbASW8pmNiYTfhgxGfDu7//kP1ci7xDsItmjJv/Q25Qwdq1bR6iRM0+iMPHJctdx5rffzuNwFu63CVtlO0dlvdZ8gQfjBBaWT04/ajqQNOoj7Us4/KuZN5AuHu4jco6aCImduApM+w7opwczv467hDa5v/z/n/c//EDM36//7v//nxr9z0I6shtEFNkwJe+2WsMJhsAScJ4ZN+P4x2a0LI4g8eOteV/oUh/6tYMKQsJrYmhXjHCmEj000RPUKKU4mDkmtGajM9fnDAp37luti/UeR/lcvpvoFX0eca/JMod4Sdtsb6qGApj4OaJsgiVLFmQL8QSw1MlFnwbThyikL+o/g/cOR/vhaMg51eiw3jQD/Dpi5VF422SsAHu2tPprhsei0g1Mum7Oq9+DcY+V/1AiNB51vrndw0pcEl/5CbBWNJmVPlSLbE5tod7qzLOv83EPlfpb7f1T4Gx0GbUtFncdgKk8bKMSHRQ1gMTmEJvGL+Wuz/iiG/fnMlYPrn97sVy1AISOilpetXQ8ifpFQTR2ZYLHGkAtGIH26Iy8L/hpD/VXLRyaUEHTprSNh9zbmPMzb2xE9KZ+ecWeO/Qsj/PB7yMBuojN66E7px746wRMK2G9P5jmlRTfiDMthRHBS2H80V7Fbw9wjBHS63q/r/Fwj5n9Vjayp7rViL7Co3wOuVzo6oRXlkWNkpXpY5VEMe3YJxyKFl+ANemGX/M4T89ka3xBmaA6YO6nFJGKkjZZOTWCF8efS886rbA/bKX5X+r/DxP49ijKtc1yZBjzLSQ+7Ozsazitr9ygqMK9qcsrfLvfnpdVX7ZUfxr+jx21NOWfY/tcliRBGLY+EYJ4kNoWxd6KFEyubLt/gf4OO3cyJkxdzukkIvkg2SOJRwbMYIgeMdDsoIK5MfmhJoErfRfgiTnwX/A3z8dsvliMRlawbKrAMFfbQ1BGqj3v8Dl+V8+eL+G3r8o0rey9oPnRgWh8UMwKDXJfveZpXDuczFr1X+T+jx+4dVulJvXKIxD9L1Z9dsy8hYF2Nvws14iTWJ3u62NC01+sFf67LqP8DZt+e622ko1bZOeT6xXgdEbNzq0BaNLpO78vrjqf6Nzf7zmSIegxW+vZrIMMhCUASwXcCcW8n8Yq1KWNr5sNO7LPN/geH/eXsxAShoAOSt+wnDJ4c5jiaT11V7n9daoY+PQLIkdaZce7bCCMrMWn4r3RiXcIvK8F4CtDI8z+fCufqXb99L/RWTEY+1gRyWRXF7mMR4FWTt73+fJ9ywT5PV7nTe837N1uvHZM3ran8HZYzZeifda48qZGfW6sDwbPFilgkCn528uCFPSLePLKMyE9WcNh5Fxf9R+4+YjPqavPM2zA7ps/FCZPwAlVzIRC5racYtOyc23MmgaTdzmGe5z4Cy9zDWs9UobjivJ2W5tRnQHptxQoESsBOTLXwZ9dSDivOy1nvAjDkxtiel42cZmMt70nYDmpBepu6GAzb043ZPAcjn88vHZ5EZ50R24npWh3Sh9o7gXfFC9Hrc+jzzjnTH20P3qcnuFjTq3cGw97L2e+AsuawoaCKeRE7gfMu232tGB8mrrJubZGuz4meRj6EzdUsVElWtW6OImxJpDbv0CSgPnkXVkEbiTtTM0Zk+uWzIDXNnxRYc6F9X5d8CZ0zpG473cTublM4JWth6G0XmMWPoTHN1sPAHKuorjURe5XZ0kG3Msh8DZ01TJsJ5y5jPm+s87FD7S0RoUI5UAJ139Txu8vF5bAYDoKqDKF6m+KICFoUd8mv4aTDMuSc9R5IvvSi6yobz/0P5v6MzkAOq6Q2wVzaNxdzKoiVaQRGNxRz+3eIauZOzL46KB9BZlRURB1PxWAo3hgQZ0wR27CjRwMNeLZGb0dN5b05mtng82BbMgh9AZ4At5/XTMnaSW5UlOshwYUacxo/QovwxGvPxSdijlT5p8L3q4+967xiZ5z49LlmnQHZhMez0Q/gJisqrpK813wM9uuKqhBp9bqTKupESXfzIYNaI8rIDfgj1KPMnssJtifToYB461TLk2UjJjmjpGsLwCHu1r1fv/7iQ+q9amRo7mtyE7RqhnySFZstGyLMrA53LFrDOoLt4eRk8M0agD5BfVmV7k5VQZcMDVHrz8cEKj4tlbDuPyIN7BKYFWTBnyVfcMB1SRhUC/2IaYxiPnVwKjZIMplUZmx2sWK9r/RWnaRxv+Se9Yj/1vjsTrSP7c2LMciXoS+6WC6ZklXoMYr6u9QZKwxbLM1TeDqXhIx6qiDDMjqMaGP5UtQ5baRs5KdWhJ6kmcTU6hoH9R+m/Ls6YYGZxKVNvCthrrFWhpsAgxCMjqtEsxsP3JoDCsG/ngl28wQ9uzjw6t1RIJPEhdpt66pz1phDQ5FPy7/Gp0WgeeIGXhd7GPE4Jl11qtoRzNL4O2vmIRZWqcakYPyuzTvv0njVJC6Lkfn/EvyMeSNiSXHVsNCBaMrjJ06oEVXy0ndngUenMOOhNZ43PrqP2c6Fzo1f6qg0VwFfrMoWC7NAY+BRt2itTUQfbEci0j1bSQX+aznud4J5DPFC6GnzQ6Lro91qe+VAlGvFtUhlF3I7s22S/0c2upI2JzqnDDe5JxMPOL4+HrMRNVLFIw+GL+BlaJKerPFT2c0aya1/6X8XeRj0oMnKhrQ6NozYWrfritF6SawkfniKzqy3ZtmOHdbIyp+PB/ey/ir+5kYq6EIagAxvTakazyVx7uTCQhsdjf17Kwf5jlvkAglCifKGpwRhWWS/eOIDoZL2dFL0uGRSQYMIrfK3wRl9WEBKwuymJFBK8NJ05LcqvlUyCEWQ3BziQA8tB+39Z5T2cI7NPHqN3QUuaPtYjwfjLng2gwn/A40AxFjojOeX9QriDh/Nl1TeQTnQ8Q9+JL/Oy3uurAf1kDVJrWSD5VuFVd/MQ1GGw7DAAiZSZ8SsigqbYO8pUphtzZfz8GBr1fiAxXpZ5e8FTY+Cf5KeBSzNbyzjOhD4WZTQ9YVKa68uXr13BfSpQyS1ADxsTeQ5LmcTlubDnSoDzJku7cS6xVfOX9+sDoxh8c5z8VIMCCCrXfA5BtoHEd7+bwffTpEZIHUpJyLBxSIPy5zlHcI9CXd5XBBrbz8rlVC3sL1gDi5K8Ds47er8yuvl4nhy8f4dn8KPvXcOpmNr7EM+Ye8XcOGiLMS917YdB/FkS0Nmvt0Ms93Wpt6iXe3PCl5TIZ2hMhXOF2O7ntBa/BxKNw/s3N/iIZ1B+1fy91BvosSsWo5AOHeSo2SveLo6tThDjsjHGVdCUGB9lBvHG2KBwBq353Z+P+ecdH2ePZ9/oS3GEGZMslAuclB6N8VyCaCjdWEDesjcV2+zDZb3P4Ee+7sQgvrrKFKuzNkthxitDXeXT0y4wrh0sM4j0yvlrsffP3P21fX/yDVv77bLvahYgqZliDwCDJ253x0uM4Nb+KvVrsY/QL2vwWpe6TlwS27tYnZDZTPsSumWyny2/0LsoR3RlbhwSYy8Lv3n24nbcFBLpR+6XXWDRSEDybB+3mATTLEpYPoRX/l7rTWxeKsdB7Qf9cQIO1DHbIIOsuTHDDetx5i+Ps8ewuZcqj6HydkQBqTaIrTuYYXJGL135X9qwuQLgFGaEFQVf2db5eiPgbJjso2esz2FzCCu+ah6b87v47fUABTaMciTqCxm9Hj9GIDqD3Ciw/PQU3Nrky8PiUapo904sZievOMch3MxsPpvsMIVpppDcQrsq/hC19F+13obm4nz2kW8LczxH+JcwAJLsorq1Fp7zJUqZIptWmdY3mRCeaW0X5d9bSCZPyxgqO4bIyKzYioy/HOBZWnhjoMp+iKqZdT5FF00Nv7vtTO4aksIoahqOTYJQldWZ2G+TlOezC7ITRSp88D+dFT/FF81cwrF3mVFHWz4mg2V6vGHQM2fkKeLV83bvXOFNuuh25LI12dqIhkSSVnjMPkubCYBpJv6Mu5h870Ny5WWRD7BFu8Pm0r8XP0hd4CzGGfVFamBAbHgw7B0iw0oT/T4Ed7L716Lv7E23IxQNhOxU5BJc5jVrfzDYun2NhRwk3O8V3pkmyENNRiWyjW5xqv3nRCkYRai1owWfF4nz5fzXMu9MEyAns7rbs8Mr0M1sLA9GNWV8NDqB+erJFeYjO5h/bP/z4f/cbdbo9CjLuSh1oGJC0YK2uhIseHSnaJCoP1n2gzfGHXu3rUFfd3wXxf4CKIcfzIZPOMi3f1ATk1nuRHCACat8H07s0Zqb4RqH7emImW/pe7G/QUp7vHlfLUJb3v3QZYYgPnYm3wkI1mFPQeFVIgTUzNA1FYVoGOR4VQ4eK/9R+w+QclrClN5QvGUFVVSE/TkrZl4KOktOajJwDuYB58za26e2tuQq9z6iNEuYItKX19SDEqqyc8xUWK4JfQCy6Q6IX3ZYZzefdf4OJkepPTgxOwCwamM9xxh0riAclAxYaJjXT4Yw8Xu1d9DkwRCmaqyYC4TPQsBtwlwiA3IIXfFHCjH3lmy3cmpTztfdweHqsvTfMNpMOG5Q6lyTK6R6Gtufml0z0+U1uL2jmDn4ws0an8Boh4TAWvGxbH57LZl9Q7rcmz7s55Gq44SVefRNqjlaHtixNTQGOqOTWNclH+X/CtEsQbS4kJImZngAhSCdbNEoSQZNTTQH5qgVLYxGUOML1DBqO5XDxRXyCEQzxUsbK1zPNwj84RV+QwmmzsnEKAwkpqeGGIQH54f/KvUOQjNjzX2eMxLBkBImN+j9MwsOW0mCCGCYSi2sFMRKm6zZkA+XZ/ITAM0CV6LKCAKPBFSwUTWLy3Awv7IG0whwe/pH/izzJj6bbjC1Mj7YHUSrFn9ojBrLvI6WdhqBFLYRCjAR5ZHsBax5TnsKVXwTn40eaDstBp8cHTK6KHbA0Y43P3sFvrP1oiv9kLt0WeOPCM3Msj0NTvRk7clLFkhpe7+suHSTHaZjjFGMr1S+FvkzQjOHwd2Sj75X8+YkUV4weZHWqZ4kcsbnJlMvPcrkBBbO5eH1AKowY0loSsnLNNBEscNG0jyVBg7JJRhtpL7i1+p+AI/TBqZ3Ob6BFcvBDz2d3E5Ns2FGp5y1fpWZXvzgv2FHO1bq8CMY7tx8yxp6jdcQYr3m4H4Jhh3cmpUU/tm+3BiHj3T5uN1HDHPJbiiEOmDZnwZLOJtvVknTWqux38P8YyXdhv/z7hEAyQfbZK+4B2zyAHlBE8kerB/YWCuwlOG5OnPz14kKwV4pPRfF/gogeSn78EfrmOtsIEtMRgLIyAWDl600CowIymA4u8FoD9tL8MeDvYEfWUk2krb3tOgmLRACY6+05aJ3VYon0EPHqpV/q8veopymsyfs691D+NELwLTh8IJJc3U4MfK3weugSFnBSDlZ/CBdOINDzR/Crme1z8BHnoerlv6hx5QUa24JNBo9JGcbPkZJecoOAcLnhsW7JzFkIQOUd7RCp9wbLHmam+mm7jOcWulxfDsmlqFziK9ev1Z7F0PKKF75AlvzwmoaVdxOCHs32cFySBJpayXM/pULbPtvcIcoA/MVvj/mewgydlnpJHwTJCXIJkrPtpYMYTJw6yksMF483McQpAJMa9Yl0HB/alEJqBU2QBG/VoIDBMuZN1xRkxiM1l45tvF63hvhL8Xfwo/MaV0R97MU3FkDXsM+Q1AISNkHB49JU6id22/EToxRU1RCwlXZz+FHKBOV4Ux1XvkCCefFMvGW/jWs8mTfZXGLLfV+5Z1ace+eR5HKHNZtlh0MnAQaCA0xKj8GUE1xdorr6+YaET2bTDn7+suv8CkQ2aDgIkYt1U/WKCcDXY43UxiQRDlScNmzlq3zvbirH0CRUIE0HfVbH8EkGj6Tkjlx7GS7XnqyFCYdb+qMffET9fbz7Mm7ZzCkZkPuzWDJKcOuxmC0mqAL+2+SZecRPO2MhojvNEHw7jEQic5Ei73dBNe2pblUU8fNWAoFELiF3My+tK2rns8yb8FI8S6DF17YniIdmgTzCmdOs4PAYVbD3zhG0T1KBE7QWTpkRF0WfQOrxYzrWghaKrhDemAbf5Gtjf3wc32CRCmcsa53z4E14qqqAn+U14vnpazpjTaMLwfpq0eJEcKBWg5pSpdl3oHkur1ouz3NNSEzGCSgFzHOqBwvbYLqt0auTFniqvDfKq2PADXUNA4s5t/O0hhyQ8kHqMlgiShOCUTcXEWHhTia+yHi8LrUX2EaZ33qWesnB59jz6oFwKMm0paHA4DNKjexCPFzVEtT3laLmIuCb2A1HKsaNpaxtliL6Gx8TAo2ZJYYkKIH4sMCto0wmyKvy9bMV/6TXnlg9Y/Sf131cZN27PX2Kb0j4yOiW2nJNPMYuNKt+3i0XrEMGLFdc/iAlvVZsLZL+7E2lL67i4FU8gzi0x5CmPOgS7crrJFTlb/Wen/f53erI1KpvKQDfJGEHiJQHTkQJMYlW1ra2JbON75C+Vru7YUfX5/DSdKXUt5nbkX3knpCNF1sFJrEhJWiK5lvwob0OGD4P3P+uITrU3AN9oQ+uhZJSAeAebNGB7MVO5nhZ/ZlKp7KB3aoD+I1rtadqkqsy/acQWQNT+rUXVRSEXvKyhaKh45KWc5C6Fe3TkPGynKuWA3GPsq/vfHLGx6QkiSJqRTqiBpoWvXhCiLtnmBcOgQHNneylEorF1ZlP4bY3nSfpihUp0QezFOI8WbFY+w1QltbXjKIceQI5621r89DNRh0VQu/7dVAI0MUSNS8UkHKyRy2vSRW0Ii0pohKGqphTK3jX+X/DtZEEsVZMimCGEgp82JLustm+pzr4hGDI0b6AD/1uZVfdBEFUthqxU/MYTRa6XV21dH7xIUwopVpN4KpNC3dDx9AVAkf/Xp9BrBJle7IZoSZB6kwwI8v5t/JpDcPUqa5E4OV8yHn+7LCezDIa/GgLap8h4PPcpBKB3laNLDOKwwDsjE+dfGQ61teKXwt+g4McoDbPR3Xmfu0l3jThJPe2om4uGPy322rydzFU72BgmhdtY9IBFw1p+yr0c3UyXVl5xaN/3gcM7UzWcjXx1dWycu+OZG2UAHgLKz74mkzAj+MW9qVb5MlTfz+s9+YLKDO6MqbZ6aoAQgPde4jwxomZ36zKJXzx0ypPocstV/Q1yT/CuXB2NZi/KVYMHGb6i85M53h7/tGeGr7t/Wq8Fk7i6qaWPhRKXm3XLJKM+IiJY3Vz+uVAIB05tN81PozqgTKFjTHvkR5oDrYHxVGMZaYnpS+nsSdYRc7u4BJIj4bj14UfANVkqqTqmKfthaczqArFSSJa19luQMGy8rwfYPlMhfZcafO1mlps91Xf1T+K6h8HwYxygnZ1eqEZ8jLdjCulBbHts3pdkiH/K1uNu/4yHn3chcP+0EOafQKh2tDYsuTqja5kbeNnInj5Aeko+FD/JiOnCt9gEVaoF3m4UObQV1gdh615geaj05irrFzoULUc1N7rvY2qLSQSQYGLSq2quOgEdHPoQQPBiqrIhf8XKmEnmQ7R/d+7mfPld8kkQbNwxxOxAyeZdk476puC7McVkw5oo0uvrTHdoAcxtvJFjGjrxLW72lhZHeS6MmEqdKQFxgvFQ3o7h7xPq071q9eMd8iza+eBh/13weV3WEjldweHMI/Wl0XI4SgwOygM46WFw1K5VDrpkRQZls/BHrPsh9eA7rCtqwqsckzfezJ25icOwPXk0PM5yQNpHbJh74o9zayZA5d6piTOY4GkJgESoNEisMNh7QMq/3MmtnuTzcNR85OTZfV39sCbqUkVm2NFGrILWDitGQZSOtXjwgIHlrxhwDEWecTW7U3WIlZtBb5jMIsZ1vih4lR8bNTD8txjEPT9jBd/Vrkzd53J5Amhv1YPnO4JdudYpdbLGuhLcm58DZOGsTPIu9TM/cm5v1t9OyHhFLULVOgiaEZMYzo1jeQ+Fy6yNtsj17ta8V3uvUoe4gs+TpTjak18mVm8U3wYwY5Pha4epB5zpj349negJSAG0forGNKg4qAhIhppc1hW6Zh8szTbuSstIsT9oEpTRnEQriMsUJviXJQz9xvYGMuLj+taI9UJ58iEAS3wbwaCH0+1x9nCTDZxazLsoXK03bHG5b38widP76zHXa9bBWeg+j80xsyE6ml5bhhDF0ureku6IbPmPoBboQFPMQHJInR7qd9PMcYo5LCmpkixK7F7+S7j/EdMUF5TuPU1QAtVjZ+fEaSGAezrWmauJ3lDl1Zg0SK407TsQqw4dCHPaqworVZLC//x5P9DVDGMR+oW8+CyfzeMiZcxyGPJnbAApSxaAeJ0leKNEZk8X2Rpbz1x+KQwfRcdmnxGUmirWnC9k9T/lqBpba1r9Dd2QIzT259QsjsvLn11WZrSi6L1S89PqVIjLalDCMaApvZrZkNcpacZAsWr3AgmTdkyy+YoX4lrc1sfFCWOIQDtYoE1pt2NkBzGEwaIvZgw5oor6A4zjLbn6R1Xx0fVSXa4+0V8wefPPrqjE5uBxHgHuMzJEX64mQAwViU4ygGlvwFl1FufJLUH81fDIOSSj7yyI4Kqyi82Uh/ZLuWNI/IuirC43O6RDsmtqdacX5oO40BgaKywEpBAky/1XDrKjgkJSE1BiUAjV3ZyIBS2uW8brHjU8JEMx3fziw8jraGHKHBhhyHeCtqCMaZp8wkzrqubD9vXkic1LrQV55mfFCYGOc012NdswHhNBJFDOUqPsx2lrHOHnjaYqGuTGuoXHxam2juklunJpVndbgra1ERsa1PKBj4WyqYWySmOdlJYvwyWK2nVKT4nDZxHCAbGGdSmdEYcDkjQuVaaeNfEZBY6xIags99f1085Jst8DiRQ0uy1tkthd4tMBqKgpk55zQDv84Vw3QsyqcDxUvEPA3pbV6hRXxEmhjNihY5cEq47ycC4VF7pcHXQwjI46sLX08i3HXeFJ9SJo5EtrL1Pw6JONlX0OExKm0D/oIYGKXFo30Ii8C4WmvH55SJ0TBh812bsu0AllOAMiuyqbyDn2mYDdY+RgfyXAcnIWGs5a+qfwBA0bS+2kcE8s1Y7+oFrrZMLVPr6xYrWgHRNUgqPiUAjAOG7RFBeBdASkAxk5ylifLZTxfNVhbzGOia5VX8107ht8FzHGHElX3kPlFgWOiN48rb2ud20lSLxqIYWsrevj7KX+cdcfBe97wl4rrJPmME2o3tGv0cegQbyUEyRvcvrsi6oowPCBTn7VQ2NMlL54AtFdvRDOUO1hJp1WiUfVQe1Izxnbu/dsrPjs/oE+31DBvkFTPN0YG8Y+vf72GRYYQ+l2KsTB90ugbTpzlzqd7laN8L/h1RQnytDtpO2rORtbIp0MsVG0OsWOhmLcPtRkhINpOurVvjaFYi8dnfJD4jUozjrQx9a//HLrVLuYOfmOJ5gWei6Cp9i28P/nHJq8/Nbl4RPit+BlWym85sZ6oLYtwU7TvcvPMZi+DahEEBu6D1pm1h9RCKDwoVx0nWYpFWXvmywyy1OhvfK8sG2wpN091g25hj5n6efa/2LqyE0lC7hN+1KdgiQkqDkE5mAa8N8xI5DhEiwiR6/++WaY3YyhnwPCNVHA95z6qRFTFcICLZit1kHA/d9LRpuS70cuTLj+0xVCn1Z6vvGULriclsk91GziwlKvO9UpX6gNQvuoMjKUZJtW0ImtOFkeTJUTU+JVc0VLkdChk1zL50x9zCiXkj/XVRUhu8i8oYVU4IxAnAO3EWqLl9Auepw3N6RYOV27GKNK5WqSRl75bN514/i/mOHUwanJHK9pck/1XsbVTJZthlBWV5dn0pKalP0eXN2K58oK1W+/v8kbabHC0WHMQzlzA+p1W0Jrh21IdVSTbaSoYZ1mPBaMnE2JMxwF4uvy4OugdAJQC2ombf7uY0ogHep0YF0uJE1+rh/UADMOzkWb516FFNsW4lfVb8AKoE7WZ0n4lLOedgDLJsvh3QYvM0HIuGLAJ/upX9Gp/SKlrQd6IZS4VuBz4cY6hq1nNSCCWTfabFcmwDFsl/rfIWrmRBVeFj9t75eZtuPzXNzThD4LTCHjCYffF21oViS6OWX+VrxTcwZWh9bFIloHAWdxYO2yj6ZcOU6fhIU3zl7y/nHUjJmjlraM8JJb82eYMvZmIxT9vMZF/9OIXXfepnl3Bz/EzL25lmVmlje5psj2y6SvNLPPBzE0QGCzo5HaX1uQ1gLEwBt6MfinuB+pgYIMtZhvYW/3LsEPEkNZdfFF49nbH6I1JFa8h7lu11HL4EnQmedlRYQbMZhPnYxJAedEFn6QG5vVr+XusNsKb+mvF23HoUuSko8axFcJkG5Gqrujz3+aNJFwyvrSryOegxtz/eiJ+xmpMgRnOlhItY6xkJOAq1Giy3vIoUgh6C7stINrHJmPnlLx71k0gtVXHDepAMVIGt7qBPrPbKFt/sUDVfXVIg43lX+aTsb353vYjm3ArclUYLVkguR+6i0BadWW4qsjXqy9t1MuFn7a/y/TH/Dn1oCgJEpRAU4snU3sK4aB2bLf5ObuVJRuD9s8bHkA9jg+3cxbE4dNaoPXYeq9JmKoCoE1FavCy+onxRGFZ5DGQJAQ0aB5fz0PQh2Z8NSvL2dCHjbs0X4FEk+a1n1JkgX2s2xJgER/TMMAi8UR3UaHj36hevxnPAx2sL/96nVc2mdjjxPni99dsyOydyRE4IcXG7QJ3UXin+Ve9t7MOKesgqmuIstKOKlbDwepDWae7DmxznNtsXx0mvGLqwRq3G57R/hjJzqhroVjkMJBukzpZHRj/FLJjzkkhZ/OofHx8R/xn82Y6GoA217DYCRj0tvZ9W19iXtA5Znmt6xpJTuaVkmmGAnNaoi/iI9s/e4d6ikqKbuh3+oeZI90YaIIs08/8sKFwr1e8V3kA/bwpeLcKuRCtrxu6Mi5nN7lNay3z86ZvSgEv7WuS9pZou3CBVX69p0Ir4gsokjemjAu1MovGQt7sxciI/JH+v+vaepUEc315UdWzZ9iwcvnZQkw9cjMWhhKIsI93evxZ6Z/uXeoyi6Jfpk4kF1syPqDaMkef52agn++8vwA2olvjIwdmig2B7ppFjMv5znD4i3h35Tdif97oqkeKDrhHjg+riUpTtSdL/grn1Og7XRzPviQr8you+h+9t9f+MDygAD1jNMQr11THxKHQziasK+IPIN8tEHurKyJU3sPbuztp5iPuIAtBuqN2BnKS5rRlTpE4h3oB1uuyeuxzZaWsP4PKwDnQX0anxKQHg5Gs2aT+3N7YrzxcgscNN7tcikyR2rkG7Yg11OJXZAlSaZKXEt7DKLeMzGsAJ2VJw+vYjLvzdvQ+o4ioNMKsU9OqcFIgLmI9Zlx7E+4+v5j/rfRCy+ZhwiWgCZkVuf+kgfUnzboDsJieZNVi75K+VPsDXlNYotSZjkFFkMPW8aiXVzZvnZ1yv3bJmosVH9X/Hk6IpfdjhnVgyUTLJzcUamepKl0FNQ/SUvtqCHsGr5TlTHJ7R/8XpKaPoIK+RE6SgvqzUmKe19eY1cJndmXPzmPzPDNN3mDCymnYPGUXKYYHTPJucjomjl7pv62ICaiMnh0eZJb4vn6I0EkLPt+/vfOE9pAE0lkjd7i+e195eBXFgYG7ixxKZRUSRCEi6T4MpEKqtYJ0NNN9Dnv5Z92MQs0FgiMorpAUrM7uHzMU83GWS7OTDccLD2KT0M+p5WP8Xp7NMzmrLuqhvSpwrLCTkdhtn2CN+cKLKymA8Sp3z/l/YG6L8V/U36ZqOsME9TwDRYjLZJ7XaNoWgrdyWeB9IsXmNRImPSJasBy6yF9gtgyUSrY1FhJxDhBucaH28pCTZFX8Imu6YpAPq3Znu/YRocRSda2+QdzAJwkwoiiFpSX/F+GekbJ4y3+pl2/YgZzMoOSJCAWDOS9+OusNyDxg39IWsS1xcP0+oH5Ms2tZ6t/ojqM6nAvdJzUzRSY3bTTPtRxW/EAdQ/pu44XB5t/7Xr38HtTl+/CCQobWLzIpPgX+mSTDRGv/B2FYblPiUXNFQ23Y5AMMqcfFIJzAMILlhklziTHu0hgxWf3qF9LXMOzid0RCUtu3zluDEfMX6FH5a7FQ1M94sg4T3L7Da5MX/e/8pH+JC1hiU0bGhCpzCi/BZsE3viJuSM1Y/cJvKwoXs8YwfPmr9Gax5yTFgWNVK9sUeUw1l+10dpwBIBwsDhk+cFTOckG6xt1Vif1HujeVaxoujKTu1ydxxn4txrosJQkvLhxYYRUXWK2yLUNPsY0olAiq66VX/qv0WVOu+KumgNdyI0ScWPPmxG5RcHIYNyi896jjz/rzy/k5Um3e9z0A1rIJAvaUOT+WkHHM/xbdhLteyiLJ5WbxzebnVxOez1ntgTQZOmB9uX2ARpNC4MdhTQ2eEKoXe16d+pG1yUcfztudc7jM8yN50NW39OEMRiDcFtlBr1VIaiLb0LI5xJhR+3t4bti6Z3Os1xuOz9Jt4rWUkPQmnmSJJWh73BPY+0y8E34u2eoDm81rqXeSzPEjfeoFc6hU8Uh2OSLvGFUDECgV5TxqcRyndYcRCKtg+BeZ8bpg89vqt/vvbwCR3z10A0MXqVRwh5k6ej9MrVRxhaQgN81ge+jgxQP9+p6lfnBiPQTUurOKYqdYq6Rm3SRw9Yi8W3aH5WVhIkE6QvsW/Sn0Eq8Wk4ch2UfAjF1jISabdzFGiXHQYo/Il1Lki2BAqMB40l9KZY3ZR/k0a5Dg7ahtaciPqAiWcyUMUYnc0a6FdD2cq/fs//xBW2wOTaHZ3qQ27PggECMGa/N0q9AfaiTRZkGqR9U6P2L/TfuVd8BNbQPpXfBtyiLJwogk2L+NiYwXstdgCxrasWGp4xa813twDVlf1guId1IjBqJbTAFrztgHoS5Ew6fsrh69FPrAH3I9SHcWs08NQJ+Phr8N6+kV3Vm3pEMyeY5imajWfh5Hnqm8BtahEHly3A4cmOLLbtZLNXHXy9tzYam3vZ0rfH+tNImRPCmTvDWIkSmYWQW0AXMYM8lf1g6Jz0DJugLL1r23CA0TI6DBE2y4eMSzyNLZwZvDmZ9irGVFsZzEGaVx9awBO+j/3IxMyWI3J1lW7n65kJXK1YmmS4Iwm6AecAa4bAOJUwnh94rV6GkVflPq/47W1Wm6bQOby9k+LDnzWJe1gZsMfACMsf3RkKNaMO6s7lfX8v6j2X+Da6enCza1OJtVRS74dr6mfQbrhFKEXZIvPYBqoSbgigDNgy64IBN9Wp6Gr2v9nuHaqXDnxQfZryetEjRAsGJgQOoVfkmJowJ995gGzopPUY506qN5f4drnu9Ey7vw5O7kkDePtPA21Rd6fwmvJCgf84dtMLx+/lvqvaG2tFsoHs+ac5DI3XDpooLggfDSiSBhv85F1I6/Il+tfq/13sHZ1TmxQAKnihtcTTEEFnKOY6hMOjbRFZWpl+/S2MybJ7Bw9w2p38Vn6v4C1z1diD3YhaIwiqgyQmrEwiinVotke204Ym9uyOM2oxN+h2lolxM0N1UYFADuHRs1vrRWuHBnvvN2/tir3np1bQwgAomcZgJN83wkyaUY2NLeOzj/+DP8G105/giQiOmdVi5D/Q2pST1TxSKtyZtN0A40IGGqeTrI07aJ9vsLFiXEDrp1ea74oL3C8MwsPjrxxBqRoyOMOUWWsKeLCrO9unVVe1vvvmO2q6N7xZ9gtTVgVOzoFBnxEkuDQHRTTQBhcNiixc05kZckGcd1cXBb/L4jt4gjZQA6YXrkTxEyLu+nHFAqdv8wul1TxiEXfZYfxE2b7PJZDHnkNucMv7I5ERY7pyhLFYcKWJ8CP0hxn5bExtMoa9ly8Fj9htrXgN2ehY5CwK64A6sHIONq8DtymEqPF7rkZFOdWVtxnjf+E2dYysfuU601OQUm9Zp31fr7KCzW4WdNi24IDdnul9rXKfwRtp3eULztVcXYd47EgOJ6VglunpVaSxq6YieUIMhTvd5hY/vFw/2fU9nnFba8lR/0g73FZyBbY1mvFyk1+8azFOLas87yLB/svsO3i08/KJ9u+DGYKJEZPVylMdmVMsgSNTwPj7F79a5X/tl073WNSHHDgO87I7M3uUdRe83hxgxQg7/Awieb+xBlK/+fTI3hNeQiYO259GCih9EGqUPQuST7vB5akqnt/TMkG0DMHp7g1juqi1l8BGxOPAk7fzkQoIZ0DoNB+E42AeKnAYyjRrJcnFbIzfVqZkBe13oRrtTY5V/bCCxsrO/T9YmCRlkYeI7p7lEFNHQJDEO5gdTeyhslxHY1cFf8jXsMIJ6Yk27mO/G+DiKxRpLd1Y/Me7QrzNGfZT89FZ7fv9gd4pfJZ8jOQrYm7gumcxyQxKH27KNQwmSEkcxus+yFD5rbaOvVXTF+LvQfaRH2rY6etUGOKkzssuTTyYY6mxlScu+ntyFFaRWuf5d5GbTAiE1DAV4eDUi04WfJtFYRLWFPlYRM9Y6gUht5QH3t9uquG4rP0f56drZVzdMUR68XWHWlpsoZhDsVZQfCtcRM7zL/oeM/dl09PQUymIRC5o29S2tHDVnMOSOO24KuCvZWXxmZDOvXiYHsMZGo+V5HF9BBaQo5E1HxuOJQVmDoVF6hKAFjhkvZdwdGe/wTqABlYtb5yID/qvwUwq2ZP+FdvDSR7q11mwxxNUW+wSZ0CUNESiqlMUlS0rXxMmgWvXD3V/RjCxNi+YClRsZPgGinNGJvVjB/xkJ10Q7v4toPY1b/qvI0scdzdvh6JLwdlhGF/6yjnWGCBLIDpJG+VND2+a6Zz0grBtZf/8zH/ji2l0eV3l+HESMctRt30418FrTLXAHeZCueLs+IBaCn+XdTnmLP8VVmqVY3SaUFwraSR1JgkTq3ChiyFTyj5FFikkh8AlySWucDEDMsy5Cx8RtNaBrPN982sUeVRWB5PnlqfFd6Alu+jIfCa7aYocW6E5IA8vq2SzRGULdc4CjCk/ph++PQ0stxTTGXLXRIGhlVGhT3ZBFLSZ02cxFHLtlvdUakuPaZUq1zls+470DI1dlBJ5EGx/PzqjFLtakv56LapTLPVafXiwd5AlhiSdpFvnOv285O1Vi1VD5+yXKa95hgt6E8VwuUV9iS4dCJjK2JI8hnQkXETvE0RcHkDsxU8EKBwrvky6f+CfwRcZsWCawns8NPsOI8UqIKNuQITaBFwsPjI2hMbuoQyt5vYtu/V3oKXdZCeqw/ysnZo2vBHUyq6E5CXgAUG18lekd1QjechbvDPYUzUJ7HJWTsUCX+rPp0KVVoZL2CN4HCNBiHRX7ID3H4tcSOhqq7ZCFeV31oIbk8aGebOu2C8iVJMe7d+2MTr4qedVwyJoUttcNd0QJX75D5QQ5DS5B3SZIkxzdtcn+HhsRlVZGyJKzyiV/la5zNArTZFCGwNAKFjBVTGtIfXnKWrsmj8SBc1A7KdP8QEMrMNOreNwT+7XkNsEhMCr0KzcOBCmn9amIF20xgFq72VxasaH4M+ssPxncH91saGutwa8IY6l2zFca7ySnSRnIiIoS/eDr0iJq0mheeeMfjHoI+n6UoQc2LuRfbGMsNPSuLW/8l7s3UGTb5m74M72XDaWVCJD6dARpX98G7NywNyZ1Czc3rfY8po1Eb4kOmRbQo1kwacnPX8n+XeBkBBtAetchr+iilKIhWqydXYpsWKm0c3kobm7iE6+T54MeuT/6v63/EPrQ3/rLCB+2wzSBH9LUGSDtObCYEp45usEfxFmQ/AHyHLjCFvyEiwt+bAk0vIgH3cC3ikqLlgQFHiHAduB6UotfgqlYvP7wH8wxIKTnTKTrzIQzKREbZEr5+B0wc+pNIGQvpa483lWvWK4y7YLFamTwRN2/iJywzSnD8qtBVd18+LgOCfhECscXqXI0JTL9baMCA/eKJ4UzYJFDODYDxSvJgy2OlfHgwPtu2+F/Hpnd7PMmwfp+LKmQGKxWXvbtkWP3omzH+WeQunIT4KXr5zLc+jqM7t3xR7rP5kqNtWB8uLX/8GTmNe6xjbOyWME43gLOp85mLI5N8vXCcRN326vG8fHfNvELKyRGOZFqJMZZIze+sgw0q4+8UW66ZSQih60tV+VntzVC6TDl6ySleLO4727W5JcuhhrNpHxCoEbhg6q1vhVmt7BFiy7kht2AXV9/1awTAJylIpzYLV5O6jZBefV58OB1H6TH78qPUWzbS6YRIfWd6U3nGcUX6MM5YbYgi0KXC5DVGSQORfrn0v9XdAKaibsKnc/ZGYuWX870KUt61cXMZsHOt7YccALbXL/RTvuiBVrjuR3z5r/xVSQvkqcqutjXiMlpjOopdBwFZQ4QVF2pWZE2zkY8rdAPCJCfku9xlICWqsGopXYGQY0ThiUmWb43FjAS68TC2Nc4HpzmrF+1nsfZLpdtvi6ZiiazPVeo8pmT5kStSZai8dvO20gSjpa7V3UTDQcLtkOVeTU/qmxBuuW7g1eykB3UCeJK1BV1AJ05SAAcwaa/hZ+M0TGCIQe5GW8FYQ+WcG7hUL3POD1sI6M9j0r7381zLvQnXinaIX70JmaIbKqxkzk12J7VdfeoS8amZU47NQPZfd/vPd522Q5v2g5NpSAlPmymq98YJU4qOL2slOHCaZWttNDRdVgt3ygW/as1vK0hvn0+7DCuxyOCeFkeJQg/KzkCvSJQAkZXeKpbCbfdDWmYeLV/hhrB4j9O6mhMLt5CgzG1AU2OHVwhM3D75qPC3OO+dWM+HLim/DdRhiqfHL18A9kSk4JlwbMHUQ842zmrkTtFiJbSIvPSfiToYMf1V/D67nCJE0hi6LdBCZRdIk838KGjstbhPvb6X6NVtHdT7FhI2R7BOfnWzGi6RANZvdODv4KmE8Ql1AHCdbaKjz+tBVXNzPT4H10rSkDLS5XBPBWl7krAgsZ/swo6yC7NF7+1rjzXXldh7wD+ru3TP2rICr8ZTYWTJuOOW4238m9jNx4VzlA0zY3ruATYHHtD1XxeLCNUdi0Ga7yI+udTX/IxsYHWMd/I3r97rv4OAucm5xGjRNh37+Zbdrptu7MDmmRKafYvcunuwNIMyGqcmqksOJYVhqFuKRjaCdy9Sqxbqm5KTLI/ahwQfHJYYWQbllGG2HGdDAO1GnzZBlWIbBeSkykzheX/v/u4srrWvazm0nVVIBfVVJkFykpmrRe0lzXWJc6DPDenO1vjblF7X+giuNP7wHDsHCbIkR7QYwscPTBsdpH8xWR3tLrFxSnbaE07ypn0y3L0r+DV/aMr/uPSP7fQ8Mjg6/ozBWlEni+yTVEe4eYwnop+dX2zplWc0y6Vvf4qvifwCYeUDjuHVdRRQ1qdccd37BCqNxxDrl95QJiBML7DINQrXtXiWj+qfdx5jZMGano9meOS2OcJrcZ+CK4O4GQS9Ne5yZvsdl118ufi32d4yZx6xkX48Rw5fFkJZFpdzzglkMBWQzg5Q+pHc2nA59Tf76LPcOyMzjAI5OA73t7xdpiuAIya4Snh5hvSPmgzN6BhvugVV+pnfuSsbytfTf8Nt4yrlDyN06l5AP09OZJZxtsNvLx35nzFLXrkH/+08AuGyz5uhkUNV3doNSqyppqF1oAelw1FAfhy1kVh5/MJrL5jzAXhLS0yb+o/xf8Vsej2qfk0hs3ZmkbfhCW3ljWkDCIYRPzQUwrnPEG887KpIlrTJG/QMfgW/j0OhJ7JDUaLt4mhUp27su+ovJ4eS9jZMBye7+8nR7DrhlYxptwHik/8BWKChItW5lkpIx1oL6hg4HLMK5vP0vKHGjj632MgC8LP835JaNaOql/ICXIbM1iVasAaJBNsNII8XxUuXXxUO+idvyzMiOWB5spcHQ9QiEGo6bnsuj46qK7MLL7Cnbo91ZR3gQZGimsX6WfBO55TEGa11KSae+HK9YU02gXyKSb/o4mKlW1eHm0tcSfwRueUgYmwwxIo2N/EGT6Svr5BUfqH2xH43yd4PQ/rXKn4HbFKn17dWku/UQB4N65AR9hBOtTHFN1fQjDOS5tXl1dhvepTUz7LPqH2CbvbCOTPntHVSrNtG4HFymS2gamywzCK3Knaj++2P9DbVZE7wnGb77RocrHUnNyq46HK02n/Zp5bHAeQlh3bN+9gk3xtFZ2plUi8xjUpHOAwmmval5PDjAZLEQ9Z2kbJG+IZyf6vtXeAi59Sgbv9bD+zVrhKUU7YdJzMGTTorcNId5SGvdFBn48srfa/0VubEz61oCb+0rbCvPhr0SJ97l9kbOrYi+LUynrIOxqYZ3pX2v9wZse3ezpbPdTdVzsm/3At14oJ+NsgqWIQ2RzolETs441kZpg6HMdJhNufM7/Fn6j6BNYcYeb4vt7wfZYOEbXtE696GeeK8J3EHiCvPBVldBqrX4iuWz4GcwGzzzrLVlH1hNpk4z6UusFglNujE0zPivS4jg/NdSH0FseN7WoMfGpEzxdgFXGTwBZZ6VbEKSrZPJKLJT/FruXcTGx+d0VOTiSGWQEQ7dV9J6qpnwWT4TB+Lx9tWxmpGTWj0j43Ph9/Ba2jrTirsTa0hsQhn4md8BUoo2+4bJeqzokfzFGfEUXpNWfZfmFznHywrYJ0esQNNi2w0THzwxGqSNBjE2FDkl81UGeMkyL9oFIPnbn+E+aPMSY6dUq5Kx5fnUGo+1ZhF3tOqGwskmn27XkDL75JZXxzVV/Rhmk8GNCyIfi//fFX8ge9tuo1Ve2tKLEaEmmwDhVThD+4uCbwM38bCQrW2ojeTz4fhDXIbiTKRiZOqNm1U/rAV2GX06/MHO05OL6n/HbaJu6qyLGp10y7JL5pMCqieTrRwX4GDPszhEdT6A3FjvRXm7bY0w/e7WbGKQRA+a9DFiIMZpRvhonBfffkiqg3pPBF8Xd/UDwE0MbydL05YGMeb9LNugnr5fcAizeU7P8swNxOj51b5XeRO7bU2tVxQ1mWyY4GgSvDAQ6SFILbKQbxyfL8+EZ6HbzuCVsaqXvLmnyXsKYsN2c+7ZXpFg/B1OjO2y5D+AfCCsIpDPsn9dFOWRHaiHuh2d0MzoJhQDZnORZJo3pPrMsQuJ4Gy4Vn7GZ6V3UOauSWY1hTm6awbSvLWeikc2V5ppF6wMzqtu5yGU6RH/sg0U2ihOsWs24fXDXVzEOZcW82i2WO3jQfZHcBtLhxaqvK4YNOUqm3627PSxoU3/GRSrQb5q60janechH6Xegm0uYWaw3alg9QZxL4Mham92lGYx+BnRYdUdFm5AyR+/f38OsxHpVJSjt4ckQBgTVWiri4F002z54E0VktLr4JgxptpBSDjg4/4B5vuTq7ath2n4IdWt1UZ4S9pWY2OBt0SdTboHcKIcR+fjDjMnv/q5qN4HF2374KkhatVRKw8DWhQsXRRrn20Y7WsbV8Vcwm6Q2LWvxd6DbQw9k3MQBhI6ez3GCqs3zkYWPJdpKjk8LN/B89Wl8LXc24s2ZYcr4bQ6uHylyzkawyeUw4qPTbOdkec1L27KTZ7aDKZWM7XP0p8YoBXM7XelEhssiEV1PEmNAm25wvo7yUW/jLFvKKvn02exv6PMItWXOkcEmPLYM/PSMlmdwWZ+MxE5aSJdP2t8bCnYhHQk9MsNy6wNqXl5QDp5NvOCoH0lEyirxyFknMlk3fcbB3bkDjDbt/pvAUxWqZ5ddnK+asfTmDR1YEQIYjzI3LSLdeqmWD5aZKMyEps/76redT+7FlRSWEl1zCzf3W8tI8CK1JU0x6q6t5dIu/oJz/rz4FKmPknh59tHf4iCSSlMPj1Ww8qfyLzF9Wg/s904pJ/J8e7yyHgUXXZS9WJjPsVVoYs4jyea0DzU4V417S35e+k8we7PgEvtWzHO3+6GLpYuntJV1j0jrTrib4Ycr80LGlzSCn0St2N4XbwXD4BLmYoTkh055HC3Yy4pnDEwGs6mHMJxcXiPpyCSzxJvIEsIZjRkW/NDBBzEGwhx2dxnUOU069jtp0fF2lb7mc8q70FL6RilvQwZblMAsvuqJi5NlhPBS1gGdzOl2sG+ogLeIqx0eXM8hNcy98Kec3nGa8GgmZ//Voqf5jN1TR2+eKw38FoirYzghl6wsn0/OKb/2JhWI+iIa9+XrHfyBf2rf//570B0WJkyEa/QIukGRMCoNgtuo+xsdFkfScBUTuerrgDo/WXeB5bwS2uWm2Lnt9+OH1mKAB3oX2l0GKASoySThwmCsxaCLn8v9i6Xs2rf3iRNj/LWZILgJZoI4nLKXjzwtk4jyznF3YB79N9LvrkUrPsqTV5zfDcxktkUIg81QH8Lw9ZAxyh+3PL/IsCk4fgig/EQz0OHz9p/xZfvgz6KX7ibbfLze8a3Suz0TpG3mR2h8h4IcfXmH+CMtL7bFvb+WfJze8Gt/QqwCDH68TDfumzAZvALYveMIGCNVJIHyHnleq70gbXg1roAZiMCtoCxoscqVkN8+foFaDs2LUtlGevk7WX4Xu8jTM7Qt+OMyyCyixCHIPfkjf82jDnl+zM3hqNd9FH0sa4w3O8vxW3Mhhehx/ZP8zIsBOpAjnyK9I9l2QxCYW1rcIaKfAy0iYiscL3WKg1hrYw7cmDZt2e9IgXLugQhbhTJht5PmhHLbltoc+oN+9T2rfzbmK3mlLVD7eRcRo8rchjTnsKxByd1A2vSY/Ep8BN1o3LCuvb1PEN7/8OeWwvKLpNTY7uylQqH5j25mTAgHzZ8UIKx9uZeBdV6vTyTHwZuPM3umApvj7UwV2CHopAHbuoWjMEJSGZbqPty3zpXkyTvrLMc/6r+Hptz+/B11DlBHVYTyRxznLkK17Y0RrYVSO4swHj/5x+jc/qo99YJqGmXNTZFUky7gpESM0pmZS3Mh7v9O8WPhVwsZ93Fu+Yn1oKAIPwXc4FlqkN5jsraTNSWrMLcdDjkhJG/VXgTuLWmzLUE8IXAhRjrjdm6pfDFY/ZSXSgauf/1IO8hN346r3lG8IxMg9fVywUGjFOmoDftAgI9xUjuu2VvLWetq8rts+w7iIPoFsRuWUFmAwb5YZxj+xWmqriQB4tXuOzMniKcFm38cjxEmAaLMxRMtgnSXBKyQaIhq/n7734DWmJtDmEzZUAlHSQMXiTvxSSMB8asKWoUh/yxmDh3M0+MyyN9wobV+Xz8DGnONuTQuDyv43JH7h3j8rqufMr/udt802LLiO0A5bKJPVekvsyV4EMnhk1IhyEBaaibTM7sZsDKdjktUPii1l/QZTEHmlbF1i8VfrFEgExllkestAdZRpsvvjvMG9YZ+UWxv+HKYjmHNSpcLZbmINog29g1gnWOw0OPikdAV0DuaZx5zXtQIsKZrinlyg25qv0HXGmVh63LgvW2PVnUYBo7oN8YSU4IBGlxkDlzLBhzbCTixrU1V733QWUZe8vtdkdIV5TmDlvWS99KP6tgOW8eWz4vdlpkk6dXbF9rvQPTitE3o7yOt2YLKw94eUlK+PfvjuGSFM8sXEcmnsKLiiwFQNQrf/Oz8t9QWjH+ZpdWMCOn4+nBFOuWhNysWyyLnzxb1rQmlanGJ0BamYSaVKWI2s1Yg7hqLLZr4J1sJO9sb03icGCrw1w/AOM57HbzZASzIny2uHqPfPwZfkVq9ifIuywJTKvt8J40KS1gFMkBCCwlXhFwoLPMZrDkpl1Y3Nqy/Fn2I0DNIqB83OMs38+uaYyp0BQGfkhHU5zqXP1kfQlgY+gTVo/Iy4LvIDWrOuQM59XvDUaQITUuvs3SMdnba2ORSCF435ZMSkqU/Qtpc3XdD14W/xtQs+u7eJngdvjpsHmUHTg3bNE+SJyYPmgai22cCr0J1crgb8Ya8QJ1OYicx+qq0qGJIR0JUabX5ZnzqigZVdRYtrJ1HaSp4ptAzZ7q7oeMmQ+GUKDhBBqbxil52qU7i31wB+OHV8pfi/wRqxUhgz0M26tVKxbtnFIcvSSnM42kicJsZsY5F18xfC3yZ6Q2T4SRQbxLLKCiy3ENExQlvstWp8wek8GZ/AmCptsIC1+hfq36ByBkL6yTuLnndGCciwRpf5nGxvRJec3Q7q/vL+iPQMgCDGvvndkWkoIqikIety5uKvPF1YbVgDo85PLXz/8r4h0v6dbNOC0X3p9uVFp3MBqsN7+UZjoQuHMZrA4ECWvK5Wdr8/usf9TaRBrLGVvFrQBWgSTkDPNIllv2Z/GhHz9+6NJ13bJt1fZHMFtQ5ACvX2v9/b1U9n+yBaxM9tEQKDMBloDMAduqp2nrFuWi1l8x2/DwjzoHSmnKu45MQ3TcDzqUNoLi0frpZzj7goB08wP99MeQW4AE5lgE5p0dJLmfPPuTjKIBZkF7uKbUXr5QTRrRxlesvKXa2xvgP96NX6EbTnn/v7Yzy5bcRpbtiBQLfTOYN/9pPDK2wREgueJUBnl/qkpSqtKThwTc3K3ZOkJ+ha+S+nkE7Q2zdi+wzmysBWV6Mmt05tLpZr+b66v0c8kPorcobVVLySkjSw+rmruPrCMlhnc2Ep+wHi5zWI3qzsXePylqRsSY08hk7PLdnClEIoWgMkac0j8NxmF0tTW881zsXayp9nZPRObYj55eQEM8lIMoEJKEsXL/M79kr7yTosce8cpfxVXn0n8Hm+8vK7Ho2c4PvZuQmtxoavDK6UbIYzsY1nu4rpM+FfkY2oQHvTV8Ev7UxF5t37fzQgd8zbYvUPbdci9LEW9UhhWAvSoHvt0UvBjf3u8Ek/7tD3ELbpLwmjijsnM87VjgbG1tlxMHMdJI8tpWhjvuQ22DF48z5llwaXWZVd2P4U3YZOi/tjIRZ3KDFwu6QtM7O+N+cPmHmHaaSfTncWZW3J3264nY+UxgVETlyCRb22/ZVYRq/0B7ztJ7nvwY7/qpi+sPIk3wr/I+vLxD5TViD5M4wX5IEpxJ1YyI1kBP1fkA0CRrL4kKk1sUqyi+n11XZ4HGURkaYyJIE9qr7QreiXTRsPLqSqOSH0CaDFPxSEqBmQ6sXvRDqQxKHCvX6s0opy4pMPucoX0t8QbOrMQrMWTPDQMqTIjoHtK419CWq7PIn2SdTkbxacjQnwSa0nkNb0jfFdjGi5D45sSU8rbDyoKjaUj3eyLZzYvZcfnC3seZVaxuBnnqF3oy7uNHkGA2/mnyn1xOKcXiysu5eKw3gGamEx4HrPgXqCecaVmLOfPKCNktBrIEFcfLjv2ZjVsZhuMFQfIe5YtOZcpC2/hwgrUOYTgtVaxg3g+0nfYU/TlAjLOtFuzNPKK5B8aZMAZ03rhRDHZ4HfyxPl8eAZawfio6rg0ggHkrfMfMsqSgxsRfcWQefugMSlmmt2/D6/i92F+RJbdLafICz+yjOi6mpfKm5mTaa8K1+NN8MgBmtc0dBwy+PLcNhPsjhVfMmtPvqnsAVtJfR3HPpduoYgDPHHJJJJpZ7THFyX+VfmsZ2JyQYxVTsPF6FOg1ReINaomTdSq/1jj3ECIYrnYuqvcZOFlJkxarpio9jbdVfj1lRqxhwKxdMXIm2wVmKEEufi31Hpikfc4Kf/EC7r0pbbQZ33E4hsKrjzMSzpxnOIaPXAFf/g/gZHQRKqnvAbZ5wwu3wBeRgBg2pCSM0Alq+vDw8EAkL6qWPy57fHlyeblPcsinY40DaYh4PZZPYUxMYVCXvGbSw0A9rtB8eRxP7lSMok4LD4u2oS+09kjrGgT0ii9yJlWhKl8UX5ccCLvsDDGV9rBByZK+1X8LSnrsI7Bwj7slPiJt4lm9hg3be83FjLEdzPvtjMEdI9HBWyS9EhaOuzRfHt1cahwqv9DGYmVPyJykef/Bh3JhOmeD2CZJj/dplSxc1nsbUOLGUZMUbFEZhuRTb99lBV4SqWL3t8+SZuXJ8toZ+UjmdSheviWPAkpfhx4UqSK6Jq63Zv8RCP41Nz4TbGtyfVgD+fIgngyxMITsTRnZHrpZhTvfmedqCNmVSoJQaLpkb0dkiGYEv5VcLvq3xzaXjpiwrSFCYccZx02RTPqcLVZD9v5xUV41f3mLPIMocTbqEV83WhxETDINTWYbie1dmXfxgnv3o/h7lfcQpfKqopKRQxXtIuhn2wyYDTsErEfYaaYy9Kw7c12ibBrn1S7jXPYdhMGEfOR7y3pCCg6btY8/HWdtmy/Ph44wvvzXIu8A3+g0aOGYHalqtnz5QL8om93goJrF3r60Kt9/+Ddwr5rFoEl56gohwLqpDAY0MnHIIsEAkAXdadK7ZyGXr33NTeiL5idL3K3geYa2xaJzFDrxPraGX4NW2hp7gScOa+t3Q/IQ1XQnYKm/wXk3YxKaPDIfuU99xAwosUTc0hlJI455id9rvQUu4wbC6E9KHN4rxPo4sk6HS8r7wGTKpBMLvsDUJnHdHrd+p3JvrCwDGdxhBOQQe5y8jHBqY0lZO8+bjhAuXxrBslwVeAmnqmi8ppfqSGU5F/8rwORQ3dOU9Pq+f/QtMnQqRWFnBjMxqvJV/YFbXHLoYno8Ejjf5T6DLxXUWyipueEXqW+9Tv8sCmU6ziv8PrpsSoKJijsctMdSn6A1NKWHdw0Xsw7c8LFbddYNcuXK+r4sDVc+UgWO1d6GlzjkOHLKtkcI4i2K8qTLKrLLSVPNo/kJFDHGjjUiDFJM3nEV9a78YdZpK07y1bxBeC7/zD6kBiIGu247ebc29YZFUTG8YhpFh4CYICjEb3WbP/0RbkE3BS8S2L7nTLIXcUDLrcPx/LKSpDCd1lCRkXmXBZcNe2Sl7lZ1oMp+GLpt7y/kXtcZQgetKprZNPiZ6p3EilktQ/OwDP2r2tvATRlNnsJyJyo5YUsfnTaBBfrvvAHxveNklhlqqPi+a/f5avGv4u8yTgNk9e2HLkADTHe2CDTbCdpivRW2DWAydHXoPUU43U4xnMBccV4/emaTrFrRWvSW7KX1QGhZJkgsWBJ5mSCo1TBFFT+0Bhz+htnhypxQI1JTHhw56MYjSnLxN0TwH4+g/Vjj3T1gKAJeJGs3GdmlAdDenxJOP5OrO9eARZ4u7WuR90Ab6ilZbu4d/GiAomx6LIhWdo0tz2AY0dE07ulJu8NAtPZVt/kU4xTi3vbCpo+M3I+Yh4/Uhzo+Jz89fZIEt99f0TuIiCgaJ5eOzDCSOQK9hXEgI6w42wxOQg7SBPdXC3GTNeTkDFllTygqhTlN5blKhV1aPudKGo28Svj6KO9C9OCHvBIqvJdYpa4/bEuhiJaTuP2w/bQpby+/Fvpeajy0Ddx6b2lLcpA+NglfRDO6gCEvpnTU4t+bWnmmrtXT5OtU6z281kvWlBl79g7aKRKpaSXBWv99OpGRwrr/MObflcDxe7E3loGI5hoKwLTngGksoqRpL+Pg2ifxKvSuVdyM0lAKeM26MPTmlCOZ6Vz7r/xSGNwt0f4FJcDtYXddQEO5FLwA3BIMcnw3fjpt44fr39a49HYu+bmF4O4DAE1eOU9eIVDBfyQ400qhm0mTbZzmuwF8fvX6tdgHVoK+8FK0qj6QsyFw/mOFz1ycSWNVMJAbg17LzohpjVQ5l3sbs2EVkkKWYFQQvjN46hCFFJHAkSZ7C/dhgC52aoozjqKd6DfH0m/eFU3m/NLdwhpkEyEq7JicIVgoi1Ho8LmIF8faY8BS2bYt4hO9tQgQwTzeU3nkAhV5tQOXIWBur5Do3NkGJ9s5iFFGlKylrikwp/pvoUpqctCsUkyFE8RFLQaxTApZf5t3PIuZp9WAYpEGqsQ12/XVQ1ZlP4Yqme3VLA0FLSHWItx43Y35vuZmxXaEcT0vtm7C/1XpbUTJBdIdCVe+cTUU7X8yBnzY7iVv22GfJKcrcw1fG2iUT8KH6xbjKUz5Li9EuMXy60U+GnBAqMNphq4Oone/IHrH1TJddT61C9zDgTiAN0yhEGL2foEDiwijlsDhwM8WjbCuGft+5vV5k7jV4FI1P4AqiccA9aQWlHTmjOma+ioPZMeF2U/+NIvcLcv61xIfoG2WLlXVhn+6JpS0cvHjxWS9Bl0DfkyoxkCtnYscw8ByFFUci761vcIxKESpeugn4sxTN18U/lEqy/YKnvQr/PFU77I2aySIsWIOjIVUZuJlUR7I9UXO8AMhuRk36PPl7fbc7goX9qqEM+XaiTBs2j/ktM4k7dXEg6G06T8UymUX+aDgdjugMPFQxjS03JCX7XqaAkfuqrxgy7Riy/rf+9L7AbJFq68OyBaHL+lbaEtGy/u8KZz3GGD1d5nwbbbzXbZkZnDr5kbbxVVKdVHs/47Z1nqbPiEYTzm6LpMRnuP7cZLXCU0IyoWHoDAiWw1hIsY62EFeVPsvoO3wfCthkbCptjaVyOP9zmJ0U6HpB7l/BolnuH+T+gkGE+/uyyOhYAbc3AqOr0r/nzHbofAiDyJWeUVJwpWc7ozkoGDGi3C0DgQys6qMehFktBcXi2uV+yteWwuGS8okLO9WdJ9mf8m8TmBrcpsB3Hz6JInUpPCc/LXQfwc/h8c78rDdWKbjLS+fxxHV7EBC7zOYFJAPPqz+PFvfU2b4U1g5vefK/wX7nJ/w9nOnrQrsUDH5SfBL2zjQdK56Y0OGT7ZpLJfHw+/YZy0zDOJoi7KfdF2Be1t7GxQMI7tYebnIyp9TcMP4GHDxV/LcLEnuAvIDW/vb05/h3/DP4U/A1LHQecftKhaoa/qzsYINlttNO/RufqIS6wd3YnyA3IMhrARDlX0D/1y81ttzbjhmao7uMeOQY8d00mIjBPyX0/86Ttsecv2r2n/HQIeS5cHL+mxryFiUxY7KBvNsUC80+6hLjhXbiHKE0qdYW0KN26v/+az/BQKdb8IUSQUKFRcaJdKWqayz/HRC3VdjpapIMx/PZf6EJs4V7gMGhcDIEg6wYCse7K/LfEVdXTzdSaWsK2w/1/hPLdpaJp8LN9b2yedPf8A2Dedtph7aaCuPjghxdcg/V/mPoOfworJlrEWO7JV4nyBZPsYHBBepDU/6hc0SRJXKlVhzD3u7NY/8XPa/rS3Wqt9voQdKetFexvJiIp405tugj4mHmi/m4B3qVffwCzw732vbG8nTHG6g3Vncky/rfyRr1/18ATxskfrHC/Av+Ozix19dHgxYJjUez36LGSB8DbFFt2Gj5bEGvRFrYpXq/Gnocf6WQnOZH21PyE/2pSjKWNyaICEERWOLa8p59pkj6LD0gC9wmHmc+5p/nZ6vhaNBCkqWAdsG+KZeFtxoUKS2bPPmgk8/LlqOsr5Gm56r/Wf8e3gZQD8iOXPqSzwfbeGSbJQahvmybGRZBDOEXzXg9b93O3wfV6IPKKVqw5fEH+VaSnF6GDN0jpxIXoOcsri6JXHgW/le6h1UuX33BE/5PS6poJYhyxaWU5NJ+2zGcTooRlexQc12E/T6vdSbkLJs/Qrz+N2sH6WXH/Z9+KYhShGHYTvXWEKAEuR0yxBvO2LdnJSFsnqxXtX+I6ZU0ligTfEbKAaMeRggIy3amaVFyX1ufACg3s5cRIz7sOHirXgGU8q5P+J23L1C6aqbgYu6XZWJkS1WC5+AOhUS4cKq/1zs/VOs7+NQIhog3SkGuXzmV4piwewuTbbxQtuM29mQv1Z7FwVz0yavUWJh/bABXvlYsHjgukW5o1U9TW8cZCG/Ew6TtYvZHeH7sfCbxy/nbZPjNv4A2Gyir43V5nbWLM4I3P00zB/U+T8e8j3AnoPm8wFz+MoPupvRH+7N7H+ceUX0z7DmfHAbUo2PAXa1WoqRbS4BVmrCjHU7JrCOgDpYKuCSkEspGz0iNcYR262DPVX0ItheHREPYXXgQqvKiU3QKUIrii9MDPoY9wYsFyVl3L5QaOGMh/0E60SRtsu7+TGw3pV/znGRm+ZJ/BDy3DcpZR7tj0xMwydhgL/c0HpPf5V7G60DursoRi3RPeQmmyHFYBZTvgM7PTKXBKjQvMw3Hn8jKOjV/F/V/47WmZ2xXNkPqzC1izixWkhGmtomOGZ11a8cGOmq84HefYDJPnJ7ucGwP8r8e3QKEIqLYInENt1UrNunzK+Tt91ql66CH5gv0AfBvk1J9wRPkz7eHmeKZmbKzGnOmYratfi1xBvjhUoQq3aqhN8SwSorHPPzgEaiHJL4OZQGA5dX/F7lvfFCZK2gxXTMXtR9xgudK6I6o1WMhXatNhUZJ4UObs0ndz+P9LXwO8C9qBq16az6xMnqBnPmCGRNgOpjufb9wd6A7aCGKmddtjdy928WIVPM+yr1YgOluMZP1PJy4WuddwY1HEAwMkOE68iiAZ/NYGsSuZt6swbWC1KjpW7Fl1uf6LvDu48qYWX3oCgXV7A5kBC4O3RL71Zbq1bWQHGapHlL7w7KB6nH1eqp2F9xJY+vblhABiK5KGvPd5GqiHHmfkVfoM2Es6CnaYTCtr3FPwu+gS4ZGARcONJWM9OFKqpgb0lCZaUl0NbgOEb7XauylshxcHJNQsN50Nhd1X4LXfYkHnFzsEY7Q6UiyXgmoxk3TqnzETW3JUNSe56Sjruqd73PwEuav4KTxR7/pvhiAbJk6iLvpj+aWJBuzTyO8YLLfy72HryUKIZYl1poW0PXzcHZoFjmbDargskIiUfHyBozrc4t53Jvb1n16iIY3v0Pg4YLrCrDzDKkMc+SbGNQyFHMtzsyLPC+73lNcjiX/jtqw8DPy3KfqUeWEbOtItDbIgibGbO2xKbNfLl6rvEp1Ca58nZe4YPVY+Y+K0GWN6TjNqa4GfFPwV2tNSfi8bTTq224hGoMd1r6HOq/BdtkRsZYLLnIMCRsPbpSzznYEHMHXt+AvFQkg+6qrdzmfGr7pcfN8Pv/+dkV6+64RqC7PENYptRSrHnkhNCdzItsgZhT0pjrcSF8Ue1t0MZ8MuMIuEGMItd5+YBinlRhEmQysPD5hmU9yQ4pkdWkDVJcfQcui7+H2WLBKylEFhXRT/+0YCTT4edrydnLhnWr0vdzmQ9ANjkg4VW3ncBKmnfMp6sfV8V7UPbhtiYZfNI+i59KSFLBI1y8ei0eAG1sdLjjUnL43iiEJo2DjU6YFWueO5b62bSXvFo0n0u8uxPe+kx6INkDUhWcdJOE5eldC7ll/OjxTNiuuPy1yFuYjd2Kg+jSGoEjPosVS0cTy/x8cN8r09QUjVMS+0/yvFeu30u+gYYUxUrLVdlWjWW7eVoStMWKIlmIs9Hj5ftWL6+3+6iyKL+bHbWWKqg5LVERiDHJz0ZKNr1gaMdR/7FDuDmDZs8EWXwfK05HRZlBm9NqniG32fgfwdU58g/p9DNvj+A1ituOG/3gJKRT1J7CvnRROaPGei4KoR8bM+rQ34MNw/dib7FLXVYgcPLYZXdH4mbiM8s46cVpvO7lr1xNVWtE+JCPS8tTsTewWidkFRC2CxhJEUlwwIJypSKJOJGnunUvyJWYT+PQyfI4bRdynvyRnk4ovj3FLkWx44dSNJG618Dzhc+taQjKUkDMflkdDKrIB7s7Hxcp72qfQ2rdAdTLdvSIEJCmXtHLR6lOR9CPWPRsrj5Od5f/Wuo9nIbPkNpwmdsGUXC0nRQtHpgG383bdtX4IrxX7tXD12rvwjQ+uz1cXJPHADsAqnTBKRrEQ1Int0L6sBqSoDQ2tkF4p7jjFv5Y+E0urA/DOB4YA++m5EUpE5U3Pe41218zEc6vfi7xWSpsTg4E0Ft2zD8aK5JSkUs18GUv3M+04jXKIJIJNcqE3Ya6mczK1/qt+FsALUHL015tewuU6hEHWQEOLNbIgbhThXlH8muaEiWNhC576e3+OFf9HD5TNpFc4LbeFuRCpACzqXG/mB971sAkjlmws/iiHk+jhvZ/Q4LdDoJGTUm+PZFPMvBeoAHTPJBeCNaOTHP4o8n+znO31+PO4qL43xEaHxkZBzFgl5ia7kBjmM6tmkxxF+omw7fyShcP+SlGXK/omP12KOvaxWqk4tLcULFkGJAyYczGOJZ7bOr4PL8f/YbQ+kXFDyA0WACty/MTNhHxNFzXaJaM8T/iwdyieSc20q2CtXORNxdr2+eFRjVBIMe5Esli82NzVoNFcWpuWo8i0J6/lvkEcdeBc/zWTcqEfbBZ+OXNZD04X3Qul2h7ll5pfATj+mnY257bqlWiUELk3Bopi8E4LH3Yn2iy2xY6LPPV+ip/PNYbSBK4kLkeEow9csh4IfPcqGPwEof/5kSSUM3iapB2LvP2Wq0W9qaBXhFUC5WU9OvwYeJtYYZayFY//zSrnVT7z90ma7Z5+ifZauzT0Pe3A2DY//LdhyOWm1M6D+WJf6ulJWovH7rxi1J/AWlmOhtiVPudnAI7nHn+JVPN7XJrS7nsaCSYkZp1DxfwdgH0Px7tbzjNIjly1Vgubkc/Frpbp8uGWhHNVWpv+CmdjpxcrcKjTqLTQyCRbaQLL5f+qP0HnNZsVFCLHIGrZyTWo4I92AThgCe4wWWARNjP2ROLZI6vsFr7qd77SK1ZqHvBmW3DlZIRiM4f5vEq2MYkqkxL9nJYutf1nj0X+ztWG7ktPQbtoNCpB2mrYdEo9JShvmLKpjRmrtQgtqyr4XO1d7CanRVbTy2BxI4g8HCjQYDZUhTA6qfHMeevMrBHh8gejtahuNUs9lz6b2htPOSUkxIDKiTRNi0doeOYdCIovvkzigzCZFyhsGp8Aq41k7zsfibA4v0A5vYXr3UDyXJUo2ASe937xC0yrwOoFdn79CarFM0AV6nzqf5fEVsbK7WtG0/IpLbDQvxjUXKyjqsqS/6i8B8OO8fuMBlVwOFlJbHlYtKhsh+BbG0I1XpR28DVQHoDu2GY//YfCgSsi7d8gge6xixdFnoHqzWjQLao4PmtcE7egpkmptLEROU4Q/e296raao0t9vZgOzNWqRhXf83L6n8Da83AWqdFS9woRN2S1kGzkcb8KeDoHz7ZyJrrhBURq86bYG2GaLUe1fPq5XSSozqRYt9gEn+4JqIZ/hw8RknwArc7DsP9dXFu3ARrzSjeGFTG7OhviavK9oLChXYWPT2zst0wdt9aS/e9wp8h0Owwq6+ysWkybNGGUk5CNc+hpDaYaRq2RHwplAVVcdds34v+AQKNp7pnbKkdc1PooUWaMfsE6y1nwodPymbIK3vo4qn+hoDsHNi6LiZ5DosFRtS4VyJS8oNITJyHT+7TXdUrl+uV49e798ayqo1lVUDPvjWx8D1k2R8HfESO3Iz+KG9rvq9qzc72LbX09aH+OFQYJ0COlBaTOCuMkUIcTYKaW2OJyUR8+LXg9bLa552L/BVUthHXUdVGbRBncvK5av1sJkZ3E42X0CDx0lWWl1+PUu8fQZRCKxLs5MINU9mcJNkKYSbEjz3LAB36dlwhGgyjti4pL2q9Bym325LPOXeK2k56dpPhDdXbmxqEZoNgwKHc4BKYM0VWVm3d/V/UexdSRh9ldxa6DpxMXy4BTGBVEpCEBZr0yDyxyI+K17UQDYazXnPHhsv7pxAlv50I0cE5R9vqGIFXhF74R3gEuF3jT+k5nAnYuNHARXk1cVLFz2BKQqER9OQm7XzszZikPvUPq3hn6ELTxrZmr6Yj/PX+SUQpr3Kchzoer0FOTfqZ692o1vrJtzSlT0TJZPWgpTtX+wyizAnC8Hazs/evpLgkRGEkHFTOswKvcPrSaZUSJShliLafF18L/x1PKh2LTydy2+LCnwQbrJ+tpuyC0OIX5UlsL3dR5FOAMiiipcHRbSWx4KkNI6Ecwes1DM9jZji4GTSlI0tNhZAhIRdT4psrq9D9VP8tQMmeISRFhyedcaUog86NUWDRbYO7LRQBhDbIMb2FS2iCnS5f6scApSy3M76Cuxcvk34GZXV+a35GK4mWha/Wyus+5klflnsbVjLqc0XOoFnJPh2VeBEzAFYbglbpsT+S0GVF0uWfD/Xbp/+h/N9xpcIt5KemIOwPRXu08HNtLizDzGia7y3nHoh+0Qs9ANIUB1k5UKsiR/AOptMtw/aeKVqa24lpiQTpuK6LynORN5pfbl5+ajli68YWivEzQknjNg0r4Lw4QDoe72qEfi7zFpzkAk6sKbaGDKOvIv9whkYUB3xg7wsfB6dAqfC0/EYHv7JFziXf79ht94DyKM8HJqGyNe8uDXmHaATTzWM31/RfC72FemXq2rSQbNVaW2+RByg+cExqn8IDOC31rwLvoF5c59hEb6cO7Yti6+KgDU+LHlFB3KKWwR40v8pFmU+NkdKGHmloukw3OvJ1/F8hEJIgP5YmKKZIbZdFeqWfTxxkr/S1obkJ0hkUN83rG6yKlKZlfB6zuGgLhzRTJwJukNplni7Y9giu1MhTKo2tBWC52+RZjzaGqSfuFh+RM5CwzKxUjIG0esxdVPorqlQGHkknuwcS6Sbiufcu0cv7BRAfVn8olNiLf0iQV1sK34v9HVKyhUk7EhuBKBxCjGzDLoGCa0xPRTOGAWuU4xhpCUoDc1XUkD50lq79UfyPoBJKWshSdGZZYm43bZrjBraryACzFtgQMbLNaZ1R2zZAWS/eiweXlNuTg+3edLx2zWjipD0z+dBuLUwu0EzeRUga1kTjc7H3IOX7wAqukrSpmNhOL63YP3bw0F+xtI2T75rMHWn4l6ev1d6FlMhhSh63P4qyrCC0JvMT7Af5T5lOdksRxwxp9yjqUyzlX/lr3TcPYK5W8sM2cPnpNxanQn8Kqsabj4OhpoH7/74q81lMGXNF+tBCCnKvx7kpZ7qcgnCrwmcreod7ZewDmgTUl467fdBGMJ8asfYcplSAbME6vOmS3r75LGMkjrXQNKqWwyo8+verrjQws6gUAzkfEg9U9nOYkuY2QRKtTnt1XpAmWoa1jjK2oK0UnXocGbjq9VdNf5X7DKb0MciPUuaKySlejccKc0GWSJLC82D9uK99CJ+k2T3E98/i724qHa/IBjOibU/I1IRVZs0mr8W0QpjG/jUdOQ2+PddixjdIhwfUuTS2D4m2QYEG6MJoKBXdkcK8S3i2Vb8c947d2fii5gdgMJMNyei2lwJiNyudNh4rmk/SC81BLZp8ArFzvfzxPweCS6DBTBKcFLZPQGGj49GUM0BLi68ux/PqxH0u8t5GlT2kQ9a5XV2o7YMsePAW8iIaTiEgGUvshityz86LgeF/OxJEfHsEW8oruWpKNMR187xKE1bahRfD50ZVnu2vVr8/1RvYEnINTnlp9Am52E49rxSFqHi7z7QGHVDh8iN6jMwUcx9jWD5aziU692I7vzbTo90nP1dAedXXnx/lnYFHwotcK/3WPzcOk0BcrKMJZkjHXyvllm/Mv9Yv6f273geT5AVtnwpEy4AjbQOgZziWtU7DHtRpHr6NTCxnnCaWAu2V/qj15yUlGHy3SeABRVNckCHE0/PDlus9WZaVAgPO0Iz9ODlL9QTVTxXfxJTbAx3DzkTS0fZpZaayeKhGjqiIOn3rLdnsvSFwh7DAtCF6lsa0Z9sTOK5Yz7X/uqfkCsqs+fZMYE5RaUKb2hGnwL8qDwxGJ/ANg834nN1xe3d7UfEzsJIBcX5fsCVlHbLqB4HiHKmyaWuWFw2tZbaIsGcP/oPnWu9TX6sa7u1m4NZUhcxKWFSOrQJ71Tjt0eqnSWWsh+nYsdjbe0rZjGXFJfWkXquBbMI0xUPMnOpoXd/HRZxPfnvB4eQxEVrtKc+V37wrGpk+IXNfJYUWR3PHc1PAkU8OadJy+CMj4P17PsZ81bC+IlZt29eGT4wj4X77B/RZLPBKwsAJ1V/p2hxLdosauDhobgp1Pe5ZD+XfwpRQ1QIuX2l3ZGbrKxAZVAkEgiAhY5GODqk18/7pIj4M647dzruIxzBll48TJhyYpfU04/7YTUzmq2SKIr0sKUoprzaPl6XexpMsQRztxM4oxg2/j/EvS4FkizX+d5eZWpujlNSUHacdlj826xfV31xRZnBiUJafwlj5wbsxWAnznY3LZoVBX/Jr7KbqfABQ8sZWGDf7KFXzBtYRVRFKMFig7WMR6OXeIedHPmaZ4FZtLerFO/wAniQAAaO/5PCpJHJTYR4WRRSBy8XuCguBROgUL9/dR7eVewAK76JmutWre5u4Vn6ZIEwsujHj5ZYQaOfoS6/vD/XGDjCUJtVMzDMd0c9JO2DNm4/AynwVAcqtsTIXz/QGUGODxje+fU/cDTjaeGNoiliIi9M0yYurj4zPr96/FnqXTloC6r3Yqe195MikpZg8tVvIG4eZ//RySyd69rFHeGL0nIaQm6OJAXNxMw3OsqnsqMKBpFp/1FctZf/P3eaTGqP1HaKq2HV0XRksGYs2p0oaMrsIZk1hZAAuss92YKVclPoLUuu2+ItljGyRpBeS7xMmPfm9b8rKh8bW09mwprmFn50PXlcXtf6G0cwgN9Ue5K3StfP10s4lsHmQrr8GzXK7cgyJkzbaawwRap4m0+4V0x+l/wDR+tz6la7U19a9NPU4VseZkFNEOGZWRuyxwiCTEUk5gsPKaFO99wHaeDG2/oqlTcJmw5dxDqW5R0uyt7PRDhdEqsss7DBhPJd6B/LMz65E2qjt58tMvCZNa7hyFa7KOy7mdp7+TSCL1AZFTNPoVXFwrv030NMHOzPGWtSEU2Q1+hqST9uJQO4GIo07jH83vsrFCfEE5ulmzrIBgFRxlAoIDZrD4iRH2qnSMDGo/EGQF5WqbaAYsRkuAXrBILNE90f9v4KebvdACCCV6IJAWO3iOLF79zIcjMMYqRM8E2336o3sCJ1r648WFZqqfgTzTHGE84WjN8uzPKQZ6aNW5/02SJ7i7KtM048/Y8ac/iz3Du6Z+97alI/VCsPRXKKsvOJMCxVcL3PZI8ecJK15JOw9DPZL+av633BPV3ew3cRyZoaUSeMTmbHb5EEuSWl8ezZPhxvbXu7iId+EPX3sJXL3wxyLdU4rSkVR+qDazQ9cjJI/TyPV7eDGz5+OuK/Wxir4Jujp5s6yJ8fyw1bQprNdGgebbSvGR7Voxbll9jQi/7XIHzvf8WCL02xga9DfQ4U2x2LT8R5XBuhObVF7Sj2xZomfq/wZnM3jYKtJXqmRztErGJ50Di1KkX8yoeLvE8IHq7sqjwoX2FcIX4v+dbfSpabb2p6qATPNV5+cTGyvvbm5m++vumd8BRC5HhSK50J/AJLd5gnop7fOMYZjjZOQXSY2q5+Z9/z8d3Oe7z/+33Cktb69FmxII5Xh/Mz1wJefBveZAZP4wmZLKUfm1dj+3ND8Piwf31PbekRWU0Em/IyiST3iRNeODe5+mpYy5sxUykVUaQcF3sdpUow4sTa2jgb6KsJkhuDykOFVVpgprBtMo8JizZXay6fvpf6K05RuEWUgkwLpFx3VYkEz1XgH8mxyPfFUUYuVlYpX/DpOuCj3d6hG+5pDlMBop7ihl8Q4ffsbWKERJ8RANxR4nCK5Ke+cEXX1/GQU+pLLCay1h8AaPcA+Iwcqhi5Vt0gnUtNDLHbmYKE3Pob54bkZu7ydXvFc7jNYjcshNEjbnXgD39Qt1mnE5XUO5/k6T+uxGdzUwsoFOhd774BAptH48EtXqrZIYh+WfJJEwJ+fwhNbPRhF82utt5ElASyh6/TvTlbFnbcTvqUO3TA1wYOP7gbxwsec/Qc1KJwwz3MczT4HZYpugvQl+ck0tjWhhKodHiP6NQzK/qjzJv4t0Fj3AIkPggiH/1QnRrsrcl88IfhhvOrFUfYY/o0yK8cDsecKBuue3UNJBJRWhDutgrccVkkoJwLTBcy+WkmOGRZSS3f9LjyDf/Eay4rd3prGIiF1wg1ADaQk5ZHVXmAxEbE90Wc5EyS09Svu8hR+DAF3+lcyFStGLJJ8Zmt6oML0mbsazEp8ZovXA13sstJnwG9wyvTaQBcOu0yfAn43iCyUtVja3FXhegMC3u4cyZXejyGssWSXxd/EvlUnREeOzQoSYWU0EwaOD7Jjw+cUipFgK6uWTnU+AH5htAbYzWGDNwoOwEW3MqjukEglBuTxwdhFBsDwtbuc2jTU3E6Oci75AfjLwmc4+UEriqUd/G4siCEGdz7bmEpctmnPYF8cSZH27Ba6pJby25YxIqCFm7cwHvLl0zx+e4wufS3yHvTl9O9ZOsMGeTjEPPIxGeBZrBMiHyWwyAaDn3lTWJVs46P/WvWPkJLM4pH36tK0Wm+Gej8gvQkm2+elFsO66714pjfw5HuSnBgOJJmRQ3qNyoYeZvCQnVmR1IU5/m44t5M1fP+C7gwQ1LBWTAHED8+DbW2G0H3UGcbfrkoE5P/g5dZzyedHMCQXu8Mnbmvr0BlvIBcXIT5p4i1IdAx81tVoTX1lTdRy3Er6/CiEjFWTgZQrjJMSFVUsis37CPXmUIwgMSrWLSw5unvsgv9e7Y1lH/ZQXbyT3rom8niw+V6FxLPUoLQtJN0LCsOmkJ9Yy0T/KWzGH1tGn58CkJEhcnNj8VEld5E1SKeP4RbyHAtwNBmA5W7utEwc2VfkNftVFT+DId83pyc3ZGtvtQp5P9MuKBDtDVD2Qp3XqBnHEIDTVg7AudJ7AJI+qSk8HmerIEs7UdckSesTNYSpsjdBFPRXtxrqnqu9DSHhY5aC9X8N6P+bVtLof+kQpLLFswlZK36kFu6n/FrQxEFddC79d2yGKssVJciz4XXeQAt892IsTEUyfXaFXY/XXRxpj2EzDs/s1ZvEPcSU9HiEZQ2OdoVZniFd5oh0sWvcoIB28TFrc8tBkcu3+m/tJoEqTUrlnLqNS+lfR6Yx5k0SJ8iPm/+i+Ql5hWa+pmP34PPj0MxlhQWj/YdtRzISDVi3ob5cptZ8LMeWZdW1X1b60F4ysTXbYBUcEumwI9EXSQGVvAxiiCFPqR9GOLunAw0eHpqXh91T4AyowEm8PWb5csfphxYt369Zvtu6ndCg6rjn8/k5bBbqSO2ptdIbgNWKnIQwa2PZp6adSMU6V1G7pFVCCmIjysVzfWoxWSNc57QVCL8JflYyT47ZU7Y+89PyksdQDsmf5yJvgDPcaqAC7RsfbobGmtL2p9X8Q3w2G9ryabWdwpGT5fPje8kNmsFadg4jZ99198mRZY4zGBZUuJqcYZ1sbB50hCq/Oqaei76x7gtFXIqKIkkOz4qOmJs+871COzP2Jxr2rg7KF0/1JjzbW3XS14m4Zm2LDansuizGHAlPcMvuHF5L8Ksv/LlJuDloRh0g7+bdfdAcQmA2SQht5xIkfqNobq9Dme5XcQ0j7P+9v877UA2Q4BgJ+CxSfQ1qDouzTGUm+lUmBdA2MeWKB5vPfry4TrX+CtYkPnWKDMtRwm0axmHyzBrBGVPXw2SSC/E6RXKvFr/XeheqOQ9RcTtDyewKFfKJb0QEhabkYvBN18AR43gIFaC3XpU0o5/Bafx5rv1XYmaWntJJfcgiJxcROtguMPvqH1o50mAlp6+2Xtea9XXxpJ+DaXU7aCklDzESnW+fbkxQppgqd6MUW+Irt5xfDdrOhd5f8229OCv0jIjEY/YqzacIl3J7bpaX6J37dKyXZfjlwfD8oq/IPnuf2eJWD2W7c+eKAo9+K1hWi9asnC67fUQ0Fkn3l6/vcwu03QX4XQJfFLmJzLxzMC24dj1mqj5422yD42oCrRofA2kcuntwj7JuShCdQlnOtSRFSbEr9Y21TpK1wkiY4teypa6daYPXFb4K505/hFs4DXhQFdYWk+wsfJZXhQJQpF1Fiu1hywcaocL4yh/MWEJeg8dU9tMk0u3qe6/dQ9PKCV+FXs2MxdsaLUm5YinHc2ndDvG7l9XexmpAtIp+eetfaH1jlMd+IIkBpaib0x65FJK5XeQ1IVZcI2Wz/Fn8zTVaSYGBSRF1SMHnQ4ZIsn0wy0/SttIiSNp3leFc51Mc0pKZju4hB4AzMiEKRg0NZY34ZH36vEVNuWXOwrHIC5OPEPhd8ANQTQOZkVILmd9PS09UwdlWFS7blMHCNLERaOX1vcSbDNKt4RVXkSENjYRoZFYqBJH3VSel8xJtkV/ta40PLNFy1gjEOVYOXi6/Uaq5NPMtIpL1NoOG9G8qDakgnTzOx45V3+Fl6tzabbjSZDBJNbC6kTIOKeNvOgNENawJbxfP9QZS85DCkKo3gBgEd46t9w+bA4zbKo0r2bye+b5yP5Kcj2XeXqTVKlK4cqFZSRbzqR1dUDKxeEdqMFUg5dTM9Mfw2d6IQzHYORQsIMGRnPbspBNsCe0j6rwAyjxGZZPb+vdSf4VntLK1NTkloG2pRedTyjYG5YETWlwZ07yxUCufwdU7fyl8L/UGOkOAkShiJ6WQaFPkVtG8WAdCZyx5RyQWkqk6Y+M3dOb8zGPYM/LyH2/EvUXa9psrjtoxieusIQoBC6zOYF4VZf3CDPST+cgtq8XnUTb3rvc52Zx3iSO1FCFCAph8KB9T5DINhnit+ft5xt2gEDzOF4/F3sdozTlF5Eb9OuSdLAOD+BLhg/kTJn3Gf47EolvNPc/VPiPz295gldjp7Iriw5JUBGD4Pq3f5bfgpiXL9nwRY3ML5na8evujMzIeFpmUIWe5VXTjO2Lsmsdkj/06tLEuVx8zCojp1b/WenPptx2+iI2aAuKDucdhxFPMlr5Y0lBYzM9iP6q13jU+hSe9BvKZBL+6dSQIdAJepCliWJtFtUVekFFBpSo7WI1P0dvKfUjk3dwPyr5D+bew5DD2VMCzp8sOmZvBV8xvAjZOAT8332VsTXbWWGeZHpHfbAM4F2/GY1gSZVRSwHZSale2bhf7FQv0gu02FTxubgD7USlxUehtGMmkvzKl2645EEvBYz/hFZFx6UGPJuJ2/8ggk5AqyFVEsqB4FORflH9z5dcrAtntebPy87ZknzERLP/cRay1Tufj5P9d51NA0kJs9hpx0NV3RgaDC/Zm4Cvvs+yFpgXs1imn/jHyO9II3wU/xcaMepbNKVG12BxG1CBz9IxmdxHGq6vu55X61wrvsjE7+9PdkzxZ64UFdLVL4f1aojDo5VOJCG3ev1r5WuQ9IKlQN7Xge66fnIj5kTLsd8nW0V4xSVCe67gkWu+0kO8/1+5y0b4WfUvfx6IvRJY4XpvGjyWUmTZN35Bp6AkN6+X+eKo39X01JRkgM2dUnpEzc5Vq160STUL49CyX+NPlo6TzWOhtIFkKBNrePwcFJqvLBoyNP45xiHRevC6f9oLe/fc+xn4Akmn8L3F5aPVHTlgngqky1U/MFIucidQcMP4UgF8wgyCSX2N9r4r936HkWi+PIowXshXYyk02nsiH3u1iI+EXRyHtdrK9BFP2X8vCyrwq9l/A5OHxRrVXDKzcPpwTyVEcWDVoTkNjiB2kF2ArM5yg+VuhYFLuNbBdXt3L2v9nMHmoXKmDcoDJifupMmDKhMnAFSuNTmfKTSI7IbOdDF1z/k8nx1Htr1ByrbfKSUM3apZXKjihTNcHXhe85cZXaHcWBk2rhPaizH8FkedKtzoVSo3gMSiUh30ZTvAyaktTBYPfu5FH0Uq0l/dfq/13EHl4E8QFIB/O5wz7rmi8lHjkGuzNAAZ8HvFgkRX0BijlDBJFh45fK/8XYHZ+xsl1RZ9BlBEbM6UpzzDKUrLgV58/J02hLTSwUePvwGwtM8hpWGywtk8a8Rkf8zxkk7UwA2ednsVvgXfpiyfblhYsNE0jvdh2nzucc/3/hswO1cv1Q8PcPdxek74sV7YmLpN61yLWGtOwbK6qKHzm0iS4DTFcfII3kNnhlSZ2FpeV7XU16xiLra3VeHYS1M6bO66woayBMtfF/js6u/gIdyaDrMd6keAQCotcdWVPWi0asfIypEkfNWGA2Bfu1f980v+Czc7f4W4WEVhKUGxrxrbiX8w2o5h58baUYD1fFnruKPMnaHauMGxQt/GAnaQbLiONgYrTxdVTJICSYdNHol9Qmkir4xrJafFJHCX/BM7OPdDWpimLCajN+QvVnKvZWl2ou+z+0zJXKKvw4KLEf0Jna5WifyTpYZQ5CTdlipUtAw1mcS6f+10ZgC7o7KLIf0Rnhw9LFu+ITluNbFSwiOi9fcQZFKO1Vg02ytik1pra/KU5LBrEi5L/DVEcjl1UcpiXyAce5LZovKqty8ff7j7Z6NGnJVb5osT/GT6u1XG4q9VOOc++pc0QxGCe5qaS9UuCQXi179X9E3a8OEqLb3KYbHIX9Zb7wNS2m8rfRfNSmNBRB8LCA7poYf55Dn7+WW+vJvvjiLI7MSpAVmqre2RpfmljvEy2jSq6fuzv7ughBJmD/G5Lw7q5RrmWQaR5fxck4RYZMJUPJu7cOnFY+YXNfFXrrwCSMWUsQ0HW369fySyfCZFD8U8OE3hXAQDN4p6NLX7uEE+l/g4fMTFuiVDMtKEu2O2ZCK6dDNYRQzdaW4QOI9iXSSFxj8SzlwSRTATOXTPr/yj+V/yIh2cHvvr9voKs02V0RMPLC9GtgVV6EHvUmejY6cxe7aLaZ/AjuLAzni9BFDw2kViYEKugEFqFJs9rYPJnFBR++Vo8BiLfJISCiVlxRB8HVE1bu+VN361/gpWC7HLTYnY4bM18/1ruXRSpXW7Xd+fkXSQj34xsFtvOPAX++EkyVmLSU6qifVn/LllnF2XfhZAJfJidfBnhOZuvM7sdwFAfWMG4oiLLLwv/UeNjEJKF7f7dsD4q/f05dYcTYwmJPNKqrOQKTkwQb6QrgN3//heqL4pE82NLVsu3+m9BSGb4Hc3u9qcg0TOoPt/kaSkJV1KEMY+5Y1QN48kCVWUSklYPxFH2sxByv2AdftRJs356m5zHqkEcZ5p1MRr66HTdMgwpf5V7G0RyiY0ed+vK8+DgIZeDchnmD189G/ICOXlh60aYrAUux/pX8b+DSBhhWTl8jJCwPg38b/Naidl8FhgkhIXZtoegnct8AETKbBTxvy+VS6w1R4An4k4GHpU0bT3F+sGF5/prLU9OVl5J2qPipzBk7zJuLe92FlYIz5fZXjcXV9wX0iLpk1/x5fHwDIakNfNs6TLbkxonq/X9qk6v0eRscGed+lBzxq813oOQkTFcHkN50e/19YgOSNfOrIOXoHYLJW4YiGeJA4NcjOrXon9EaJoR0b06yQ7rh4Oc7faAHXku+GzwRZsUl+Xu1WO9gdIA0ihht86FNxXfqjngkE2yaY45qGYOGgK1JVrlosw7aBy+JVwJ3+kfZTuJRiuY1thN6/cpxd/gUrLcSXfcm71/zX2IFrVjYpARFXWWG3aX8DIZxfKyxmFj1oyB2We6htyxa/te6q8IzUv1JvJt0lDNi7RUcycCVYTW/inmYvnk1jUfjU85jhROBd9Y8/E5bM0sC6RSoRnIbWVXtiQp+0AzSvTEl8BxN00Hse2JO/r2pIT5w97sXPqPKI23czv/tdtpcKu3N4LpPEnPeAaBa94V9VaNWfyJ3UVoeLV8LvcZmMbPWZnBpUqXjP+0V0p5qh/pBHDKq9EXDL1DJt1pFP1rsfeXfdu5njUEEUCXZMcFI1B40dZwOHFTQN8OnIqWvlb7zLIvuaa5docXWpHCpU4Tw5VLDA8nH46O49NzIoaJ+sqLsyQ6XpT+O1TDN0UJV8VrHzbdcGczk+fwLpfFOw665uWb+xRUkyl1krl42xoG5kniqdWu9Sl6Uxku4LSQs4xpg/aCcMVYvurD83FhkZ7Lv4XUGInVxNjUZaw5d5thPjTnFD0qBdkIe8XHAPEWZgsWC6GnUl8XD/0xoEbMAIy6fYI2Yxwzg900Xga8IfCrX6IKaHd246P4V6G3IRoR9LWI75dCkacBbTh/hX86gz3lZrJn+fA12M5l+edWOR4vkYPX5d8EaU7mrY2eYbhiJlu2J2NhzuW7bdw7bMcjHedd5mObPkVtBOchDu6jqIacD6bd+53A2YA3u7qZQeU1zUyIUzg16nGI+q74AZDWUNPL+lYsTPy223ymbXJcu0UtLCyGVC7P3mcwGodtA38n3LKzTBTqiOIhSjCa4WTrnxiNb7O+yvciH9jzbadU5LE0trhF+l6+kTCVvF6MeG9fEG+Gr9LQkR1w2VQ+g9FCVb6LQktovEcoiWG0GUbM9MMeKjhvSWO6eqg3IBruplGJJTLd0F/5oTATz2me96GN7a8zLLz9qRaK+0V7cHOTBl2RpJqt5XLNeI0J0sHMQo2WTmMUhe0NqLYQXFPLL57pHTz5ZqbURjhcngzmNIb+A8FX7djx/K5mYbWmfu/V1UcwJIYIld7Pb82KFPKsIBGSKLexz6Qi5d/KD9N674rn1XEjeSr1Fk3UNf2+u5M80k0MHVycWsPKPJz5ltiA0bpWZ9vrrUvpfxR7Az/yzYTha5eLY7bvlCQnkristbp8WCR4er+1hSkTix6X2JKgdaj51BfWp/Cj594pVRMPlmRdmm3ZjqN8wRIXcg8dq4LjLEk9iiqfT214fZQnuoc+8Lry7HR0tTLHBRrH4rjXJ33K8FhTau/x6q+Po8fYlPzEsF1j+t05zn7gcgeR5Y63dM+8WHDl8qrxa7W30aPUxYN9WDBpz7RQySndpJjBKHZMOL8y1rPHLxQM5aoeiUrHyu/t+WKB3BpSxitIO5A0ICMjRkYyRrmYxxleN+ny8T626JPlkmed0LZHF4hISDFKshw4yqCQykiZI0/b9a6doCw+6XODQin7H/Xf54pu51mWql+63s4D91oEeyRRw6Ic41c5A2flL4zTYpzT/fJ0e27RB7Z2UUFBMjfDcksEMVFu6L/eJ4zmfW3R2SuDMB/n0RcF38aR0Ca2G0U3YEIHkwQPFF7Rba9HF+dFEaMHcmPVF4z+UNxiX3Fd/D0UGUurCrtsxfw/lHzkLQogm0Firp+7CcI025HP8C7zqVXf1u5IFlHg7zf4Q1mJngEXALSSjHADOrlqtjV++3MVN9wcd/RTzwU/ACLhOlf8fvOG0LqtIZOU34MpqBch2DFsNzPqzxZO2Lw+iiO3JsapnQRASIVksQoMHqfCkxdlpez3E5Koj+PIPa9aOszAIkKj/ZDnTaxBNCcvZjzoljBicGyEZb+zhOFdFH0HU4g7oTSjII59NeE8a544GtEyPXHHQrMbzaUdmXnHQu9sJR299vYwPydXH1vJMu1rLGvBfEZhlrklO/nqx39zKVlqkL1Kk1yeUVa3jXm1tXmYse953TvElcvm/3O32Zh+CgrrMGtIrBG2Hz4JnKK1xqkTqOK79w/jL7uw0D+s7fhFqb/AtJFDsYEGhxZyl/K/z6IGgZyLCdJrVZocooU8t6wzUJ0k0tWl8arY32Ca7b9z7ujz4naYYsBZgGv7kICVb2TQTY4ODq+B3QjBs9AbY+hF0fBDJx/jH7X/gNO84bTYwvBrgIdXOzKjpHx1GCrTrFFO73hdtekMI/O1Vb+lcu/DNHszXEl4fNSiL79oHN8mUpBaBAFXthltms4wzCSW2JWLYn9Han6E9GVg+v6xcVoNOewkI/ixgjdOLqPQ8EkZjH8WeweozQ8vC9n6FjWCfTcJcZxvbNDwoCcxincpjq7Fe30C8Nvi6sR3UfeNIZ4fdPisbIoURBqctgSMFvPYNJRo8oIk1ZRlMfm6DPHOpf6GKL06mT3chsylFudkLM5RI+lyzrg3rCONOcof5HXxNJ/Ak3Yk7NJDOW/tijIPNZR5g7JbM75R1dGFDf1kEcDI1u+W2tllD2u88ErxW/2/4kk/hA/bSeyUwTT4TDXRLTRln+neq8qFwMFA+WcEelvMK2a6wfnFFWaU/QieHJ9e1Vo9e5oH7COLW10r2O/FNAdRbjHUrmllA1xWegdImpBkjzfkSMtR/imYTEZgPBaoRGlojKPY1DR9OrfeLiqNVrGpn3bg19X/hiS9pfShO9l+xtHbbpcdQDSlnCYjzejb1qkxT+mXndpNKDnOidC6Ekmc46fa2fYUXk8yq5URkRQH0KbrrCTArXZvw4ccVvWsKr6JJYemLPXxoyVWAbyogW4YjPSQLUg59SX728vRKH8v8UckOarM2k9s7S30EzSHyVw2IIxO6nhtn8xB5n95nXWci/wZSfq5uWuh4yrrmCJ1iUpcNdzt2f+RnixmWbcQ8xyZtsI5Ti/Xv9b8Az4bDzW0qqCoqj34pCp/RkAYMRxeSlg4NvmV2veH+hs+8+P3LxGleYqpfRh84wFgLyTO1NnIt2YJxASspBXnnsv8FZD7AcgjvObtClacS7DPg2WbTR+z7fkl2iZtARTnjresd48AScyP97hhehT8PxqU+0yaAsvepsuYHksZKtVa73lhbV3ikh12VeyvUNILcomC1rxy2ELDtVXJUI61vxh4Lpbp7i0kPDXSSlE8ohzvngOUVS58eKy5opAihz4v+OriR1ofBP3Q+K+eFOY6OTa5ZEg0mjOuWaiXtf8KKMGF+6CBsVYVD4mYxJodHPb3HLlieaIoA+zkkn1qOPJpFHAcNXj3GKQkDALX7j1p9iOpuVIbKuoyhMm0kixZ5/UFOn7Fr2XeA5MVhgq4oGG5GIS6cTGRjoBPDoaNOq24GlQ0Vfv9qd6Fk0rs2zlK3GkJyYuyorwk193SCOQi5YjfEo9Yo6uiT5RF8iqwPpd+E6Ztj5fpaB8SWyOqpCkrmlEEKX3CND3f9EoXp9pTQM3r3YwyfnOBM7noTNtuuYLYn3NYPtrs3gsXsef6w6ux9MSQx2S1PXwr/zZO2ymvlaGy6/h+dIXbuK6esQ6TZanJARdQSKrN+52pboMPlxffYziNg6ET7rodrBrWIySr3SgiSkZ8P/lg7dD8BFFJrcnv18Xehmr0j0Us0K07K/JoZWrXiumNGERAjyk08PojCUZ0CQLItF0dOC6L/x2pYVzPxbxdhELlxXYUwuxzihnMI2YSdKO+w4vr7gGkJmvUCgZuTX5mDs5zqQzyygRsZSgOdK+bIMVvOPp9d/LHTK+L0+0BoMZGrWu3lLN0tvip+DF+Kn5S2qZWdVLzolLqY/9a5E2otvU4729s6xnhZZXpAZ9tIsLSz1sAy0eyIATTy87yKazGnsnhWdFKltKFDDcnb6hoGQE0vkWiuTqgWt0H8LYSrO44WPDuOYghx+z3Bw6y5ATuHxxCC0CkqUHgbgTD1SDmXN0dILldBGLRsimVz8Jc9OVJ2Z1EcXsxHbUucfRXP/IbSJLdPdv77fKEYoPRmWhWJv9PZjXc62dsGELvfhBHn1uYJ4bi27HCjECfPOdnM/tQwV3jBfePoTjbtBFXsZZan1tK9t1cmt8RdUjquDJn5oYcAg7BTjJ0qRwCN8MEOWZXMcZFqb8iySo3f12FO/OHGFb6wYJmp9tuJGmEO3Omc1/upViOc1pfH95J7j9/pLGuiaamWIICSyx4sadEe2cK5wgA6LO/jTE0ZZ8lmV59L/xH/Ii96B7yrUxLFA2VZMnUO5t2ri1Wv3yW9OJ1Lp3c5Kykejqz6qMbye1TATr4XDQWKXqj526PlxyLdHlRWPysyVy2hrCGr6XexmSSZNKxbi8mXLWCT3Zq5CjgyKSJqKw6eQ/yTK8KrcZgx3Tpxy2fr09hMuYwTI82MBCaYUWUTzna6gy+ph+n8FydMdhfkt5HjY/tzsTF1MK0tgZRu3nc/rfXRB0AjgS0V5npaYYAG/BekbfyBuX43RQUUZZokHP9tzAZusKtaFptB9FiNwZBUcJuxyuYOIseCsiXdHyoZ8zgl2FbPHXg9VFMRr9V0/t13ACvyKMJasWHj0aY6Z7ZfxCiZ8oZjO+V8npZ721YJvNLTctTjdqWyYoechWb06T8cr69bkI5jEW2XysfcwwUV/Pny+JvLtASAdqh4w6QpOPxo4WgOVNgxGhzw7SJ4HI6Tvx9fQaWoYkoSCR3jit+rF0EECZNfHNMraE3gYO5tXmcFWb6u/roV+qoyn0KlNU6cqmx5mK6p4TyNKRymFu4udNLq3SmtCWf+KLIG6CMi6HTNzoRmhnbYq1jYlmFaXvL5wuf/IWQlqzOiyKf2J8Vfp42swhYtnpNFZWjm2c/zviIsYyHksV555CFn4BkfQz3xECzGDzTOV4BMUSzzfrm7iSZOmh+T6mthmIXj/XmBq2G3gGLuAzj25hEUrB31Nk0oftlgwZT3h9XvL4+B29lu8Kn7Gi+0c1zEB1sVyCFlxlfkZN5t8Z4CSWepYaVzoonO/pw0YEjB3vDCKTaxSSubrBR1wwryYeR0fvdvQ/R6PkjNPutk+1JShGNZgpiP8sIE0Ew8t1je2zvKYl+7ng/nUr9edlHG+NwSdmdxXVUYvVfGYF3+fYSryNdUfpY9c03lkvWr0beFwXfwGmEGm8AB7eKhgA5evhhIbgh7GYfxt/ldogOTOEAykx1q8OHkP9DX+Iqn74q/tddn7Y72kDViklfBzeW9C6A7otpfpHxlUiZzmiazowdfV2zi0a9D7JHfewR/yeFqePO4+FRSMkfp9abppIurbSFA7SztfPXYu8dEciOXZEdE3NDBEdy5kkz6J0VJIrfkj/9smXmeOxpj7XeRpa8z1rybU0/1JPtBRm06Pdt0aZHBdRXcTSzuW5s/x6hfhx0+QQsj5XfW/YlV6UXSZK/zKMWJlifmwWb8ZmwqCNbXF3dVeNjwFKs6wgFvu8MaICKTmDPOKwSmbDvAuEAvIG5vEBgOdb321B3zTOfHV26e6Xwrf7by76yV68Pv3EDd1TgweGWrzl/xNAiBLXd2nMyqSx2XFSpV1Y3PNX9GLKEiMFycndVBprDdMy2KjFjSS4YSmtLGnlOx8nDRaG3IWWRbZfGMgX/3Ex8e6S5gSEo9xC5pfVmM1ZvmaAM0zSbrcdp9UX5v4PKJrtRmepC0ZMNmoU9ygHaPIxTWrwH0SHm18VTfmjVty962Jlur7CIlRkXXamrnfwEcMZTuFG0Y9kPn9rgy0fGZ7/o3B7AlbgtJDnqOIXkikg0Jo/RTOLBmnW5OUzBXOLXEu+yMhvZQHE7nFD1cFXYVYYgcUZGcXS5Tw+07QT+/hjvgUoaygZnacPAXfymNM3Jx083TpsYMIc3D5EecJSAHt3CK9evNd/ZpeUqy60qO6U4F/nZcHI0tnD0nzYx/ORjexX//anewJRsxIHiSUSmAseG0EuTdkpYNb0XZoteCWJZtdPnFuHmMo3Oq8O00ZlEj6iB/8JF0BBa32B1yUiwfTUmPz/P27vdjkgnz0EGvJ8xwLFuIuivoiyP3n+0tdMK/71fl1so0t6ysGMaXv7i5P1HcIXiGiEmodXRIkdeh5PHPGHk9iZ/hgtf1foLjAxzReJlNp486uNOqnEZNgnRFBpkaxGhHuSRWhZf1B5XR5CLan/DkGFG0zvFGbYNgUH+lFC2NdQu3FXb145DCIeo8psVfCu3LqcTQUHf6yDkqvYfIGSwcUyvSR3qdmAO2zqIEe8zgvacTWYXt4JbVQEM4zAQw2nrtfK53vsQMgwOpiO6bHvksEUZyXcFmOSZbOeyuYaQ9Bg/l317APLXOn9Hj1Zqd2yeelHklwwSoDdq3drtEpCcJ5bP2XKDOHh5NjyEH8MMFCzyONze54opozykaLOJJGADKJM2RmMs2qNy3zuSYCa5eQ3dOJf+G4AcD3mDjZK8gMGLpPtmTwApxJusrKw2krwl2xV28XyfQJBhnvnbR8/4wCVYStuTZJrYCaivCuaBsZCIJmjanqHuYw3bYmVTpUynPR6zf6v/VwRp2qHd90zSzajgB6/Uj6z4lR7ahx64KQJCEDmZc/I0Bt/PinhxuD0CIO0u2XAuO5yC0lTJMQirP1ykGgu0ZkPIybnzktxH/1exd0BkMGVf9WWkSjvEJiyrI/MDEjfISmX75yG6xeY+1Ncb4vwgjYS4El4uy/8NRIYJIqHF56SesZu5JBqKYMnJwsFr4Hu4GOaozpsoMkzCaBrZ3zWQ/8xgHDGapqjQQaRox30qfODz6tFeM7HKax6ECr6JIe31raIOpwJ1Ec6NAiGirXyiUcu46wxEahi1+q+ca/wRRI4+dq8OKgJNhCBlmVX6OTQwxlson/5A2yV31aY9gSKDocjtmxDWCpy5nmgerxE4vVAJxhtjnuB7HnC4OxmhQNapq1f5uehfQUUYxpPSlpZuZAm+/zFBtQVaGDs4lu2g0Vdo35/pbxjSDqtWaHBzcpphdJtwcdCWcelGDZjLJ/MK6rg/8vHOhf4Ax4NlH7oupXR2H+GRE4R/xCBOfwLb8cmHPPavfcwNlDt+1j40yEvSmIVoq1tvUzj/QXAdXtqiNdP3rhTmrdD2CI7EMi4pczM2+Ea5Yk0kxROW9HAww0cARKDzmf6dAYL4YhN3UeqvMBJEFecZ/r7eW5T6lGwXYqKQdhdJEdFjmHOVs5jWvkrjL2r9HUSSKRhL96w4EofUdsuQR7O1JZB8GMjAdA085oiLmCf4OCoZeftnblLXdrPp+EfxP6JIcNf2KJnIJO0TlKWe0DiJrIATS1fLyp8hDqUOXBVt9o5opz2GIRt0k0qmYGe8kWU7XubBLvo7nNzymSP7aTZawpq0dC71Hox8n6gON5DtCasrlK2Zn6Zw8jmETVGmwVVdLMfj5VvwJIrkjKhBFowRSu6ul4SXQgfTbdGXBlc3z8IZiGVMTZQl4y4PisfwGdv6/WwT3TZ6aQcqb3OFiNT45DrWRlXctcSILQRl+jEvISZRc9N92vz1D3ALoMGp66zJ99yjiKCDNnwDExUUKhaObhGICw6tHKSdPHpxGYZUvxpXq+xnAdoGv3C5KU4BdhBx8DOopi56t2tRkvs0mG5uTvTz6tB0WextgBZ1C8p/M4N6N0DLi4Sn6vuKjPrhcAOlYAhYf6fBSyaSqqZ1iH5Z/O/wDMBY9SPv8p+bekOIUH46r0Qzcpw7PukOL16IB9AZq69Cn/B24MBIQ7ucpMQb2JrvK0WZ6fXDw1OdPFMRohnyuj5TwQ+gM2xkKTMFLDxTFlHI2AvZdD4cIGFN6+MNP/Xo7TFwxg49M18cJuuQQVieNuONFhsnMIAORyFnTl+rvIfOOOxFrfBe6CzIrCjL5czPkWlWUki0uEYFTjkI/ooYy6v34LnsH3EFrkWN/qFLmFTcIQ3CYBJT3RgWi2qZx6xBIBcP9gZEw4YA7VbsjJXowDCxgtRsryr9sVzSLOg5cED90ZT9PsctUpyhNg6MZPVhJ8uKMt0x1MycPtXGWTP97z/rO1hc2bdijWPXyTyoTzXquNNYlzf9/Sa7Sd7xl1txxPvPcB+eAQi3r1oLZ1dBhiwQIIhm2l6NW5hKQ3lkFlYXv50aVobdRam/wjOJ2yCk7SQ0ZM0wObIyWtlAYC+cWP6mKYOaSz4io/zqmHBR7I0lX2EEnrWj27o64HgUORw9nB/GCVCsuO2D5iIRBg13qidixVQSa8bkVe2/Lvnk7AAw34ddQuX4UxRUnw27KwQXUYMy1tfejlJn4q49TtCVc8HPIbR9agAo7kg9PYZGe07mhDvQoxBrCHH0sfb5CPasq/3Wudh7GI3YdwfLOXDPbzcus+0woyDkH0RX+xHTmP1n5FIoLx++VnsbpEEddvKZ3lp/7NJZQGfpfJW2xXnhpv//MIbxY9XnjQq7g5zvD/reFZEqRkbRl66d1Ey0chYn2O0p57rECTKDPF5j7xqfQpLiS+62FECYzqZvD92QDS3RQQQNZ2WQt2GKpksFW3jo/Vs3g6/TOCpK+Vb/LSCpgFH8umJNSWEE2Lts7Rnidd51rbMD27Ltr/Adi1Ys6jmx7lbPIJX9GJBUNBxIoiJbx05ZvqJt9IcKyGzGx5ppntgMrdZil4XeBpFwVUIevmhMEIq8PkBfOaFWjUbc9rBGmJxgBOt3zXCdW77dgKf/Vf7vMFIJs2i6+qcNMR773HHVZD7J9MHTaxLxysHQVXU+teVrHvsX3zPpKl1yanBEJ/qSg47OvSnWIpmkazsOdat78TDzRTP0AJAkhrNx39ZIpsKHl8E82mT+PDkuhtEaK6KVJ3wu8YEFWm3ByVKpy/asyxXzQzalJW+xBwzpFh+3CG/Qi761mjqei74F0BR36TXChWHzEf2drW2vtke1xQ/vd3l9r+8OPKu4EynZuXQFdbENGBW0uWv2k2djDKEA3HX1uOM93r43F1RRHtMAbsQQzRP2Usa2D5J+swOqWULMbnsQzd81Hefmx6d6Y+ZBs47Rbaz8rsj8GSqwYstDMymbmOV7Kpxsx1bsfag8xMjcWgLNNhqPqmbXZ8RCQfX5/ic4g3gvq5tuI09nfPxdJNDi92Lv7NKC6xKN7SwPQh7UyUBlcrIKeV+x72ON8aFMCMriX1XdmqxzUexdsLY9XKVNF9e6wBom80jPdoYmmiktLZD5g5rlPMx+LeiXiGh4nNadS/91lYYtusMmfU/eAPUquM9Fb17DpWPXXae9q+Qk5nMTJV4+NeXvep8jZFatpVIN8lSDF6AB/6RitmhXmlwWPnFPjEcazbHOZ5ZTIeQRxVwwESLQLPK+JvEdGZijistTx6yrz4kqm0H2q2ryXPlNhmPUJdZhYWYioVqw3qCMITP707XhaoPtelHjYws0KTES3V3fULBHcqFQV6k0tquO/3LEF0QBT3ULzQLJ2x4CnKcJXqnHLuFQ/y3YA/k2QRLZEEsUXlfSZ8KfMciZOI2unTDf0szLIhitVMq+2F7Bn8t+bn8mHgvThv2gY4H9vvK4myE5wRSBGeZtuz2jxOjO2qrnu6z2Nvah3Y5JwocU2IkQcBGimLpp5ofQNOofB/sjudydM2+BFo/0jIvab9Ibe1Y0I+ts0vmUK2SkO0V2tTGHMnoj+L8fd5TvMp9aR/Uh72YXjUxySIBHz6hsANu1x7L4KBd3hOrHEu9yBbvGOIkle+aabXkhM/LzpsXon7I4gNoJ6hyLvAd1gojN4gdnpUFJcjYC5T72UMFN72TtJ2RHK+sT1uxxjf4+l31nQwEHlNn9SIgUOGDekS1iJs88m5nj5mViwBQy5q+F3qHj1SDWHQHeymJyB2FcMP3udEY0VLbB8da/vwA3YBkCKU6WpJ8q2a2yF5yU1mLNARetoTJ6dpdftX1tDu4Pn1sCQObhR05mtjgHSjRQnBmrtjxJ7uMKkN3+aomsah8YyzAw7EmxCj4N63/83Zko6nUgeg4bNw/kTXoFuiRs3ex6U10tp88P+AleZpKvNHJOBY02o+5FM1rKNgHD7rdFN4M4jnuI90/gNpwsNFYyweZ5BVRz26nDOLbOSGGUfrXPwMYxIBfn57jaOVX5K45MBDyxiewA3CTqF9aHIB2CCNjpKzWBe2F8Wwlf8tcfT/N3CNnpA+EDbt0ULMbttRXRGtaBD8oPVehda5O8lL3+v/n3shLPlOu4endflf4jhFTMk4fGIcZXwqI5oJdU3hlTOdmxVfO9spaQdiUfuQnvSp8BjzQbCuFt9M4dlWePy+wLKmuZWXy2MYMjsKaLnou8d8RGZVNArw1qASJ7U2+8I7XeDD3aoI1bSAV7snxc/h9LvQtyEWS7911UKwuFSCpnQNAQ+a44ADrPOJpcb1gAVJPq+HxqtfrzB2zEnb3pUAVpzQYaONWtyU561wvBYYP4Xr+/B7/jcPxORhyGQ40l63uLO452FXTj1NksGQXoSS3yLvEpGK7kCQfQGw6KW1MAS6lm8ae0vOVFIKF+e+IzjY1mIZTcuK7D8MVP32q/A8G9xPBwf4Kvok0meoGtMaA/kJ27xl4KcY7GaQnTPEMs83oCM/1JAE7AWlX+F6oslOoBW057W8Vcimb2YC8GWpPV6+GyzrvQmyfqq9iyXlMluv9ep69C/FjZoPLAB48YRGVXyMb+KIq8qPt32K1QEd7CRAKJrHGiW0l23ZiKarw/h4u+XTY1D/S11OKZEPU0WDPsQCuk0PiRu/f+o4g1mD7y4ur74MUIoJ5mdf2ZGUFUILKUGmUaQ2qw2caLOUnWlj3gbF/1St/LuzEfQEOoNVfDhQhfp5HCNYT8cn2ZskJLQmYbeXkXPDUf0NhSQ7QC6tf8MuUhJuZ1VPMyX1pwZJfbDiufV/la7I9gW7/n+zLtrVlgND5lgx08qA/vh27hX8wFLk+lZ0A265bOVH7YTpWZLhBtNsX/RfCDpGyj7SKbnN3K+P/9fw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Week\" = _t, #\"Platform\" = _t, #\"Post Type\" = _t, #\"Platform Group\" = _t, #\"Format Group\" = _t, #\"Year\" = _t, #\"Quarter\" = _t, #\"Month\" = _t, #\"Posts\" = _t, #\"Impressions\" = _t, #\"Reach\" = _t, #\"Engagements\" = _t, #\"Likes\" = _t, #\"Comments\" = _t, #\"Shares\" = _t, #\"Saves\" = _t, #\"Link Clicks\" = _t, #\"Followers Gained\" = _t, #\"Followers Lost\" = _t, #\"Video Views\" = _t, #\"Mentions\" = _t, #\"Sentiment Pool\" = _t]),",
                "    #\"Typed\" = Table.TransformColumnTypes(Source,{{\"Week\", type date}, {\"Platform\", type text}, {\"Post Type\", type text}, {\"Platform Group\", type text}, {\"Format Group\", type text}, {\"Year\", type text}, {\"Quarter\", type text}, {\"Month\", type text}, {\"Posts\", Int64.Type}, {\"Impressions\", Int64.Type}, {\"Reach\", Int64.Type}, {\"Engagements\", Int64.Type}, {\"Likes\", Int64.Type}, {\"Comments\", Int64.Type}, {\"Shares\", Int64.Type}, {\"Saves\", Int64.Type}, {\"Link Clicks\", Int64.Type}, {\"Followers Gained\", Int64.Type}, {\"Followers Lost\", Int64.Type}, {\"Video Views\", Int64.Type}, {\"Mentions\", Int64.Type}, {\"Sentiment Pool\", type number}},\"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Social\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}
